### ISSUE TITLE
(예시) Array.prototype.map이 작동하지 않습니다.

### ISSUE THREAD

**Issue by woohm402** [wafflestudio/19.5-rookies#10]
`이 질문은 예시입니다.`

안녕하세요, 세미나 1 과제를 진행중인 18.5기 루키 우현민입니다.
배열의 map함수를 이용하여 구현하고 있는데, 결과가 예상대로 나오지 않아 질문드립니다.
아래는 저의 코드입니다.

```javascript

const studentList = ['우현민', '김김김', '이이이'];

const items = studentList.map((item, index) => { 
    id: index, 
    name: item 
});

console.log(items); // [undefined, undefined, undefined]

```

데이터 가공 과정에서 문제가 생긴 것 같은데, [이 문서와 같은](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) map함수에 대한 레퍼런스를 아무리 찾아봐도 이유를 모르겠습니다. 어떤 부분에서 문제가 생긴 건가요?

**Comment by Leeingnyo** [comment]
`map()`안의 `(item, index) => { ... }` 에서 `{`와 `}` 가 arrow 함수를 열고 닫는 중괄호로 먼저 인식돼서 그런 것 같습니다. 신택스 에러가 예상되는데 그렇진 않았나 보네요. `Object`로 반환하고 싶으시면 `=> { return { ... }; }`처럼 따로 `return`을 써주시거나 `=> ({ ... })` 처럼 소괄호로 묶는 법이 있습니다. 저는 후자가 더 예쁠 것 같습니다.

**Comment by woohm402** [comment]
> `map()`안의 `(item, index) => { ... }` 에서 `{`와 `}` 가 arrow 함수를 열고 닫는 중괄호로 먼저 인식돼서 그런 것 같습니다. 신택스 에러가 예상되는데 그렇진 않았나 보네요. `Object`로 반환하고 싶으시면 `=> { return { ... }; }`처럼 따로 `return`을 써주시거나 `=> ({ ... })` 처럼 소괄호로 묶는 법이 있습니다. 저는 후자가 더 예쁠 것 같습니다.
> 
> 예시 질문인 걸 못 봤네요ㅋㅋ 답변 예시로 하죠

ㅋㅋㅋㅋㅋ 답변 감사합니다!!

**Comment by woohm402** [comment]
여담으로 다음 코드는 에러가 나지 않고 실제로 다음과 같이 동작하는데,

```javascript
const studentList = ['우현민', '김김김', '이이이'];

const items = studentList.map((item) => { 
    name: item
});

console.log(items); // [undefined, undefined, undefined]
```

대체 왜 되는 건지 좀 찾아봤는데 아마도 javascript의 [label 문법](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/label)이 적용된 게 아닐까 추측하고 있습니다. 혹시 정확한 답을 아시는 분 있으면 제보해주시면 감사하겠습니다!

역시 어메이징 자바스크립트..
