### ISSUE TITLE
우분투에서 git push할 때 패스워드 입력이 안됩니다

### ISSUE THREAD

**Issue by jaylions** [wafflestudio/19.5-rookies#148]
![image](https://user-images.githubusercontent.com/82078863/130477490-f9006d90-3f00-4b92-8f79-aa1bcdec9b9f.png)
여기에서 패스워드에 깃 비밀번호랑 발급받은 코드 모두 입력해 봤는데 둘다 옳지 않다고 나와서 혹시 여기에 무엇을 입력해야 하는 것인지 알 수 있을까요?

**Comment by gyusang** [comment]
[이 문서](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token#using-a-token-on-the-command-line)에서 설명하는 것과 같이 personal access token을 발급하여 입력하는 것이 맞습니다.

**Comment by jaylions** [comment]
감사합니다
