### ISSUE TITLE
push를 wafflestudio/19.5-rookies.git로 할때 오류가 생깁니다

### ISSUE THREAD

**Issue by Songmin17** [wafflestudio/19.5-rookies#149]
안녕하세요,

제가 fork한 레포를 push하려고 push origin master를 입력을 했는데 이런 오류가 떠서 질문을 올립니다:

Permission to wafflestudio/19.5-rookies.git denied to Songmin17.
fatal: unable to access 'https://github.com/wafflestudio/19.5-rookies/':
이 문제를 어떻게 해결할 수 있는지 알려주시면 감사하겠습니다.

**Comment by gyusang** [comment]
wafflestudio/19.5-rookies가 아니라 Songmin17/19.5-rookies에 push하셔야 합니다. 'origin'을 변경하는 방법에 관해서는 [이 문서](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#changing-a-remote-repositorys-url)를 참고하세요.

**Comment by Songmin17** [comment]
origin을 변경하려고 이런 커맨드를 입력했는데도 계속 permission denied 오류가 뜹니다:
git remote set-url origin https://github.com/Songmin17/19.5-rookies.git
입력한 후에 git push origin master를 했는데도 같은 문제가 발생해서, 어떻게 해결해야 하는지 다시 질믄 드립니다.

**Comment by Songmin17** [comment]
해결했어요~

**Comment by woohm402** [comment]
@Songmin17 어떻게 해결하셨는지 코멘트로 달아 주시면 좋을 거 같아요!

**Comment by Songmin17** [comment]
git config - -global - -edit해서 직접 url을 바꾸니가 해결이 됐어요~
