### ISSUE TITLE
WSL이 무엇인지 정확히 이해가 안 됩니다.

### ISSUE THREAD

**Issue by footprinthere** [wafflestudio/19.5-rookies#160]
안녕하세요.

저는 현재 Windows 노트북을 사용하고 있는데, OT 때 Linux 환경을 갖추는 게 좋다고 말씀하셔서 WSL2를 설치했습니다.
그런데 이게 어떤 역할을 하는 것인지, 어떻게 사용해야 하는 것인지 잘 이해가 되지 않아 질문글을 쓰게 되었습니다.

어떤 프로그램을 설치했을 때, Linux 환경에서 실행하고자 한다면 Windows 버전을 설치하는 것이 아니라 Linux 버전을 따로 설치해야 하나요?
이를테면 Backend 세미나에 참여하기 위해 필요하다고 말씀해주신 mySQL을 어떻게 설치해야 하는지를 모르겠습니다. 일단은 Linux 터미널을 이용해서 설치를 해보긴 했는데 맞는지 잘 모르겠네요.
VSCode의 경우 WSL extension을 따로 설치해서 Linux 환경으로 연결할 수 있는 것 같던데, 이런 식으로 각 프로그램마다 알맞은 방법을 찾아서 따로 적용해주어야 하는 것인지 궁금합니다.

구글링을 해보았는데 WSL을 설치하는 방법에 대한 문서가 대부분이고 자세히 설명된 것은 찾지 못해서 이렇게 질문 드립니다.

**Comment by woohm402** [comment]
WSL은 윈도우용 리눅스 하위 시스템입니다. 윈도우에서 리눅스와 거의 동일한 환경을 사용할 수 있도록 제공합니다.

윈도우는 unix 계열의 os가 아니기 때문에 개발할 때 불편한 점이 많고, 개발을 하려면 무조건 리눅스 듀얼부팅이나 맥을 사야 했습니다.

하지만 wsl이 나오면서 그냥 윈도우에서 리눅스환경을 거의 동일하게 사용할 수 있게 되었고, 듀얼부팅에 대한 부담이 많이 사라지긴 했어요.

하지만 이건 리눅스 경험이 충분할 때의 이야기이고, 반대의 경우 윈도우에서 리눅스를 돌리는 거인 만큼 말씀주신 것과 같은 많은 어려움이 있습니다. 이걸 윈도우에서 작업해야 하나 리눅스에서 작업해야 하나 등에 대한 고민이 생기고, 문제가 생겼을 때 추적하는 게 더 힘들 수 있습니다.

때문에 리눅스가 익숙하지 않으시다면, 그냥 리눅스 듀얼부팅을 하셔서 리눅스에 익숙해지신 다음 나중에 wsl로 옮기시는 걸 추천드립니다

**Comment by footprinthere** [comment]
감사합니다! 듀얼부팅으로 다시 시도해보겠습니다.
