### ISSUE TITLE
Git push 할 때 username과 password가 잘못되어 authentication error가 발생합니다.

### ISSUE THREAD

**Issue by chaemin2001** [wafflestudio/19.5-rookies#171]
안녕하세요 authentication 이슈로 git push가 되지 않아 질문합니다

Personal Access Token을 발급받아서 keychain 암호도 해당 암호로 변경 완료했는데

chaeminlee@Chaeminui-MacBookPro 19.5-rookies % git push origin master
Username for 'https://github.com': chaemin2001
Password for 'https://chaemin2001@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/chaemin2001/19.5-rookies.git/'

계속해서 authentication fail 이 떠서 해결 방법 문의드립니다ㅜ

**Comment by woohm402** [comment]
password에 personal access token 입력해보시겠어요?

**Comment by chaemin2001** [comment]
> password에 personal access token 입력해보시겠어요?

password를 타이핑하는 것이 안되어서 keychain 에서 token명으로 바꾸어 보았는데도 해결이 안됩니다ㅠ

**Comment by VioletXF** [comment]
타이핑이 안되는 것이 아니라, 비밀번호가 노출되지 않도록 입력 내용을 화면에 표시하지 않는 것 뿐입니다.
