### ISSUE TITLE
우분투 듀얼 부팅 설치에 관해 질문이 있습니다

### ISSUE THREAD

**Issue by isaac0622** [wafflestudio/19.5-rookies#179]
안녕하세요, 루키 오이석입니다.
리눅스를 구동시키기 위해 듀얼 부팅에 대해 알아보고 있는 가운데, 궁금한 점이 생겨 질문 드립니다.

1. 우선 일반적으로 USB에 Linux를 깔아서 듀얼부팅을 한다고 알고 있는데, 혹 이를 micro SD 카드로 하면 지장이 있을까요? micro SD 카드의 속도가 더 느려 문제가 생길지가 걱정입니다. (서피스 프로 7을 사용하는데, 찾아보니 최소 30MB/s ~ 최대 100MB/s의 읽기 속도 정도의 성능을 낼 수 있을 것 같습니다.) 이번 백엔드에서 장고 세미나에 참여할 것 같은데, 이 정도 수준에서 보시기에 지장이 있을 것 같나요?

2. 내장 SSD에 용량이 얼마 남지 않아 내장 SSD에 파티션을 주기보다는 리눅스를 설치할 USB/SD 카드에 파티션을 주어서 OS와 저장공간 둘다 사용하려 하는데, 이 역시 혹 지장이 있나요?

시간 내어 읽어주셔서 감사합니다.

**Comment by gyusang** [comment]
라즈베리 파이가 SD 카드로 우분투 부팅을 해서 쓰니, 리눅스 사용에는 지장이 없어 보입니다. 어차피 세미나에서 엄청난 로드를 가하는 건 아니기 때문에 읽기 속도는 큰 문제는 아닐 것으로 보입니다.
다만 읽기 속도나 SD카드에 설치된 형태, 부팅 방식 등의 특수성으로 인해 예상치 못한 문제가 발생할 수 있고, 서피스나 SD카드 부팅을 사용해본 사람이 적어서 troubleshooting이 조금 힘들 수 있습니다.

**Comment by woohm402** [comment]
@isaac0622 

이슈 해결되셨나요?

**Comment by isaac0622** [comment]
네 해결되었습니다! micro-SD에 설치해도 조금 느리지만 잘 돌아갑니다 :) 이만 닫겠습니다!
