### ISSUE TITLE
Review할 파일에 다시 돌아가서 고치고 반영하려니까 계속 "nothing to commit, working tree clean"만 뜹니다.

### ISSUE THREAD

**Issue by kc626** [wafflestudio/19.5-rookies#192]
seminar-list.md 파일에서 선택함 세미나 이름을 고쳐달라고 하셔서 다시 이름 고치고 git add seminar-list.md 하고 git status 를 체크해보니 계속 "Your branch is up to date with 'origin/master'." 하고 "nothing to commit, working tree clean"이 떠요.. 어떻게 고쳐야하나요?

**Comment by woohm402** [comment]
1. history
2. git log
3. git diff HEAD HEAD^

이거 세개 쳐 보시고 각각 결과 캡쳐해서 올려주시면 도움이 될 것 같습니다

**Comment by kc626** [comment]
<img width="566" alt="git log" src="https://user-images.githubusercontent.com/81491087/130783445-cff59888-0c1b-412c-96f2-9622772baaf1.png">
<img width="603" alt="git diff HEAD HEAD^" src="https://user-images.githubusercontent.com/81491087/130783455-e0c8a321-b9a4-419f-ab10-6bf2f0fa49cf.png">
<img width="434" alt="history" src="https://user-images.githubusercontent.com/81491087/130783459-60360de9-b5d1-434a-8987-67ca1b377360.png">

감사합니다!

**Comment by woohm402** [comment]
우선 210번 줄에서 `git init` 하셨을 때 문제가 생겼을 가능성이 있어요. 바탕화면에 `.git` 폴더가 있다면, 삭제해 주세요. 
(Finder로 들어가셔서 `command + shift + .` 하시면 아래 사진처럼 보여요) 

<img src="https://user-images.githubusercontent.com/39977696/130784372-c0aab2b1-632a-433b-beb5-fc981be53c72.png" alt="img" height="80" />

`git init` 은 로컬의 폴더를 git repository로 세팅하는 명령어인데, clone하면 원래부터 git repository이기 때문에 git init을 하실 필요가 없습니다.

저거 때문에 현재 Repository가 잘못 잡혀서 제대로 처리가 되지 않았을 가능성이 좀 있을 거 같아요

---

혹시 이렇게 했는데도 안 되신다면, 처음부터 다시 하시는 게 제일 현실적으로 편한 방법일 거예요 (git은 한 번 꼬이면 잡기 쉽지 않아서)

로컬에 clone하신 폴더 지우시고, 바탕화면으로 다시 가셔서 아래 대로 해 보세요:

```shell
git status # 이때 not a git repository 라고 떠야 합니다
git clone https://github.com/kc626/19.5-rookies.git
(이후는 처음에 하셨던 대로)
```

**Comment by kc626** [comment]
감사합니다! .git 파일이 없어서 자시 하려구요..!ㅠ 도움주셔서 감사합니다!
