### ISSUE TITLE
download_survey UnicodeDecodeError 질문입니다.

### ISSUE THREAD

**Issue by rightafter** [wafflestudio/19.5-rookies#219]
백엔드 세미나 0의 과제 중 5번을 진행 중 발생한 오류입니다.

download survey를 하니 
`UnicodeDecodeError: 'cp949' codec can't decode byte 0xed in position 0: illegal multibyte sequence
`
라는 Error가 발생합니다.

검색을 해보니 open 함수를 수정하면 오류를 해결할 수 있는 것 같은데
19.5-rookies\django\seminar0\assignment0\survey\management\commands\download_survey.py 파일을 수정해도 괜찮을까요?

혹은 해당 error의 다른 해결 방법이 있을까요?

**Comment by woohm402** [comment]
@rightafter 해결되셨나요?

**Comment by rightafter** [comment]
> @rightafter 해결되셨나요?

download_survey.py 파일의 27번째 줄을
with open(tsv_file, encoding='UTF-8') as f: 로 수정하여 해결했습니다!

**Comment by numnum97** [comment]
참고했습니다! 감사합니다 :)
