### ISSUE TITLE
MySQL, Postman 입출력 형식 관련 질문입니다.

### ISSUE THREAD

**Issue by rightafter** [wafflestudio/19.5-rookies#229]
1. 과제 (2)번에서 Python 3.8.3을 설치하라고 하셨는데 3.8.5 버전으로 진행하여도 괜찮을까요?

2. **(해결)** 과제 (6)번에서 survey_surveyresult table을 출력할 때 mysql에서는 os_id가 출력이 정상적으로 되지 않는 문제가 발생합니다. 
정확한 원인은 모르겠지만 os_id만 뽑아서 따로 출력했을 때는 정상적으로 출력이 되고, DataGrip에서는 전체 table을 출력할 때도 정상적으로 출력이 됩니다.
mysql에서 table 캡처 시에 혹시 이 부분을 무시해도 될지, 혹은 해결방법이 있을지 알고 싶습니다.
--> 테이블이 커서 mysql Client 상에서 줄이 밀린 듯 합니다. 정상적으로 출력됩니다.

![6-3](https://user-images.githubusercontent.com/46552678/131217289-3c8f193d-c83d-4e7c-b01e-fc253bbb26ea.PNG)
![6-9](https://user-images.githubusercontent.com/46552678/131217330-54807c47-392f-4173-a0eb-f07664db021f.PNG)

3. (9), (10)번에서 예상 외의 parameter가 입력되었을 때,
즉 (9)번에서의 status code가 404가 되도록 할 때와 (10)번에서 status code가 400이 되도록 할 때, 
Postman에서 status code가 404, 400를 반환하는지 여부 외에 따로 출력해야할 것이 있을까요?
혹은 첨부한 사진처럼 빈 화면만 출력해도 괜찮을까요?

![10-3](https://user-images.githubusercontent.com/46552678/131217398-ff0c8fce-b3d7-46d6-ba74-064be5e95dcc.PNG)

4. (해결) (10)번에서 os가 될 수 있는 것이 Windows, MacOS, Linux라고 하셨는데
os가 Linux인 데이터는 없고
Linux 대신 Ubuntu (Linux)를 입력해야 제대로 출력이 되는 것 같습니다.
이 부분 확인해주시면 감사하겠습니다.
--> os 이름을 Linux가 아닌 Ubuntu (Linux)로 입력하면 된다고 합니다.

**Comment by esc5221** [comment]
2. 의 경우는 columm 수가 많아서 다음줄로 넘어간거 같아요. 자세히 보시면 os_id도 출력되있습니다.

**Comment by rightafter** [comment]
> 1. 의 경우는 columm 수가 많아서 다음줄로 넘어간거 같아요. 자세히 보시면 os_id도 출력되있습니다.

아 그렇네요..! 제가 너무 대충 본 것 같습니다. 감사합니다!

**Comment by Jhvictor4** [comment]
아 4번의 경우는 저희가 실수한 듯 합니다 죄송합니다. Readme 업데이트 하겠습니다 Ubuntu (Linux) 로 진행해서 제출해주세요!
