### ISSUE TITLE
백엔드 과제 0 makemigrations가 되지 않습니다(m1 - mysqlclient)

### ISSUE THREAD

**Issue by ksiyeon27** [wafflestudio/19.5-rookies#232]
안녕하세요. 백엔드 수강생 김시연입니다. 

과제 3번 내용까지 모두 마친 후에, 
4번을 위해 python3 manage.py makemigrations 명령어를 입력하였을 때 나는 에러 입니다.

<img width="1194" alt="스크린샷 2021-08-28 오후 10 10 37" src="https://user-images.githubusercontent.com/76062959/131219152-e8067bbd-d069-479e-9fd0-f8fee3c8edb9.png">
<img width="1153" alt="스크린샷 2021-08-28 오후 10 11 08" src="https://user-images.githubusercontent.com/76062959/131219158-134fa2b6-5991-4a6e-b9f0-36dca18bbb7c.png">

"Symbol not found: _mysql_affected_rows", "NameError: name '_mysql' is not defined" 같은 메세지를 구글링하며 해결책을 찾아보던 와중에,

https://adamj.eu/tech/2020/02/04/how-to-use-pymysql-with-django/
https://stackoverflow.com/questions/67420897/cannot-connect-django-to-existing-mysql-database-on-m1-mac

에서 비슷한 문제를 겪는 m1 mac 유저들을 발견했습니다.
둘 다 PyMySQL 를 이용하여 문제를 해결할 것을 권유하고 있는데, 아무래도 다른 라이브러리를 사용하는 방법인 것 같아 이러한 해결 방법이 가능할지 여쭤보고 싶습니다.

계속 구글링을 하면서 m1과 mysqlclient 사이의 문제라는 글들을 자주 보고 있는데 
혹시 비슷한 경험이 있는 m1 유저분이 계시다면 도움을 주시면 감사하겠습니다.
+) https://github.com/PyMySQL/mysqlclient/issues/496

**Comment by VioletXF** [comment]
혹시 x86_64버전의 파이썬을 사용하고 계신가요? 다음 명령을 통해 확인하실 수 있습니다.
```
lipo -info $(which python3)
```

**Comment by VioletXF** [comment]
저의 경우 M1버전의 파이썬을 사용하여 문제를 해결했습니다. 찾아보니 파이썬 3.8.10부터 공식적으로 M1을 지원하는 것 같은데, M1 Homebrew 등을 통해 설치 후 사용하시면 해결될 것입니다.
(단, 이 경우 과제 조건을 어기게 되므로 세미나장님께 문의하시는게 좋을 것 같습니다.)

**Comment by Gorani9** [comment]
저도 M1 사용중인데 과제 스펙인 python 3.8.3의 경우 x86_64 밖에 안되기 때문에 생기는 문제인 것 같습니다. 
저의 경우 Homebrew로 3.8.11 설치해서 해결했습니다.

**Comment by Hank-Choi** [comment]
파이썬 m1호환 버전 다운 받아주시기 바랍니다. 혼란을 드려 죄송합니다.

**Comment by ksiyeon27** [comment]
@VioletXF @Gorani9 정말 감사합니다!!
@Hank-Choi  확인했습니다 감사합니다:)
