### ISSUE TITLE
백앤드 과제 0번 질문입니다.

### ISSUE THREAD

**Issue by ishlove77** [wafflestudio/19.5-rookies#235]
백엔드 과제에서 requirements.txt를 깔던 도중 위 스크린샷과 같은 오류가 발생하였습니다. mysql역시 설치한 상태였는데 위와 같은 오류를 어떻게 해결하는지 알려주시면 감사하겠습니다.
![Screenshot from 2021-08-29 00-09-03](https://user-images.githubusercontent.com/88336033/131222531-c3d1746f-273b-45c4-820b-9134a4ec71cf.png)
![Screenshot from 2021-08-29 00-09-16](https://user-images.githubusercontent.com/88336033/131222536-c589a7cf-a7d8-4ee1-91f2-cff67432fe7d.png)
![Screenshot from 2021-08-29 00-09-26](https://user-images.githubusercontent.com/88336033/131222540-5f52a204-8dd5-47b8-9ebd-bef6e86d5a5b.png)

**Comment by VioletXF** [comment]
다음 명령을 실행한 후 다시 시도해보세요.
```
sudo apt-get install libmysqlclient-dev
```

**Comment by ishlove77** [comment]
네 잘 설치되었습니다. 감사합니다. ㅎㅎ

**Comment by jaylions** [comment]
apt-get command not found 라고 뜨는 경우에는 어떻게 해결해야하나요

**Comment by VioletXF** [comment]
apt는 리눅스용입니다. 맥에서는 [Homebrew](https://brew.sh/index_ko)를 설치하신 후, 다음 명령을 통해 mysql을 설치하시면 됩니다.
```
brew install mysql
```

**Comment by jaylions** [comment]
감사합니다

**Comment by woohm402** [comment]
@ishlove77 이슈 제목 수정 부탁드립니다!
