### ISSUE TITLE
파이썬 버전 변경 질문 드립니다

### ISSUE THREAD

**Issue by jaylions** [wafflestudio/19.5-rookies#237]
<img width="1440" alt="스크린샷 2021-08-29 오전 12 37 21" src="https://user-images.githubusercontent.com/82078863/131223468-3907a895-c8b9-4f11-82f5-0ea6a30533ba.png">
파이썬 버전이 3.8.2인데 3.8.3으로 변경하는 방법을 잘 모르겠습니다
<img width="1440" alt="스크린샷 2021-08-29 오전 12 43 08" src="https://user-images.githubusercontent.com/82078863/131223473-0fffc113-f050-4ddd-b63c-a57fbf3175c1.png">
그리고 requirements.txt에서 mysql 2.0.1만 설치가 제대로 되지 않는데 이유를 정확히 모르겠습니다

**Comment by VioletXF** [comment]
혹시 M1 맥북을 사용중이신가요? 만약 그렇다면, #232 에서 언급된 바와 같이 3.8.10 이상의 M1용 파이썬을 사용하면 문제가 해결될 수 있습니다.

**Comment by yabsed** [comment]
이용할 파이썬 버전을 변경하려면 어떻게 해야 하나요

**Comment by VioletXF** [comment]
1. 먼저, 이미 설정된 가상환경이 있다면 venv 폴더를 지워주세요.

![image](https://user-images.githubusercontent.com/27609690/131232432-bb87c1fd-ba86-4d1d-807d-ab5d00d8a716.png)
2. 우측 하단에서 Python을 클릭한 후, Add Interpreter를 클릭하세요.

![image](https://user-images.githubusercontent.com/27609690/131232438-4ff74928-a5ae-4054-a321-1c621fab4503.png)
3. 마지막으로 Base Interpreter를 원하는 버전으로 선택하신 후, OK를 눌러주시면 됩니다.

**Comment by jaylions** [comment]
감사합니다!

**Comment by woohm402** [comment]
@jaylions 이슈 제목 수정 부탁드립니다!

**Comment by jakdurider** [comment]
관련해서 질문 있습니다! 그러면 파이썬 버젼을 꼭 3.8.3이 아니라 3.8.10이나 그 이상의 버젼을 사용해도 되는 것인가요?
