### ISSUE TITLE
ReactJS 세미나의 참여 요건이 궁금합니다.

### ISSUE THREAD

**Issue by footprinthere** [wafflestudio/19.5-rookies#24]
안녕하세요. 이번 Rookie로 활동하게 된 정성태입니다.
어떤 세미나에 참여할지 고민하던 중 궁금한 점이 생겨 질문 올립니다.

Frontend의 ReactJS 세미나에 참여하기 위해 갖추어야 할 요건에는 어떤 것들이 있을까요?
이를테면
  ▶ HTML과 CSS를 간단히 다뤄주신다고 하셨는데, 그렇다면 이에 대한 사전지식이 어느 정도 필요한 것인지
  ▶ Javascript의 기본적인 문법은 모두 알고 있다고 가정하고 세미나가 진행되는 것인지
같은 것들이 궁금합니다!

**Comment by woohm402** [comment]
안녕하세요, 프론트엔드 세미나장 우현민입니다.

다른 세미나들도 마찬가지겠지만, 프론트엔드의 경우에도 루키로 들어오실 때 푸신 코딩 테스트를 해결하셨고 자소서를 올바르게 제출하셨다는 것 이외의 어떤 실력도 요구하지 않습니다.

즉 기본적으로는 아무것도 모르신다고 가정하고 수업을 진행합니다만, 미리 스포를 조금 드리자면 HTML과 CSS에 JS의 기본 문법까지 60분 정도에 끝내고 바로 React로 넘어갈 예정입니다: 다 가르쳐는 드리지만 진도가 매우 빠릅니다.

때문에 역시 다른 세미나들도 마찬가지이겠지만, 오늘 오티에서 미리 전달드린 링크 등을 통해 예습을 하고 오시면 훨씬 수월하실 거예요. 답변이 되었을까요?

**Comment by footprinthere** [comment]
감사합니다!!
