### ISSUE TITLE
creating resolved label

### ISSUE THREAD

**Issue by Kangji** [wafflestudio/19.5-rookies#240]
별 건 아닌데, 해결된 issue들을 구분짓기 위해 resolved label을 추가하는 건 어떨까 합니다!

**Comment by woohm402** [comment]
일단 좀 번잡해질 수 있을 것 같아서, 해결된 이슈들은 close하는 방향으로 논의되었었습니다. 공지하고 진행해보겠습니다! 의견 감사드려요 :+1:
