### ISSUE TITLE
백엔드 과제 0번 질문입니다.(mysql command 문제)

### ISSUE THREAD

**Issue by knt0613pow** [wafflestudio/19.5-rookies#242]
안녕하세요. 백엔드 세미나를 수강하고 있는 김남태라고 합니다.

세미나0에서 진행했던것 처럼 터미널에서 pip3 install  -r requirements.txt 를 통해
mysqlclient를 설치했습니다.
![스크린샷, 2021-08-29 14-55-44](https://user-images.githubusercontent.com/84067480/131240324-94134021-a425-418d-a5b0-26565c89cf06.png)

터미널에서 설치가 되었다고 나타났고, python packages에서도 mysqlclient 2.0.1버전을 확인할수 있었습니다.
![스크린샷, 2021-08-29 14-58-47](https://user-images.githubusercontent.com/84067480/131240366-62680ac8-8a18-4f40-9a80-924ef8e1a1bb.png)

하지만 터미널에서 mysql.server start 를 실행했을 때, 'mysql.server: 명령을 찾을 수 없습니다.' 라고 뜨는 상황입니다.
![스크린샷, 2021-08-29 15-10-08](https://user-images.githubusercontent.com/84067480/131240579-f03517a3-bc31-4445-8ee6-c1799a2ca794.png)

이에 관련해서 'mysql.server cant find command'로 검색했을 때, mysql폴더를 path를 설정해주는 방식을 사용하라고 나와있는데(https://phoenixnap.com/kb/mysql-command-not-found-error) 가상환경에서 mysqlclient를 설치한 상태에서도 이러한 해결책이 유효한지 궁금해서 이슈를 올립니다.

**Comment by VioletXF** [comment]
mysql 설치하셨나요? mysqlclient는 mysql과 파이썬을 연결해주는 라이브러리이고, mysql자체는 포함하지 않는 것으로 알고 있습니다.
mysql은 다음 명령을 통해 설치하실 수 있습니다.
``` 
sudo apt-get install mysql-server mysql-client 
```

**Comment by Jhvictor4** [comment]
mysql.server start는 맥 용 커맨드입니다.

리눅스에서는 service mysql start로 접근해주세요

**Comment by knt0613pow** [comment]
'service mysql start' 커맨드로 해결했습니다! 답변주셔서 정말 감사합니다~!!
