### ISSUE TITLE
(backend assignment 0) mysqlclient 설치 오류

### ISSUE THREAD

**Issue by footprinthere** [wafflestudio/19.5-rookies#243]
지난 세미나에서 `pip install -r requirements.txt` 커맨드를 사용해 과제 수행에 필요한 패키지들을 설치하라고 말씀해주셨는데요.
이 커맨드를 사용해 설치를 시도했더니 `mysqlclient`가 제대로 설치되지 않았다는 에러가 떴습니다.

그래서 아래와 같이 `pip install mysqlclient==2.0.1`로 다시 시도를 해보았는데도 여전히 같은 에러가 출력됩니다.

![image](https://user-images.githubusercontent.com/84006386/131252475-5fd098e1-9272-42ea-a747-028b3408dbdb.png)

아래에서 확인할 수 있듯이 MySQL은 정상적으로 설치가 되어 있습니다.

![image](https://user-images.githubusercontent.com/84006386/131252587-2d826ea5-beea-4bf4-8986-30b823553e74.png)

무엇이 문제일까요?

**Comment by footprinthere** [comment]
`pip` 대신 `pip3`을 사용해도 같은 오류가 출력되었습니다.

**Comment by Jhvictor4** [comment]
sudo apt-get install libmysqlclient-dev

치시면 해결 될거에요. mysql_config이 다른 패키지에 있어 발생하는 이슈입니다

**Comment by jaylions** [comment]
혹시 맥에서는 어떻게 해결해야 하나요?

**Comment by Jhvictor4** [comment]
@jaylions 똑같은 에러인가요/? https://elfinlas.github.io/2019/01/23/pip-mysql-error/ 이거 참고해보시겠어요??

**Comment by jaylions** [comment]
감사합니다 확인해보겠습니다!

**Comment by footprinthere** [comment]
말씀해주신 대로 `sudo apt-get install libmysqlclient-dev`를 실행한 후 다시 mysqlclient 설치를 시도했는데 이번에는 이런 에러가 나왔습니다.

![image](https://user-images.githubusercontent.com/84006386/131254369-55e67725-3d66-4566-ac21-903f09032985.png)

그래서 [여기](https://hongjuzzang.github.io/howto/install_mysql_ubuntu/)에 나와 있는 대로 python-dev 파일을 설치해보았는데도 여전히 같은 에러가 나옵니다.

**Comment by footprinthere** [comment]
`sudo apt-get install gcc`를 입력해 gcc를 설치했더니 해결되었습니다.

도움 주셔서 감사합니다!!

**Comment by Jhvictor4** [comment]
넵 ㅎㅎ 에러 로그를 보면서 잘 쫓아가 주셨네요 :)

**Comment by jaylions** [comment]
보내주신 링크에 있는대로 했는데도 해결이 안됩니다 ㅠㅠ

**Comment by jaylions** [comment]
![Uploading 스크린샷 2021-08-30 오전 12.30.54.png…]()

**Comment by jaylions** [comment]
mysql의 설치 위치가 문제인 것 같은데 해결이 잘 되지 않습니다

**Comment by VioletXF** [comment]
전체 에러 로그를 올려주실 수 있나요?

**Comment by jaylions** [comment]
ERROR: Command errored out with exit status 1:
   command: /Users/gubukson/waffle-rookies-19.5-backend-0/assignment0/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-install-z10zosmx/mysqlclient_246670fdb7744a52a8999b06e7350f4c/setup.py'"'"'; __file__='"'"'/private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-install-z10zosmx/mysqlclient_246670fdb7744a52a8999b06e7350f4c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-wheel-iz8xzdr2
       cwd: /private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-install-z10zosmx/mysqlclient_246670fdb7744a52a8999b06e7350f4c/
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-universal2-3.8
  creating build/lib.macosx-11-universal2-3.8/MySQLdb
  copying MySQLdb/__init__.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
  copying MySQLdb/_exceptions.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
  copying MySQLdb/connections.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
  copying MySQLdb/converters.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
  copying MySQLdb/cursors.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
  copying MySQLdb/release.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
  copying MySQLdb/times.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
  creating build/lib.macosx-11-universal2-3.8/MySQLdb/constants
  copying MySQLdb/constants/__init__.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
  copying MySQLdb/constants/CLIENT.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
  copying MySQLdb/constants/CR.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
  copying MySQLdb/constants/ER.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
  copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
  copying MySQLdb/constants/FLAG.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
  running build_ext
  building 'MySQLdb._mysql' extension
  creating build/temp.macosx-11-universal2-3.8
  creating build/temp.macosx-11-universal2-3.8/MySQLdb
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Dversion_info=(2,0,1,'final',0) -D__version__=2.0.1 -I/opt/homebrew/Cellar/mysql/8.0.26/include/mysql -I/Users/gubukson/waffle-rookies-19.5-backend-0/assignment0/venv/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c MySQLdb/_mysql.c -o build/temp.macosx-11-universal2-3.8/MySQLdb/_mysql.o
  gcc -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-11-universal2-3.8/MySQLdb/_mysql.o -L/opt/homebrew/Cellar/mysql/8.0.26/lib -lmysqlclient -lzstd -lresolv -o build/lib.macosx-11-universal2-3.8/MySQLdb/_mysql.cpython-38-darwin.so
  ld: library not found for -lzstd
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mysqlclient
  Running setup.py clean for mysqlclient
Failed to build mysqlclient
Installing collected packages: mysqlclient
    Running setup.py install for mysqlclient ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/gubukson/waffle-rookies-19.5-backend-0/assignment0/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-install-z10zosmx/mysqlclient_246670fdb7744a52a8999b06e7350f4c/setup.py'"'"'; __file__='"'"'/private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-install-z10zosmx/mysqlclient_246670fdb7744a52a8999b06e7350f4c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-record-a5sv50xr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/gubukson/waffle-rookies-19.5-backend-0/assignment0/venv/include/site/python3.8/mysqlclient
         cwd: /private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-install-z10zosmx/mysqlclient_246670fdb7744a52a8999b06e7350f4c/
    Complete output (29 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-universal2-3.8
    creating build/lib.macosx-11-universal2-3.8/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
    copying MySQLdb/_exceptions.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
    copying MySQLdb/connections.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
    copying MySQLdb/converters.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
    copying MySQLdb/release.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
    copying MySQLdb/times.py -> build/lib.macosx-11-universal2-3.8/MySQLdb
    creating build/lib.macosx-11-universal2-3.8/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
    copying MySQLdb/constants/CR.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
    copying MySQLdb/constants/ER.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
    copying MySQLdb/constants/FLAG.py -> build/lib.macosx-11-universal2-3.8/MySQLdb/constants
    running build_ext
    building 'MySQLdb._mysql' extension
    creating build/temp.macosx-11-universal2-3.8
    creating build/temp.macosx-11-universal2-3.8/MySQLdb
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Dversion_info=(2,0,1,'final',0) -D__version__=2.0.1 -I/opt/homebrew/Cellar/mysql/8.0.26/include/mysql -I/Users/gubukson/waffle-rookies-19.5-backend-0/assignment0/venv/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c MySQLdb/_mysql.c -o build/temp.macosx-11-universal2-3.8/MySQLdb/_mysql.o
    gcc -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-11-universal2-3.8/MySQLdb/_mysql.o -L/opt/homebrew/Cellar/mysql/8.0.26/lib -lmysqlclient -lzstd -lresolv -o build/lib.macosx-11-universal2-3.8/MySQLdb/_mysql.cpython-38-darwin.so
    ld: library not found for -lzstd
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/gubukson/waffle-rookies-19.5-backend-0/assignment0/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-install-z10zosmx/mysqlclient_246670fdb7744a52a8999b06e7350f4c/setup.py'"'"'; __file__='"'"'/private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-install-z10zosmx/mysqlclient_246670fdb7744a52a8999b06e7350f4c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/yh/hgff3rm12310wgk60ntsb0hw0000gn/T/pip-record-a5sv50xr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/gubukson/waffle-rookies-19.5-backend-0/assignment0/venv/include/site/python3.8/mysqlclient Check the logs for full command output.

**Comment by jaylions** [comment]
찾아보니 mysql이 usr/local/bin에 있어야 하는 것 같은데 저는 opt/homebrew/bin에 설치가 되어 있는데 이 부분을 고쳐야 할 것 같은데 방법을 잘 모르겠습니다

**Comment by VioletXF** [comment]
저도 같은 에러를 경험했는데, 저의 경우 아래 방법을 통해 설치에 성공했습니다.
```
brew install zstd
CFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib" pip install mysqlclient==2.0.1
```

**Comment by jaylions** [comment]
정말 감사합니다 해결됐습니다!

**Comment by Jhvictor4** [comment]
넵 위의 방법 시도해보시겠어요? ㅜ 저도 맥에서 비슷한 경험 한 적이 있긴 합니다

**Comment by VioletXF** [comment]
> 찾아보니 mysql이 usr/local/bin에 있어야 하는 것 같은데 저는 opt/homebrew/bin에 설치가 되어 있는데 이 부분을 고쳐야 할 것 같은데 방법을 잘 모르겠습니다

Homebrew 버전의 차이입니다. Intel버전의 경우 /usr/local/bin에, ARM버전의 경우 /opt/homebrew/bin에 설치됩니다. 설치 경로는 본 문제와 큰 연관이 없습니다.
