### ISSUE TITLE
백엔드 과제 0번 service mysql start 오류 

### ISSUE THREAD

**Issue by ishlove77** [wafflestudio/19.5-rookies#249]
![Screenshot from 2021-08-30 01-29-00](https://user-images.githubusercontent.com/88336033/131257975-18e84e18-2486-4c67-a1a4-3ef64c50e056.png)

![Screenshot from 2021-08-30 01-29-24](https://user-images.githubusercontent.com/88336033/131257976-bc1cba7e-6d54-447c-b1d9-7f89f786a494.png)
![Screenshot from 2021-08-30 01-30-02](https://user-images.githubusercontent.com/88336033/131257980-9879fe9b-1cf2-48a6-af18-a86d51fbc159.png)
이렇게 mysqlinet역시 설치했고 mysql 역시 설치했는데 service mysql start 명령을 내리면 mysql이 아예 작동을 하지 않습니다. 구글링을 해보았지만 error을 수정하는 방법만 나와있는데 제꺼는 작동이 된건지 안된건지  error가 없으니 파악이 안됩니다. 이게 작동이 된건데 그게 화면에 나타나지 않은건지 아니면 작동자체가 안된건지 궁금합니다.

**Comment by Kangji** [comment]
아래 커맨드를 시도해보세요.
```sh
$ service mysql status
```

**Comment by woohm402** [comment]
@ishlove77 `label`이랑 `milestone` 설정 부탁드립니다.

**Comment by ishlove77** [comment]
> 아래 커맨드를 시도해보세요. mysql 서버가 작동중인지 아닌지 알 수 있을 거에요.
> 
> ```shell
> $ service mysql status
> ```

서버는 작동이 되는데 알고보니 타 오류에 의한 것이었습니다. python manage.py migrate을 실행하니 
![Screenshot from 2021-08-30 15-43-21](https://user-images.githubusercontent.com/88336033/131296686-087d4b30-0b40-4496-99d8-d0c6f5cba50a.png)
위 사진과 같은 오류가 생겼는데 이것은 engine설정을 database에 해주지 않아서 발생한 오류인가요??..

**Comment by ishlove77** [comment]
폴더 다시 삭제하고 다시 설치하니 해결됬어요 ㅎㅎ 감사합니다.
