### ISSUE TITLE
백엔드 과제 0번 파이썬 설치 버전 관련 문의드립니다.

### ISSUE THREAD

**Issue by kohandy1902** [wafflestudio/19.5-rookies#250]
이전 여러 이슈들에서 파이썬 버전 관련 문의들이 있었는데 아직 답변이 달리지 않은것 같아 다시 여쭤보려고 합니다. 파이썬 버전이 정확히 3.8.3이어야 하나요? 아니면 3.8.x이기만 하면 되나요? 감사합니다

**Comment by Jhvictor4** [comment]
넵 별다른 이슈가 없을 것 같아 3.8.X 로 진행해주셔도 무방할 것 같습니다.

**Comment by woohm402** [comment]
첨언하자면 제가 알기로 파이썬도 [Semantic Versioning 2.0.0](https://velog.io/@slaslaya/Semantic-Versioning-2.0.0-MAJOR-MINOR-PATCH%EC%99%80-%EB%AA%85%EC%84%B8%EC%97%90-%EA%B4%80%ED%95%98%EC%97%AC)을 따르던 것 같습니다. `3.8.x` 의 경우 `3.8.3` 과 ***호환되는 마이너 패치*** 들만 차이가 있는 거기 때문에 큰 이슈는 없지 않을까 싶어요
