### ISSUE TITLE
(backend assignment 0) MySQL 실행 오류

### ISSUE THREAD

**Issue by footprinthere** [wafflestudio/19.5-rookies#252]
윈도우에서 WSL 사용 중입니다.
과제 수행을 위해 `service mysql start`를 실행해보았는데 아래와 같은 오류가 나왔습니다.
![image](https://user-images.githubusercontent.com/84006386/131278196-5eb52829-f9a9-4d6e-b220-9e14164bbbee.png)

구글링을 해보니 사용자 암호가 설정되어 있지 않기 때문일 수 있다고 해서 암호를 설정해주었습니다.
![image](https://user-images.githubusercontent.com/84006386/131278236-1fdbcc0b-47f9-4a16-889f-45a7ead3076d.png)
![image](https://user-images.githubusercontent.com/84006386/131278252-62903e36-3153-4428-8dd4-9840b1e5726b.png)

그런데도 여전히 같은 오류가 나왔습니다.

더 찾아보니 `service` 명령어를 sudo로 실행시키면 된다고 하길래 시도해봤습니다.
그랬더니 정상적으로 시작이 되는 것 같았습니다.
![image](https://user-images.githubusercontent.com/84006386/131278334-5311de8b-d21a-4bb7-88f4-a4967d7d9646.png)

그러나 `python manage.py migrate`를 실행했더니 아래와 같은 오류가 나왔습니다.
![image](https://user-images.githubusercontent.com/84006386/131278459-2db8fb00-5531-45e5-bab2-98b278d725ab.png)

검색을 해서 이것저것 시도해보았지만 여전히 같은 오류가 나옵니다.
어떻게 해결해야 할까요?

**Comment by Jhvictor4** [comment]
넵 저것은 오류가 아닙니다.
로그 & 과제 settings.py 코드를 보시면 waffle-backend라는 user가 seminar라는 비밀번호로 접근을 하도록 설정된 것을 확인하실 수 있습니다. 해당 유저를 잘 생성하고, 비밀번호를 설정하고, 또 waffle_backend 데이터베이스에 접근할 권한까지 허용해주는것이 과제의 일부입니다.
권한 허용은 DCL 중 grant 부분을 참고하시면 쉽게 하실 수 있습니다 :)

**Comment by footprinthere** [comment]
아 제가 과제를 제대로 이해하지 못했었네요.. 다시 시도해보겠습니다!
