### ISSUE TITLE
백엔드 과제 8-9번, 10번 형식에 관한 질문

### ISSUE THREAD

**Issue by ishlove77** [wafflestudio/19.5-rookies#254]
1.8번에 보면 여기까지 개발한 내용을 repository에 포함시켜 달라는 내용이 있는데 그러면 10번에 수정한 내용은 포함시키지 말라는 것인가요???
2.status를 200 Ok로 표현하라는 이야기는 콘솔에 그냥 200이 뜨게하라는 것인가요? 아니면 Ok까지를 요구하는 건가요?
(404 not found, 400 bad requset 등 )

**Comment by Hank-Choi** [comment]
1. 수정했습니다. 오류 잡아주셔서 감사합니다.
2. 콘솔에 띄우는 게 아닙니다. 200 ok는 http response의 status code를 뜻하는 것이고 200코드가 ok라는 의미로 사용됩니다. response의 status code가 200을 반환하게 하면 됩니다. 정확한 내용은 장고 공식 문서 참고해주세요

**Comment by ishlove77** [comment]
네 감사합니다 ㅎㅎ
