### ISSUE TITLE
[백앤드 과제 0] Window에 깔려있는 MySQL Workbench 툴로 리눅스에 있는 MySQL 서버 접근 문제

### ISSUE THREAD

**Issue by jaejae2374** [wafflestudio/19.5-rookies#261]
안녕하세요 19.5기 이재현입니다.

백앤드 과제 0에서 6번을 해결하는 과정에서 'MySQL Workbench 툴로 survey_surveyresult, survey_operatingsystem table의 모든 row의 모든 column을 출력하세요' 에서 막혔습니다. 윈도우에 깔린 MySQL workbench로 리눅스에 있는 mysql 서버에 외부접근을 통해 확인하려 했습니다. 결론부터 말씀드리면 "Failed to connect to mysql at 172.29.20.14 with user waffle-backend, unable to connect to localhost" 라고 에러가 뜹니다.   

현재 진행상황은 다음과 같습니다.

0. wsl remote를 통해 vscode와 연동하였습니다.

1. 가상환경을 만들고 해당 가상환경에 mysql을 깔았습니다.

2. mysql에 settings.py에 나와있는대로 'waffle_backend" 라는 database를 만들고 "waffle-backend" 라는 user을 만든 후 권한을 주었습니다.

3. migrate 후 table들이 추가된 것을 확인했습니다.

4. Windows에 깔려있는 mysql workbench를 실행한 후 실행되고 있는 리눅스 서버의 mysql에 접근을 시도하였습니다. - 실패

4번의 실패 과정을 구체적으로 말씀드리자면

**1. 가상환경에서 mysql 서버 start 후 root 계정으로 접속**

**2. waffle-backend 계정에 grant privileges on \*.\* to 'waffle-backend'@'%'; 를 통해 외부 접근 권한을 부여**

**3. quit 한 후 가상환경에서 ip addr와 mysql service status를 통해 가상환경 ip와 port번호 확인**

**[ip addr 내용]**
eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:2c:76:41 brd ff:ff:ff:ff:ff:ff
    inet **172.29.20.14**/20 brd 172.29.31.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe2c:7641/64 scope link 
       valid_lft forever preferred_lft forever

**[mysql server status 내용 중 port 번호 부분]**
![image](https://user-images.githubusercontent.com/80879249/131451311-4119dfd4-eb47-472f-9f44-9541cb4f873c.png)

**4. windows에서 mysql workbench 실행 후 mysql connections + 아이콘을 클릭 후,
hostname : 172.29.20.14 / port : 0 / username : waffle-backend / password (Store in Vault) : seminar 를 넣고 test connection을 하면** 

**_"Failed to connect to mysql at 172.29.20.14 with user waffle-backend, unable to connect to localhost"_ 라고 에러가 뜹니다.**   
  
무엇이 문제일까요..

**Comment by Jhvictor4** [comment]
DB 연동 포트는 0이 아니라 3306이 표준입니다. settings.py에도 3306으로 명시가 되어있습니다.
설명해주신 바로는 포트 연결이 잘못된 것 같으니 재시도 부탁드려요 ㅎㅎ

**Comment by jaejae2374** [comment]
> DB 연동 포트는 0이 아니라 3306이 표준입니다. settings.py에도 3306으로 명시가 되어있습니다.
> 설명해주신 바로는 포트 연결이 잘못된 것 같으니 재시도 부탁드려요 ㅎㅎ

port 3306으로 해도 같은 오류가 뜹니다 ㅠ 일단 계속 구글링으로 찾아보고는 있습니다. ㅠㅠ

**Comment by WallabyG** [comment]
저도 wsl 사용 중 같은 문제가 발생했었는데, mysql server의 listening ip가 문제였습니다.
[이 글](https://jwkim96.tistory.com/34) 참고하시면 좋을 것 같아요.

**Comment by jaejae2374** [comment]
[해결]

원인은 hostname에 들어가는 ip 주소가 잘못되어있었습니다.
리눅스 서버의 ip는 172.29.20.14였으나
mysql 설정에서는 bind-address 가 127.0.0.1 이어서 이를 리눅스 서버 ip로 수정한 후
mysql 서버 재실행, windows workbench에서 접속 가능했습니다.

mysql 설정에서 bind-address 이부분을 찾으려고 mysql.conf.d를 뒤적거렸는데 이 곳이 아닌 /etc/mysql/mysql.conf.d/mysqld.cnf에 설정이 있었습니다.

[참조] https://dhan-description.tistory.com/84

**Comment by jaejae2374** [comment]
> 저도 wsl 사용 중 같은 문제가 발생했었는데, mysql server의 listening ip가 문제였습니다.
> [이 글](https://jwkim96.tistory.com/34) 참고하시면 좋을 것 같아요.

헉..! 방금 해결했습니다 감사합니다 :-)
