### ISSUE TITLE
Backend mysql 패스워드 길이 제한 관련 질문

### ISSUE THREAD

**Issue by LiTi0416** [wafflestudio/19.5-rookies#262]
Backend 과제0 진행 중 mysql DB 연결 과정에서 의문이 생겨 질문드립니다.

과제 내용의 3번에서, 로컬 MySQL 에 user를 생성하기 위한 명령어로 create user 을 시도하였는데, settings.py에 명시되어 있는 password 'seminar'를 사용하였더니 다음과 같은 에러가 발생하였습니다.

![Screenshot from 2021-08-31 16-00-23](https://user-images.githubusercontent.com/82010257/131457555-11ec4516-a8ae-4057-8ed5-5824bda259b1.png)

password policy에 대한 문제인가 하여 LOW로 설정을 바꾸기도 하였는데, 찾아보니 길이가 8자리 이상이어야 비밀번호로 설정할 수 있다는 언급이 있어 의문이 들었습니다.

제가 과제의 방향성을 잘못 이해하고 있는 것인지, 혹은 비밀번호를 바꾸어도 되는 것인지 알려주시길 부탁드리겠습니다!

**Comment by VioletXF** [comment]
다음을 입력하여 패스워드 최소 길이를 7자로 변경하실 수 있습니다.
```
SET GLOBAL validate_password_length=7
```

**Comment by LiTi0416** [comment]
앗 간단한 것이었군요 ㅠ 감사합니다!
