### ISSUE TITLE
[React Assignment 0] keyup과 한글입력 관련 질문

### ISSUE THREAD

**Issue by HyungGeun-Cho** [wafflestudio/19.5-rookies#263]
안녕하세요? 
19.5기 루키 조형근입니다.
React 과제 0번에서 학생입력을 'Enter'키로 구현하는 과정에서 생긴 궁금증입니다!

처음 Javascript 코드 작성 시 
`EventTarget`의 `addEventListener()` 메서드 옵션을 `keyup`으로 설정하여 실행해보았습니다.
그 결과 영어는 별 문제 없이 작동이 되는데, 
한글을 입력하고 Enter를 누르면 학생 추가 이벤트가 두 번 중복으로 실행되었습니다.

현재는 `keyup` 대신 `keypress` 로 변경해 해결한 상태이긴 합니다만,
왜 `keyup` 옵션에서 한글입력 시 이벤트가 두 번 실행되는지 궁금하여 issue로 올리게 되었습니다~!
감사합니다!

**Comment by woohm402** [comment]
좋은 질문 감사드립니다.

[이 링크](https://levelup.gitconnected.com/javascript-events-handlers-keyboard-and-load-events-1b3e46a6b0c3) 에 따르면, 한글 입력의 경우 isComposed 값이 일부 브라우저에서 다르게 동작하여 생기는 이슈인 것 같습니다! (아마 `keyup`을 이용하셔도 방향키를 이용해 커서를 움직이고 엔터를 클릭하시면 정상적으로 한 번만 나올 것 같습니다)

**Comment by HyungGeun-Cho** [comment]
답변 감사드립니다~!
정말 해보니 'Safari'에서는 괜찮고 'Chrome'에서만 문제가 발생하네요..!
말씀해주신대로 커서를 움직이고 엔터를 누르니 잘 되는 것 같습니다.
감사합니다! :)
