### ISSUE TITLE
스토리보드 구현과 코드 구현의 Best Practice가 궁금합니다.

### ISSUE THREAD

**Issue by shp7724** [wafflestudio/19.5-rookies#264]
안녕하세요. iOS 세미나 수강생 박신홍입니다.

과제 0번을 하면서 묘한 불편함이 좀 느껴졌었는데요.
곰곰이 생각해보니 가장 큰 이유가 스토리보드 구현과 코드 구현이 서로 연동이 안된다는 점인 것 같습니다.

예를 들어, 화면 전환은 스토리보드에서 쉽게 구현할 수 있지만 `navigationController?.pushViewController(controller, animated: true)`와 같이 코드로도 구현할 수 있다고 배웠는데요. 문제는 코드로 구현하게 되면, 스토리보드 상에서 Navigation Controller와의 연결이 끊어지기 때문에 스토리보드 Inspector를 이용하여 Navigation Item의 값들을 조정할 수 없게 됩니다.

이처럼 어떤 View의 일부 속성을 스토리보드 Inspector로 조정하고, 다른 일부를 코드로 구현하게 되면, 나중에 이 View를 유지보수하게 됐을 때 스토리보드 Inspector를 봐야할지, 코드를 고쳐야할지 꽤 헷갈릴 것 같다는 생각이 들었습니다.

저만 이런 불편감을 느끼는 건 아닐 것 같은데, 혹시 Xcode 개발을 할 때 주로 사용되는 기준이나 Best Practice가 있다면 공유해주시면 도움이 될 것 같습니다. 스토리보드를 아예 사용하지 않을 수 있다면 좋겠지만, UIKit에 익숙하지 않은 지금 단계에서는 효율이 많이 떨어질 것 같아서요.

감사합니다.

**Comment by JSKeum** [comment]
View를 Storyboard 위에서도 구현하고, 바깥에서도 구현하기 때문에 말씀하신 것처럼 일관성이 조금 떨어지는 듯한 느낌을 받을 수 있습니다. iOS 개발자들이 이 부분을 고민하고 있고, 어떤 팀에서는 Storyboard를 전혀 사용하지 않고 코드로만 View를 구현하기도 합니다. 워낙 다양한 방식으로 구현하기 때문에 Best practice가 이거다 라고 말하기는 어려울 것 같고, 몇가지 규칙을 정해 팀 내에서 공유를 하는게 좋을 것 같습니다. 한 예로 하나의 Storyboard에 하나의 View Controller만 연결하거나, View Controller 마다 Xib를 연결하는 규칙을 정할 수도 있습니다. 

그런데 불편함을 느끼신 Navigation Controller와 관련해서는 해결책이 있습니다. Stroyboard 상에서 Navigation Controller에 View Controller들을 연결하고, 각 push 가 발생할 때마다 데이터를 전달하는 방법으로 segue를 이용하면 됩니다. 시간이 부족해 이 방식은 저번 세미나에서 다루지 못했는데, 다음 번에 한번 다루도록 할게요.

참고 자료입니다.
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621413-performsegue
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621490-prepare

**Comment by shp7724** [comment]
좋은 설명 감사합니다. 답변이 된 것 같습니다 :)

**Comment by Ethan-MoBeau** [comment]
추가적으로 하나 코멘트 남기자면

개인이 작업할 때는 그냥 본인이 편한대로 하면 됩니다

다만 팀에 사람의 숫자가 늘어날 수록 storyboard 보다는 아예 뷰 구현 자체를 코드로 하는게 코드 리뷰와 유지 보수 측면에서 더 도움이 됩니다

실제로 회사 팀장님이 카카오 출신이신데, 말씀하시는 걸 들어보면 5명 이내의 소규모 팀에서는 사실 스토리보드 써도 각자 구현부를 잘 인지하고 있기만 하다면 유지보수에 큰 문제가 없지만 수가 10명이 넘어가는 순간 스토리보드 꼬인걸 발견하기도 어렵고 고치기도 어렵다는 말씀을 하시더라구요.

진섭님이 말씀하신대로 best practice는 없으며, 팀의 상황에 맞게, 개인의 성향에 맞게 사용하시면 됩니다.

저는 개인적으로 언급해주신 뷰컨 1 - storyboard 1 매칭 시켜놓고 데이터 전달이나 push, present 등 view 이동은 코드로 구현하는 걸 선호하는 편입니다. 질문자분도 개발을 하시다보면 아 이게 편하네, 이게 불편하네 하는게 느껴지실 테니 차차 본인에 잘 맞는 방법을 찾아나가시면 좋을 것 같습니다.
