### ISSUE TITLE
[PyCharm] Invalid Python interpreter selected for the project 오류

### ISSUE THREAD

**Issue by minkyu97** [wafflestudio/19.5-rookies#265]
안녕하세요 백엔드 세미나를 듣고 있는 이민규입니다. 

어차피 runserver 등의 명령들은 venv 가상환경에서 진행되므로 일단 과제0은 정상적으로 완료했습니다. 그런데 에디터에 문제가 있는 것 같습니다. system interpreter를 사용하면 제가 가상환경에 깔아놓은 library들이 인식이 되지 않아서 자동완성이 작동하지 않고, 원래대로 venv/bin/python 파일을 interpreter로 설정하면 Invalid Python interpreter selected for the project 라고 뜨네요... 구글링을 통해서도 마땅한 해결책을 찾지 못했는데 혹시 무엇이 문제인지 알 수 있을까요?
<img width="982" alt="Screen Shot 2021-09-02 at 12 31 45 AM" src="https://user-images.githubusercontent.com/71511067/131700873-4cdca626-2d31-4733-8658-72fd88aa054f.png">

**Comment by gina0605** [comment]
`runserver` 등을 할 때 사용한 것과 같은 가상환경을 선택하신 건가요? 붉은 글씨로는 (assignment0)이라고 나오는데 오른쪽에 잘려서 보이는 경로에는 assignment0/ 다음에 venv가 있는 것이, 가상환경을 잘못 선택하신 것이 아닐까 싶습니다. 아니면 혹시 가상환경을 만든 후 가상환경 폴더를 이동한 적이 있으신가요? 가상환경을 activate시키는 코드는 그 절대 경로가 하드코딩되어 만들어지기 때문에 위치를 옮길 경우 에러가 발생할 수 있습니다

**Comment by minkyu97** [comment]
`runserver`등을 터미널에서 사용할 때에도 assignment/venv/bin/activate 를 통해서 가상환경을 활성화 시켰고, 오른쪽에 잘린 부분의 파이썬 인터프리터의 경로도 assignment/venv/bin/python 입니다...
다만, 명령어 연습을 위해 파이참에 프로젝트를 불러올 때 기본적으로 만들어주는 venv폴더를 지우고 `python -m venv venv`를 통해 새로 venv폴더를 만들어서 사용 중이었는데 혹시 이게 문제일까요?? 해결 방법이 있을까요?

**Comment by minkyu97** [comment]
gina0605/
지적하신 부분이 제가 제대로 이해했는지는 모르겠습니다만, 인터프리터의 경로는 assignment0/venv/bin/python 으로 제대로 설정되어 있었는데 말씀하신대로 다른 경로에 문제가 있는지 찾아보다보니 git root가 엉뚱한 곳으로 설정되어있어서 git root를 `waffle-rookies-19.5-backend-0` 폴더로 바꿔준 뒤에 다시 assignment0/venv/bin/python 파일을 인터프리터로 설정하니 해결이 되었습니다. 감사합니다!

**Comment by minkyu97** [comment]
추가) 제 추측으로는 가상환경 폴더를 다른 곳으로 이동하지는 않았지만 줌 세미나를 들을 때 알려주신 커맨드를 연습해보기 위해 파이참에서 기본으로 만들어준 venv 폴더를 삭제하고 `python3 -m venv venv`명령어로 새로 가상환경을 만들어줬는데 아마 그 과정에서 꼬인 것 같습니다.
