### ISSUE TITLE
GitHub Desktop에 관한 질문

### ISSUE THREAD

**Issue by ZALF0615** [wafflestudio/19.5-rookies#266]
저번 OT 때도 git을 사용할 때 cmd 등 프롬프트 창?을 이용해서 여러 기능들을 사용했었던 것 같은데,
GitHub Desktop 이라는 프로그램을 사용하면 비슷한 기능이 생각보다 많이 사용이 가능하더라고요 (repository 만들기, close, push, commit 등등...)
프롬프트 창을 이용하는 것이랑, GitHub Desktop을 이용하는 것이랑 각자의 장단점이나 Desktop에서는 사용할 수 없는 기능 등이 있나요??

**Comment by woohm402** [comment]
일단 cmd같은 커맨드 라인 툴을 사용하는 건 `CLI` (command line interface) 라고 하고, github desktop처럼 버튼 투르고 막 이쁘게 보이는 건 `GUI` (graphic user interface) 라고 합니다.

오티 때 제가 github desktop 쓰지 말고 cli로 처리하는 걸 추천드린다고 말씀드렸었는데, 일단 특징부터 비교해보자면

---

1. CLI
    - 터미널 화면에 코드 (커맨드)를 입력하여 모든 작업을 수행
    - 뭘 하고 있는 건지 눈에 잘 보이지 않아서 진입장벽이 다소 있는 편
2. GUI 장점
    - 프로그램을 켜고 버튼이나 인풋 등을 이용하여 작업을 수행
    - 뭘 하고 있는 건지 눈에 보임

---

이외에 할 수 있는 기능의 차이는 딱히 없을 거예요. 그런데 제가 CLI를 추천드린 이유는 다음과 같습니다.

1. GUI는 뭔지 모르고 이상한 걸 클릭할 확률이 높습니다. CLI는 잘못 입력하면 입력이 안 되지만, GUI는 잘못 입력해도 동작합니다. 즉 깃이 꼬일 확률이 더 높다는 걸 의미하는데, 깃은 한 번 꼬이면 상당히 귀찮아집니다. 때문에 정확히 공부하고 정확한 커맨드를 입력하기에는 CLI가 좋습니다.
2. 개발을 하다 보면 실행해야 할 프로그램이 굉장히 많습니다. 구글링을 위한 브라우저, 코드 작성을 위한 에디터 또는 IDE, 그리고 세션별 빌드 확인용 프로그램 (포스트맨, 에뮬레이터, 브라우저 등), 터미널, 슬랙, 카톡, 노션 정도가 항상 켜져 있습니다. 여기에 github desktop까지 켜게 된다면 (별 거 아닌 것 같아도) 은근 스트레스가 될 수 있습니다. (본인에게도 컴퓨터에게도)
3. 나중에는 결국 CLI에 익숙해져야 합니다. aws 서버 접속이나 `npm` / `pip` 등을 이용한 패키지 관리 및 스크립트 실행 등 대부분의 작업이 CLI를 통하기 때문에, CLI에 미리 익숙해지시는 게 좋습니다.
4. `tig` 등의 외부 프로그램을 확장 설치해서 사용하기에도 CLI가 유리합니다.

---

열심히 말했는데 어디까지나 개인적인 의견입니다! github desktop 사용하고 싶으시다면 사용해도 괜찮습니다. 다만 제가 알기로 주변 모든 분들이 CLI를 사용하고 계셔서 troubleshooting이 다소 힘드실 수 있습니다.

**Comment by kohandy1902** [comment]
저도 CLI와 GUI에 대해 개인적인 의견 남기겠습니다.

앞서 현민님이 말씀해주신대로 CLI는 진입장벽이 다소 있는 편이고 GUI는 조금 더 쉽습니다. 그렇기에 git에 익숙치 않으시다면 GUI 방식을 써도 괜찮을 것 같습니다. 처음에는 저도 GUI를 사용했고, 이 방법을 써가며 git의 사용법을 익혔습니다. (staging, commit, push 등의 과정을 직관적으로 눈으로 확인할 수 있고 커밋이력 또한 예쁜 그래프로 보여주어 알기 편했습니다.) 하지만 git에는 이것 말고도 수많은 기능과 옵션이 있습니다. (stash, rebase, cherrypick, etc.) 이러한 기능을 이용하려면 (사실 쓸 일이 많이는 없지만..) SHA-1값이나 다양한 command와도 친밀해질 필요가 있는데, 이들 중에는 GUI에서 지원하지 않는 것이 많습니다. 따라서 사실 GUI를 쓰시더라도 언젠가는 CLI와 친밀해져야 하긴 합니다. 그렇기에 GUI로 git과 조금 더 익숙해졌다면 CLI를 써보시는 것을 추천드립니다.

어디까지나 저도 개인적인 의견입니다! 본인에 맞는 것을 사용하시는게 가장 좋은 것 같습니다. 감사합니다.

**Comment by woohm402** [comment]
@ZALF0615 해결되셨나요?

**Comment by woohm402** [comment]
@ZALF0615 해결되셨나요?

**Comment by ZALF0615** [comment]
> @ZALF0615 해결되셨나요?

앗 넵 해결 됐습니다.. ㅠ 혹시 질문 해결되면 해결됐다는 마크를 어디다가 표시하는 게 좋을까요??

**Comment by woohm402** [comment]
> > @ZALF0615 해결되셨나요?
> 
> 앗 넵 해결 됐습니다.. ㅠ 혹시 질문 해결되면 해결됐다는 마크를 어디다가 표시하는 게 좋을까요??

해결됐다는 코멘트 달고 close해주시면 됩니다! :+1:

**Comment by ZALF0615** [comment]
앗 넵 알겠습니다!! 다들 답변 주셔서 감사합니다 ㅠ

**Comment by ZALF0615** [comment]
해결되었습니다! 답변주신 분들 모드 감사합니다!
