### ISSUE TITLE
과제 7번 관련 질문

### ISSUE THREAD

**Issue by hansmaan** [wafflestudio/19.5-rookies#267]
7번에서 postman을 통해 get api/v1/results/{surveyresult_id}를 호출하라고 기재되어 있어서, 제가 따로 구현해야 하는 부분이 없는 것으로 이해했습니다. 그러나, 호출해보면 아래 사진들 처럼 나옵니다.

![스크린샷, 2021-09-02 14-34-00](https://user-images.githubusercontent.com/88359757/131788373-05c308c0-0293-4d2f-b2f2-e562056745b1.png)

vscode 터미널에 가보면 아래와 같이 나오는데, 
![스크린샷, 2021-09-02 14-33-59](https://user-images.githubusercontent.com/88359757/131788412-18e01b2c-c58b-4211-8eff-63ebb395ff1f.png)

처음에는 오류라고 생각해서, primary key row와 관련하여 구글링해보았으나, 위와 같이 { ~~~ }를 통해 primary key row를 호출해내는 방법론은 찾아내지 못했습니다.

vscode 터미널에서 {surveyresult_id}를 'id'의 일종으로 인식하는 것으로 보아, urls에 제가 추가적인 구현을 해야하는 것으로 보여지는데, 문제의 의도가 맞는것인지 아니면 제가 오류에 봉착한 것인지 여쭙고 싶습니다.

**Comment by woohm402** [comment]
`{surveyresult_id}` 자리에 surveyresult의 id를 넣으셔야 합니다?

**Comment by hansmaan** [comment]
> `{surveyresult_id}` 자리에 surveyresult의 id를 넣으셔야 합니다?

surveyresult의 id를 넣는다는 것이 {surveyresult_id}가 들어갈 자리에 1이나 2같은 id를 넣는 것을 말씀하시는 건가요?

**Comment by Jhvictor4** [comment]
넵 보통 중괄호 표시는 API에서 parameter를 의미합니다. 1, 2, 3 등의 숫자를 넣어주세요 :)

해당 개념은 세미나 자료에서 URL parameter, Query Parameter 따위의 개념으로 설명드린 바가 있습니다

**Comment by hansmaan** [comment]
> 넵 보통 중괄호 표시는 API에서 parameter를 의미합니다. 1, 2, 3 등의 숫자를 넣어주세요 :)
> 
> 해당 개념은 세미나 자료에서 URL parameter, Query Parameter 따위의 개념으로 설명드린 바가 있습니다

제가 착각을 했네요. 정말 감사드립니다!

**Comment by woohm402** [comment]
@hansmaan 다른 분들을 위해 이슈 제목 변경 부탁드립니다~

**Comment by hansmaan** [comment]
> @hansmaan 다른 분들을 위해 이슈 제목 변경 부탁드립니다~

넵
