### ISSUE TITLE
Backend 과제 9번 관련 질의

### ISSUE THREAD

**Issue by hansmaan** [wafflestudio/19.5-rookies#268]
9번에서 window, mac, Ubuntu를 제외한 나머지 입력 사항에 대해서는 400 Bad Request를 반환하라고 기재되어 있습니다. 근데, OperatingSystem의 종류를 보면 위의 3가지와 Linux까지 해서 총 4가지입니다. 그렇다면 OperatingSystem에서 Linux는 제거하고 진행해도 되는 것인가요? 아니면 4가지 다 올려놓은 상태로 Linux를 포함한 그 외의 것들을 대상으로 400 Bad Request를 반환해야하는 것인지 여쭙고 싶습니다.

**Comment by Jhvictor4** [comment]
Linux는 제가 Ubuntu (Linux) 를 코드상에서 착오가 있었던 탓에 잘못 기입한 더미 데이터입니다 (ㅠ). 필터를 걸면 설문 결과로는 아무것도 나타나지 않을 것이니 무시해주시면 감사하겠습니다.

**Comment by Jhvictor4** [comment]
아뇨,, 그냥 400처리해주세요 !

**Comment by hansmaan** [comment]
넵 감사합니다!
