### ISSUE TITLE
iOS 과제 StackView, AlertView에 관한 질문

### ISSUE THREAD

**Issue by VioletXF** [wafflestudio/19.5-rookies#272]
1. 과제 스펙을 보면 모든 View에 Auto Layout을 적용하라고 나와있는데, StackView의 자식 View들에도 적용해야 하나요?
2. AlertView를 띄워야하는 조건이 이상한 것 같습니다. username이 (1)두 글자 이하일 때 (2)두 글자 이상이어야 한다는 경고를 띄우라고 하셨는데, 둘 중 하나를 (1)한 글자 이하 또는 (2)세 글자 이상으로 바꾸는 것이 적절해 보입니다.

**Comment by JSKeum** [comment]
Stack view를 사용하시는 경우 Stack View의 property들을 이용해 layout을 설정하시면 됩니다. 

'세 글자 이상이어야 합니다'로 해주세요~

**Comment by VioletXF** [comment]
넵 감사합니다!
