### ISSUE TITLE
Android Kotlin 개념 중 R.drawable의 type에 대한 질문입니다

### ISSUE THREAD

**Issue by dongho-Han** [wafflestudio/19.5-rookies#274]
안녕하세요.
과제와 관련된 질문은 아니지만, 안드로이드장님께서 추천해주신 Android kotlin 기초 codelab 실습을 따라하다 궁금한 점이 생겨 질문 올립니다.
01.3 Image resources and compatibility의 coding challenge를 수행하다 생긴 궁금증입니다.
Challenge link : https://developer.android.com/codelabs/kotlin-android-training-images-compat#7
code link : https://github.com/google-developer-training/android-kotlin-fundamentals-apps/blob/master/DiceRollerFinal-challenge/app/src/main/java/com/example/android/diceroller/MainActivity.kt
Challenge에서 Tip으로 주어진 getRandomDiceImage 함수의 경우 Int를 return type으로 가지는데, 이 구현은 code link 내 57~68 line에 구현되어 있습니다. 여기서 제가 가진 궁금증은, 결국 return으로 보내는 객체(?)가 R.drawable.dice_x 일텐데, 이것이 왜 int type인지 궁금합니다. 결국 이 객체를 setImageResource의 input으로 입력하는 것도 이해했는데, 저 객체가 int type인 게 와닿지 않아 질문드립니다.
현재까지 구글링을 해보았으나, 명쾌한 설명이 없어 질문을 올려봅니다.
감사합니다.

**Comment by VioletXF** [comment]
일종의 id값이라고 이해하시면 됩니다. res/drawable 폴더에 이미지를 넣고 빌드하면, 자동으로 R.java라는 파일에 해당 이미지의 id값이 int형으로 선언됩니다.

**Comment by dongho-Han** [comment]
아 id값으로 이해하니 편하네요 감사합니다!
