### ISSUE TITLE
Backend 과제 질문(6번, 8번, 번외)

### ISSUE THREAD

**Issue by OTY-Math** [wafflestudio/19.5-rookies#275]
안녕하세요 과제 중 질문이 생겨 이렇게 남깁니다.
저는 wsl2를 이용해 ubuntu를 사용하고 있습니다.

![survey_surveyresult 1](https://user-images.githubusercontent.com/87603284/131901189-74f33fc2-37c4-4afd-bdfd-90c5756fe99b.PNG)
![질문](https://user-images.githubusercontent.com/87603284/131901332-4dc2cf8e-b29a-426a-a0bd-d9ca1d3f34b2.PNG)

6번의 경우, 제가 survey_surveyresult, survey_operatingsystem table을 DataGrip을 이용해 출력하고자 했는데
1번째 사진과 같이 한글이 깨졌습니다. 구글링 결과 utf-8로 출력하면 해결되야 한다고 해서, 2번째 사진과 같이 setting에서 encoding 부분을 전부 utf-8로 바꿔주었음에도 여전히 깨져서 출력되었습니다.  혹시 해결책이 따로 있나 궁금합니다.

8번에서는 이미 짜여져 있던 get_survey_results 함수에서 GET request를 받았을 때 params =request.GET.get('os')라는 코드가 있는데 이 코드의 역할을 이해하지 못했습니다. 구글링으로도 명확한 답을 얻기 어려워 질문 드립니다.

번 외로, mysql을 사용하려 할때, 어떤 페이지에선s mysql -u root -p를 사용하라 하고, 어디서는 sudo /urs/bin/mysql -u root -p를 사용하라고 합니다. 후자가 정확히 경로를 지정해서 sudo로 강제실행시키는 느낌인데, 저는 후자만 정상적으로 기능하고 전자는 작동하지 않았습니다. 특별한 이유가 있을까요?

**Comment by gina0605** [comment]
우선, 첫 번째 사진은 Datagrip이 아니라 mysql cli로 보입니다. 그렇기에 두 번째 사진처럼 datagrip에서 인코딩 설정을 하더라도 소용이 없는 것이지요. mysql cli에서 인코딩 설정은, cli를 실행시킬 때 `mysql --default-character-set=utf8`처럼 해주면 된다네요. 제가 해보진 않아서 확실하게는 답을 못 드리겠네요. 이슈 #219 도 관련 있는지 한 번 확인해보세요.

`params = request.GET.get('os')`는 9번을 위한 힌트로, 8번에서는 필요하지 않은 것이 맞습니다. [관련 문서](https://docs.djangoproject.com/ko/3.0/ref/request-response/#django.http.QueryDict)입니다.

sudo는 루트 권한을 가진 채로 명령어를 실행한다는 뜻입니다. mysql의 경우에는 root 유저로 접근하기 위해서는 sudo가 필요하다고 합니다. root가 아닌 유저(가령 3번에서 만들었을 waffle-backend 유저)로 mysql에 접근하시면 sudo를 필요로 하지 않을 것입니다.

**Comment by OTY-Math** [comment]
@gina0605 
![survey_surveyresult](https://user-images.githubusercontent.com/87603284/131917064-d854e54a-b92a-4fb5-ac17-ec801c3f87fc.PNG)
첫번째 사진은 제가 첨부를 잘못했네요 ㅠㅠ datagrip에서도 같은 문제가 발생하고 있습니다...ㅠ

2,3번째 질문은 이해되었습니다 감사합니다!

**Comment by gina0605** [comment]
혹시 operating_system table은 잘 보이나요? 데이터 조회가 아니라 download_survey 부분에서 인코딩이 깨진 것이 아닐까 싶습니다. download_survey에 인코딩 추가해서 다시 실행해보시겠어요? (이슈 219 참고)

데이터가 중복해서 들어가는 문제는 테이블을 아예 drop한 후 다시 migrate하거나, mysql delete query 이용해서 row들 지워주시면 될 거예요
