### ISSUE TITLE
Backend seminar0 requirements.txt 설치 issue

### ISSUE THREAD

**Issue by Victini00** [wafflestudio/19.5-rookies#277]
wsl2로 ubuntu 18.04를 사용하고 있습니다.
vs code에서 bash 터미널을 사용하는데, pip3 install -r requirements.txt 명령어가 잘 작동하지 않는 것 같습니다.
![requirements issue1](https://user-images.githubusercontent.com/87114100/131910495-9b30298c-006f-4802-86c9-3b0fb508ba01.png)
![requirements issue2](https://user-images.githubusercontent.com/87114100/131910601-38d214cc-32d5-48c9-84bc-e4f82ce00a81.png)
![requirements issue3](https://user-images.githubusercontent.com/87114100/131910697-dac59f98-963e-4b90-8243-097a4d7170ad.png)
 mysqlclient와 django가 위와 같은 문제로 설치되지 않아 pip install 명령어로 수동 설치를 해 주었는데, 이 이후로 python manage.py migrate나 python manage.py help 명령어도
[django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?]
위와 같은 명령어로 실행되지 않습니다. pip list를 통해 확인하면 mysql과 mysqlclient가 잘 설치되어 있는 것 같습니다.

**Comment by gina0605** [comment]
지금 `pip install -r requirements.txt`에서는 mysqlclient 설치에서 에러가 나는 것으로 보이는데, 따로 `pip install`을 했을 때는 에러 없이 설치가 되었다는 말씀이신가요? 같은 파이썬(같은 가상환경)을 사용하고 있는 것이 맞는지 확인해보시겠어요? `which python` 같은 명령어를 통해 사용중인 파이썬의 경로를 확인할 수 있습니다.

**Comment by Victini00** [comment]
> 지금 `pip install -r requirements.txt`에서는 mysqlclient 설치에서 에러가 나는 것으로 보이는데, 따로 `pip install`을 했을 때는 에러 없이 설치가 되었다는 말씀이신가요? 같은 파이썬(같은 가상환경)을 사용하고 있는 것이 맞는지 확인해보시겠어요? `which python` 같은 명령어를 통해 사용중인 파이썬의 경로를 확인할 수 있습니다.
> 
> 그리고 mysqlclient 설치 관련 오류는 이슈 #235 확인해보시면 좋을 것 같습니다

**Comment by Victini00** [comment]
> > 지금 `pip install -r requirements.txt`에서는 mysqlclient 설치에서 에러가 나는 것으로 보이는데, 따로 `pip install`을 했을 때는 에러 없이 설치가 되었다는 말씀이신가요? 같은 파이썬(같은 가상환경)을 사용하고 있는 것이 맞는지 확인해보시겠어요? `which python` 같은 명령어를 통해 사용중인 파이썬의 경로를 확인할 수 있습니다.
> > 그리고 mysqlclient 설치 관련 오류는 이슈 #235 확인해보시면 좋을 것 같습니다

**Comment by Victini00** [comment]
답변 감사합니다.  #235 역시 확인해봤었는데, 여전히 잘 안 되는 것 같습니다. 
![piplist](https://user-images.githubusercontent.com/87114100/131914469-c7c83c10-4748-4f57-b471-ede7dd788a7f.png)
which python을 사용해보았는데, 동일한 가상환경을 사용하고 있는 것 같습니다.
이전에 anaconda를 설치한 적이 있어 파일 탐색기에 mysql을 검색한 결과 mysql 파일이 anaconda의 패키지 안에 들어있었는데, 혹시 이와 관련이 있는 문제인가요?

**Comment by Jhvictor4** [comment]
https://victorydntmd.tistory.com/275

여기 참고해보시겠어요? 설치 경로를 못 찾아주고 있는 것 같습니다.

**Comment by Victini00** [comment]
whl파일 수동설치로 해결했습니다.. 감사합니다!
