### ISSUE TITLE
Python 가상환경 버전 변경

### ISSUE THREAD

**Issue by kwonlauren** [wafflestudio/19.5-rookies#280]
requirements에 python의 버전이 3.8이어야 한다고 나와있는데 제 컴퓨터에는 3.9, 3.8이 모두 설치되어 있는 것으로 나오는데, 3.8로 가상환경을 만들려고 하면 에러가 뜹니다. 어떻게 해결해야 하나요? 위에는 python3.8이 설치되어 있는 경로에서 3.8이 있음을 확인한 것입니다. 
<img width="730" alt="스크린샷 2021-09-03 오후 12 09 43" src="https://user-images.githubusercontent.com/81508275/131944876-b2c8c2a9-761a-47ac-806b-6494862d6f0d.png">

**Comment by Jhvictor4** [comment]
이것은 파이참을 사용하시는게 더 편리합니다.

파이참 상단 바 > Find actions > Switch Python Interpreter 로 들어가시면 기존 인터프리터를 사용할 수도 있고, 새 가상환경을 만드실 수도 있습니다. Add Interpreters > New enviroment 에서 3.8 버전을 base interpreter로 설정하시면 경로에 새 venv가 잘 생기실 거에요

**Comment by VioletXF** [comment]
Homebrew의 경우, python@3.9를 먼저 설치한 후 python@3.8를 설치하게 되면 다음의 안내문구에서 나타나는 것처럼 python@3.8을 PATH에 등록하지 않습니다.
```
$ brew info python@3.8
python@3.8: stable 3.8.1 (bottled) [keg-only]
...
==> Caveats
Python has been installed as
  /usr/local/opt/python@3.8/bin/python3
...
python@3.8 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have python@3.8 first in your PATH run:
  echo 'export PATH="/usr/local/opt/python@3.8/bin:$PATH"' >> ~/.bash_profile

For compilers to find python@3.8 you may need to set:
  export LDFLAGS="-L/usr/local/opt/python@3.8/lib"

For pkg-config to find python@3.8 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/python@3.8/lib/pkgconfig"
```
위에서 안내하는대로 3.8을 PATH에 등록하시거나, `/usr/local/opt/python@3.8/bin/python3.8 -m venv waffle_backend`와 같이 경로를 직접 명시해서 쓰시면 됩니다. (단, 전자의 경우 python3을 입력해도 3.9가 아닌 3.8을 실행하게 됩니다.)

**Comment by kwonlauren** [comment]
확인해보니 python --version에 3.9만 나오는거로 봐서 3.8이 제대로 설치가 안되어있는 것 같아서 삭제하고 다시 설치하려고 하다가 이런 메세지가 떴는데 뭐를 입력해야되나요?
![image](https://user-images.githubusercontent.com/81508275/131946838-afeb0ed5-c2ff-4688-9d78-79023e6f19c0.png)

**Comment by VioletXF** [comment]
python --version은 설치되어 있는 모든 파이썬의 버전을 조회하는 명령이 아닙니다.
그리고 brew를 통해 설치한 프로그램들은 rm으로 지우지 마시고, `brew uninstall python@3.8`로 지우시면 됩니다.

**Comment by kwonlauren** [comment]
알려주신 명령어대로 python@3.8을 삭제했는데 밑에 python3 --version에 3.8.2가 뜨면 제대로 삭제가 되지 않은것 아닌가요?ㅠㅠ
<img width="761" alt="스크린샷 2021-09-03 오후 2 04 37" src="https://user-images.githubusercontent.com/81508275/131953206-dd496103-34cf-41b0-9a40-1f0e7d20bfa7.png">

**Comment by kwonlauren** [comment]
그리고 저는 open project 할 때 가상환경 설정하는 팝업창이 뜨지 않았는데 터미널에서는 venv가 나오고, venv폴더는 생성되지 않은 것 같습니다. 이것은 어떻게 해결해야하나요?ㅠㅠ

<img width="1032" alt="스크린샷 2021-09-03 오후 2 11 41" src="https://user-images.githubusercontent.com/81508275/131953759-6c6294c4-c3fd-460f-8dac-9fba2f71d762.png">

**Comment by VioletXF** [comment]
brew를 통해 설치하셨던 버전은 3.8.12고, 지금 python3 --version으로 확인되는 버전은 3.8.2네요. 아마 Homebrew가 아닌 다른 방법을 통해 설치된 버전같은데(아나콘다 등), `which python3`을 통해 설치된 경로를 확인하실 수 있습니다.

**Comment by VioletXF** [comment]
> 그리고 저는 open project 할 때 가상환경 설정하는 팝업창이 뜨지 않았는데 터미널에서는 venv가 나오고, venv폴더는 생성되지 않은 것 같습니다. 이것은 어떻게 해결해야하나요?ㅠㅠ

#237 에서 설명한 방법을 통해 venv를 생성해보세요

**Comment by VioletXF** [comment]
이야기가 좀 꼬인 것 같은데, 정리하자면
1. Python 3.8.12가 원래 설치되어 있었는데, PATH에 등록되지 않아 `zsh: command not found: python3.8`이 뜬 것입니다. 여기서 python3.8이 제대로 설치되지 않은 것으로 착각하셔서 rm을 진행하신걸 보고 필수 파일이 제거됐을 수도 있을 것 같아, 꼬이는 것을 방지하기 위해 `brew uninstall python@3.8`을 실행할 것을 제안드렸습니다. 그러나 원하신다면 `brew install python@3.8`을 통해 재설치하실 수 있습니다.
2. 지금 3.8.12는 제대로 제거가 된 상태고, 3.8.2는 다른 경로를 통해 설치하신 python인 것 같습니다.
3. 현재 활성화된 venv는 waffle_backend의 venv가 아닌 것 같습니다. #237 참고하시어 waffle_backend에 venv를 생성하시고, `source venv/bin/activate`로 활성화해보세요.

**Comment by kwonlauren** [comment]
넵 해결된 것 같습니다. 감사합니다!!
