### ISSUE TITLE
세미나 4에 사용될 서버 배포 스택 관련 질문

### ISSUE THREAD

**Issue by woohm402** [wafflestudio/19.5-rookies#281]
안녕하세요, 프론트엔드 세미나 진행중인 우현민입니다.

프론트엔드 세미나 4 과제 출제를 위해 작은 서버를 하나 파고 있는데, 배포 스택을 아직 결정하지 못했습니다.
먼저 현재 사용된 스펙은 다음과 같습니다.

```
DB: postgresql, (typeORM)
Framework: NestJS
```

나머지 계획중인 부분은 다음과 같습니다.

```
Docker: 고민중
server: EC2 t3.nano
DB: server 인스턴스에 그냥 띄움 (크리티컬한 데이터도 아니고 용량도 얼마 없어요)
```

도커를 띄우는 게 맞을지 없어도 될지, DB는 저대로 인스턴스에 같이 띄워도 괜찮을지, EC2를 굳이 사용해야 할지 아니면 더 저렴한 방안이 있을지 고민중입니다.

루키분들 계정을 수동 생성해드려야 하기 때문에, psql 접속은 할 수 있어야 합니다.

**Comment by Jhvictor4** [comment]
EC2에 서버, 디비 모두 도커로 띄우는게 가장 간단할 것 같습니다.

디비 접속 및 마운팅 관련 설정은 밑의 사이트 참고하시면 될 것 같습니다.
https://judo0179.tistory.com/96

도커 빌드 관련해서 찾아볼 것이 필요하시면
https://wlswoo.tistory.com/41

참고하시면 될 것 같습니다

**Comment by gyusang** [comment]
t3.nano에서 메모리 부족으로 nest build가 실패할 수 있습니다. Github Action에서 컴파일을 하고 js파일만 올리는 방법이 있고, t3.micro를 쓰는 방법이 있습니다.
도커는 개발자가 원하는대로 선택하면 될 것 같습니다.

**Comment by woohm402** [comment]
@gyusang 현재 예약 인스턴스 남아있는 현황이 어떻게 되나요? 남아있는 마이크로 예약 인스턴스가 있다면 `micro` 사용하고 아니면 말씀해주신 방법대로 처리하여 nano 사용하겠습니다.

**Comment by gyusang** [comment]
현재 사용중이지 않은 예약 인스턴스는 없습니다. (만약 있다면 심각한 낭비)
t3 class에서 필요한 사이즈의 인스턴스 활용하시면 됩니다.

**Comment by woohm402** [comment]
@Jhvictor4 @gyusang 답변 감사합니다! 집가서 도커 얹고 github action 으로 빌드 돌리고 나노에 띄워보겠습니다 :+1:

**Comment by gyusang** [comment]
네 어차피 잘 안되면 종료하고 micro로 변경하면 되니 nano로 시작하는 것도 괜찮습니다

**Comment by woohm402** [comment]
t2 micro 로 배포했고 빌드 그냥 해도 서버 안터지는거같습니다.

**Comment by gyusang** [comment]
> t2 micro 로 배포했고 빌드 그냥 해도 서버 안터지는거같습니다.

@woohm402 ??? t2 쓰시면 안됩니다! t3로 바꿔주세요
micro는 안터지고 스누보드는 nano가 터지더라고요.
