### ISSUE TITLE
backend 과제 9번, 404 NOT FOUND에 대해 질문 드립니다

### ISSUE THREAD

**Issue by ggumnet** [wafflestudio/19.5-rookies#282]
과제 9번에서 status code가 404 NOT FOUND가 되도록 하라는 것이 

![image](https://user-images.githubusercontent.com/88571662/131955245-e9def506-57ce-4412-bdc4-4998a4bd1de1.png)

get_object_or_404를 사용했을 때와 마찬가지로 위와 같은 화면이 나오면 충분한 것인지, 아니면 다른 의미가 있는 것인지 궁금합니다.

**Comment by Jhvictor4** [comment]
넵 충분합니다 :) 문자 그대로, postman 따위의 툴에서 http status code 가 404 이면 됩니다.

**Comment by ggumnet** [comment]
감사합니다 :)
