### ISSUE TITLE
python 재설치 후 bad interpreter 오류

### ISSUE THREAD

**Issue by kwonlauren** [wafflestudio/19.5-rookies#283]
기존에 컴퓨터에 설치되어 있던 파이썬 3.8, 3.9를 모두 삭제하고 3.8로 재설치한 상태입니다. 
bad interpreter 오류가 떠서 검색해 보았더니 심볼릭 링크의 문제라고 하는데 어떻게 해결할지 모르겠어서 질문 남깁니다. 

<img width="928" alt="스크린샷 2021-09-03 오후 3 41 06" src="https://user-images.githubusercontent.com/81508275/131961696-c94b94cc-e900-4557-85b2-8522b5dace4e.png">

**Comment by VioletXF** [comment]
아래 명령을 입력한 후 다시 시도해보세요
```
brew link python3
```

**Comment by kwonlauren** [comment]
감사합니다!
