### ISSUE TITLE
backend 과제 9, 10번 status code 관련 질문입니다.

### ISSUE THREAD

**Issue by ding-young** [wafflestudio/19.5-rookies#284]
과제를 할 때 response의 status code를 특정하게 설정하는 것, 특히 에러를 일으키는 것과 관련해 궁금한 점이 생겼습니다. 
과제의 요구사항으로 특정 status code 를 반환하는 것'만' 신경쓴다면, 아래처럼
`raise Http404`
`return HttpReponseNotFound`
`return JsonReponse(~~~ , status=404)` 나 이와 유사하게 직접 response 인스턴스에 status code를 설정해주는 것 등등등
모두 Postman에서 확인했을 때 status code 는 의도한 대로 반환이 됩니다. (다만 Http404 같은 경우는 django에서 제공해주는 standard error page 를 볼 수 있었고, 나머지는 제가 원하는 메시지를 넣으면 그것이 나타나는 정도의 차이가 있었습니다. 이는 [장고 공식 문서의 view관련 문서](https://docs.djangoproject.com/en/3.2/topics/http/views/)에서도 설명을 찾아볼 수 있었습니다.)

1. 그 외에도 어떤 에러를 나타내는 status code를 반환하며 response 를 전달하는 여러 가지 방법이 있을텐데 그러한 방식들의 차이나, 특정한 상황에 맞는 선택이 있을까요?? (django에 대한 이해가 부족해 질문이 다소 막연해서.. 읽어볼 만한 관련 문서를 추천해주신다면 감사하겠습니다!)

2. 또한 get_object_or_404를 사용하지 말라고 하신 게 학습 목적 외에 특별한 이유가 있는지도 궁금합니다!

**Comment by Jhvictor4** [comment]
2번은 django에 대해 본격적으로 소개하기도 전에 과제를 진행하는 단계에서 shortcut을 쓰기보다는 뷰의 처리 로직을 간단하게나마 경험하시도록 하기 위함입니다.

1번의 경우, 네 맞습니다. 아주 다양한 방식이 있는데요, 뷰 관련 문서를 읽어보셨으면 직접 장고의 django.http.reponse 코드를 보시는 것도 좋을 것 같습니다. Http Response 안의 클래스들 뿐만 아니라 장고의 많은 클래스들은 Base class를 기반으로 각각의 특징을 더해나가는 방식으로 구현이 되어 있습니다.
제 짧은 식견으로는.. 보통은 그렇게 구현되어있는 에러를 바탕으로 프로젝트 단에서 개발자들이 직접 에러를 한번 더 추상화 하여 사용하는 것 같습니다 :)

**Comment by ding-young** [comment]
감사합니다. 코드를 직접 볼 생각은 못 해봤었는데, 한 번 살펴보겠습니다!
