### ISSUE TITLE
backend 과제 8번 operatingsystem id 접근 관련 질문입니다.

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#285]
안녕하세요. backend 과제에서 views.py를 수정하던 중, 어떻게 operatingsystem_id에 접근할 수 있는지 모르겠어서 issue를 남기게 되었습니다. operatingsystem 내 id는 멤버 변수가 아닌데 어떻게 접근할 수 있는지 궁금합니다! 과제에서 주어진 부분을 참고하여 첨부한 사진과 같이 해보고자 했는데, 이렇게 하면 `TypeError: 'OperatingSystem' object is not iterable`와 같은 에러가 뜹니다. 처음부터 접근 방식이 잘못된 것 같은데, 힌트 주시면 감사하겠습니다.
![issue](https://user-images.githubusercontent.com/84329238/131965664-0f62e778-a06d-45d0-8e5c-0f261406de9d.png)

**Comment by VioletXF** [comment]
migrations/0001_initial.py의 18번째 줄을 보시면 OperatingSystem에 id필드가 추가되는 것을 확인하실 수 있습니다.
따라서, OperatingSystem.objects.get(id=os_id)가 유효합니다. 그리고 get은 해당하는 오브젝트 하나만을 반환하므로, iterable하지 않습니다.

**Comment by kk0in** [comment]
> migrations/0001_initial.py의 18번째 줄을 보시면 OperatingSystem에 id필드가 추가되는 것을 확인하실 수 있습니다.
> 따라서, OperatingSystem.objects.get(id=os_id)가 유효합니다. 그리고 get은 해당하는 오브젝트 하나만을 반환하므로, iterable하지 않습니다.

**Comment by kk0in** [comment]
@VioletXF 
답변 달아주셔서 감사합니다.
그런데 과제 조건에서 get을 이용하라고 해서 저렇게 작성한 것인데, 혹시 get을 이용해서 여러 개의 오브젝트를 반환할 수 있는 방법이 있나요..?

**Comment by VioletXF** [comment]
id가 일치하는 row는 하나 뿐이기 때문에, 하나만 가져오셔서 serialize후 반환하시면 됩니다.

**Comment by kk0in** [comment]
@VioletXF 
음... 과제 내용을 보면 입력한 os_id와 일치하는 row를 전부 뽑아내야 하는 거 같은데, 이게 아닌가요..??

**Comment by woohm402** [comment]
@kk0in 이슈는 모든 대화가 끝나고 질문이 해결된 이후 닫아주셔야 합니다.

**Comment by kk0in** [comment]
@woohm402 github issue를 처음 다뤄봐서 뭔 줄 모르고 실수로 닫은 것 같네요.. 죄송합니다.

**Comment by esc5221** [comment]
OperatingSystem에서 os_id를 가져오고,
뽑아온 os_id로 SurveyResult에서 다시 필터링을 하셔야 될거 같아요

**Comment by Jhvictor4** [comment]
제대로 알려드리지 않은 부분이라 어려움이 많으실 것 같습니다.  ㅜ
Esc5221 님 말씀이 맞습니다. :)

**Comment by kk0in** [comment]
@esc5221 
필터링을 한다는 것이 어떻게 하는 것인지 설명 부탁드려도 될까요??

**Comment by VioletXF** [comment]
> 제대로 알려드리지 않은 부분이라 어려움이 많으실 것 같습니다. ㅜ
> Esc5221 님 말씀이 맞습니다. :)

8번은 survey_operatingsystem에서 id가 일치하는 row만 전달하면 되지 않나요? 왜 SurveyResult를 사용해야하는지 궁금합니다.

**Comment by esc5221** [comment]
> > 제대로 알려드리지 않은 부분이라 어려움이 많으실 것 같습니다. ㅜ
> > Esc5221 님 말씀이 맞습니다. :)
> 
> 8번은 survey_operatingsystem에서 id가 일치하는 row만 전달하면 되지 않나요? 왜 SurveyResult를 사용해야하는지 궁금합니다.

제가 9번과 착각해서 답변을 작성했네요. 세미나장님도 그러신 것 같습니다..!

**Comment by kk0in** [comment]
@VioletXF id가 일치하는 row가 하나만 있다고 하셨는데, os id는 일치하는 row가 여러 개 아닌가요??

**Comment by VioletXF** [comment]
survey_surveyresult와 착각하신 것 같은데, survey_operatingsystem 테이블에서는 유일합니다.

**Comment by kk0in** [comment]
아 제가 문제를 잘못 이해했었네요.. ㅜㅜ 감사합니다!!
