### ISSUE TITLE
Backend 과제 10번 관련 질문드립니다

### ISSUE THREAD

**Issue by jakdurider** [wafflestudio/19.5-rookies#286]
10번에서 get()을 사용하라고 되어있는데 이 방법으로 작성한 코드를 assignment0에 포함시켜야 하는것인가요?
혹은 get_object_or_404를 사용한 코드를 assignment0에 포함시키고 10번은 따로 결과만 스크린샷으로 제출하면 되는 것인가요?

**Comment by Jhvictor4** [comment]
무슨 말씀이신지 잘 이해하지 못한 것 같습니다.. 질문이 정확히 어떤ㄷ 뜻이실까요??

**Comment by jakdurider** [comment]
아아 9번에서 여기까지 개발한 내용을 assignment0 directory에 포함하라는 내용이 있어서 10번은 포함시키지 않는 것인지 혹은 10번의 내용을 8번을 처리할 때 적용해서 assignment0 directory에 포함시키라는 내용인지 헷갈려서 문의드렸습니다!

**Comment by Jhvictor4** [comment]
아 넵 ㅎㅎ 10번도 적용 부탁드려요!

**Comment by jakdurider** [comment]
감사합니다!
