### ISSUE TITLE
Backend 10번 os 로 Linux 가 들어올 때 질문드립니다.

### ISSUE THREAD

**Issue by ptkjw1997** [wafflestudio/19.5-rookies#287]
10번 문제 해결할 때, 조건으로 os 로는 Windows, MacOS, Ubuntu (Linux) 가 들어 올 때에만 처리를 진행하고 그 외에는 400 Bad Request 를 반환하라고 되어있는데, 

survey/management/commands/download_survey.py  23번째 줄부터 있는
    OperatingSystem.objects.get_or_create(name='Windows', price=200000, description="Most favorite OS in South Korea")
    OperatingSystem.objects.get_or_create(name='MacOS', price=300000, description="Most favorite OS of Seminar Instructors")
    OperatingSystem.objects.get_or_create(name='Linux', price=0, description="Linus Benedict Torvalds")

때문인지(이 부분은 추측입니다) OperatingSystem. 에 실제로 데이터는 없지만 object로(?) Linux 가 있습니다. 

문제가 get_object_or_404 를 안쓰는 만큼, 단순히 조건을 일일히 확인하는 것보다, 데이터베이스의 Object가 가지고 있는 값들을 알아서 확인을 하고 없는 데이터면 400 을 반환하는 방식으로 하는 것이 맞다고 생각하여 코드를 작성했는데, 이 경우 400 Bad Request 가 아니게 됩니다. 

그냥 단순히 인풋 비교를 통해서 결과를 반환하도록 해야 하는지 의문이 들어 이슈 올립니다.

**Comment by cs71107** [comment]
#268 이슈를 보시면 도움이 될 듯 합니다

**Comment by ptkjw1997** [comment]
아 이전 이슈를 안찾아봤네요. 죄송합니다. 이슈 닫을게요!
