### ISSUE TITLE
mysql service start fail

### ISSUE THREAD

**Issue by herry123435** [wafflestudio/19.5-rookies#288]
pip list에서 mysqlclient가 존재하는 것도 확인했고, sudo apt-get을 통해 mysql-server와 mysql-client도 설치하였는데, 다음과 같이 mysql이 시작되지 않습니다.

혹시 해결 방법을 아시는 분이 계시면 알려 주시면 감사하겠습니다.
![image](https://user-images.githubusercontent.com/21451248/131991155-3b03c4ac-8ff9-4596-b6e9-698ac9d38bbc.png)

**Comment by VioletXF** [comment]
해당 에러와 관련된 StackOverflow 글을 발견하여 링크를 남깁니다.
https://stackoverflow.com/questions/44247342/starting-mysql-on-bash-on-ubuntu-on-windows

**Comment by Hank-Choi** [comment]
wsl사용 중이신 것 같은데 https://github.com/wafflestudio/19.5-rookies/issues/261 해당 이슈와 같은 문제는 아닌지 확인 부탁드립니다.

**Comment by herry123435** [comment]
감사합니다! stackoverflow 글대로 하니까 잘 되네요
