### ISSUE TITLE
Android assignment0에서  EditText사용에 대해 질문드립니다.

### ISSUE THREAD

**Issue by Whiteppanda** [wafflestudio/19.5-rookies#289]
'''kotiln

        numberInput.addTextChangedListener(object : TextWatcher{
            override fun afterTextChanged(p0: Editable?) {

            }
            override fun beforeTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {

            }
            override fun onTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
                val number = numberInput.getText().toString() + " "
                numberInput.setText(number)
            }
        })

'''

EditText에 1234를 입력할 때 1 2 3 4 이런식으로 보여지게 하고 싶어서 TextWatcher로 시도해보았는데
에뮬레이터가 멈춥니다... 왜 그런지 알고 싶습니다..(제가 공부가 너무 오랜만이라 너무 기초적인것도 모르겠네요 ㅠㅠ)

**Comment by Whiteppanda** [comment]
감사합니다 덕분에 잘 찾아서 해결했어요!

**Comment by sanggggg** [comment]
@Whiteppanda

<img width="194" alt="Screen Shot 2021-09-04 at 7 46 24 PM" src="https://user-images.githubusercontent.com/37951125/132091898-a7af2bbf-3f53-428a-b5cf-3c2a58d32d4c.png">

- 위와 같은 형태로 이슈(마크다운)를 작성하셔야 코드 하이라이팅이 됩니다.
- 따옴표(**'**) 가 아닌 백틱 (**`**)  입니다

e.g.
```kotlin


        numberInput.addTextChangedListener(object : TextWatcher{
            override fun afterTextChanged(p0: Editable?) {

            }
            override fun beforeTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {


            }
            override fun onTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
                val number = numberInput.getText().toString() + " "
                numberInput.setText(number)
            }
        })
```

**Comment by sanggggg** [comment]
참고 - #204
