### ISSUE TITLE
mysql migrate access denied

### ISSUE THREAD

**Issue by kwonlauren** [wafflestudio/19.5-rookies#290]
저번 세미나 영상을 다시 보면서 해보고 있었는데, migrate를 하면 다음과 같은 에러가 뜹니다. 
에러메세지가 너무 길어서 처음과 끝만 첨부합니다.
<img width="982" alt="스크린샷 2021-09-03 오후 8 41 19" src="https://user-images.githubusercontent.com/81508275/131999682-ca1cf4b5-79be-42d5-b204-6b3286aaf7dc.png">
<img width="973" alt="스크린샷 2021-09-03 오후 8 41 36" src="https://user-images.githubusercontent.com/81508275/131999712-886ae4d3-5f33-4f05-8594-b8b6e3c1a078.png">

**Comment by VioletXF** [comment]
과제 3번을 진행하시면 해결되는 에러입니다.

**Comment by kwonlauren** [comment]
아아 넵 감사합니다!
