### ISSUE TITLE
Android Assignment0 에서 intent와 fragment 사용에 관해 질문드립니다.

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio/19.5-rookies#291]
안녕하세요.

안내해주신 https://developer.android.com/courses/kotlin-android-fundamentals/toc 를 따라해 보며 공부하고 있습니다.
그런데 intent 에 관한 내용은 implicit intent정도밖에 나오지 않는데, 이건 과제에서 제시된  IntroduceActivity로 이동하거나 KotlinPracticeActivity로 이동하는 것과는 다른 내용 같습니다.

저 문서를 통해 배울 수 있는 것 중에서 과제에서 해야될 것과 비슷한 것은 fragment같은데, intent 말고 fragment 만 써서 과제를 해도 될까요?

감사합니다.

**Comment by VioletXF** [comment]
[android-seminar-0.pdf](../blob/master/android/seminar_0/android-seminar-0.pdf) 25페이지를 보시면 명시적 인텐트를 사용하여 Activity를 시작하는 방법이 설명되어 있습니다.

**Comment by veldic** [comment]
Intent가 뭔지 가볍게 이해하고 Intent를 활용하는 방법 및 Activity 전환 방법을 아는 것이 목표입니다!
[Start another activity](https://developer.android.com/training/basics/firstapp/starting-activity)
위 링크 참고하셔서 구현해보시면 좋을 것 같아요! 나중에 fragment는 따로 다룰 예정입니다 ㅎㅎ

**Comment by JuTaK97** [comment]
> [android-seminar-0.pdf](../blob/master/android/seminar_0/android-seminar-0.pdf) 25페이지를 보시면 명시적 인텐트를 사용하여 Activity를 시작하는 방법이 설명되어 있습니다.

**Comment by JuTaK97** [comment]
> [android-seminar-0.pdf](../blob/master/android/seminar_0/android-seminar-0.pdf) 25페이지를 보시면 명시적 인텐트를 사용하여 Activity를 시작하는 방법이 설명되어 있습니다.

감사합니다!!

**Comment by JuTaK97** [comment]
> Intent가 뭔지 가볍게 이해하고 Intent를 활용하는 방법 및 Activity 전환 방법을 아는 것이 목표입니다!
> [Start another activity](https://developer.android.com/training/basics/firstapp/starting-activity)
> 위 링크 참고하셔서 구현해보시면 좋을 것 같아요! 나중에 fragment는 따로 다룰 예정입니다 ㅎㅎ

감사합니다!!
