### ISSUE TITLE
iOS seminar 0 assignment 제출 방법

### ISSUE THREAD

**Issue by leejoey0921** [wafflestudio/19.5-rookies#300]
안녕하세요! iOS 청강생 이준경입니다.

과제 README에 따르면 waffle-rookies-19.5-ios 리포지토리에 seminar-0-assignment 브랜치를 판 뒤에 PR을 하는 방식으로 제출해야 하는데, 제 소유의 repository는 fork할 수 없는 것 같아 막혔습니다.
![스크린샷 2021-09-04 오후 3 09 30](https://user-images.githubusercontent.com/86173819/132084737-9b0ed541-7e6f-4284-83c6-8dfd9d52af5c.png)
그래서 그냥 waffle-rookies-19.5-ios/seminar-0-assignment 디랙토리에 과제 파일들을 push 했는데, 혹시 제가 잘못 이해한 부분이나 실수한 부분이 있다면 짚어주시길 바랍니다 ㅠ

**Comment by ars-ki-00** [comment]
Fork 여부와 상관 없이 브랜치를 팔 수 있습니다. 생성하신 레포를 클론하시고, 이 레포 내에서 브랜치 따서 작업하신 후, PR 생성하시면 될 것 같습니다.
iOS 제출 방식을 정확히는 몰라서, 원하시는 답변이 아닐 수 있습니다.

**Comment by leejoey0921** [comment]
아 branch이랑 fork랑 혼동되어서 삽질하고 있었네요... 감사합니다 ㅠ branch 생성하는 메뉴 찾아서 해결했습니다..
