### ISSUE TITLE
Android assignment1에서 git branch 관련 질문입니다.

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio/19.5-rookies#308]
안녕하세요.

Assignment0에서는 waffle-andriod-assign 폴더에 프로젝트 assignment0을 만들어서 제출했었습니다.

![image](https://user-images.githubusercontent.com/88367636/132100217-27363c47-8c89-49d9-93fa-f1cff5e5dd04.png)

그래서 waffle-android-assign 폴더를 들어가면 이런 모습입니다. (Assignment0 폴더를 따로 만들지 않았었음)

이제 과제1을 하려고 하는데, 이번에는 Assignment1 폴더를 따로 만들어서 그 안에 assignment1 프로젝트를 만들었습니다.
git branch assignment1 -> git checkout assignment1 -> git add Assignment1 -> git commit -> git push origin assignment1 을 해서 과제0을 제외한 부분인 폴더 Assignment1 만 assignment1 브랜치에 push하려고 했는데, 과제0을 포함한 waffle-android-assign 폴더 전체가 assignment1 브랜치에 들어가게 됩니다.
어떻게 하면 Assignment1 폴더만 assignment1 branch에 넣을 수 있을까요? 이리저리 구글링 해 봐도 잘 모르겠어서 이슈로 질문드립니다!

감사합니다.

**Comment by veldic** [comment]
의도했던 구조는
```
-waffle-android-assignment
  - Assignment0
    - files
  - Assignment1
    - files
```

입니다! 설명이 부족했나보네요
위대로 구현하시면 Assignment0 폴더를 건드리지 않고 Assignment1 폴더만 건드리는 식으로 과제 진행해주실 수 있을겁니다!

**Comment by veldic** [comment]
https://github.com/wafflestudio/19.5-rookies/blob/ab269fa680d66a8d7357a994cb7a505241dc46d5/android/assignment_1/README.md

관련 정보 업데이트 했습니다! 확인 부탁드릴게요

**Comment by JuTaK97** [comment]
![image](https://user-images.githubusercontent.com/88367636/132102002-5a884187-2c2e-4b0c-98b9-f1d12812e2ff.png)

폴더 구조를 이렇게 수정하고, 
git branch assignment1
git checkout assignment1
git add Assignment1
git commit
git push origin assignment1

을 했는데, 제 repository의 assignment1 branch를 보면 제 로컬 저장소가 아니라 github 저장소의 master branch의 내용에 Assignment1 폴더만 추가된 것 같습니다.
뭐가 어떻게 된걸까요..

**Comment by VioletXF** [comment]
A브랜치로부터 B브랜치를 만들게 될 경우, 생성 시점의 A브랜치 작업 내용이 B브랜치에 반영되는것은 정상적인 현상입니다.
assignment1 브랜치에 Assignment0 폴더가 존재하면 안되는 특별한 이유가 있나요?

**Comment by JuTaK97** [comment]
생각해보니 정말 당연한 거였네요! 답변 정말 감사합니다.
그러면 master branch를 수정하고(Assignment0 폴더로 묶기) 그리고 나서 assignment1 branch를 만들면 되나요?
