### ISSUE TITLE
Django 과제1 2번 관련 질문입니다.

### ISSUE THREAD

**Issue by HunRotation** [wafflestudio/19.5-rookies#316]
Django 과제1 2번 수행 중 문제가 발생하여 질문 드립니다.
코드를 보면 post 방법으로 api/v1/user/에 query param을 아래 스크린샷처럼 붙여 입력하면 회원가입이 진행되는 것으로 알고 있습니다. 그런데 username, email, password를 정확히 입력했는데도 아래 스크린샷처럼 400 Bad Request가 반환됩니다.
![as1_2_error](https://user-images.githubusercontent.com/48827296/132129044-5211dcf9-4234-42eb-aab2-cff9521c3560.png)

400 Bad Request가 발생하는 이유를 코드에서 찾아보니  username, email, password 등 매개변수가 제대로 전달되지 않은 것 같아 UserViewSet 클래스의 create() 함수의 맨 앞에 print(request.data)를 추가하여 로그를 확인해본 결과, 정확히 query를 입력하여도 request.data가 비어 있는 것을 확인하였습니다.
![as1_2_error_2](https://user-images.githubusercontent.com/48827296/132129127-2f182204-93b6-4c58-822b-e1807d8e360b.png)

이 문제를 구글링하여도 비슷한 문제가 최근 DRF 버전에서 발생한다는 언급만 있을 뿐이지, 자세한 원인과 해결책을 찾지 못하였습니다. 제 추측으로는 csrftoken 등 django 자체의 보안 시스템이 POST 방법을 이용한 data 전달을 막은 것 같습니다만, 정확한 원인을 현재로서는 알 수 없는 상황입니다.

POST로 전달한 query param을 request가 제대로 받으려면 어떻게 해야하는지, 그리고 이러한 현상이 발생하는 원인이 무엇인지 질문 드립니다.

**Comment by Jhvictor4** [comment]
아.. 해당 부분 미리 알려 드리지 못해 죄송합니다.
https://www.django-rest-framework.org/api-guide/requests/#query_params
참고하시면 원인에 대해 좀 더 이해하실 수 있을 것 같습니다.

.data는 request body를 담고 있고,
query params는 .query_params 라는 데이터에 담깁니다.

여태 request body를 이용한 api 가 없었다 보니 충분히 설명드리지 못한 제 잘못 같습니다.

반영해서 리드미 수정하고 공지하겠습니다.


.query_params 를 사용하셔야 합니다.

**Comment by HunRotation** [comment]
아 생각보다 간단한 문제였군요! 알려주셔서 감사합니다.
Postman에서도 request body를 생성하는 기능이 따로 있는 걸 발견했습니다. 스크린샷은 이를 활용해 남기도록 하겠습니다.

**Comment by kk0in** [comment]
@Jhvictor4 안녕하세요! 저도 비슷한 문제에 부딫혔는데, 
해결책이 UserViewSet 클래스의 create() 함수에 있는 .data를 .query_params로 바꿔야하는 것이 맞나요?

**Comment by Jhvictor4** [comment]
@kk0in 아뇨 request body로 post 요청을 날리시는 연습을 하시면 좋을 것 같습니다 :) 포스트맨에서 쉽게 할 수 있으니까요..

**Comment by kk0in** [comment]
@Jhvictor4 아 넵 감사합니다!
