### ISSUE TITLE
Spring patch API 수행 여부

### ISSUE THREAD

**Issue by numnum97** [wafflestudio/19.5-rookies#319]
안녕하세요, 스프링 세미나 듣고 있는 김동현이라고 합니다.
아래에 있는 Patch API는 과제에 스펙이 명시되어 있지 않은데 이번 과제에서는 진행하지 않아도 될까요?

감사합니다.

![image](https://user-images.githubusercontent.com/56782035/132149591-d2c06bbe-9921-47d3-aee5-f883eb5fac30.png)

**Comment by Hank-Choi** [comment]
네 코드를 먼저 짜고 과제 스펙을 정했는데 로드가 너무 많아보여서 제외했습니다ㅎㅎ 깜빡하고 코드를 수정 못했네요 수정하겠습니다. 제보 감사합니다~
