### ISSUE TITLE
wsl2 ubuntu 사용 시 한글입력기 uim 오류

### ISSUE THREAD

**Issue by JiyeonP** [wafflestudio/19.5-rookies#320]
현재 윈도우에서 wsl2로 ubuntu 설치하여 리눅스 환경 사용하고 있습니다.
웹스톰에서 한글을 입력하기 위해 한글입력기 uim-byeoru를 아래와 같은 명령어로 설치했습니다.

sudo apt-get install uim
sudo apt-get install uim uim-byeoru

이후 .bashrc에 아래의 설정을 추가하였습니다.
![uim_bashrc](https://user-images.githubusercontent.com/66158942/132198942-c6d5bc61-2dd3-460d-87f9-a4b509a16886.jpg)

source .bashrc를 시도하니 아래와 같은 에러가 발생합니다.
![uim_error](https://user-images.githubusercontent.com/66158942/132197461-28a77a75-bdc9-4c07-8ac0-7456b976e563.jpg)

구글링을 통해 방안을 찾아보고 있지만 아직 해결하지 못하고 있습니다.
한글 입력은 가능한 상황이라 당장 급하지는 않지만 도움 주실 수 있으시면 답변 부탁드립니다!

**Comment by woohm402** [comment]
구글링해보니 이런 게 나오긴 하네요
- https://bbs.archlinux.org/viewtopic.php?id=251753

그런데 윈도우에서 웹스톰 사용하실 때 한글 입력이 잘 안 되는 상황이신가요? 🤔 어쩌다 uim을 설치하시게 된건지

**Comment by JiyeonP** [comment]
윈도우에 깔아서 wsl 환경 세팅하는 방법 말고, ubuntu linux에 직접 깔아서 사용하고 있어서 한글을 입력하려면 추가적인 세팅이 필요한 것 같습니다
