### ISSUE TITLE
Spring SurveyNotFoundException.kt 관련 질문

### ISSUE THREAD

**Issue by kohandy1902** [wafflestudio/19.5-rookies#321]
안녕하세요 스프링 세미나 수강중인 고동현입니다. skeleton code인 SurveyNotFoundException.kt에 대해 질문이 있어 이슈를 올리게 되었습니다.

![issue](https://user-images.githubusercontent.com/33983582/132253147-9b1f52e7-b089-4089-b366-6d41ef83ba2f.png)

이 파일은 위 사진 처럼 되어있는데 에러 메세지인 OS NOT FOUND가 오타같아 질문드립니다. SURVEY NOT FOUND 등으로 적절히 바꾸고 진행하면 될까요? 

감사합니다.

**Comment by Hank-Choi** [comment]
네 그러네요ㅠ바꾸고 진행해주세요 저도 수정하겠습니다. 감사합니다~
