### ISSUE TITLE
리액트 앱 start 실행 시간, js 수정 반영 관련

### ISSUE THREAD

**Issue by ice1039** [wafflestudio/19.5-rookies#322]
안녕하세요. 리액트 실행에 불편을 겪고 있어 질문을 남깁니다.
저는 wls2를 통해 우분투를 사용하고 있고, 브라우저는 웨일을 사용하고 있습니다.

두 가지 질문이 있어 이슈를 남깁니다.

먼저 리액트 앱을 실행할 때 yarn start/npm start 명령어를 입력한 후 웹페이지가 실행되는 데 약 5~7분이 걸립니다.

![image](https://user-images.githubusercontent.com/86710785/132269628-671ed845-8a44-4217-83ac-29a81929e7a4.png)
![image](https://user-images.githubusercontent.com/86710785/132269786-e12f221f-a6a1-4eb3-bacb-ba1dfa5a0412.png)

위와 같은 화면이 각각 3분 정도 지속된 후에서야 빌드가 완료됩니다. 
불편함을 느껴 구글링을 해봤을 때는 노드, npm 업데이트, 삭제 후 재설치를 권장하는 글이 있어 앱 내 파일을 삭제하고 다시 설치했고, 노드 버전 14로 업데이트를 했으나 실행 시간은 동일합니다.
브라우저를 크롬으로 바꿔 실행해보기도 했는데 큰 변화는 없었습니다.

보통 실행시간이 몇 초 내지 몇 십 초인 것 같은데, 혹시 해결할 방법이 있을까요?

두 번째 질문은 App.js 수정사항이 반영이 되지 않는 점과 관련한 것입니다.
![image](https://user-images.githubusercontent.com/86710785/132270875-562fd65c-1ce1-49fb-b299-b0d7ba561217.png)
화면처럼 App.js를 수정했는데도 수정사항이 반영되지 않고, npm start를 통해 다시 빌드하여도 동일한 화면이 나옵니다.
지난 주 과제를 위해 만들었던 앱에서는 재빌드시 수정사항이 잘 반영되는데, 특정 앱에서만 수정사항이 반영되지 않을 수 있는 건가요?
구글링해도 관련 문서를 찾지 못해 이슈로 남깁니다. 

혹시 아시는 바가 있으시다면 답변 부탁드리겠습니다! 감사합니다.

**Comment by woohm402** [comment]
일단 저는 맥에서 개발할 때는 5초 정도, wsl에서 개발할 때는 항상 15초 정도? 소요되는 것 같았습니다.

1. 사용중이신 컴퓨터 사양이 어떻게 되시나요? (컴퓨터 모델명, CPU, RAM, SSD)
2. 사용중이신 create-react-app 버전이 어떻게 되시나요?

-----

두번째 질문 관련해서는: `npm start`를 다시 했으면 원래는 무조건 앱이 바뀌어야 합니다.
1. 일단 `npm start`하신 폴더가 코드 수정하신 폴더 맞는지 확인해보시고,
2. 맞는데도 안 된다면 (아마 하셨을 것 같지만) `ctrl+shift+r` 로 강력 새로고침 해 보시고
3. 그러고 안되면 시크릿탭으로 해 보시고
4. 그래도 안되시면 크롬으로 시도해보시겠어요?

**Comment by ice1039** [comment]
1. 사용하고 있는 컴퓨터는 그램 19년형입니다. CPU는 인텔 코어 i5-8265U CPU @ 1.60GHz   1.80 GHz 이고 램은 16기가이고 15.8 사용 가능이라고 뜹니다. SSD는 삼성 mznln256hahq 이고 256기가라고 합니다!
2. create-react-app 버전은 17.0.2입니다.

두 번째 질문 관련해서는 실행을 다시 해보고 코멘트로 다시 달겠습니다!ㅠㅠ

**Comment by ice1039** [comment]
두번째 질문 관련해서 말씀해주신 네 가지 방법 모두 확인을 했는데 수정이 되지 않습니다.

**Comment by ice1039** [comment]
두 번째 질문 관련하여 https://github.com/facebook/create-react-app/issues/659#issuecomment-281704082에 나와있는대로 명령어를 입력했을 때 저장한 변화가 실시간으로 반영됐습니다. 

첫 번째 질문은 아직 해결하지 못했지만 일단 과제 수행에 큰 어려움은 없을 것 같습니다..!
감사합니다.

**Comment by woohm402** [comment]
넵 나중에 npm이랑 이쪽 환경에 좀 익숙해지시면 서버 켜는 거 원인 한번 찾아보시면 좋을 것 같습니다!
