### ISSUE TITLE
SpringBoot assignment1-8 질문

### ISSUE THREAD

**Issue by yeonsumia** [wafflestudio/19.5-rookies#324]
안녕하세요, springboot 수강생 전현성입니다.

다름이 아니오라 assignment1-8에서 exception 처리 중 403 NOT FOUND라고 기술되어 있는데,
404 NOT FOUND를 의도하신건지, 403 FORBIDDEN을 의도하신건지 여쭙고자 issue 게재합니다.

감사합니다.

**Comment by Hank-Choi** [comment]
404 NOT FOUND입니다!
