### ISSUE TITLE
Django assignment1 1번 질문드립니다.

### ISSUE THREAD

**Issue by OTY-Math** [wafflestudio/19.5-rookies#325]
user_id 를 추가할 때, foreign key로 참고할 테이블이 무엇인지 잘 모르겠습니다. ㅠㅠ

짐작해보건데 user/model.py 에 user table을 만들고 foreign key로 연결시켜야 하는 것 같긴한데 확신이 들지 않아 질문 드립니다.

**Comment by footprinthere** [comment]
User가 django의 built-in model로 제공되는 것 같습니다!
https://docs.djangoproject.com/en/3.2/ref/contrib/auth/
여기를 참고하시면 좋을 것 같아요.

**Comment by Jhvictor4** [comment]
답변이 되셨나요? 확인하셨으면 이슈 닫아주시면 감사하겠습니다.,!

**Comment by OTY-Math** [comment]
@Jhvictor4  @footprinthere  답변 감사드립니다. 

from django.contrib.auth.models import User

class User(User):

로 장고의 User를 상속시키긴 했는데, 추가로 id라는 attribute를 만들어 줘야할 것 같아서 .... models.CharField로 만들면 될까요?

구글의 대부분의 예시는 abstractUser에 관한 내용만 있어서 이렇게 질문 드립니다.

**Comment by Jhvictor4** [comment]
from django.contrib.auth.models import User 코드를 확인해보시면, 이미 User라는 모델이 구현되어 있어

특별히 더 구현하시지 않아도 User.objects.all() 등의 행위가 가능합니다.

말씀해주신 것처럼 AbstractUser를 상속받아서 커스텀 모델을 만들 수 있지만, 해당 과제를 진행할 때는 장고의 built-in 모델을 그냥 사용하셔도 좋습니다 :)

**Comment by OTY-Math** [comment]
감사합니다 이해된 듯합니다!
