### ISSUE TITLE
Spring Boot: DTO 관련 질문

### ISSUE THREAD

**Issue by WallabyG** [wafflestudio/19.5-rookies#328]
안녕하세요,  Spring Boot 과제에서 DTO를 사용하던 중 몇 가지 의문이 생겨 질문을 올립니다.

### 1.
Controller에서, ```ResponseEntity```는 ```body()```로 주어진 객체의 모든 프로퍼티를 json으로 직렬화하는 것으로 이해했습니다.

만약  ```body```가 ```SurveyResponseDto```의 ```user```나 ```os```처럼 다른 객체를 프로퍼티로 가지면 nested json이 되는데, 이때 그 객체의 프로퍼티를 모두 포함하는 것을 확인했습니다.

이번 과제에서는 해당사항이 없지만, 이후에 ```user``` 모델에 여러 정보들을 추가한다면 이 방법으로 직렬화했을 때 외부에 불필요하거나 민감한 정보가 노출될 수 있습니다.

```SurveyResponseDto```의 ```user```를 모델 객체가 아니라 모델의 일부 프로퍼티만 가지는 별도의 객체로 바꾸는 방법도 생각해봤지만, 이 경우 ```ModelMapper```가 본래 모델에 foreign key로 선언된 다른 모델을 잘 변환할 수 있을지 모르겠습니다.

Django에서 필요에 따라 여러 serializer를 정의해 사용하는 것처럼, foreign key의 프로퍼티 중 일부만 선택하여 반환할 수 있는 효율적인 방법이 있나요?

---
### 2.
과제에서 POST 입력을 받을 때 ```@ModelAttribute```를 사용하는데, 이 과정에서 변수명과 관련하여 문제가 있었습니다.

api의 파라미터 이름은 ```spring_exp, rdb_exp``` 등 snake_case를 따르므로,  ```@ModelAttribute```를 사용하면 snake_case의 프로퍼티에 데이터가 바인딩됩니다.

java에서는 camelCase를 사용하므로 적절하게 이름을 변환하여 바인딩하는 것이 좋을 것이라 생각했습니다.

```@JsonProperty, @JsonNaming```등을 통해 해결할 수 있을 것 같았는데, 과제의 스펙에 따라 form-data로 입력을 받으면 위 어노테이션들이 의도한대로 작동하지 않았습니다.

camelCase의 프로퍼티를 선언하여 ```getter```를 지정하거나, 커스텀 ```HandlerMethodArgumentResolver```를 구현하는 방법도 찾아보았지만, 이 경우 ```@ModelAttribute```를 통해 간편하게 데이터를 바인딩하는 의미가 사라질 것이라 생각합니다.

POST api의 content-type이 form-data일 때, snake_case로 작성된 파라미터를 camelCase로 간결하게 변환할 수 있는 별도의 방법이 있나요?

---
### 3.
DTO의 사용과 관련된 질문입니다.

DTO를 사용하는 목적 중 하나는 도메인 간 데이터 교환을 효율적으로 이루어지게 하는 것이라 이해했습니다.

과제의 코드를 보면 Controller에서 ```ModelMapper```를 이용하여 모델을 응답을 위한 DTO로 변환하는데, Service에서 모델을 반환하는 것은 DTO를 전달하는 것보다 비효율적이라고 생각했습니다.

다만, 응답을 담당하는 Controller의 역할을 고려한다면 Service에서 비즈니스 로직에 따라 모델을 반환하고, Controller에서 그 모델을 응답으로 변환하는 구조도 타당하다 생각합니다.

도메인 간 데이터 교환의 효율성을 위해 Controller와 Service 사이에서 DTO를 전달하는 것이 좋을지, 아니면 각 도메인의 역할 분담을 위해 실제 모델 객체를 전달하는 것이 좋을지 궁금합니다.

**Comment by PJH6029** [comment]
1번의 경우, nested json이 될 프로퍼티들(user나 os)의 타입을 User?가 아닌, UserDto.Response?로 변경하면 해당 modelMapper에서 해당 객체로 매핑하는 것 같습니다. 그러나, 개인적으로는 Dto 간의 의존성이 생기는 것 같아, 더 좋은 해결책이 있으면 좋을 것 같습니다.
[code]
![Screenshot from 2021-09-08 13-22-34](https://user-images.githubusercontent.com/46991571/132446237-2f2c8f24-f149-43c5-9885-7b6164908586.png)
[result]
![Screenshot from 2021-09-08 13-23-39](https://user-images.githubusercontent.com/46991571/132446261-4f88e630-f60c-423e-b20d-e5b0d4cde2d6.png)

추가로 1번 질문과 관련해서 비슷한 예시로
-  User와 SurveyResponse가 ManyToOne 관계를 갖고,
- 양방향 매핑인 경우(User 모델에 OneToMany로 Set&lt;SurveyResponse&gt;, SurveyResponse에 ManyToOne으로 User),
- SurveyResponseDto에 user 프로퍼티를 포함시키면 user 프로퍼티의 모든 요소들을 json으로 만들게되고(여기에 Set&lt;SurveyResponse&gt;도 포함),

개인적으로 이러한 매핑이 드문 일은 아닌 것 같아, 이때도 일단은 타입을 Dto로 설정하면 해결할 수 있을 것 같습니다.

**Comment by Hank-Choi** [comment]
1. 위에 말씀하신대로 DTO 안에 DTO를 넣어 매핑이 잘 일어나도록 할 수 있습니다.
2. 사실 해당 부분은 제가 정확히 고려를 안 한 부분입니다. 대부분의 경우 @RequestBody 를 사용해 json body를 받습니다. 다만 postman에서 json 만드는 부분을 처음 하는 분들이 제대로 못하거나 불편해 하실 것 같아 @Modelattribute annotation을 사용했습니다. @RequestBody, json body를 사용하시면 될 듯 합니다.
3. 일반적으로는 Controller에서 DTO로 변환 작업이 일어납니다. 다만 DTO가 왜 레이어간의 Data transfer를 위해 나온건지 제가 이해한대로 말씀 드리자면 사실 DTO라는 것이 옛날부터 존재하던 개념이고 그때는 백엔드 프론트엔드가 나뉘지 않던 시절입니다. 당시에는 rest api를 통해 소통하는 것이 아니라 view단에 노출되는 것이 곧 유저가 보는 데이터였기 때문에 이러한 개념이 등장했다고 생각합니다. 최근에는 실제 모델 객체를 전달, controller단에서 유저에게 노출하고 싶은 부분만 골라 전달하는 것이 일반적인 것 같습니다.

**Comment by WallabyG** [comment]
이해에 큰 도움이 되었습니다. 감사합니다! :)
