### ISSUE TITLE
Django assignment1 3번 관련 질문드립니다.

### ISSUE THREAD

**Issue by Victini00** [wafflestudio/19.5-rookies#330]
3번에서 user들의 정보를 db에서 조회하라고 하셨는데, select * 명령어로 password를 조회할 경우, 2번에서 post 명령어로 입력한 password와는 다른 문자열을 조회할 수 있었습니다. 왜 이런 결과가 나오는 것인지 궁금합니다.
![result3-참조](https://user-images.githubusercontent.com/87114100/132389072-42f9fd03-802c-47a1-820b-16b3f401cafb.png)

**Comment by Jhvictor4** [comment]
넵 이것은 장고가 보안을 위해 자동으로 암호화를 거쳐 비밀번호를 저장하기 때문입니다.

[Password management in Django](https://docs.djangoproject.com/en/3.2/topics/auth/passwords/)

를 참고하시면 좋을 것 같은데요,

첨부해주신 사진에서 값들 앞에 붙어있는 pbkdf2_sha256 은 장고가 암호화에 사용하는 해싱 알고리즘입니다.

이 부분은 깊이 이해할 필요는 없는 것 같습니다..! 아 그렇구나 하고 한번 슥 훑어보시면 좋을 것 같아요 ㅎ
