### ISSUE TITLE
SpringBoot ResponseEntity 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by kohandy1902** [wafflestudio/19.5-rookies#331]
안녕하세요, 스프링 세미나 수강 중인 고동현입니다. Skeleton Code의 ResponseEntity관련하여 질문이 있어 이슈를 올리게 되었습니다.

SkeletonCode를 보면 GET의 Response로는 ResponseEntity<...Dto>를 반환하고 POST의 Response로는 ...Dto를 직접 반환하게 설계되어 있는데 특별한 이유가 있나요? ResponseEntity로 모두 감싸줘도 된다고 생각이 들어서요. 결과는 같은 데 Status Code 등 조금 더 많은 정보를 내포하는 것으로 보이기 때문입니다. 혹시 특별한 이유가 있는것인지 궁금하고 아니라면 감싸줘도 되는지 궁금합니다.

감사합니다.

**Comment by Hank-Choi** [comment]
여러 방식으로 반환 가능하다는 것을 보여주려고 일부러 다양한 방식으로 짰습니다! 실제로 나중에 exception handler를 만들 경우 간편하게 후자의 방식을 많이 사용하기 때문에 예시로 넣은 것이고요 과제1 진행하면서 어떤 방식을 사용하든 상관없습니다!
