### ISSUE TITLE
spring 과제1 질문(exception handling, trailing slash, DTO, validation ...)

### ISSUE THREAD

**Issue by PJH6029** [wafflestudio/19.5-rookies#332]
### 1. Uniqueness 관련 exception
- User.email은 unique해야합니다
- 중복되는 값을 집어넣으니 ```SQLIntegrityConstraintViolationException```이 발생했습니다
- 에러 처리를 위해 ```@ExceptionHandler(SQLIntegrityConstraintViolationException::class)```를 담당하는 함수를 만들었습니다<br>
![Screenshot from 2021-09-08 13-51-45](https://user-images.githubusercontent.com/46991571/132448449-2fb9656a-4d55-47bb-b47e-fe8b5683b4ce.png)
- 그런데 작동 x
- 구글링해보니, ```SQLIntegrityConstraintViolationException```를 스프링 내부(아마 dispatcherServlet?)에서 미리 잡아서 ```DataIntegrityViolationException```로 던져주는 것 같아 일단 ```@ExceptionHandler(DataIntegrityViolationException::class)```으로 수정했습니다.

- Q: 원래 SQL exception은 바로 잡지 않는 것이 일반적인가요? 만약 관련 에러 메시지를 response에 주고싶으면 그 exception에 접근해야 할텐데, 방법이 있는지 궁금합니다.

------------------------------------
### 2. Trailing slash
- 과제 스펙에서  ```@RequestMapping("/api/v1/results")``` 이후, 아래 메소드들에선 ```@GetMapping("/")```이런식으로 지정되어있습니다
- postman에서 실행해보니, /api/v1/results/ 는 작동하고, /api/v1/results는 작동하지 않았습니다.
- 구글링해보니 ```@GetMapping("/")``` 대신 ```@GetMapping```으로 하면 둘 다 되는 것 같은데, 실제로는 하나로 제한하는 것이 일반적인가요?? (/api/v1/results/{id}/도 마찬가지)

------------------------------------
### 3. DTO mapping 관련
이름은 같지만, 타입이 다른 프로퍼티들은 modelMapper에서 매핑되지 않는 것 같은데 (ex. ```os: String?```을 ```os: OperatingSystem?```으로 매핑), 이러한 매핑은 보통 직접 하나요? 한다면 Controller와 Service layer 모두 가능할 것 같은데, 어디가 더 맞는 장소인지 궁금합니다.

------------------------------------
### 4. Controller 리턴
Controller의 리턴타입이 ResponseEntity가 아니라 그냥 Dto면, status code는 어떻게 지정하나요? (400 같은 따로 처리하는 것이 아닌 201과 같은 경우)

------------------------------------
### 5. 모델 단의 validation
- controller의 body에 ```@Valid```를 달아주면 해당 타입에서 validation을 한다고 이해했습니다.
- 그럼 모델에서 달아준 annotation에 대한 validation은 어떻게 진행하나요?
- Ex. SurveyResponse의 major, grade, backendReason 등을 model에서 ```@NotBlank```로 해줘도 blank 값이 db에 그냥 들어가지는 등
- 이와 관련해서, Controller layer 단계의 validation과 Service layer 단계의 validation의 장단점도 궁금합니다
<br>
질문이 많아 죄송합니다ㅜㅜ 질문을 쪼개는 게 더 나은 경우, 말씀해주시면 분리하겠습니다.

**Comment by PJH6029** [comment]
5번 질문은 해결했습니다! model에도 ```field:``` 를 추가해주면 되네요 :)
참고자료: [kotlin spring의 annotation 위치](https://velog.io/@lsb156/SpringBoot-Kotlin%EC%97%90%EC%84%9C-Valid%EA%B0%80-%EB%8F%99%EC%9E%91%ED%95%98%EC%A7%80-%EC%95%8A%EB%8A%94-%EC%9B%90%EC%9D%B8JSR-303-JSR-380)

**Comment by Hank-Choi** [comment]
1. 네 저희가 jpa를 사용하고 있고 jpa에서 한번 추상화를 합니다. 대부분의 프로그램에서 추상화 레벨을 뚫고 내려가려면 그만한 처리를 해줘야 하기 때문에... 추상화된대로 사용하시는 것을 추천 드립니다!
```
val e: DataIntegrityViolationException
e.getMostSpecificCause() ~~~
``` 
와 같은 방식으로 조금 더 specific한 에러상황을 파악할 수 있습니다.

2. 일반적으로 trailing slash를 붙여주고 api에 따라 붙이지 않았을 경우 다르게 동작하는 경우도 있어 하나로 제한했습니다.

3. 네 직접해야합니다. #328 에도 말한 것처럼 DTO 매핑을 거의 controller에서 처리합니다.

4. `@ResponseStatus(HttpStatus.CREATED)`를 메소드 위에 달아보세요! 사실 일반적으로는 200과 201을 구분 지을 일이 거의 없어서 대부분 200으로 처리합니다!

**Comment by PJH6029** [comment]
넵 감사합니다!! 정말 큰 도움이 됐습니다. issue 닫을게요
