### ISSUE TITLE
Django assignment1 5번 질문

### ISSUE THREAD

**Issue by leejoey0921** [wafflestudio/19.5-rookies#333]
readme의 5번 항목에 따라 update() 함수를 구현하던 중 의문점이 생겨서 질문합니다.

제시문에는 유저가 로그인되지 않은 경우에만 `403 FORBIDDEN` 처리를 하라고 제시되어 있는데, 이렇게 구현하면 한 유저가 다른 유저의 정보를 수정하는 것도 허용될 것 같습니다. 제가 이해를 맞게 한 건지, 아니면 request의 유저와 lookup key가 가리키는 유저가 일치하는 것도 추가적으로 확인해야 하는지 궁금합니다.

**Comment by Jhvictor4** [comment]
이해를 정확히 하고 계신 것 같습니다. 따라서 url의 pk를 통해 유저를 직접 불러오는 행위는 위험할 수 있습니다.

일반적인 구현은

https://www.django-rest-framework.org/api-guide/authentication/

해당 부분 참고하시면 될 것 같은데요, request.user를 통해 요청을 보낸 유저 모델을 (유저 모델 ORM 없이도) 불러올 수 있습니다.

Best Practice 는 여러가지가 있지만, 과제는 예습 차원에서 진행되는 것이기에 편하신 대로 구현해주시면 됩니다.

**Comment by leejoey0921** [comment]
넵 참고하겠습니다! 감사합니다 ㅎㅎㅎ
