### ISSUE TITLE
React 과제에서 각 요소들의 css의 크기 고정 여부

### ISSUE THREAD

**Issue by mgahn0706** [wafflestudio/19.5-rookies#335]
안녕하세요, react 과제 1을 진행중인 안민규입니다!
Figma에서 로그인을 하면 각 요소들의 css가 뜬다는 것을 방금에서야 알았습니다.
그래서 여태까지 css를 모두 화면 전체의 45%, 50%와 같이 상대적인 값으로 설정하고 있었습니다. 화면 크기가 바뀌었을 때도 예쁘게 출력되게 하고 싶었습니다! 그런데 이렇게 하면 Figma 사진과 스타일이 약간 달라집니다.

화면 크기와 상관없이 figma에 제시된 각 요소의 크기를 px로 고정되게 설정해도 상관이 없을까요?

**Comment by woohm402** [comment]
픽셀도 괜찮고 비율도 괜찮습니다. 개발하기 편하신 방향으로 가 주시면 됩니다! 화면 사이즈 변화에 맞춰서 각 요소가 잘 보이는지 같은 내용까지 확인하시는 않습니다 :)

**Comment by mgahn0706** [comment]
감사합니다!!
