### ISSUE TITLE
seminar1 과제 관련한 git 질문

### ISSUE THREAD

**Issue by kmsgm** [wafflestudio/19.5-rookies#336]
안녕하세요 react 수강 중인 김민서입니다.

깃을 처음 써봐서 그런지 구글링해도 이해가 안되는 부분이 많아 질문드립니다...

레포에 딱 들어가면 리드미, gitignore, src폴더, packagke.json이 있도록 설정해 달라고 한 톡방 글을 읽고 이해가 잘 되지 않아 질문드립니다.

처음에는 git push를 src 폴더만 해야 하는 것인가... 라는 생각이 들어 질문드렸는데 아예 로컬 레포 안의 폴더 구조를 저렇게 바꾸어야 한다는 답변을 들었습니다.

예를 들어 리액트 앱을 my-app이라는 이름으로 create하면 이렇게 폴더 구조가 만들어지는데,

![image](https://user-images.githubusercontent.com/49176503/132481352-a03f5e30-0ae6-475e-8ab0-831c0ccb4be1.png)

저기서 src 폴더, .gitignore, package.json, README.md를 따로 빼내어서 새로운 폴더로 만든 다음에 git push를 해야 하는 건가요?

**Comment by woohm402** [comment]
각각의 상황을 설명드리기 위한 예시 첨부드립니다.
- [1번 방식](https://github.com/woohm402/cra-example-bad)
- [2번 방식](https://github.com/woohm402/cra-example-good)

요청드린 사항은: 1번 방식으로 해 주신 분들께, "웬만하면 2번 방식으로 해 주세요!" 라고 전달드렸던 거예요!

**Comment by woohm402** [comment]
이론상 아래대로 하면 가능은 하지만 개인의 레포 상황에 따라 안 될 수도 있습니다.

create-react-app 한 앱 이름이 my-app 이라고 가정하겠습니다.

```bash
cd waffle-rookies-19.5-react-seminar-1 # 레포 루트로 가서
git mv -k ./my-app/* . # my-app 밑에 있는 파일들 옮기고
mv my-app/node_modules ./node_modules # node_modules 도 옮기고
```

이러고 나면 아마 `my-app/` 안에 README.md 랑 `.gitignore` 두 개만 남아 있을 텐데, 걔들은 적당히 잘 처리해 주시면 됩니다. 따로 뭐 건드리신 게 없다면, `my-app/README.md`는 삭제하시고, 레포 루트 폴더의 `.gitignore`를 `my-app/.gitignore`로 덮어씌우시고, `my-app`을 삭제하시면 됩니다.

**Comment by kmsgm** [comment]
아 이제 제대로 이해했습니다!! 정말 감사합니다ㅠㅠㅠ
