### ISSUE TITLE
UITableView was told to layout its visible cells and other contents without being in the view hierarchy 해결 방법 질문드립니다.

### ISSUE THREAD

**Issue by shp7724** [wafflestudio/19.5-rookies#337]
안녕하세요. iOS 수강생 박신홍입니다.
할일 추가 화면에서 완료 버튼을 눌렀을 때 콘솔창에 아래와 같은 경고 문구가 뜨는데요,

> [TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x7ffb62027e00; frame = (0 0; 390 844); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x60000062b3f0>; layer = <CALayer: 0x600000830f80>; contentOffset: {0, -143}; contentSize: {390, 130}; adjustedContentInset: {143, 0, 34, 0}; dataSource: <assignment1.MainViewController: 0x7ffb60505f40>>

에러 문구만 봐서는 정확히 어떤 문제인지 이해가 잘 안돼서, 나와있는대로 `UITableViewAlertForLayoutOutsideViewHierarchy`에 symbolic breakpoint를 찍어보았습니다. [Symbolic Breakpoint Xcode in 2 Minutes](https://medium.com/swlh/symbolic-breakpoint-xcode-in-2-minutes-5ca86f257b51)를 참고해서 BP를 걸어보았는데 `tableView.insertRows(at: indexPaths, with: .automatic)` 코드에서 멈추는 것을 확인했습니다.

조금 더 찾아보니 [여기](https://stackoverflow.com/questions/64568183/warning-once-only-uitableview-was-told-to-layout-its-visible-cells-and-other-co)에서 저와 같은 문제를 겪는 분을 찾았는데요.

```
view.addSubview(tableView) // 1
// 2 and start adding constraints..
tableView.translatesAutoresizingMaskIntoConstraints = false
...
```

위와 같이 하라고 나와있는데, 위 코드를 어디에 추가해야할지, 어떻게 이게 제 문제를 해결할 수 있다는 것인지 잘 모르겠습니다.
현재 제 프로젝트에는 2개의 `UITableViewController`만 존재하며, 문제가 되는 `tableView`가 포함된 VC는 아래와 같이 생겼습니다.

![image](https://user-images.githubusercontent.com/33917774/132501792-a095c79e-cb1f-4ca3-8994-3c2a7d30178b.png)

읽어주셔서 감사드립니다!

**Comment by Ethan-MoBeau** [comment]
사실 이거는 프로젝트를 제가 뜯어봐야 확실히 알 것 같기는 합니다

일단 저 에러에 대해 설명해드리자면 우리가 iOS에서 뷰의 디자인을 잡아주는 방법은 세미나에서 설명드린 AutoLayout과 그게 나오기 전에 사용되던 구형? 방법인 AutoResizing Mask가 있습니다. 

첨부해주신 링크에서 translatesAutoresizingMaskIntoConstraints가 false가 되어야 하는 이유는 저게 true가 되면 기본적으로 뷰에 잡혀있는 AutoResizing Mask 값이 AutoLayout의 constraint 값으로 전환되어, 우리가 잡아준 AutoLayout Constraint와 충돌하기 때문입니다.

그래서 AutoLayout을 사용할 때는 translatesAutoresizingMaskIntoConstraints를 꼭 false로 돌려주어야 합니다.

아마 지금 신홍님이 저 에러가 뜨신 이유는 스토리보드 세팅이 잘못 되어서일거에요

<img width="258" alt="스크린샷 2021-09-08 오후 10 06 04" src="https://user-images.githubusercontent.com/48316900/132515420-0d3313b7-b16c-49e1-8548-fa4b89a90880.png">

TableView 선택하시고 저 Layout이 사진과 같이 Constraints로 설정되어 있는지 한 번 확인해보시고 만약 AutoResizing Mask라면 바꿔주세요

그래도 해결이 안된다면 UITableViewController를 만들지 마시고 강의에서 보여드렸던 것 처럼 UIViewController를 만드시고 그 안에 TableView를 넣는 방식으로 진행해보세요~

**Comment by shp7724** [comment]
확인해보니 Layout이 AutoResizing Mask로 되어있긴 한데 다른 옵션도 Inferred (AutoResizing Mask) 뿐이네요 ㅠㅠ
translatesAutoresizingMaskIntoConstraints를 false로 바꿔봤는데도 문제는 동일하구요.

다음부터는 UITableViewController 사용하지 않고 해보겠습니다.
답변 감사합니다 :)
