### ISSUE TITLE
Present modally 방식으로 화면 전환시 상단바가 보이지 않습니다.

### ISSUE THREAD

**Issue by shp7724** [wafflestudio/19.5-rookies#338]
안녕하세요.
현재 스토리보드 구조는 아래 그림과 같습니다.

![image](https://user-images.githubusercontent.com/33917774/132507301-c16fab6d-8975-451b-837a-2db60b532a13.png)

위와 같이 메인 화면에서 '추가' 버튼을 누르면 push 방식으로 이동하고, '수정' 버튼을 누르면 present modally 방식으로 화면 전환이 이루어지게끔 하고 싶습니다. 그런데 present modally 방식으로 이동하면 상단에 navigation bar가 나타나지 않습니다. Navigation Controller의 Stack에 쌓이지 않기 때문인 것 같은데, 혹시 코드로 상단바를 따로 정의할 수 있는 방법이 있는지 궁금합니다.

[구글링](https://stackoverflow.com/questions/47100596/how-to-present-view-controller-modally-while-keeping-navigation-bar-present-fo)을 해보니 *수정 버튼을 누르면 Navigation Controller를 생성한 뒤, 세부 사항 VC를 rootViewController로 설정하고 이 NC를 `present`하는 방식으로 구현할 수 있다*는 답변을 본 것 같은데 저는 지금 `performSegue`와 `prepare`를 이용한 화면 전환으로 구현한 상태라 바로 적용이 어려워보였습니다. 그리고 분명 이것보다 더 좋은 방법이 있을 것 같다는 생각이 들었습니다..

<img src="https://user-images.githubusercontent.com/33917774/132508874-2d5669b9-5210-47c7-bb1d-6ea258d19be9.png" width="300">

위 사진과 똑같이 구현하려면 어떻게 해야할지 힌트 주시면 감사하겠습니다!

**Comment by Ethan-MoBeau** [comment]
이런 디테일을 챙기기 힘들다는 점이 뷰 전환을 스토리보드보다는 코드로 하는 것을 추천드리는 이유입니다! 

만약 굳이 스토리보드로 원하시는 기능을 구현하려고 한다면 storyboard 파일에 들어가서 present 될 예정인 viewController에 Editor - Embed  In - Navigation Controller 로 viewController에 navigationController를 붙여주는 방법이 있겠네요.

위 방법으로 해결하셔도 좋긴 하지만 조금 익숙하지 않고 어렵더라도 코드 레벨에서 뷰를 컨트롤 하는 방법을 시도해보시길 추천드립니다

**Comment by shp7724** [comment]
앗 생각보다 그렇게 간단한 작업은 아니었군요..

말씀주신대로 Navigation Controller를 Embed In 하게 되면 아래와 같은 구조가 되는데 이게 맞을까요..? 이렇게 하니까 '추가' 버튼을 눌러도 modal 형식으로 present 돼서요.
![image](https://user-images.githubusercontent.com/33917774/132520690-20a01f4f-2bb1-4581-8c6f-1d2599476c11.png)

그리고 코드 레벨에서 뷰를 컨트롤 하는 방법을 조금만 자세히 설명 부탁드려도 될까요?
아니면 검색 키워드 몇개 추천해주시면 제가 찾아보겠습니다.

감사합니다!

**Comment by Ethan-MoBeau** [comment]
네 저 그림대로 된다고 생각하시면 됩니다

그냥 "navigation Controller with code" 아니면 "navigation Controller programatic" 이런식으로 검색하면 많이 나올 거에요 이건 그냥 한글로 검색해도 나올겁니다.

제가 강의시간에도 말씀드렸지만 초중반부 세미나에서 다룰 내용 중 이런 제너럴한 ~~~ 하는 법은 구글링하면 쉽게 나오니 검색 많이 해보시길 추천드립니다! 구글링도 실력이에요

**Comment by shp7724** [comment]
네 알겠습니다.

> [구글링](https://stackoverflow.com/questions/47100596/how-to-present-view-controller-modally-while-keeping-navigation-bar-present-fo)을 해보니 *수정 버튼을 누르면 Navigation Controller를 생성한 뒤, 세부 사항 VC를 rootViewController로 설정하고 이 NC를 `present`하는 방식으로 구현할 수 있다*는 답변을 본 것 같은데 저는 지금 `performSegue`와 `prepare`를 이용한 화면 전환으로 구현한 상태라 바로 적용이 어려워보였습니다.

아까는 이렇게 썼지만 생각해보니 `present` 방식으로도 구현이 가능할 것 같아서 그렇게 해결했습니다!
