### ISSUE TITLE
Spring boot Reload without restart 방법

### ISSUE THREAD

**Issue by gina0605** [wafflestudio/19.5-rookies#339]
저는 터미널에서 `./gradlew bootRun`을 이용해 spring boot 서버를 띄우고 있습니다. 그리고 코드의 수정이 일어날 때마다 서버를 껐다 켜야만 수정 사항이 반영됩니다. 매번 서버를 껐다 켜는 작업을 하지 않아도 알아서 수정사항이 반영되도록 할 수는 없나요? **spring-boot-devtools**에 대해 찾아보기는 했지만 방법을 잘 모르겠어 이슈 올립니다.

**Comment by Hank-Choi** [comment]
스크립트 언어인 파이썬이나 node.js와 달리 자바는 컴파일 언어라 변경사항이 실시간으로 반영되도록 할 수 없습니다. 특히 kotlin + spring은 컴파일 시 매우 많은 작업이 일어나기 때문에 더욱 불가능합니다. devtools에 변경시마다 재시작하는 옵션이 있다고 보긴 했는데 저는 사용하지 않고 필요할 때마다 재시작합니다.

**Comment by gina0605** [comment]
언어적인 특징이었군요 답변 감사합니다 :)
