### ISSUE TITLE
Django assignment1 mysql 접속 질문입니다.

### ISSUE THREAD

**Issue by Victini00** [wafflestudio/19.5-rookies#342]
wsl ubuntu를 사용하고 있습니다.
hyper-v 관련 문제로 이를 잠시 비활성화 시킨 후 다시 활성화 시켰더니 vscode에서 migration이 진행되지 않습니다.
wsl의 ubuntu bash를 이용하여 mysql을 사용하고 있는데, 다음과 같은 오류가 계속 발생합니다(python manage.py makemigration 명령어 입력시. hyper-v 설정 이전에는 wsl로 mysql과 django를 연결하여 migration이 잘 진행되었습니다).

C:\Users\82108\waffle-rookies-19.5-backend-1\venv\lib\site-packages\django\core\management\commands\makemigrations.py:105: RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': (1045, "Access denied for user 'waffle-backend'@'localhost' (using password: YES)")
  warnings.warn(
No changes detected

비밀번호 관련 문제가 있어서인지 mysql을 재설치하여 root 비밀번호를 새로 설정해주기도 하였는데, 오류 내역이 그대로입니다.
![image](https://user-images.githubusercontent.com/87114100/132550029-b1432fe3-1cb2-45ae-8a59-4013ba0e1059.png)

wsl을 통해 mysql을 연결하는 과정입니다.

![image](https://user-images.githubusercontent.com/87114100/132549719-8c7c2db0-9df5-4435-9351-7ea875928e43.png)

settings.py의 내용입니다(assignment0과 동일하게 두었습니다).

mysql -u waffle-backend -p 명령어 입력 후 비밀번호 seminar를 입력하면 이전까지 migration 했던 내용들은 잘 확인할 수 있었습니다. mysql 접속 과정과 migration 과정이 이전과 완전히 동일함에도 불구하고, 왜 저런 오류가 발생하는지 잘 모르겠습니다. 어떻게 해결할 수 있을까요?

**Comment by Jhvictor4** [comment]
윈도우는 참....ㅜ

**Comment by Jhvictor4** [comment]
저도 대응을 어떻게 해야 할 지 잘 모르겠는데요. 혹시 장고 앱은 어디서 돌리고 계신가요>?

**Comment by Victini00** [comment]
vscode의 bash 터미널에서 돌리고 있습니다.

**Comment by Jhvictor4** [comment]
./manage.py dbshell 접속도 당연히 막히고 계신 거죠? 이건 제가 해결해드리기 어려울 것 같습니다.. 🥲

**Comment by Victini00** [comment]
듀얼부팅 환경 세팅 후 다시 시도해 보도록 하겠습니다.. 감사합니다!
