### ISSUE TITLE
Django Assignment 1번 질문

### ISSUE THREAD

**Issue by hansmaan** [wafflestudio/19.5-rookies#343]
1번을 진행하다가 변경 사항들을 하나 하나씩 migrate해가면서 하다보니, 한 번에 migrate하지 못했습니다. 그래서, migrate된 상황을 롤백하고자 구글링을 해보니, https://docs.djangoproject.com/en/3.1/topics/migrations/#reversing-migrations가 나와서 migrate된 모든 파일들에 대해 migrate zero를 진행했습니다.
![스크린샷, 2021-09-09 01-51-07](https://user-images.githubusercontent.com/88359757/132551491-04a89cc8-21b6-446e-b1ba-12628ea74875.png)
위와 같이 실행하고 나서, 
![스크린샷, 2021-09-09 01-52-31](https://user-images.githubusercontent.com/88359757/132551662-ccffdc47-676c-4515-b9cd-9508e3b24202.png)
위 사진과 같이 makemigrations와 migrate를 해주었습니다.
![스크린샷, 2021-09-09 01-53-06](https://user-images.githubusercontent.com/88359757/132551778-e5905aba-816b-4a0f-b405-9864d9ff47e3.png)
그랬더니 이미 surveyresult의 DB가 날아갔습니다. 롤백이 아니라, 완전 모든 migration들을 초기화했기 때문인 것 같은데, 이런 상황에서는 어떻게 복구할 수 있나요? 구글링을 해도 복구를 하는 방법을 도저히 모르겠습니다..

**Comment by Jhvictor4** [comment]
이러한 경우는 보통 --fake 옵션을 지정해서 디비에 영향 없이 장고 Migration 의존관계만 해소하는 것이 일반적인데요, zero 옵션만 넣는 것은 기본적으로 database drop과 비슷한 행동을 합니다. 그래서 디비가 다 날라가신 것 같네요..ㅎ

지워진 디비는 복구하는 방법이 사실 .. 없습니다 ㅎ
다행히 저희는 과제 및 실습 환경이고, 데이터도 엑셀 파일로 보관해서 ./manage.py download_survey 를 재실행 해주기만 하면 될 노릇이지만요.

그래도 마이그레이션 롤백에 대해 어느정도 이해도가 생기셨을 테니 오히려 좋다는 마인드로, 다시 데이터 받아서 시작해주시면 좋을 것 같습니다 :)

**Comment by hansmaan** [comment]
그렇다면 --fake 옵션을 지정하고 나서 zero를 시행하는 것이 옳은 방식의 롤백인것인가요?

**Comment by Jhvictor4** [comment]
넵 보통은 _migrate <롤백하려는 시점>_ 커맨드를 입력하면 해당 파일명 이후로 생긴 마이그레이션이 롤백되는 형태라서 이렇게들 쓰는 것 같습니다. --fake 옵션은 장고가 migrate을 한 것처럼 인식만 시켜주는 역할로서, 직접 디비 조작을 한다거나 해서 마이그레이션이 꼬인 상황 등에 사용하는옵션입니다.
