### ISSUE TITLE
Spring boot wsl 설정

### ISSUE THREAD

**Issue by cs71107** [wafflestudio/19.5-rookies#344]
안녕하세요. 다름이 아니라 환경 설정 부분에 있어서 질문이 있습니다.
전 원래 ubuntu/windows 듀얼부팅을 사용하다가 우분투쪽에서 계속 crash 가 나서 wsl2로 전환했습니다.
그런데 검색을 통해 환경을 설정하려고 하다 보니 환경 설정에 대한 방향이 여러 가지로 갈리는 것 같습니다.

vscode를 쓸 것인지, intelij를 쓸 것인지
그리고 terminal을 wsl로 둘 것인지 wsl 환경에 설치 후 gui 설정을 할 것인지 등에서 차이가 있는 것 같습니다.

혹시 wsl을 쓰시는 분들이 계시다면 spring boot 환경 설정을 대략적으로 어떤 방향으로 하셨는지 답변해주시면 감사하겠습니다.

**Comment by cs71107** [comment]
label 등 github support 관련 이슈가 있는 것 같아서 해결중입니다. 해결 하면 labeling 하겠습니다.

**Comment by WallabyG** [comment]
IntelliJ가 2021.1 버전부터 wsl2를 지원하고 있어 그걸 사용하고 있습니다.

IntelliJ는 윈도우에 설치되어 있고, 프로젝트를 \\wsl$\{distribution name} 아래 경로로 열어서  작업 중입니다.

대신 이 경우에는 project sdk를 wsl 환경의 java sdk로 설정해줘야 되었던 것 같네요.

**Comment by cs71107** [comment]
감사합니다. 일단 저는 windows 에 IntelloiJ 설치하고, 에디터? 처럼 사용하고, wsl2에 각종 필요한 환경(kotlin, sdk, etc...)들을 설치해서 사용하고 있습니다. postman의 경우 상관없어서 windows에 설치했고요. 감사합니다.
