### ISSUE TITLE
postman 출력 질문드립니다

### ISSUE THREAD

**Issue by jaylions** [wafflestudio/19.5-rookies#346]
원래 json파일 형식으로 잘 나왔는데 어느순간부터 포스트맨에서
그림에 있는 형식으로 나오는데  http는 200이라고 떠서 무엇이 문제인지 잘 모르겠습니다
<img width="1440" alt="스크린샷 2021-09-09 오후 3 50 20" src="https://user-images.githubusercontent.com/82078863/132637142-c0973057-eaec-4603-933b-7168021ac780.png">

**Comment by Jhvictor4** [comment]
담을 데이터가 없어서 그냥 빈 값 보내주는 것 같은데, 로직에 뭔가 잘못된 것이 들어간 게 아닐까요??

**Comment by jaylions** [comment]
아 한번 확인해보겠습니다 감사합니다

**Comment by jaylions** [comment]
혹시 코드를 잘못 건드린건가 해서 원본파일을  복사해서 다시해봐도 똑같이 나오는 것 같습니다

**Comment by jaylions** [comment]
아아 해결되었습니다
