### ISSUE TITLE
장고 과제1 리드미 url 수정 요청드립니다.

### ISSUE THREAD

**Issue by ksiyeon27** [wafflestudio/19.5-rookies#348]
<img width="625" alt="스크린샷 2021-09-09 오후 4 39 28" src="https://user-images.githubusercontent.com/76062959/132643656-9ffd9147-8aee-4215-a1c3-52e1c2909e52.png">

사소한 문제이긴 하지만 PUT /api/v1/user/ 뒤에 login/ 이 빠진 것 같습니다.
코드 주석에는 잘 적혀 있습니다.
수정해주시면 좋을 것 같아서 말씀드립니다!

**Comment by Jhvictor4** [comment]
앗 넵 확인했습니다. 죄송합니다 ㅎ
