### ISSUE TITLE
[React] useState와 모달 전환 효과와 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by HyungGeun-Cho** [wafflestudio/19.5-rookies#349]
안녕하세요?
와플스튜디오 19.5기 루키 조형근입니다.

React Seminar1 과제 스펙 중 모달 전환 효과가 포함되어 있는데요.
이와 관련해 계속 어려움에 빠져버려서 질문을 하게 되었습니다!

현재 저는 `const [showAdder, setShowAdder]=useState(0);`을 통해
리스트 위에 있는 추가 버튼을 누르면 `showAdder=1`로 전환하고, 
모달의 닫기 버튼 및 외부 영역을 클릭하면 `showAdder=0`로 설정하게 하여
이 `showAdder`의 값에 따른 모달 표시 여부를 구현하였습니다.

대략 
`if(showAdder===1){return(Adder)} else{return null;}`
이런 식입니다!

다만, 모달을 새롭게 나타낼 때는 페이드인 효과가 잘 구현이 되는데...
모달을 끄고자 하면 showAdder의 상태가 0이 되면서 페이드아웃될 겨를도 없이 바로 꺼져버리는 문제가 생겨버립니다.

버튼을 누른 후 프로그램 상 상태를 업데이트하기 전에 화면전환 효과 구현이 가능한지 
아니면 결국 구조적으로 showAdder를 사용하지 않고 다시 코딩을 해야할지 궁금합니다!

감사합니다 :)

**Comment by woohm402** [comment]
현재 조건부 렌더링 방식으로 구현하셨는데, 말씀하셨다시피 해당 방식으로는 켜질 때 효과는 구현할 수 있으나 꺼질 때 효과는 구현할 수 없습니다. 끄는 순간 unmount가 되기 때문에, 스타일을 적용할 겨를도 없이 바로 사라집니다.

해결 방법으로는 모달이 unmount가 되지 않고 항상 떠 있으면 되겠군요

즉 조건에 따라 이 Adder를 보여주거나 / 보여주지 않는 방식이 아니라, Adder를 항상 띄워놓고 showAdder를 props로 넘겨준다면 Adder 컴포넌트가 언마운트되지 않고 계속 떠 있을 테고, 그 안에서 css를 이용하여 보여주거나 보여주지 않는다면 해결될 거 같네요!

도움이 되셨나요?

---

추가: 모달이 떠 있는지에 대한 상태를 나타내는 `showAdder` 변수가 0 또는 1의 값을 가지는 코드를 구현하신 것 같은데, 모달이 떠 있는지에 대한 상태를 나타내는 `isShowAdder` 변수가 true 또는 false를 가지는 게 좀더 자연스러울 것 같네요!

**Comment by HyungGeun-Cho** [comment]
@woohm402 답변 감사합니다!
바로 적용해보겠습니다~~!!

**Comment by HyungGeun-Cho** [comment]
@woohm402 
제가 처음에는 말씀해주신대로 시도를 해보았었는데요.
Adder.js에서 Adder.css (둘은 같은 폴더에 담겨있습니다)에 담겨있는 속성을 변경하는데 계속 실패해서 
위와 같은 조건부 렌더링으로 방향을 틀게 되었습니다.
`document.getElementsByClassName("Adder").style.visibility="hidden"`로는 
style 속성을 계속 찾지 못해서 혹시 다른 방법으로 시도해야 하는지 질문드립니다..!

**Comment by woohm402** [comment]
[세미나 1 자료](https://docs.google.com/presentation/d/1hZbGqQFWWNJ3axvaRnQE24keNCmOWMz_u_iXZWG_3yQ/edit#slide=id.gec40ce685e_0_340) 34번 슬라이드 참고해보시겠어요? element의 스타일을 직접 조작하는 방식보다는 저 슬라이드와 같이 `className`을 변경하여 스타일을 변경하는 방식이 주로 차용됩니다.

**Comment by HyungGeun-Cho** [comment]
@woohm402 앗 감사합니다!!
바로 적용해보겠습니다!

**Comment by woohm402** [comment]
넵 잘 해결되셨나요?

**Comment by HyungGeun-Cho** [comment]
@woohm402 
넵! 잘 해결되었습니다.
기존처럼 `const [showAdder, setShowAdder]=useState(false);`를 활용했고,
조건부 렌더링 대신 세미나1 자료에 34번 슬라이드처럼 적용하였습니다!
감사합니다 :)
