### ISSUE TITLE
Github에서 Pull Request 하려 할때 Labeling 위한 탭이 보이질 않습니다.

### ISSUE THREAD

**Issue by isaac0622** [wafflestudio/19.5-rookies#35]
안녕하세요, 19.5 루키 오이석입니다.

다름이 아니라 이번 세미나 신청을 위해 PR을 연습해보던 중, 라벨을 추가하고자 하였는데, 화면 우측에 Labels 등의 탭이 보이지 않아 질문드립니다.

![image](https://user-images.githubusercontent.com/88360025/130453357-fbf43f64-864e-45b2-9d90-1c623fee5fae.png)

위 사진과 같이 화면 우측에 아무것도 보이지 않는 상황인데, 이에 지식을 공유해주시면 감사하겠습니다.

**Comment by jakehsj** [comment]
![캡처](https://user-images.githubusercontent.com/30540215/130454557-2ebb1fe3-9600-4e01-b343-d701284ce11e.PNG)

저는 일단 생성하고나서 옆에 label 부분에 톱니같은거 눌러서 추가하면 되더라구용

**Comment by woohm405** [comment]
![image](https://user-images.githubusercontent.com/89297482/130454826-71a52606-3221-43d3-b626-9895cf05fc85.png)

저도 같은 상황이었는데, 생성하고 나서 달 수 있는 것 같습니다. @woohm402

**Comment by isaac0622** [comment]
답변 주신 분들 감사합니다!
