### ISSUE TITLE
List and View Binding. Android

### ISSUE THREAD

**Issue by junhee-k** [wafflestudio/19.5-rookies#351]
button을 2D array안에 저장하기 위해서 button id를 index로 저장했는데 이것을 for loop으로 어떻게 구현해야할지 모르겠습니다.

혹시 다른 방법을 사용해야 하나요?

![KakaoTalk_20210909_190747024](https://user-images.githubusercontent.com/73790085/132670484-ea12040e-c5f1-457c-8324-1c73f2377ccf.png)

**Comment by veldic** [comment]
```
buttonList = listOf(
    listOf(binding.button11, binding.button12, ...),
    listOf(...),
    ...
)
```

`buttonList[0][1].setOnClickListener(~~)`

와 같은 방식으로 작성해주실 수 있을 것 같습니다. binding 자체에서 list 형식으로 받아오는 방식은 조금 힘들다고 보시는게 맞을 것 같습니다.
