### ISSUE TITLE
WSL환경에서 IntelliJ를 통해 Gradle 빌드시에 발생하는 오류

### ISSUE THREAD

**Issue by Alexjonghyun** [wafflestudio/19.5-rookies#353]
![캡처](https://user-images.githubusercontent.com/88361017/132677767-c512c80d-9e07-4828-aeb2-70a0c6d3699f.PNG)
이런 오류가 계속 나옵니다. 방화벽 문제인가 싶어서 윈도우고급설정에서 intellij 방화벽도 모두 해제해주었습니다.
혹시 같은 오류가 발생한 분 계신가요? 구글링해도 방화벽 이야기 말고는 나오지않습니다.

**Comment by Hank-Choi** [comment]
gradle jdk 와 프로젝트 jdk가 잘 설정돼있나요?
