### ISSUE TITLE
학생 리스트 표 관련 질문

### ISSUE THREAD

**Issue by kmsgm** [wafflestudio/19.5-rookies#354]
안녕하세요, 피그마에서 나온 디자인대로 학생 리스트가 나온 표를 작성하고 있는데 뭐가 문제인지 모르겠어서 질문드립니다.
[깃허브, 빈학생, 리액트] 학생 목록에 대해서 피그마처럼 표를 만드려고 합니다.

StudentTable.js
```
<div className="tableContent">
    <ul>
        {studentList.map(student => (
            <Student key={student.id} name={student.name} />
        ))}
    </ul>
</div>  
 ```

Student.js
```
function Student({ name }) {
    return (
        <div className="studentBlock">
            <li>{name}</li>
        </div>
    )
}
```
이런식으로 코드를 짜서 "studentBlock"을 만들어서 리턴해주는 식으로 짰는데 [깃허브, 빈학생, 리액트] 박스가 수직으로 쌓이는 게 아니라 같은 위치에 겹쳐져서 나타나는 것 같습니다.

구글링을 해보니 "tableContent"에 `dispaly: flex` `flex-direction: column`을 적용해주면 된다고 하는데 문제가 해결되지 않고 있습니다...
![image](https://user-images.githubusercontent.com/49176503/132694396-6d47c812-acd6-4a16-90f9-b9853b82ae93.png)

Student.js에서 `<div className="studentBlock">`를 없애고 그냥 출력하면 세 명 다 잘 나옵니다.
![image](https://user-images.githubusercontent.com/49176503/132696197-b34f41bc-e9d1-495e-9b48-c63818fc2c5b.png)

**Comment by kmsgm** [comment]
이렇게 됩니다!

```
.studentBlock {
    position: absolute;
    width: 869px;
    height: 73px;
    left: 0px;
    top: 0px;
    
    background: #F8F8F8;
    border: 1px solid #ACACAC;
    box-sizing: border-box;
}
```

혹시 몰라서 `<div className="studentBlock">`을 지우고 그냥 `<li className="studentBlock">{name}</li>`로 바꿔봤는데도 
문제가 해결되지 않았습니다...

**Comment by woohm402** [comment]
해당 부분은 `position: absolute;` 속성에 대한 이해가 필요합니다. [MDN](https://developer.mozilla.org/ko/docs/Web/CSS/position) 또는 [w3s](https://www.w3schools.com/css/css_positioning.asp) 중 취향에 맞는 곳에서 해당 속성에 대해 공부해보시면 확실히 이해되실 거예요.

간략하게 설명드리자면 해당 속성 때문에 css 코드에서 모든 `.studentBlock` 의 위치를 동일한 위치로 강제 지정하고 있기 때문입니다.

**Comment by kmsgm** [comment]
앗 넵넵 감사합니다!!
