### ISSUE TITLE
장고 lookup_field 및 auth_token을 통한 로그인 질문

### ISSUE THREAD

**Issue by jaejae2374** [wafflestudio/19.5-rookies#355]
안녕하세요 저는 19.5기 Rookies 이재현입니다.
assignment1 과제하다 몇가지 궁금증이 생겨 질문 드립니다.

1. 장고 공식 문서를 통해 이해한 바로는, viewsets을 활용할 때 POST와 달리 PUT이나 GET시에는 어떤 USER에 접근하는지 lookup_field를 통해 지칭해야 한다고 하셨는데, 그렇다면 update나 retrieve시에 /api/v1/user/ 가 아닌 /api/v1/user/{lookup} 으로 접근해야 한단 말인가요? 리드미대로 /api/v1/user/만 치면 method not allowed가 뜨고, /api/v1/user/{lookup_field parameters}로 치면 되긴 합니다..

2. 제가 로그인, 로그아웃에 대한 여부를 로그인시 token을 부여하고, token 존재 여부를 확인하고, 로그아웃시에 token을 제거해주는 방식으로 구현했는데, 이 token과 csrftoken의 차이점이 궁금합니다. 만약 token을 부여하는 방식으로 로그인 로그아웃을 구현한다면, 이 auth_token과 csrftoken 2개의 token이 한 계정에 쓰이는 건가요?

3. 사소하지만 survey에 models.py에 experience degree 를 보면 (1, very low) (2, low) (3, middle) (4, high) (5, very_high)로 되어있는데 very low 랑 very_high 랑 형태가 달라서.. 오타인지 아니면 따로 의도하신게 있는지 궁금합니다.

**Comment by ding-young** [comment]
안녕하세요, 저도 잘은 모르지만 1번이 궁금해서 코드를 조금 구경했는데, user의 urls.py 를 보면 `router = SimpleRouter()` 를 쓰고 있습니다, 이 `SimpleRouter`를  lib/python3.8/site-packages/rest_framework/routers.py 에서 찾아보시면, 아래 사진 같이 나올텐데, 한번 보시면 도움이 될 것 같습니다. 이미 확인하신 내용일지도 모르겠지만, 어디서는 `@action`이 있고.. 어디는 그냥 함수 이름만 특정하게 지어주면 되고.. 어떤 건 말씀하신 것처럼 lookup field가 필요하네에 관한 내용을  확인하실 수 있을 것 같습니다 :)
![SimpleRouter](https://user-images.githubusercontent.com/88336128/132711304-569a351c-bc6e-41e8-8f58-503375e62f78.png)

**Comment by jaejae2374** [comment]
> 안녕하세요, 저도 잘은 모르지만 1번이 궁금해서 코드를 조금 구경했는데, user의 urls.py 를 보면 `router = SimpleRouter()` 를 쓰고 있습니다, 이 `SimpleRouter`를 lib/python3.8/site-packages/rest_framework/routers.py 에서 찾아보시면, 아래 사진 같이 나올텐데, 한번 보시면 도움이 될 것 같습니다. 이미 확인하신 내용일지도 모르겠지만, 어디서는 `@action`이 있고.. 어디는 그냥 함수 이름만 특정하게 지어주면 되고.. 어떤 건 말씀하신 것처럼 lookup field가 필요하네에 관한 내용을 확인하실 수 있을 것 같습니다 :)
> ![SimpleRouter](https://user-images.githubusercontent.com/88336128/132711304-569a351c-bc6e-41e8-8f58-503375e62f78.png)

오호 그렇군요.. 답변 감사드립니당 !!

**Comment by kk0in** [comment]
@jaejae2374 안녕하세요! /api/v1/user/{lookup_field parameters} 로 전달하면 된다고 하셨는데, lookup_field parameter에 어떤 양식으로 들어가는지 여쭤볼 수 있을까요? 저도 이 부분에서 막혀서 한참 헤매는 중입니다 ㅜ

**Comment by gina0605** [comment]
관련 문서(DRF)입니다! https://www.django-rest-framework.org/api-guide/routers/#simplerouter
그리고 이건 작년 이슈인데 확인해보시면 좋을 것 같아요. 작년에도 과제 스펙은 비슷했습니다 https://github.com/wafflestudio/18.5-rookies/issues/120

**Comment by jaejae2374** [comment]
@kk0in 저도 자세히는 모르지만 전에 이슈에서 세미나장님이 lookup_field로 user을 식별할 수 있는 키로 하면 된다고 하셔서 일단 중복이 없는 username으로 해놓긴 했습니다 ㅠ

**Comment by gina0605** [comment]
API를 그렇게 만드셔도 구현 자체가 잘못됐다 할 수는 없지만, 과제 스펙과 맞지 않게 됩니다. 과제에서 요구한 것은 `PUT /api/v1/user/{user_id}/`가 아니라 `PUT /api/v1/user/`이니까요. DRF의 SimpleRouter와 ViewSet을 이용하면 lookup이 endpoint를 만들 수 있는데, 이번 과제의 스펙은 그것이 아니기 때문에 다른 방법을 이용하셔야할 겁니다. 그 중 제가 가장 깔끔하다고 생각하는 방법은, 이 [튜토리얼](https://www.django-rest-framework.org/tutorial/3-class-based-views/)에 있는 것처럼 view의 이름을 put으로 하는 것입니다. 그러면 lookup이 없는 API가 만들어질 겁니다. 이는 ViewSet이 아니라 Class-based Views에서 제공해주는 routing 기능입니다.

**Comment by jaejae2374** [comment]
@gina0605 답변 감사합니다. 말씀해주신대로 수정해보겠습니다 !

**Comment by kk0in** [comment]
> API를 그렇게 만드셔도 구현 자체가 잘못됐다 할 수는 없지만, 과제 스펙과 맞지 않게 됩니다. 과제에서 요구한 것은 `PUT /api/v1/user/{user_id}/`가 아니라 `PUT /api/v1/user/`이니까요. DRF의 SimpleRouter와 ViewSet을 이용하면 lookup이 endpoint를 만들 수 있는데, 이번 과제의 스펙은 그것이 아니기 때문에 다른 방법을 이용하셔야할 겁니다. 그 중 제가 가장 깔끔하다고 생각하는 방법은, 이 [튜토리얼](https://www.django-rest-framework.org/tutorial/3-class-based-views/)에 있는 것처럼 메소드의 이름을 put으로 하는 것입니다. 그러면 lookup이 없는 API가 만들어질 겁니다. 이는 ViewSet이 아니라 Class-based Views에서 제공해주는 routing 기능입니다.

제가 이렇게 했는데, 이렇게하면 가장 최근에 회원가입한 사람에 대해서만 수정이 이뤄집니다.  마찬가지로 6번 문제의 logout, 7번 문제의 get도 이러한 특성을 보이는데, 이것이 과제에서 의도한 방향이 맞는지 궁금합니다!

**Comment by gina0605** [comment]
이 이슈 https://github.com/wafflestudio/19.5-rookies/issues/358#issuecomment-916643085 에서 코멘트 달았던 것과 같이, 현재 로그인되어있는 사람에 대해서 정보 수정, 로그아웃, 정보 조회가 되기 때문입니다. 아마 6번까지 진행하신 후, 로그아웃을 하고 다른 유저로 로그인을 하면 가장 최근에 회원가입한 것이 아닌 사람에 대해서 정부 수정, 로그아웃, 정보 조회가 될 것입니다.

**Comment by jaejae2374** [comment]
@kk0in 넵 저도 방금 수정했는데 되네용 @gina0605 님 말씀대로 순서가 포스트맨에서 로그인하고 그 로그인한 계정을 토대로 수정 및 조회가 가능하게 됩니다.

**Comment by jaejae2374** [comment]
2번에 대한 장고 세미나장님의 답변 받았습니다. 질문들에 대한 궁금증이 모두 해소되었습니다. 감사합니다.

A : auth_token을 사용하신 것과 리드미에 남기신 것에 대해 설명드리자면, 일단 별도 처리 없이 추가하신 경우 두 가지의 다른 토큰을 모두 관리해주어야 하는 것이 맞습니다. Auth token은 좀 더 REST api 다운 인증 방식으로, 토큰만 있으면 session이나 쿠키 없이 인증을 처리할 수 있도록 도와주는 인증 방식입니다. 보통은 이 경우에는 csrf를 굳이 사용하지 않는 것 같습니다.
