### ISSUE TITLE
ManytoOne 관계에서 부모 삭제시 SET NULL 관련 질문입니다.

### ISSUE THREAD

**Issue by Gorani9** [wafflestudio/19.5-rookies#357]
안녕하세요. 과제를 진행하다가 막히는 부분이 있어서 질문드립니다. 과제1의 3번을 보면 이렇게 적혀있습니다.
> 연결되어있는 user row가 삭제된다고 해도 survey_response의 해당 row까지 같이 삭제되면 안 됩니다.

그래서 SurveyResponse 모델에 다음과 같이 구현했습니다.
```
@ManyToOne
@OnDelete(action = OnDeleteAction.NO_ACTION)
@JoinColumn( ~~~)
```
아직 저희는 삭제하는 로직을 구현하지 않아서, 직접 mysql 명령어를 통해 user row를 삭제해봤습니다. 해당 survey_response row는 삭제되지 않은 것은 확인했는데 user_id가 null로 설정되지 않고 그대로 있었습니다.

여기서 생기는 문제점이 `GET /api/v1/result/{해당 survey_response_id}/` 로 요청을 날리면 `404`가 뜹니다. 
user_id가 null로 설정되지 않아서 생기는 문제점인 것 같습니다.

Django와 다르게 Spring Boot는 아무리 구글링해도 null로 설정하는 옵션이나 코드가 없는 것 같아서 질문드립니다.
정리하자면,
 1. 참조하는 row가 삭제될 때 null로 설정하는 방법이 있나요?
 2. 아니면 삭제하는 로직 구현할 때 직접 null로 세팅해야 되는 건가요?

입니다.

**Comment by cs71107** [comment]
과제의 힌트에 보면 cascade type이 있는데, 그걸 사용해야 전파되는 것 아닌가요?

**Comment by Gorani9** [comment]
Cascade를 정해주면 같이 삭제하라는 의미 아닌가요? 제가 이해한 바로는 그렇습니다

**Comment by PJH6029** [comment]
[Cascade Type](https://data-make.tistory.com/668)이 따로 분류되어있는 것 같습니다

**Comment by Hank-Choi** [comment]
일단 해당 내용은 혼란을 가져올 것 같아 삭제했습니다.
세미나 중에 얘기할 예정이고 해당 내용은 구현하지 않으셔도 됩니다.
