### ISSUE TITLE
Django assignment 1 5번 문제 질문 (PUT api/v1/user/{lookup} 관련)

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#358]
안녕하세요. 5번 문제에서 update() 함수까지는 만들었는데, postman에서
PUT localhost:8000/api/v1/user/{lookup}/ 와 같이 쿼리를 날리면, lookup에 어떤 숫자, 문자가 들어가던지에 관계없이 가장 최근에 회원가입한 사람의 정보가 수정되는데, 제가 lookup 부분의 양식을 잘 몰라서 이러한 문제가 발생하는 것 같습니다. 구글링을 많이 했는데도, 해당 부분에 대한 정보를 찾을 수 없어 질문을 드립니다. 첨부한 사진은 lookup에 숫자와 문자를 넣어서 날렸을 때, 동일한 response가 나오는 것을 보여주고 있습니다.

![스크린샷, 2021-09-10 04-35-36](https://user-images.githubusercontent.com/84329238/132751331-33e17be2-8e5d-4322-84c5-3f0db085b2b5.png)
![스크린샷, 2021-09-10 04-35-24](https://user-images.githubusercontent.com/84329238/132751327-ac10eb30-59f5-48b9-bb8b-0d2492772398.png)

**Comment by gina0605** [comment]
우선 제가 과제 스펙을 읽어보기로는 `PUT /api/v1/user/` API를 만들어야 하는 것이고, `PUT /api/v1/user/{lookup}/`가 아닌 것으로 보입니다. 아마 가장 최근 사람의 정보가 수정되는 이유는 그 사람이 로그인 되어있기 때문일 겁니다. (회원가입 후 자동 로그인)

그리고 이슈 이름 바꿔주세요! '과제1 5번' 이런 제목보다는, 과제 내용을 모르는 사람이 보더라도 대충 이해할 수 있는 제목이 좋습니다. 그리고 5번 내에서도 다양한 문제를 겪을 수도 있고요

**Comment by kk0in** [comment]
@gina0605 답변 감사합니다! 제목은 이 댓글을 작성한 이후에 바로 바꾸도록 하겠습니다. 그러면, 과제 의도가 가장 최근에 회원가입한 사람의 정보를 수정하는 건가요? 제가 문제를 이해하기로는 이미 가입한 여러 회원중에서 특정 user의 정보를 바꾸는 것으로 이해를 했어서요! 그리고, 이전 이슈 중에 /api/v1/user/{lookup}/ 을 통해 lookup으로 특정 user를 가리킬 수 있다는 내용을 봤습니다.

**Comment by kk0in** [comment]
> @gina0605 답변 감사합니다! 제목은 이 댓글을 작성한 이후에 바로 바꾸도록 하겠습니다. 그러면, 과제 의도가 가장 최근에 회원가입한 사람의 정보를 수정하는 건가요? 제가 문제를 이해하기로는 이미 가입한 여러 회원중에서 특정 user의 정보를 바꾸는 것으로 이해를 했어서요! 그리고, 이전 이슈 중에 /api/v1/user/{lookup}/ 을 통해 lookup으로 특정 user를 가리킬 수 있다는 내용을 봤습니다.

https://github.com/wafflestudio/19.5-rookies/issues/327#issuecomment-914375575
제가 위에서 말씀드린 issue는 위 링크를 참고하시면 될 거 같습니다.

**Comment by gina0605** [comment]
과제 의도는 현재 로그인 되어있는 유저의 정보를 수정하는 것입니다. 5번까지 하신 상황이면 아직 로그아웃 API가 없어서 가장 최근에 가입한 유저로 로그인되어있는 상황일 텐데, 조금 더 진행하시면 로그인과 로그아웃 API도 만드시게 될 것입니다. 그러한 상황에서는 (가장 최근에 회원가입한 사람)==(현재 로그인되어있는 사람) 이라는 명제가 틀리게 되겠지요.

327번 이슈에서 언급된 lookup은, 이번 과제가 아닌 일반적인 상황에 대한 설명으로 보입니다. 현재 과제 스펙에서는 `PUT /api/v1/user/` API를 만들기를 요구하고 있습니다. 그러나 보통은 `PUT /api/v1/user/1/`(혹은 `PUT /api/v1/user/me/`)와 같은 방식으로, 1번 유저(혹은 나)의 정보를 수정하겠다, 이런식으로 API를 설계합니다. DRF의 SimpleRouter는 이러한 상황을 가정한 것이라 update 함수를 이용하면 `PUT /api/v1/user/{lookup}/` API가 만들어집니다. 이번 과제에서 요구하는 스펙은 그것이 아니므로 다른 방법을 이용해 `PUT /api/v1/user/` API를 만들어야 할 것입니다. 작년 이슈 https://github.com/wafflestudio/18.5-rookies/issues/158#issuecomment-691692021 도 확인해보시면 좋을 것 같습니다!

**Comment by kk0in** [comment]
@gina0605 아 이해가 된 것 같습니다! 감사합니다. 한가지 질문이 더 있는데, 5번 문제에서 수정한다는 어디까지 허용이 가능한가요? 예를 들어, first name과 last name은 그대로 두고, username을 수정한다는 명목 하에 아예 지울 수도 있는건가요?

**Comment by gina0605** [comment]
일부 수정은 가능해야할 텐데, blank로 수정하는 부분은 잘 모르겠네요.
@Jhvictor4 username을 blank로 설정하는 것도 가능한가요...?

**Comment by Jhvictor4** [comment]
Username을 blank로 두는것은 어색합니다.
구현 상으로도, 특별히 조치를 취하지 않으면 username에 natural_key, 즉 unique 설정이 걸리게 됩니다.
빈 유저이름이 허용된다면 이런 뒷배경과 대치되겠죠?
서버 개발에선 항상 컨텍스트를 인지하는 것도 중요합니다..!

**Comment by kk0in** [comment]
답변 감사합니다!!
