### ISSUE TITLE
모달효과 관련하여 질문드립니다!

### ISSUE THREAD

**Issue by hmlinnie** [wafflestudio/19.5-rookies#361]
안녕하세요! 와플 루키 김혜민입니다.
리액트 세미나 1 과제 중 모달이 뜨는 효과를 구현 중인데,
추가 버튼을 눌렀을 때 모달이 떴다가 (닫기 버튼을 누르지 않았는데도) 바로 사라지는 현상이 일어납니다.
여러 가지 시도를 해보았는데 해결할 방법을 찾지 못해 질문드립니다!
지금 적용한 코드는 아래와 같습니다!

*추가 버튼

```
const StuAdd = () => {

    const [modalOpen, setModalOpen] = useState(0);

    const openModal = () => {
        setModalOpen(1);}

    const closeModal = () => {
        setModalOpen(0);}

    return (
        <div className={"stuadd"}>
            <button className={"addbutton"} onClick={openModal}>추가</button>
            <StuModal open={modalOpen} close={closeModal} />
        </div>
    );
}
```

*모달

```
const StuModal = (props) => {

    const{open, close} = props;

    return (
        <div className={open===1 ? 'openModal modal':'modal'}>
            {open===1 ? (
                <section className={"modal-section"}>
                    <button className={"close"} onClick={close}>닫기</button>
                    <button className={"addinput"}>추가</button>
                </section>
            ) : null}
        </div>
    )
}
```

**Comment by woohm402** [comment]
.openModal과 .modal의 css 코드를 봐야 알 수 있을 것 같습니다! 로직상으로는 별 문제 없이 보여야 합니다

**Comment by hmlinnie** [comment]
현재 적용한 css는 다음과 같습니다!

```
.modal {
    background-color: rgba(0, 0, 0, 0.6);
    display: none;
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}

.openModal {
    display: flex;
    align-items: center;
}
```

**Comment by woohm402** [comment]
'openModal modal' 을 'modal openModal' 로 바꿔보시기 바랍니다. 의도와 다르게 .openModal의 `display: flex` 속성이 역으로 `.modal`의 `display; none`에 의해 덮어씌워졌을 수 있습니다.

**Comment by hmlinnie** [comment]
바꿔보았는데 계속 같은 현상이 일어납니다ㅠㅠ

**Comment by woohm402** [comment]
개발자 도구 확인해보시겠어요?
1. Elements 탭 확인하셔서 해당 div 아이템이 없는지 확인해보시고,
2. 있다면 아래의 style탭 확인하셔서 `display: none` 속성이 적용돼 있는지 확인해 보시기 바랍니다.

결과 확인하시고도 해결이 안 되셨다면 결과 캡쳐해서 올려주시면 좋을 것 같아요!

**Comment by hmlinnie** [comment]
현재 개발자도구 화면입니다!
아직 개발자도구에 익숙하지 않아 해결 방법을 찾지 못해 다시 질문드립니다.
모달의 div는 존재하고, style탭에서 display:none만 보이고 display: flex는 보이지 않는 상태입니다.
<img width="398" alt="2021-09-10" src="https://user-images.githubusercontent.com/88392435/132802587-e3b88687-9a3c-4090-b82b-e26ad5e3834f.png">

그리고 아래는 현재 일어나는 현상입니다.
![ezgif-3-677db9ff4d93](https://user-images.githubusercontent.com/88392435/132802727-6c9ab06b-c419-4cb2-acc2-27e32076c9c0.gif)

**Comment by woohm402** [comment]
아 바로 사라지는게 `css` 이슈가 아니었군요 어쩐지 뭔가 이상하더라

---

먼저 어떻게 된 건지 설명을 드리자면, 이건 좀 어려운 내용인데, 지금 보면 form -> div -> div -> button 순서로 구현되어 있습니다.

html의 [`<form>`](https://developer.mozilla.org/ko/docs/Web/HTML/Element/form) 태그는 자기 자식들한테서 `submit`이벤트가 발생하면 자동으로 자기의 `onSubmit` 핸들러를 실행한 다음 새로고침을 해 버리는 기본 속성이 있습니다.

또한 `<button>` 태그는 기본 타입이 `submit`입니다. (참고: [MDN](https://developer.mozilla.org/ko/docs/Web/HTML/Element/button#attr-type)) 따라서 추가 버튼을 클릭하면 submit 이벤트가 발생하게 되고, form이 그걸 알아먹고 자동으로 페이지 새로고침을 해 버립니다.

이걸 해결하려고 구글에 검색을 하면 `e.preventDefault()`를 달라고 하는 스택오버플로우의 답변들이 많이 나올 텐데, 근본적인 해결 방법은 아닙니다. 아니면 `<button>` 태그에 `type="button"` 속성을 줘도 해결은 됩니다만 역시 근본적인 해결책은 아닙니다.

기본적인 문제는 좌측 테이블이 `<form>`일 이유가 없다는 부분입니다. `<form>` 태그는 말 그대로 폼을 제출하는 용도이며, 제출 양식이라든가, 학생 추가, 학생 정보 수정 등의 상황에 쓰여야 합니다.

---

말이 길어졌는데 저 위에꺼를 form 말고 div나 section같은 화면 분할용 태그로 바꾸면 해결될 거예요!

**Comment by woohm402** [comment]
수업시간에 말씀드렸듯이 프론트는 다른 데랑 다르게 무슨 코드를 짜도 안 되는 경우는 잘 없는데 원래 돼놓고 나중에 아무도 모르게 뒤통수를 치는 경우가 많아서.. 항상 자기가 짜는 코드, 사용한 태그, 사용한 속성이 어떤 속성인지 잘 아는 게 중요합니다

**Comment by hmlinnie** [comment]
넵!! form 바꾸니까 바로 해결되었습니다.
자세히 설명해주셔서 감사합니다!!
