### ISSUE TITLE
unresolved reference viewmodels 문제 질문입니다.

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio/19.5-rookies#362]
안녕하세요.

gradle(module)에 
```
implementation 'androidx.activity:activity-ktx:1.3.1'
```
를 추가하고,

새 Kotlin class  MainViewModel 을 만들어서
```
package com.example.assignment1

import androidx.lifecycle.ViewModel

class MainViewModel : ViewModel() {
}
```
로 작성해 주고, MainActivity.kt에서 
```
private val viewModel : MainViewModel by viewModels()
```
를 하려 했는데 viewModels()에서 빨간 줄이 납니다.
구글링 해보면 이런저런 implementation을 추가해보라고 하는데 해 봐도 다 잘 안되고 이걸 막 해도 되나 걱정되기도 합니다.
세미나 그대로 따라해 보고 있는데 잘 안되네요. 어떻게 해결할 수 있을까요?

**Comment by JuTaK97** [comment]
재부팅 했더니 됐습니다 .. 좀더 신중하게 이슈를 올리도록 하겠습니다

**Comment by veldic** [comment]
Gradle 수정 후 Sync Now를 하지 않으셨을 수도 있겠네요. 안드로이드 프로젝트가 열릴 때 gradle build를 하므로 재부팅해서 문제가 해결 됐을 가능성이 높아 보입니다.

**Comment by veldic** [comment]
혹은 한번씩 안드로이드 스튜디오가 맛이 갈 때가 있습니다... 재부팅도 하나의 좋은 방법이에요. (컴퓨터 본체 쳐보는거랑 비슷합니다(?))
