### ISSUE TITLE
observe가 실행이 안됩니다...

### ISSUE THREAD

**Issue by Whiteppanda** [wafflestudio/19.5-rookies#364]
***kotlin
//MainActivitiy.kt에서 

    private lateinit var binding: ActivityMainBinding
    private val viewModel: MainViewModel by viewModels()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        binding.imageButton1.setOnClickListener{//just do it
            viewModel.changeState(0)
            it.isClickable = false
        }
        viewModel.lst.observe(this,{
            val myToast: Toast = Toast.makeText(this.applicationContext,"here",Toast.LENGTH_SHORT)
            myToast.show()
            viewModel.judgeNow()
            viewModel.changeText()
            binding.textView.text = viewModel.text.value
        })

//MainViewBinding.kt 에서

    class MainViewModel: ViewModel() {
        private val _lst = MutableLiveData<MutableList<Int>>(mutableListOf(0, 0, 0, 0, 0, 0, 0, 0, 0))
        var lst : LiveData<MutableList<Int>> = _lst
        private val _state = MutableLiveData<Int>(0)//state of game
        fun changeState(i: Int){//순서와 버튼의 상태를 변경한다.
            Timber.d("clicked button")
            _order.value = _order.value != true
            if(_order.value == true){//o
                _lst.value?.removeAt(i)
                _lst.value?.add(i,1)

            }
            else{//x
                _lst.value?.removeAt(i)
                _lst.value?.add(i,2)
            }
        }
***

observe에 있는 toast가 처음 실행할때 한번 뜨고 그 이후로 버튼을 눌러도 뜨지 않습니다. observe가 안된다고 생각할 수 밖에 없는데 
왜 이러는 걸까요.. 제가 view binding, livedata 선언은 몇번을 봐도 틀리지 않은 것 같은데 도저히 모르겠습니다...

**Comment by JuTaK97** [comment]
안녕하세요, 저도 비슷한 문제가 있어서 찾아보다가 이렇게 해결했습니다.

참고) https://stackoverflow.com/questions/53790523/observe-a-mutablelivedata-list

fun changeState 안에서 마지막에 _lst.value = _lst.value 를 넣어줘야(즉, list 전체가 뭔가 바뀌어야) observer에게 callback이 가는? 그런 형태인 것 같네요
이걸로 해결이 되었으면 좋겠습니다!

**Comment by veldic** [comment]
https://developer.android.com/topic/libraries/architecture/livedata#update_livedata_objects

위 링크 참고해주시면 `postValue()` 혹은 `setValue()`를 통해야만 observe에서 반응할 수 있다는 걸 알 수 있습니다. Kotlin에서 `setValue()`가 `.value`를 통한 접근으로 표현되므로 `_lst.value`의 변화가 필요합니다.

**Comment by Whiteppanda** [comment]
> https://developer.android.com/topic/libraries/architecture/livedata#update_livedata_objects
> 
> 위 링크 참고해주시면 `postValue()` 혹은 `setValue()`를 통해야만 observe에서 반응할 수 있다는 걸 알 수 있습니다. Kotlin에서 `setValue()`가 `.value`를 통한 접근으로 표현되므로 `_lst.value`의 변화가 필요합니다. 

_lst.value의 변화라고 하시면 위에서 fun을 통한 _lst.value?.add(i)는 _lst의 변화가 아닌건가요?

**Comment by veldic** [comment]
> > https://developer.android.com/topic/libraries/architecture/livedata#update_livedata_objects
> > 위 링크 참고해주시면 `postValue()` 혹은 `setValue()`를 통해야만 observe에서 반응할 수 있다는 걸 알 수 있습니다. Kotlin에서 `setValue()`가 `.value`를 통한 접근으로 표현되므로 `_lst.value`의 변화가 필요합니다.
> 
> _lst.value의 변화라고 하시면 위에서 fun을 통한 _lst.value?.add(i)는 _lst의 변화가 아닌건가요?

_lst.value?.add(i)는 `MutableList`의 변화이지 `MutableLiveData`의 변화가 아닙니다. observe가 작동하기 위해서는 `MutableLiveData`의 변화가 필요합니다.

**Comment by woohm402** [comment]
@Whiteppanda 해결되셨나요?
