### ISSUE TITLE
props, component rerendering 관련해 질문드립니다

### ISSUE THREAD

**Issue by 0114kek** [wafflestudio/19.5-rookies#365]
동일한 component를 여러번 사용했고 이들간에 정보를 주고받을 필요성이 생겼습니다.
이를 위해 공통 부모인 component에 저장된 값을 props로 자식 component들에 주었습니다.
그런데 값을 변경했을때 부모 component에서는 해당 값이 이미 바꼈음을 확인할 수 있는데
자식 component들에서는 여전히 처음에 입력된 값이 갱신되지 않고 그대로 있습니다.

찾아보니 useState같은 것을 이용해 component를 re-rendering할수있다고하는데
여러 방법들을 모두 시도해 보아도 여전히 해결되지 않는 것 같습니다.

어떻게하면 props가 늦게 반영되는 문제를 해결할 수 있을지 궁금합니다

**Comment by woohm402** [comment]
첫 수업에서 말씀드렸다시피, 데이터 버그가 발생하는 상황을 막기 위해 flux 패턴이 고안되었고, 이 패턴은 성능을 포기한 만큼 데이터 관련 버그를 제거하는 데에 아주 효과적입니다. 즉 flux 패턴을 사용한다면 데이터 버그가 발생할 수 없습니다.

또한 부모가 re-render된다면 자식도 무조건 re-render가 됩니다. 따라서 부모가 값을 바꿔서 props로 넣어 줬는데 자식이 해당 props를 보내주는 과정에서 이전 데이터를 출력하는 경우는 있을 수 없습니다. 추천드리는 체크포인트는 다음과 같습니다.

1. 부모가 props로 넘겨주는 값을 자식이 state의 초기값으로 지정하나요? 이는 잘못된 패턴으로, 굉장히 많은 버그를 양산합니다. ([참고](https://medium.com/@justintulk/react-anti-patterns-props-in-initial-state-28687846cc2e)
2. 부모가 바뀐 값을 자식의 props로 잘 넘겨주고 있나요? 다른 값을 넘겨주고 있을 수도 있습니다.
3. 아마 자식들이 배열 render 구조일 것 같은데, map하실 때 key값이 올바르게 잘 설정되어 있나요?

위 사항들 확인해보시기 바랍니다!

**Comment by 0114kek** [comment]
1,2는 확인해보니 아니었고 3번은 key를 설정해주었는데 여전히 해결되지 않았습니다
아래 gif를 첨부했습니다. 뭔가 다른 부분을 건드려 rerendering 시키면늦게 반응이 오는것같습니다...
![GIF 2021-09-10 오후 4-43-41](https://user-images.githubusercontent.com/88540493/132819018-4b3af9df-d410-4445-9052-eccc17452fda.gif)

**Comment by woohm402** [comment]
@0114kek 코딩중이신 레포 들어가서 코드 한번 확인해봤는데 1번 맞는 거 같습니다..?

[props의 값](https://github.com/0114kek/waffle-rookies-19.5-react-assignment-1/blob/8b220024321bde51f5aef5ff858f0e58db2b728f/react_assign_1/src/Student.js#L5) 을 [state의 초기값으로 지정](https://github.com/0114kek/waffle-rookies-19.5-react-assignment-1/blob/8b220024321bde51f5aef5ff858f0e58db2b728f/react_assign_1/src/Student.js#L16) 중이신 거 같아요

**Comment by 0114kek** [comment]
아 해결되었습니다 말씀해주신 "또한 부모가 re-render된다면 자식도 무조건 re-render가 됩니다. "에서 답을 찾았습니다
애초에 부모 컴포넌트 자체가 re-rendering이 되지 않아 발생한 현상이었습니다!

**Comment by woohm402** [comment]
아하 넵 다행이군요 아무튼 이것도 해결하지 않으시면 잠재적으로 많은 버그가 양산될 수 있다는 점 전달드립니다 👍 

> @0114kek 코딩중이신 레포 들어가서 코드 한번 확인해봤는데 1번 맞는 거 같습니다..?
> 
> [props의 값](https://github.com/0114kek/waffle-rookies-19.5-react-assignment-1/blob/8b220024321bde51f5aef5ff858f0e58db2b728f/react_assign_1/src/Student.js#L5) 을 [state의 초기값으로 지정](https://github.com/0114kek/waffle-rookies-19.5-react-assignment-1/blob/8b220024321bde51f5aef5ff858f0e58db2b728f/react_assign_1/src/Student.js#L16) 중이신 거 같아요

**Comment by 0114kek** [comment]
그 부분도 수정하겠습니다 감사합니다
