### ISSUE TITLE
spring post /api/v1/results/ 관련 질문

### ISSUE THREAD

**Issue by cs71107** [wafflestudio/19.5-rookies#366]
안녕하세요. 다름이 아니라 spring seminar assignment 8번에 해당하는 post /api/v1/results/ 관련 질문이 있습니다.
현재 api는 한 명의 user가 여러 번의 설문을 제출 가능하게 했는데,
이때, 이미 제출한 유저가 설문을 또 제출 했을 경우 이것을 기존 설문을 수정하는 것으로 봐야 하는지, 아니면 새로 생성하는 것으로 봐야 하는지 궁금합니다.
또, 새로 생성하는 것이라면, Survey DTO의 modifyrequest class의 존재 이유는 무엇인지 질문드립니다.

+ 그리고 과제 리드미에는 /result/라고 endpoint가 되어 있는데, 제가 착각한게 아니라면 /results/가 돼야 할 것 같습니다.

**Comment by cs71107** [comment]
그리고 저의 경우 label과 milestone이 보이지 않는데... 제 개인 깃헙 계정 문제라 생각해서 어제 해결을 시도해봤습니다만 여전히 해결되지 않아서 일단 이렇게 올립니다. 죄송합니다 ㅠㅠ

**Comment by woohm402** [comment]
> 그리고 저의 경우 label과 milestone이 보이지 않는데... 제 개인 깃헙 계정 문제라 생각해서 어제 해결을 시도해봤습니다만 여전히 해결되지 않아서 일단 이렇게 올립니다. 죄송합니다 ㅠㅠ

제가 깜박하고 초대를 안드렸습니다 😢

**Comment by Hank-Choi** [comment]
rest api 스펙에 따르면 post는 항상 새로 생성하는 것입니다. modify 리퀘스트의 경우 과제 상 넣으려다 빠진 흔적이니 무시하고 진행해주세요

result/ 부분은 수정하겠습니다.
