### ISSUE TITLE
Django assignment 1 8번: GET /api/v1/survey/{surveyresult_id} 관련 질문

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#368]
안녕하세요. 첨부한 사진에서 드래그된 부분이 어떤 것을 요구하는 것인지 이해가 되지 않아서 질문드립니다.
어떤 serializer를 이용하라는 건지 힌트주시면 감사하겠습니다. 아니면 9번 문제가 8번과 이어져 있는
![8번 문제](https://user-images.githubusercontent.com/84329238/132839173-678df2f7-8908-4657-944a-741d61b5e85f.png)
 질문인가요?

**Comment by Jhvictor4** [comment]
넵 ResponseBody로 같은 형식을 사용하라는 것인데요, 과제 스켈레톤으로 주어진 정보 내에서 충분히 해결 가능하실 것 같습니다!

**Comment by Jhvictor4** [comment]
9번은 8번 이후에 진행하는 것으로 해주세요!

**Comment by kk0in** [comment]
네 알겠습니다. 감사합니다!
