### ISSUE TITLE
React 청강 가능한지 여쭙니다.

### ISSUE THREAD

**Issue by yeonsumia** [wafflestudio/19.5-rookies#369]
안녕하세요,
Springboot 수강생 전현성입니다.

다름이 아니오라, 처음에 청강 신청하였던 세션(iOS)을 React로 변경하고자 하는데
가능한지 여쭙고자 issue 게재합니다.
또한 가능하다면 과제 피드백이 이루어지는지 궁금합니다.

감사합니다.

**Comment by woohm402** [comment]
공식적으로 청강 세션을 바꾸는 건 불가능하지만, 리액트 줌 링크는 항상 열려 있고, 수업에 들어오신 분이 어떤 분이든 쫓아낸다거나 뭐 그런 조치를 취하지는 않습니다. 피드백의 경우 시간적 한계로 인해, 거의 수강생 분들 위주로 진행되고 있습니다.

답변이 되셨을까요?

**Comment by yeonsumia** [comment]
네 감사합니다! :)
