### ISSUE TITLE
Modal transition 효과에 대해서 질문 드립니다

### ISSUE THREAD

**Issue by Songmin17** [wafflestudio/19.5-rookies#370]
안녕하세요,
리액트 과제를 하다가 Modal transition 효과에 대해서 질문이 생겨서 이슈를 올립니다.
Fade in, Fade out 효과를 만드려고 CSS 에다가 transition 효과를 넣었는데도 전혀 반영이 되지 않아서, 
어디에서 문제가 생기는지 원인 파악을 하고 싶어서 질문 드립니다.
ModalWrapper 클래스 안에 모달 자체인 PopUp 클래스를 만들었는데, 각각의 CSS 이렇게 구현했어요:

.ModalWrapper {
    width: 100vw;
    height: 100vh;
    left: 0px;
    top: 0px;
    display: flex;
    position: fixed;
    -webkit-box-pack: center;
    justify-content: center;
    -webkit-box-align: center;
    align-items: center;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 15;
    /*animation: 0.15s ease-out 0s 1 normal none running gHmQJP;*/
    transition: opacity 0.80s ease-in-out;
}

.PopUp {
    background-color: white;
    width: 669px;
    height: 281px;
    padding: 30px 30px 0px;
    position: relative;
    display: block;
    margin-top: 0em;
    overflow: hidden;
    transition: opacity 3s ease-in-out;
    /*-webkit-transition: opacity 400ms ease-in;*/
    /*transition: opacity 10s;*/
    /*transition: all ease 1s;*/
}

여기서 주석처리한 transition을 다 시도해봤지만 fade in이 반영이 안되서, 이 이유에 대해서 알려줄 수 있나요?
감사합니다.

**Comment by woohm402** [comment]
1. transition 속성은 해당 element의 css 속성이 변할 때 (가령 조건부 css로 인해) 적용됩니다.
지금 css대로라면 transition이 반영될 수 없는 것 같습니다. ([예제](https://www.w3schools.com/css/css3_transitions.asp)])

2. animation 속성은 키프레임이 있어야 합니다. 올려주신 css에서는 keyframe이 없는 것 같습니다. ([예제](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_Animations/Using_CSS_animations#%ED%85%8D%EC%8A%A4%ED%8A%B8%EA%B0%80_%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80%EB%A5%BC_%EA%B0%80%EB%A1%9C%EC%A7%88%EB%9F%AC_%EC%9B%80%EC%A7%81%EC%9D%B4%EA%B2%8C_%ED%95%98%EA%B8%B0))
