### ISSUE TITLE
Django assignment 1 9번 문제 이해 확인 질문

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#374]
안녕하세요. 간단한 질문인데, 혹시나 하는 마음으로 질문을 드립니다.
9번 문제에서 제가 이해하기로는 연결된 user가 없을 경우에, 

"user" : null 

위와 같이 response에 떠야하는 거 같은데, 제대로 문제를 이해한건지 궁금합니다!
감사합니다.

**Comment by Jhvictor4** [comment]
넵 맞습니다
