### ISSUE TITLE
spring boot post /api/v1/results/ requestbody에 대한 질문

### ISSUE THREAD

**Issue by cs71107** [wafflestudio/19.5-rookies#378]
안녕하세요. 현재 과제1에서 8번에 해당하는 내용을 구현 중인데, request body에서 rdb_exp 등의 값이 string으로 들어온다고 생각해야 할까요, 아니면 int로 들어온다고 생각해야 할까요? 아니면 자유롭게 구현해도 되는 건가요?

**Comment by Hank-Choi** [comment]
자유롭게 구현해도 됩니다!
