### ISSUE TITLE
spring cascade type 관련 질문

### ISSUE THREAD

**Issue by cs71107** [wafflestudio/19.5-rookies#379]
#357 이슈와 관련 있는 질문인데, 답변 중에 cascade type 관련된 내용이 있어서 refresh,persist 등의 type을 하나 하나 시험해보려 하고 있었습니다. 그런데 manytoone의 속성으로 전달해주려고 하니 오류가 나는데, 혹시 다른 분들은 이 문제 어떻게 해결하셨는지, 혹은, 어떤식으로 작성해야 할지 방향을 알려주시면 감사하겠습니다.

manytoone속성으로 전달할 때 다음과 같이 전달하려고 시도했었습니다.

![SmartSelectImage_2021-09-11-11-41-20](https://user-images.githubusercontent.com/69337848/132933531-44d0da1a-5d37-48ae-90c7-4f260e6cc60e.png)

**Comment by Hank-Choi** [comment]
일단 해당 내용은 혼란을 가져올 것 같아 삭제했습니다.
세미나 중에 얘기할 예정이고 해당 내용은 구현하지 않으셔도 됩니다.
