### ISSUE TITLE
Django 과제1 제출 api 콜 이후 repository를 수정하게 되어 알립니다

### ISSUE THREAD

**Issue by isaac0622** [wafflestudio/19.5-rookies#380]
안녕하세요, 이번 장고 assignment 1의 채점을 콜 했지만 한 2~3분 이후에 repository를 수정하게 되어 세미나장님 말씀대로 이슈로 남깁니다.

로컬 디렉토리로 작업을 완료 후 12시 정각에 채점을 콜했는데, 원격 디렉토리에 push를 하지 않은 것을 깨닫고 한 2-3분 정도 뒤에 push하여 놓은 상태입니다. 불편을 끼쳐드려 죄송합니다.

**Comment by Jhvictor4** [comment]
@isaac0622 

웹 기준 해당 화면 우측 하단의 Transfer Issue 기능을 통해서 과제 1 레포로 이슈를 옮겨주시면 감사하겠습니다

**Comment by isaac0622** [comment]
@Jhvictor4 
Collaborator인 탓인지 transfer issue 버튼 자체가 없습니다. (개인 레포에서 이슈 만들면 있습니다.) 그래서 개인 과제 1 레포에 이슈를 새로 만들었습니다. 이 이슈는 이만 닫겠습니다.
