### ISSUE TITLE
리액트 로컬호스트 연결 에러

### ISSUE THREAD

**Issue by kmsgm** [wafflestudio/19.5-rookies#382]
안녕하세요, 과제를 하던 중에 갑자기 리액트 로컬호스트 페이지가 열리지 않는 문제가 발생했습니다.
방금까지 잘 되다가 갑자기 로컬호스트 페이지 연결이 안되고 있습니다.

스택오버플로우에 찾아보니 비슷한 상황이 있는 것 같아서 해보라는대로 다 해봤는데도 문제가 해결되지 않아 질문드립니다.
![image](https://user-images.githubusercontent.com/49176503/132935467-aebd5260-d595-4209-85e0-d5b4402bf1ef.png)

스택오버플로우에서 제가 시도해봤던 것들입니다!
[https://stackoverflow.com/questions/49022731/keep-getting-something-is-already-running-on-port-3000-when-i-do-npm-start-o](url)

**Comment by woohm402** [comment]
컴퓨터 껐다 켜 보시겠어요?

**Comment by kmsgm** [comment]
어제 새벽부터 이래서 컴퓨터 끄고 아침에 일어나시 했는데도 문제가 해결되지 않았습니다ㅠㅠ

**Comment by woohm402** [comment]
wsl 사용중이신가요? 리눅스 포트와 윈도우 포트가 달라서 발생하는 이슈일 수 있습니다. wsl이시라면 https://ddochea.tistory.com/140 한번 시도해 보시겠어요?

**Comment by kmsgm** [comment]
해결되었습니다!!! 감사합니다ㅠㅠㅠ
