### ISSUE TITLE
React lift state up과 관련된 질문 드립니다

### ISSUE THREAD

**Issue by Songmin17** [wafflestudio/19.5-rookies#383]
안녕하세요,

리액트 과제를 하는 와중에 lift state up을 해야 하는 상황이 발생해서, 어떻게 해야 하는지 알고 싶어서 질문 드립니다.
Parent component에서 child component List와 View로 같은 prop을 전달했을때, List에서 이 prop을 바꾼 후에 이 바뀐 값을 View에서 쓰려고 합니다.
그런데 List와 View는 sibling component들이어서 List에서 View로 바로 전달하지는 않고 List에서 Parent로 state를 lift 한후에 View에서 이 state를 쓰려고 합니다.
render함수를 활용해야 될것같은데, 지난주 세미나에서는 언급하지 않았던 내용 같고 문서만 봤을때는 잘 이해가 가지 않아서, 혹시 이 방법 말고도 다른 방법이 있는지 여쭤보고 싶습니다.
감사합니다!

**Comment by woohm402** [comment]
[이거](https://ko.reactjs.org/docs/lifting-state-up.html) 말씀하시는 거 맞을까요?

리액트에서 Child에서 Parent로 값을 보내는 건 불가능합니다. 때문에 그런 효과를 내고 싶다면, state를 Child 말고 Parent에서 가지고 있어야 합니다.

또한 이건 오늘 자세히 설명드릴 내용인데,
1. list에서 부모의 setState를 props로 받아서
2. 어떤 이유로 부모의 state를 변경하면
3. 부모의 state가 변경되고
4. 따라서 부모가 render되고
5. 따라서 view도 render됩니다.

이런 구조로 구현하셔야 합니다.

항상 리액트에서는 parent가 child한테 값을 보내는 것만 가능하고, 다른 방향의 데이터 이동은 모두 불가능합니다 state 끌어올리기는, `값이 바뀌는 걸 parent한테 전달하고 싶으면 애초에 state를 부모에 정의해라` 라는 내용입니다!

답변이 되셨을까요?

**Comment by Songmin17** [comment]
답변 감사합니다~ 그런데 제 코드에서는 이미 state 가 parent에 이미 있는데, child component 두개한테 이 state를 전달합니다.
이런식으로 합니다:
const [chosen, setChosen] 은 parent에 이미 정의되어 있고, 
return 안에는 이렇게 되어있어요:
<img width="878" alt="Screen Shot 2021-09-11 at 2 34 32 PM" src="https://user-images.githubusercontent.com/69232608/132937489-7ed2a0fe-1976-483d-a61f-d78ecd21e7b5.png">

여기서 List 부분은 부모로부터 값을 받아서 state를 바꾸는데, 이 바뀐 state가 View에서는 안뜨고 부모의 초기 state만 View로 넘어가는것같습니다.
이 문제는 render 방식으로만 해결이 가능한가요?

**Comment by woohm402** [comment]
그럼 state lift가 이미 되어 있는 상황이며, 그거 말고 다른 어떤 이유에 의해서 발생한 문제입니다.

ViewWrapper에서 props값을 받아올 때는 어떻게 받아오시나요?

**Comment by Songmin17** [comment]
앗......ViewWrapper에서 props 바깥에 괄호를 뺐네요.....해결했습니다! 감사합니다 ㅠㅠㅠㅠ
