### ISSUE TITLE
iOS swift strikethrough 취소가 안 되는 현상에 대한 질문

### ISSUE THREAD

**Issue by jubilant-choi** [wafflestudio/19.5-rookies#385]
안녕하세요. iOS 수강생 19.5기 Rookies 최주빈입니다.
세미나1 과제를 하던 중 특정 상황에서 cell label.attributedText에 addAttribute로 추가한 strikethrough가 사라지지 않는 현상이 생겼는데 어떻게 해결해야 할지 몰라 질문드립니다.

텍스트 취소선 함수는 다음과 같이 작성했습니다.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/67939075/132940595-48e7b4b8-a0a4-4e8c-b690-2d75e6887bf5.png">

세미나 1 강의 영상 1:25:00 부근에서 세미나장님이 보여준 예시에서도 유사한 현상이 발견되었는데 구체적으로 다음과 같은 상황에서 오류가 발생했습니다.
> 할 일 Cell의 버튼을 눌러둔 채(버튼 선택된 상태, 텍스트에 취소선 적용된 상태) 할 일 추가 화면으로 넘어갑니다.
그 후 다시 원래 화면으로 돌아오면 버튼을 다시 클릭해도 취소선이 그대로 남아있습니다.

영상 첨부합니다.

https://user-images.githubusercontent.com/67939075/132940506-a9165360-813d-4f76-84b7-db33a1e7a530.mov

**Comment by Ethan-MoBeau** [comment]
https://stackoverflow.com/questions/46414137/uilabel-with-attributedtext-in-custom-uitableviewcell-color-not-rendering-until

요거 참고해보세용!

**Comment by jubilant-choi** [comment]
@Ethan-MoBeau 해결됐습니다! 감사합니다.

ExampleCell Class 내에서 label.attributedText = nil하면 글자가 날아가고 다시 설정할 수 없는데
MainVC의 cellForRowAt에서 cell.label.attributedText = nil, cell.label.text = nil을 먼저 하니까 제대로 됐네요.
