### ISSUE TITLE
spring boot 과제 1-8의 설문조사 저장 방식에 대해 질문드립니다.

### ISSUE THREAD

**Issue by ggumnet** [wafflestudio/19.5-rookies#388]
과제 1-8에서 POST /api/v1/results/ 으로 설문조사를 추가하려고 하고 있습니다.
Request의 body에서 spring_exp, rdb_exp, programming_exp, python, rdb, programming 와 같은 key의 경우
상세한 스펙이 SurveyResponse model과 많이 다른데, 
해당 Request를 SurveyResponseRepository에 추가하기 위해  SurveyResponse model에 부합하도록 적절히 처리해서 넣어주면 되는건지, 아니면 User들의 Response를 다루는 새로운 Table을 생성해야 하는건지 궁금합니다!

**Comment by cs71107** [comment]
저의 경우 주어진 Dataloader.kt를 보시면
설문 조사 결과를 새로운 SurveyReponse 객체에 매핑해서 생성하고 있는데,
저도 그것처럼 createDto에서 받은 정보를 적절히 매핑해서 저장시켜주었습니다.

**Comment by ggumnet** [comment]
> 저의 경우 주어진 Dataloader.kt를 보시면
> 설문 조사 결과를 새로운 SurveyReponse 객체에 매핑해서 생성하고 있는데,
> 저도 그것처럼 createDto에서 받은 정보를 적절히 매핑해서 저장시켜주었습니다.

아 덕분에 의도가 뭔지 알게 됐습니다. 감사합니다.
