### ISSUE TITLE
React useState()관련 질문 드립니다!

### ISSUE THREAD

**Issue by yegirna530** [wafflestudio/19.5-rookies#389]
안녕하세요 리액트 세미나 1 과제를 수행하다가 또 여쭤볼 사항이 있어서 질문드립니다.
1.hover할 경우 선택할 수 있는 버튼이 생기고, 다시 버튼을 누를 경우 close 시키기
2.한 row를 선택한 후 다른 row의 버튼을 누르면 다른 row가 선택되기

이 두가지 스펙을 모두 구현하고자 생각한 흐름은 다음과 같습니다.
![image](https://user-images.githubusercontent.com/89301391/132947721-f48d23d7-1d04-46b0-a67a-22c211a5e394.png)
-> 1. 한 row를 선택하면 page가 뜨고 id 부여, 같은 id의 row를 선택할 경우 close 
     2. 한 row를 선택한 후 다른 row를 선택하면 id가 clicked와 다르므로 다른 row 선택
  
다른 row가 선택될 경우 (또는 새로 row를 열 경우)
![image](https://user-images.githubusercontent.com/89301391/132947751-1502cee7-3dce-4ddf-96a2-5c4357f8f0db.png)
이런 함수가 실행되게 되고

page는 DetailPage가 true일 때 selected를 받아서 열립니다.

이후 page의 경우
![image](https://user-images.githubusercontent.com/89301391/132947771-a303fd97-7754-4263-9fee-fd21db405080.png)

다음과 같은 edited state를 만들어 이를 input에 value = edited.name(grade) 등으로 하여 수정하는 방법을 택했습니다.

그런데 여기서 발견된 문제점은
한 row를 택한 뒤, 다른 row를 택하면
selected의 경우 바뀌며 
page에서 useState 전에 selected를 console.log 할 경우 변화됨을 확인할 수 있었는데

edited의 경우에는 selected가 바뀌었음에도 불구하고 변화되지 않는 모습을 보였습니다.
그래서 새로운 page가 열렸음에도 input의 value가 변화하지 않았습니다.

왜 이런 일이 생기는 것인지 궁금해 여쭤보고 싶습니다 !
해결 방법은 없는걸까요?

**Comment by joongwon** [comment]
저도 비슷한 문제가 있었습니다. useState 함수에 전달된 값으로 state가 업데이트되지 않고 이전에 저장돼있던 값을 돌려줘서 한참을 고민했었죠...

그 원인을 제 나름대로 추측을 해봤는데, useState 함수가 작동하는 방식과 관련이 있는 것 같습니다.
useState의 파라미터는 그 state를 초기화할 때만 사용하고, 그 뒤에 다시 useState를 호출하면 이전에 지정한 값을 기억했다가 리턴하는 구조로 보입니다. 그래서 details 컴포넌트를 처음 렌더링할 때는 제대로 값이 나오지만 나중에는 자꾸만 이상한 값이 껴있게 되는 거죠.

저는 이 문제를  useState에는 정말로 앱이 맨 처음 시작할 때 넣어두는 값으로만 해두고, 실제로 변화하는 값으로 업데이트할 때는 무조건 set 함수를 쓰는 방식으로 해결했습니다. `useState(selected)` 대신 `useState({})`을 쓰고, 실제로 값을 넣어줘야 할 때에는 이벤트 핸들러에서 `setEdited(selected)` 이런 식으로 호출을 해주는 거죠. 이게 컴포넌트 초기화할 때 같이 초기화해줘야 되는 state라 좀 까다롭긴 한데, 저는 App 컴포넌트에 state를 다 때려넣고 App에서 정의한 이벤트 핸들러 함수를 prop으로 넣어주는 식으로 구현했습니다.
```javascript
const App = () => {
    /* ... */
    const [edited, setEdited] = useState({});
    const handleDetail = (item) => {
        setEdited(item);
    }
    /* ... */
    return (
        /* ... */
        <DetailPage edited={edited} setEdited={setEdited} />
        /* ... */
    );
}
```

**Comment by woohm402** [comment]
@joongwon 님께서 설명해주신 부분과 구현하신 방식이 정확합니다. ([참고](https://ko.reactjs.org/docs/hooks-overview.html#state-hook): 리액트 공식문서에서 소개하는 useState) useState에 넘겨주는 값은 단지 초기값일 뿐이며, 그렇기 때문에 헷갈리지 않기 위해 항상 상수만 집어넣는 걸 추천드립니다.

과제 1에서는 `App.js`에 수정된 데이터를 위한 state를 놔두고, 디테일 뷰에는 수정된 데이터를 위한 state를 따로 두지 않는 방식으로 구현하시길 의도했습니다.

하지만 초기화될 때 set을 실행하는 방식 역시 나쁘지 않은데 (오히려 그게 더 좋을 수도 있고요), 그 경우에는 오늘 배운 `useEffect` 훅을 사용할 수 있습니다.

**Comment by woohm402** [comment]
@yegirna530 해결되셨나요?

**Comment by yegirna530** [comment]
넵넵!
