### ISSUE TITLE
springboot 9번 스펙 관련 문의 & response status code띄우는 방법 문의

### ISSUE THREAD

**Issue by darwinj07** [wafflestudio/19.5-rookies#392]
1. 9번에서  'spring_exp, rdb_exp, programming_exp, os는 request의 body에 key 이름으로서 빈 str 등이 아닌 값을 가진 채 필수로 포함되어야 하고'라고 나와있습니다. 그런데 major와 grade의 경우 모델에서 @field: NotBlank가 사용되어 마찬가지로 body에 key 이름으로서 빈 str이 들어오면 SurveyResponse entity를 형성할 때 에러가 발생합니다. 이 경우 major와 grade도 빈 str 등이 아닌 값을 가진 채 필수로 포함되어야 한다고 보면 되는가요?

2.  controller에서 Dto.Response를 반환하는 함수의 경우 함수 바깥에서 annotation을 이용하여 기본 status code를 설정하는 방법 외에 함수 내에서 status code를 설정하는 방법이 있는지 궁급합니다. 에러가 발생한 경우 함수 내에서 throw를 사용하면 되지만 'CREATED 201'와 같은 경우는 어찌할 수 있을까요?

**Comment by cs71107** [comment]
1. 이 방법이 유효한 방법인지 아직 테스트를 해보진 않았는데, 저의 경우 create Dto에서 defalut를 비어있지 않은 값으로 일단 설정해두었습니다.
2. 역시 더 좋은 방법이 있을 것 같긴 하지만 Response.status( {원하는 status} ).body({원하는 body}) 와 같은 식으로 반환하면 원하는 code로 반환이 되는 것을 확인했습니다.

도움이 됐으면 좋겠습니다 :)

**Comment by cs71107** [comment]
원하는 status의 종류 같은 경우 HttpStatus 를 참고하시면 될 것 같습니다.

**Comment by darwinj07** [comment]
> 1. 이 방법이 유효한 방법인지 아직 테스트를 해보진 않았는데, 저의 경우 create Dto에서 defalut를 비어있지 않은 값으로 일단 설정해두었습니다.
> 2. 역시 더 좋은 방법이 있을 것 같긴 하지만 ResponseEntity.status( {원하는 status} ).body({원하는 body}) 와 같은 식으로 반환하면 원하는 code로 반환이 되는 것을 확인했습니다.
> 
> 도움이 됐으면 좋겠습니다 :)

감사합니다

1번에 대한 오피셜이 뜨면 닫겠습니다

**Comment by Hank-Choi** [comment]
1. 네 맞습니다. 조금씩 리드미와 코드가 다른 경우가 있는데 저의 실수이므로 이러한 부분은 자유롭게 구현해주셔도 될 것 같습니다. 혼란을 드려 죄송합니다.
2. https://github.com/wafflestudio/19.5-rookies/issues/332 해당 이슈 참고하시기 바랍니다!

**Comment by darwinj07** [comment]
감사합니다
