### ISSUE TITLE
user 추가가 실패 하였을때 PK(id)가 계속 증가하는 현상

### ISSUE THREAD

**Issue by prodigy-sub** [wafflestudio/19.5-rookies#393]
- User id 를 추가할 때 아래와 같이 작성하였습니다.
![image](https://user-images.githubusercontent.com/63052192/132951958-46d7da9c-e9a6-476d-9777-3d65bf97bd7c.png)

- email 을 겹치게 하여 입력이 안되도록 하였습니다.
![image](https://user-images.githubusercontent.com/63052192/132952024-efefeb93-85b3-4130-bb26-9d3a109d075e.png)

- 몇번 400 error 를 발생 시킨 후 정상적으로 input을 넣었더니, PK가 뒤로 밀리는 현상이 발생하였습니다.
![image](https://user-images.githubusercontent.com/63052192/132952153-302d457c-5571-41ce-aeee-23384d621237.png)

- 이렇게 뒤로 밀리는 현상이 정상인가요? 이렇게 PK가 중간중간에 비어서 발생하는 문제는 없나요? 혹시 이를 해결할 수 있는 방법이 있을까요?

**Comment by cs71107** [comment]
PK 가 뒤로 밀려도 발생하는 문제는 없는 것으로 알고 있습니다. 제 생각에는 일단 넘어가셔도 상관 없을 것 같아요 :)

**Comment by pullup-dip-burpee** [comment]
(service 단에서) respository의 save를 호출하기 전에 중복 체크하는 로직을 넣어서, 중복이면 Exception을 던지도록 하면 될 것 같습니다!

**Comment by prodigy-sub** [comment]
두분 모두 답변 감사합니다 ㅎㅎ!

**Comment by Hank-Choi** [comment]
https://github.com/wafflestudio/18.5-rookies/issues/114 작년 백엔드 세미나에서의 질문입니다. 비슷한 맥락인 것 같아 참고 부탁드립니다.

**Comment by prodigy-sub** [comment]
네 감사합니다 큰 도움이 되었습니다 issue는 닫겠습니다!
