### ISSUE TITLE
Kotlin에서 다차원 배열 관련 문제

### ISSUE THREAD

**Issue by ZALF0615** [wafflestudio/19.5-rookies#397]
![nana](https://user-images.githubusercontent.com/64626607/132978265-9e0a036d-adb0-4749-8b37-1e21018af3d2.PNG)

과제를 진행하는 과정에서, Int 의 다차원 배열을 만들어 값을 참조 및 수정 기능을 구현하려고 하는데 의도처럼 잘 되지를 않네요 ㅠㅠ
nullable 관련 문제인 것 같긴 한데, 아직 Kotlin에 대한 이해 자체가 얕아서 그런지 맘처럼 구현이 되질 않네요.,..

**Comment by Jhvictor4** [comment]
nullable과는 관련 없어보이는데 Array<Array<Int>> 로 접근하셔보시는건 어떤가요?

**Comment by veldic** [comment]
discList는 MutableLiveData 객체이기 때문에 discList.value로 접근해서 작업하셔야 합니다.
