### ISSUE TITLE
React 과제2 스펙 관련 질문드립니다

### ISSUE THREAD

**Issue by 0114kek** [wafflestudio/19.5-rookies#398]
과제 문서에 "이제 다른 건 몰라도 학생 목록 데이터는 App.js의 useState 말고 Context 를 통해 관리한다." 라고 되어있는데
이 의미가 Context를 이용하면서 useState가 아닌 useReducer같은 것을 이용해 학생 데이터를 처리하라는 것인지,
아니면 useState를 하위 컴포넌트에게 props로 전해주는 방식을 사용하지 말라는 뜻인지 모르겠습니다.
즉 세미나 중 보여주신 예제처럼 useState로 학생 데이터와 Setter를 만들고 하위 컴포넌트에게 전달할때는 Context를 이용하는 방식이 괜찮은 것인지 궁금합니다.

**Comment by woohm402** [comment]
아 넵 좀더 상세하게는
1. App.js에서 useState를 이용해 관리하지 말 것
2. Context를 이용해 Provide될 것

이렇게 두 가지 스펙입니다. 수업에서 다뤘던 "App.js에서 useState로 정의한 다음 Provide해주는" 예제는 이해를 돕기 위함이었고, 그 다음에 바로 소개해드린 best practice처럼 구현해 주시면 됩니다.

**Comment by 0114kek** [comment]
아 이해되었습니다 감사합니다
