### ISSUE TITLE
장고 과제 1 예시답안 permission 관련 질문드립니다.

### ISSUE THREAD

**Issue by ding-young** [wafflestudio/19.5-rookies#399]
안녕하세요, 이번에 새로 올려주신 과제1 예시답안 코드에서 이해가 잘 가지 않는 부분이 있어서 질문드립니다.

![assignment1질문](https://user-images.githubusercontent.com/88336128/132981267-6054e996-7a0c-478e-ae1a-a9bc1fea757c.png)

[user/views.py](https://github.com/wafflestudio/19.5-rookies/blob/master/django/seminar1/assignment1/user/views.py) 에서 update(자기자신 정보 수정), logout, retrieve(자신의 정보 확인) 모두 로그인하지 않은 유저에 대해서는 403처리를 해줘야 했던 걸로 기억하는데, 관련 permission 처리를  update, logout에서 어떻게 수행하고 있는지 잘 모르겠습니다. 

retrieve의 경우 코드에서 확인이 가능한데, update, logout에서는 명시적으로 drf Permission 클래스의 IsAuthenticated 등을 활용한다거나 .. 그 외 특정한 방식으로 권한을 제한했음을 확인하기가 어려워서 어떻게 권한을 제한한 건지 잘 모르겠습니다 ㅠㅠ 혹시나 해서 drf 관련 문서도 읽어보긴 했는데 여전히 해결되지 않아 질문드립니다..!

**Comment by Jhvictor4** [comment]
일단 다 제대로 보고 계신 것 같습니다..ㅎ

명시적으로 권한 제한을 하려면 retrieve에서와 같이 하면 되는데요,

logout()의 경우에는 request.user 가 로그인되어있지 않을 경우 그냥 무시하고 끝나버려서.. 사실 403 처리를 할 필요는 없습니다..만 스펙에 적혀있으니 제 불찰인 것 같습니다.

수정의 경우에는 지적해주신게 맞는 것 같습니다.. 제가 놓쳐버렸네요.

로그인하지 않았을 경우에 아마 validation에서 500처리가 저렇ㄹ게 되면 날 것 같습니다.

잘 짚어주셔서 감사합니다! 제가 오히려 더 부족하네요..ㅋㅋ

(이렇게 일일이 권한 체크하는게 놓치기도 쉽고 번거로운 처사라, 토큰 기반의 인증으로 전환하고 settings.py에서 디폴트 권한을 관리해주는 일이 확실히 깔끔하다는 걸 체크하시면서 넘어가주시면.. 감사하겠습니다 ㅎㅎ ㅜ )

**Comment by ding-young** [comment]
아하 감사합니다! 아무래도 말씀하신 방식이 더 깔끔하다는 게 와 닿네요..
