### ISSUE TITLE
PR을 생성하려니 commit history가 다르다고 나옵니다.

### ISSUE THREAD

**Issue by yg-moon** [wafflestudio/19.5-rookies#401]
스프링부트 과제1 피어 리뷰 과정에서 문제가 생겨 질문 드립니다.

리뷰를 위해 assignment1 브랜치에서 master 브랜치로 PR을 생성하려니
```
"There isn’t anything to compare.
master and assignment1 are entirely different commit histories."
```
라고 나오면서 PR이 생성되질 않습니다.

Git history에 문제가 생겨서 그런 것 같은데 리포지토리나 브랜치를 아예 새로 생성해서 시도해봐도 될까요?

(말씀을 안 드리고 새로 파면 제출기한을 넘겨서 과제를 한 것으로 처리될까봐 질문 드립니다.)

**Comment by Hank-Choi** [comment]
마스터에서 브랜치 다른 이름으로 새로 분기하시고 복붙 후에 PR 날려주세요! 원래 브랜치 이름과 위 사항을 PR에 적어서 올려주세요

**Comment by yg-moon** [comment]
네 알겠습니다 감사힙니다!

**Comment by ptkjw1997** [comment]
@Hank-Choi 
저도 비슷한 이슈 있어서 여기에 남깁니다.
![image](https://user-images.githubusercontent.com/54579374/133072155-35faeea7-7f0c-4e1f-89ad-eeeb370bf7cd.png)
위 사진처럼, PR은 올라갔는데 좌측의 비교 파일이 Master의 skeleton code가 아니라 코드 리뷰를 할때 오히려 불편할 것 같습니다. 새 branch 하나를 다시 파서 시도해봤는데, 그 branch 에서 PR 올리는 경우에는 제대로 Master의 코드랑 비교하는 것 같습니다. 이 경우에도 PR에 문제 상황과, 브랜치 이름 적어서 올리고 이를 가지고 리뷰해도 될까요?

**Comment by woohm402** [comment]
@Hank-Choi

**Comment by Hank-Choi** [comment]
넵 가능합니다! 사실 이를 해결하는 과정에서 git에 더욱 많이 배울 것 같지만 과제와 무관한 영역이니 새로 pr 날리는 것도 허용하겠습니다!
