### ISSUE TITLE
Modal transition 문제

### ISSUE THREAD

**Issue by kmsgm** [wafflestudio/19.5-rookies#405]
안녕하세요... 이미 과제 기한이 끝났긴 하지만 정말 트랜지션 효과가 죽어도 안돼서 질문드립니다...

### AddStudent.js
```
const [modalOn, setModalOn] = useState(false);

return (
    <div>
        <button className="add-btn" onClick={e => setModalOn(true)}>추가</button>
        { modalOn && <Modal handleSave={handleSave} handleCancel={handleCancel} /> }
    </div>
);
```

### Modal.js
```
return (
    <div className="modal">
        <div className="modal-content">
            ...
        </div>
    </div>
);
```
모달 창을 불러오는 js 파일은 이런식으로 구성되어 있습니다. 
Modal.css에서 `.modal { ... , transition: all 0.5s ease-in-out}` 
이런 식으로 만들면 서서히 나타나는 효과가 있어야 할 것 같은데 전혀 적용되지 않았습니다.

혹시 몰라 transition을 .modal-content에도 넣어보고, 혹시 몰라 opacity도 사용해보고 애니메이션도 사용해봤지만 
전부 원하는 효과를 얻을 수 없었습니다....

아니면 `{ modalOn && <Modal handleSave={handleSave} handleCancel={handleCancel} /> }` 부분 때문에 서서히 나타나는 효과가 적용되지 않는 것일까요?

감사합니다!

**Comment by woohm402** [comment]
#370 참고하시기 바랍니다!

**Comment by kmsgm** [comment]
와 해결했습니다ㅠㅠ 감사합니다!!
