### ISSUE TITLE
(django assignment2) AUTH_USER_MODEL refers to model 'user.User' that has not been installed

### ISSUE THREAD

**Issue by footprinthere** [wafflestudio/19.5-rookies#406]
![image](https://user-images.githubusercontent.com/84006386/133253269-0927e476-6026-4073-8bb3-4bd7de89a69d.png)
새로 만든 seminar 디렉토리의 models.py에 위와 같이 UserSeminar를 정의했습니다. 여기서 `get_user_model()`은 `django.contrib.auth.get_user_model()`을 import 한 뒤 사용했습니다.

그런 다음 `makemigrations`를 수행하도록 했더니 아래와 같은 에러 메시지가 나왔습니다.
![image](https://user-images.githubusercontent.com/84006386/133253486-940da60d-af1c-40c4-b501-4dbab7eef955.png)

아래는 settings.py의 `INSTALLED_APPS` 부분인데, 제가 보기에는 별 문제가 없어 보입니다.
![image](https://user-images.githubusercontent.com/84006386/133253594-db23c750-ad9b-4448-9af4-6c436fe46464.png)
찾아보니 `INSTALLED_APPS` 내부에 명시한 app들의 순서가 중요한 경우도 있다고 해서 순서를 바꾸어 시도해보았지만 여전히 같은 에러가 나왔습니다.
`AUTH_USER_MODEL`은 따로 건들지 않았으며 `user.User`로 잘 설정되어 있습니다.

비슷한 에러를 해결한 사례들을 몇 가지 찾았는데, 따라해보았지만 해결되지 않았습니다.
예를 들어 `import` statement를 클래스 정의 내부가 아닌 파일 맨 위에 놓으라는 조언이 있었는데 저는 이미 파일 맨 위에서 `import`를 사용하고 있었습니다.

가능한 원인에 무엇이 있을까요?

**Comment by footprinthere** [comment]
dependency 관련 문제일 수도 있다고 해서 이전의 migration들을 철회했다가 다시 해보려고 했는데, 철회 명령어를 썼을 때도 똑같은 에러가 나왔습니다.

**Comment by footprinthere** [comment]
해결했습니다...ㅎ

/seminar/models.py에 정의한 `UserSeminar`의 내부에서 `get_user_model()`을 사용했는데, `User`가 정의되어 있는 /user/models.py에 `from seminar.models import UserSeminar`가 포함되어 있어서 `User`가 정의되기 전에 사용한 꼴이 된 거였습니다. 이 import를 지워서 해결했습니다.

**Comment by Jhvictor4** [comment]
그 생각해보니 여기에 첨언해드린다던걸 깜빡해서 늦게나마 댓글 남깁니다.

이런 경우가 생각보다 비일비재해서, 장고 3.0부터는  `./manage.py makemigrations --skip-check`

옵션을 통해 검사를 건너뛸 수 있습니다.

**Comment by kk0in** [comment]
@footprinthere 안녕하세요! 저도 같은 문제가 있어서 댓글을 남깁니다! 저도 비슷한 이유인 것 같은데, 혹시 /user/models.py에 from seminar.models import Seminar가 포함되어 있는 것은 문제가 되지 않았나요? Seminar class에서는 get_user_model()을 사용하지 않아서 문제가 되지 않을 것 같은데, 이 부분을 빼면, 해당 에러가 없어져서요.. (근데 Seminar를 참조하지 못해서 다른 에러가 발생합니다..)결국 이 import가 문제인 것 같은데, 이걸 지우면, /user/models.py에서 foreign key로 Seminar를 넣어줄 수 없어서 문제가 됩니다 ㅜㅜ
