### ISSUE TITLE
장고 assignment2 migration 관련

### ISSUE THREAD

**Issue by OTY-Math** [wafflestudio/19.5-rookies#408]
안녕하세요!

waffe_backend_2 db를 만들고 waffle-bacekend user에게 권한도 부여한 후에,
python manage.py makemigrations 를 하니, 
![image](https://user-images.githubusercontent.com/87603284/133282327-7e2d0c47-cce0-41d2-9f30-bd425cd556d2.png)

와 같은 에러가 뜹니다.
혹시 제가 까먹고 안한 과정이 있을까요...? 서칭을 할래도 무언가 빠뜨린 거 같은데 무엇을 검색해야할지 모르겠어서 질문드립니다 ㅠㅠ

**Comment by Jhvictor4** [comment]
코드 2 TODO는 다 구현하신 상태인가요?

**Comment by Jhvictor4** [comment]
모델 설계 과정이 1번에 들어있어서, 미구현 시 마이그레이션이 정상적으로 작동하지 않을 수 있습니다.

**Comment by OTY-Math** [comment]
@Jhvictor4  아 이해했습니다. 감사합니다
