### ISSUE TITLE
리액트 과제1 오류 질문 TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by linak0** [wafflestudio/19.5-rookies#409]
모달 구현한 다음에 모달 창에 값 입력하고 저장 누르면 이런 페이지가 뜨는데 구글링해도 원인을 잘 모르겠습니다..

![image](https://user-images.githubusercontent.com/81808364/133286201-3864cdcf-fad0-4224-838a-3e418415cf7f.png)

**Comment by woohm402** [comment]
자바로 치면 `NullPointerException` 비슷한 친구입니다. 배경지식으로 아래 개념들 먼저 이해해주시면 좋을 것 같습니다.
- [undefined](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/undefined)
- [map](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

해당 에러 메세지는 undefined의 id속성을 읽을 수 없다는 말입니다. 에러 메세지랑 코드 보아하니 `person.id` 부분에서 문제가 생겼네요
즉 std 배열에 학생만 있는 게 아니라 `undefined`도 들어 있나 봅니다.

이 `undefined`가 대체 거기 왜 들어갔는가에 대한 부분은 구현하신 로직을 봐야 알 수 있을 것 같습니다.

**Comment by ChrisLee02** [comment]
로직 안에 =null; 이런 식으로 할당시키는 부분이 있으면 저런 오류가 뜨더라구요.
제 경우에는 현재 선택된 학생이 없을 때, 학생 객체의 형태는 그대로 유지하고 id값에 null을 넣는 식으로 해결했습니다

**Comment by woohm402** [comment]
> 로직 안에 =null; 이런 식으로 할당시키는 부분이 있으면 저런 오류가 뜨더라구요.
> 제 경우에는 현재 선택된 학생이 없을 때, 학생 객체의 형태는 그대로 유지하고 id값에 null을 넣는 식으로 해결했습니다

넵 @ChrisLee02 님처럼 해결하는 방식도 있습니다. 즉 선택된 학생이 없을 때 state를 `null`이 아닌 `{id: null, grade: null, ... }`으로 구현하셨다는 이야기인데, 그렇게 구현하면 분명 오류가 나지 않는 건 맞습니다.

언급하신 로직과 제가 제안드리는 로직을 비교해 보겠습니다.

> 현재 선택된 학생이 없으면, `데이터가 없는 빈 껍데기의 학생이 선택된 상태`라고 생각하고 구현한다. 학생이 선택되었는지 아닌지는 학생의 내용물이 있는지 없는지로 판별한다.

> 현재 선택된 학생이 없으면, `"없음"이 선택된 상태이다`라고 생각하고 구현한다. (`null`은 명시적으로 값이 없다는 뜻이므로, `null`로 세팅하겠다는 뜻입니다) 학생이 선택되었는지 아닌지는 학생이 있는지 없는지 (`===null`)를 이용해 판별한다.

의미상 아래가 더 나아 보이는데, 어떻게 생각하시나요?

**Comment by ChrisLee02** [comment]
Table 부분에서 조건 수정하기가 귀찮아서...ㅎㅎ 
과제2 끝낸 후에 그 부분 다시 손봐야겠습니다

**Comment by woohm402** [comment]
@linak0 해결되셨나요?
