### ISSUE TITLE
1조 질문 모음

### ISSUE THREAD

**Issue by junjinyong** [wafflestudio/19.5-rookies#412]
1. Controller에서 Service를 거치지 않고 Repository를 바로 접근해도 되나요? 권장되는 방법이 궁금합니다.

2. 실제로 Entity, DTO, requestBody 사이에서 ModelMapper를 많이 사용하나요?

3. ModelMapper를 사용할 때 변수 이름이 맞지 않으면 잘못된 entity를 생성할 위험이 있는 것 같던데 이를 방지할 방법이 있나요? (ex. 한쪽은 camelcase, 다른쪽은 snake case 라던지)

4. Entity와 Dto의 createRequest 둘 다에 validation annotation이 붙는데 중복되는 것이 아닐지?

5. 실제에서 JPA 레포지터리에서 existsBy를 사용하나요? 아니면 Optional의 메소드 등으로 null을 처리하나요?

**Comment by Jhvictor4** [comment]
저도 궁금해서 와드 남길 겸 끄적여봅니다

1. 객체 간 의존성은 낮을 수록 좋기 때문에, repository를 controller, service 에 모두 주입하는건 덜 깔끔해 보입니다.
2. 라이브러리는 쓰기 나름이라 정답이 없는 것 같은데,, 저도 궁금하네요
3. [공식 문서](http://modelmapper.org/getting-started/) 첫 화면에 관련 내용이 있네요. 딴 소리지만 Kotlin 컨벤션 따라 CamelCase 쓰는게 좋아 보입니다
4. 코드 상에서 두 객체 다 접근 가능하기 때문에 두 군데 다 있는게 맞아 보입니다
5. 전자는 정말 존재여부 체크할때만 쓰고, 값이 있을 때 뭔가 추가적으로 해야 한다면 후자를 사용하지 않을까요?

**Comment by Hank-Choi** [comment]
1. 서비스단과 컨트롤러단 양쪽에 레포지토리의 의존성이 생기면 레포지토리의 변경이 일어났을 때 양쪽 모두에 전파가 되기때문에 최대한 서비스단을 거치는 것이 좋아보입니다.
2. 나름 쓰는 곳이 있는 것 같고 코드양을 줄여줘서 써봤는데 코틀린에는 안어울리네요 ㅎㅎ
3. 지혁님이 좋은 자료 올려주신 듯 합니다!
4. 지금은 entity를 저장하는 로직이 무조건 create request를 통하기 때문에 중복인 것 같아 보이지만 엔티티를 저장하는 entry point가 여러개가 되는 경우 어떤 요청이 들어올지 예상할 수 없으므로 entity에도 validation을 안전장치로 다는 게 좋습니다! 물론 서비스 로직 들어가기전에 dto단에서 먼저 걸러주면 성능상 좋으니 dto에도 달고요!
5. 존재여부만 따질 때는 exists~~가 성능이 좋습니다.db에서도 빠르고 object mapping도 일어나지 않으니까요.  따라서 객체가 필요 없을때는 exist~로 체크하는 게 더 좋아보입니다!
