### ISSUE TITLE
로그인 정보를 기억하는 방법

### ISSUE THREAD

**Issue by andhl204** [wafflestudio/19.5-rookies#415]
안녕하세요, 리액트 과제 2를 수행하다가 궁금한 점이 생겨 질문드리게 되었습니다.

실제 로그인 기능은 아니지만, 리디렉션 기능을 위해 제가 생각한 것은,
~~~
const [login, setLogin] = useState(false);
~~~
이런 방식으로 상태관리를 하는 것입니다.

그런데 주소창에 url을 직접 입력하면(```/student/1```이나, ```/sfkjhasdfkh```와 같이  존재하지 않는 주소 등) 새로고침이 되면서 상태가 초기화되는데, 실제 로그인 기능을 구현하지 않고도 이를 해결할 방법이 있는지 궁금합니다!

**Comment by woohm402** [comment]
그러게요 스펙이 조금 애매한 감이 있군요 🙏  지금대로라면 url에 `/student/1`을 입력했을 때 새로고침에 의해서 상태가 초기화되고 로그인되지 않은 상태이니 `/login`으로 보내는 것만 가능합니다

사실 실제 로그인 기능을 구현해도, 자동 로그인이 구현되어 있지 않다면 해당 문제는 여전히 존재합니다. 실제 로그인 로직도 크게 다르지 않습니다: 현재는 `로그인 버튼을 누르면 로그인이 됨` 인데 이걸 `로그인 버튼을 누르면 안에서 api를 쏘고 받고 로그인이 됨`으로 변경하는 정도입니다. (물론 여기서 세션 로그인이니 토큰 로그인이니 하는 방식에 따라서 정보를 어디에 저장하고 이런저런 이야기가 나옵니다)

로그인 정보를 클라이언트에 저장하고 싶으신 거라면 (다른 말로 자동 로그인이라고 하죠), 브라우저 저장소를 사용할 수 있습니다. 대표적으로`localStorage`, `sessionStorage`, `cookies` 등이 있습니다. 이중 자동 로그인에 주로 사용되는 친구는 [`localStorage`](https://developer.mozilla.org/ko/docs/Web/API/Window/localStorage)입니다. 일단 이 문서 한번 읽어보시고, 어떻게 구현할지 감이 안 잡히신다면 이어서 한 번 더 질문 주시기 바랍니다!

**Comment by andhl204** [comment]
늦은 시간임에도 상세하게 답변해 주셔서 감사합니다:) localStorage를 이용하는 방법이 있었군요😀 구현하다가 궁금한 부분이 생기면 다시 질문드리겠습니다!
