### ISSUE TITLE
Seminar app 생성후 migration, models.field에서의 on_delete option, view.py에서 method에 따른 함수설정 관련 질문

### ISSUE THREAD

**Issue by OTY-Math** [wafflestudio/19.5-rookies#418]
여러 질문이 있습니다.

첫 번째 질문은 on_delete=option 관련입니다.

Seminar와 Participant의 ManyToMany relationship을 만들면서,
class Seminar에 다음과 같이 정의를 해줬습니다.

![image](https://user-images.githubusercontent.com/87603284/133552348-44197f5b-47f1-4f43-bbae-d86022a138d0.png)

고민이 되었던 것은, 처음엔 on_delete를 models.CASCADE로 설정하였는데, 이 때 만약 instructor class의 row가 하나 지워졌을 때, 그와 관련있는 모든 seminar가 통째로 날라가는 건지, 아니면 seminar 내에서 그 instructor 정보만 날라가는 것인지 확신이 들지 않았습니다.
여러 서칭을 해봤을 때는 대부분 foriegnkey를 통한 1대 다 참조에 대해서만 설명이 되어있어, 여기에 질문 올립니다.

두 번째 질문은 makemigrations관련입니다.
seminar app 을 만들고, requirement 4, 5를 충족시키기 위해 seminar/models.py에서 class들을 정의해주었습니다.
그리고 user/serializer.py에서 이를 적절히 사용하여, ParticipantProfile과 InstructorProfile을 생성하게 짜주고, 
requirement5의  POST /api/v1/signup/을 테스트하기위해 한번 더 migration을 해주려고 했는데 다음과 같이 에러가 났습니다.

![image](https://user-images.githubusercontent.com/87603284/133552792-1927ba76-8b33-4da7-9032-b9e870b1f7e4.png)

setting.py에 추가한 것을 확인해보면
![image](https://user-images.githubusercontent.com/87603284/133552825-c21fc0d4-aeea-4e73-93a8-cc67405957f6.png)
와 같이 UserConfigSeminar는 도통 찾을 수가 없었습니다.

한가지 추측은 seminar/models.py에 UserSeminar class를 정의하면서, foreignkey로 user를 참조한 것에서 UserConfigSeminar가 생성되었나 싶은데, 코드 전체를 뒤져봐도 찾지 못해서, 어째서 이러한 문제가 발생한 것인지 알고 싶습니다.

세 번째 질문은 urls.py와 views.py를 통해서 request의 method 별로 함수를 만들어주는 과정 관련입니다. 
지난 assignment0에서는 method=GET으로 고정이었고, view.py에서 class가 아닌 함수만을 정의하고 urls.py에서 각 request별로 함수를 잘 배정해주는 방식이었고,
assignment1에서는 다양한 method들이 있었으며, view.py에서 UserViewSet class를 정의하고 urls.py에서는 requset를 따로 분류하진 않고 view의 class에 넘겨주는 방식이었습니다. 이 때, 여러 method들이 class 내의 알맞은 함수를 찾아가는 방식이 조금 이해가 어려웠습니다.

1. create, put, post 등 method이름과 동일한 이름을 가진 함수는 알아서 method를 구별해서 받는가? 그렇다면 retrieve의 method는? (그리고 어떻게 구별해서 받는지도 모르겠습니다, 찾아보긴 했는데 무언가 결과만을 말하고 과정에 대해선 와닿지 못했습니다)

2. \@action(detail=False, method=['{method_name}']) 의 경우는 request에서 마지막 형식이 본 함수의 이름과 같아야만 작동하는 것인가? (이것은 확인해본 결과 아마 yes, detail의 옵션은 pk와 관련)

3.  그렇다면, 한 class 내에서 하나의 method(ex. POST)에 대해 request형식이 다른 것(ex. POST /api/v1/seminar/ vs POST /api/v1/seminar/{seminar_id}/ , 근데 적절한 예시인지 확신이 들지는 않네요 ㅠㅜ) 에 대해서, 두 가지의 POST를 처리하는 함수를 만들고 싶다면, 그 함수의 이름을 어떻게 설정해야 urls.py에서 class로 보낸 POST 요청이 잘 분배되는가? 
아니면 무조건 class를 분리해서 각각 만들어주어야 하는가? 혹은 urls.py에서 class 내부의 함수까지 지정해서 request를 보내주어야 하는가?

질문이 너무 많았네요ㅠㅠ 
감사합니다.

**Comment by Jhvictor4** [comment]
1. 일단 과제 스펙 상 ManyToManyField로 구현하시지 못하도록 강제해두었습니다. 답변을 드리자면, ManyToManyField 구현 코드를 보면 아시겠지만 on_delete attribute가 그냥 없습니다. 이를 명시적으로 관리해주려면 연결테이블을 두고 ForeignKey로 해주는 것이 일반적인데, 과제 진행하시다 보면 이해가 되실 것 같습니다.
2. 이건 퇴근 후에 태양님 레포를 한번 확인해보아야할 것 같네요 ㅎㅎ;;
3. 세미나에서 간단히 말씀드린 바가 있지만, 세부 구현에 대해서는 알려드린 적이 없네요. 이건 사실 코드 타고 들어가면 바로 알 수 있는데요, venv/lib/python3.8/site-packages/rest_framework/views.py:500 여기를 참조하시면, APIview가 어떻게 method로 요청을 연결해주는지 파악하실 수 있을 것 같습니다. 요청과 똑같은 이름의 method attribute를 찾는 방식입니다.
ViewSet의 경우에는 구현이 조금 다른데요, 클래스 생성 시 _actions_ 라는 매핑을 통해서 요청을 직접적으로 매핑해주어야 합니다. 
venv/lib/python3.8/site-packages/rest_framework/viewsets.py:244 이 부분 참고하시면 좋을 듯 합니다.
다만, 과제에서 사용하는 UserViewSet이 상속하는 GenericViewSet의 경우 기본적으로 제공하는 action이 없습니다.
이는 drf가 설계 과정에서 ViewSet에 대해 Router와 함께 사용하는 것을 가정하고 구현했기 때문인데요,
venv/lib/python3.8/site-packages/rest_framework/routers.py:107 이 부분을 보시면
라우터의 구현에 이러한 매핑이 들어있습니다.

자세한 것은 항상 공식 문서와 코드에서 답을 찾아내실 수 있습니다. 코드 링크와 자료들 찾아보시면 이해에 도움이 되실 것 같습니다. 
파이썬에서 method 역시 클래스의 attr 객체로 담기기 때문에, 그냥 이런 식으로 이름으로 찾아서 호출하는 것이 가능합니다.
구현을 보시면 뭐 이리 간단하냐고 느끼실 수도 있을 것 같네요!

어찌했든 3-1에 대한 답변을 드렸고, 2번의 경우에는 action이 어떻게 작용하는지 파악하시면 자연스럽게 이해가 되실 것 같습니다.
3번은 말씀하신 방법 다 되는데, action에서 디테일 여부로 구분이 어차피 가능하기 때문에 한 클래스 내부에서 액션 선언해주는 것으로 처리가 가능합니다.

**Comment by OTY-Math** [comment]
@Jhvictor4 답변 감사합니다 열심히 읽어보구 모르는 거 있으면 다시 issue 남기겠습니다!

지금까지 한 작업물은 (미완이지만) branch에 push 해두었습니다.
두 번째 질문 관련해서만 한번 확인해주시면 감사드리겠습니다 ㅠㅠ

항상 수고하십니다! ( issue는 설명 읽어본 후 다 이해되었다 싶으면 닫겠습니다 )

**Comment by Jhvictor4** [comment]
아 레포 볼 필요도 없었네요.. ㅎ
다시 보니 INSTALLED_APPS 에 쉼표 빠져있네요, 넣어주시면 정상 작동 할거에요

1번도 제가 아까 대충 읽었네요 죄송합니다.
쓰지말란 스펙은 없는게 맞고요, 음 구현은 자유롭게 해주시면 될 것 같습니다.
다만 ManyToManyField에는 _on_delete_ attribute가 없습니다. 
장고 다대다 필드 구현은 과제 3번 스펙과 마찬가지로 ForeignKey를 통한 연결테이블입니다. ForeignKey의 on_delete default는 CASCADE 입니다. 다대다를 사용할 때, 연결테이블을 직접 선언하고 through attribute로 지정하면 이러한 설정을 조작할 수 있습니다 (세미나 때 잠깐 말씀드렸듯이)

**Comment by OTY-Math** [comment]
감사합니다!
