### ISSUE TITLE
assignment 2 login component spec 질문

### ISSUE THREAD

**Issue by yeonsumia** [wafflestudio/19.5-rookies#419]
안녕하세요, react assignment 2 를 수행하다 질문이 생겨 issue 게재합니다.

다름이 아니오라 figma에 나온 login 창의 spec에는 image만 있는데,
따로 css 정보/png 정보가 주어지지 않은 채로 구현해야 하는지 궁금합니다.

감사합니다.

**Comment by woohm402** [comment]
넵 눈으로 보고 적당히 비슷하게 해 주시면 됩니다! 깃허브 로그인 창이랑 똑같이 생겼으니 그거 보고 하셔도 됩니다 👍

**Comment by yeonsumia** [comment]
넵 알겠습니다!
