### ISSUE TITLE
리액트 아이콘 추가방법 관련해 질문드립니다.

### ISSUE THREAD

**Issue by HyungGeun-Cho** [wafflestudio/19.5-rookies#420]
안녕하세요?
와플스튜디오 19.5기 루키 조형근입니다.
React세미나 Assignment2 피그마 스펙을 보던 중, 올려주신 여러 아이콘들을 확인할 수 있었습니다.
그래서 이 예쁜 아이콘들을 제 웹사이트에도 구현해보고자 노력하던 중 궁금증이 생겼습니다!

1. 해당 아이콘들의 그림파일을 찾아 넣기에는 뭔가 적당한 소스를 잘 찾지 못하겠고,
2. 전에 fontawesome을 사용해본 적이 있는데 리액트에서 사용하기 위해서는 추가 패키지 설치가 필요하더군요!;;
3. 혹은 css를 활용하여 직접 아이콘 모양을 만들어내는 방법이 떠올랐습니다..!

이 중 어떻게 해결하는 것이 가장 좋을지, 아이콘 추가 관련 팁을 얻고자하여 질문드립니다.
감사합니다!

++ 더불어서 이번 과제의 학생 lock 기능은 
++ 학생 세부 정보 화면을 벗어나 학생 목록 페이지로 이동한 후, 다시 선택했을 때에도 lock 상태로 남아있어야 하는 것인지 질문드립니다!

**Comment by woohm402** [comment]
피그마의 경우 보고 계신 아이콘을 클릭하면 svg나 png 등 원하시는 파일 포맷으로 export할 수 있습니다!

![image](https://user-images.githubusercontent.com/39977696/133640074-0c4a0e1d-e383-4801-92e7-51052298c759.png)

[이런 블로그](https://sumini.dev/guide/008-how-to-export-svg-from-figma/) 참고해보시면 좋을 것 같습니다

참고로 리액트에서 아이콘은 svg로 다루시는 걸 추천드리는데, [이 문서](https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs) 참고해 주세요!

**Comment by woohm402** [comment]
넵 lock은 해제하기 전까지 유지되어야 합니다 (새로고침 등으로 인해 state가 날라가는 경우 제외)

**Comment by HyungGeun-Cho** [comment]
정말 감사합니다!!! :)
