### ISSUE TITLE
장고 user 모델 migration 관련 질문드립니다.

### ISSUE THREAD

**Issue by ding-young** [wafflestudio/19.5-rookies#422]
안녕하세요, 과제 2를 진행하며 [user 모델 관련 migration 파일](https://github.com/wafflestudio/19.5-rookies/blob/master/django/seminar2/assignment2/user/migrations/0001_initial.py) 에 관해 궁금증이 생겼습니다. 저희가 User 필드를 직접 작성해서 채워넣는 것도 과제의 일부임을 확인하였는데, **그렇다면 해당 마이그레이션 파일도 먼저 적용을 하고, 그 이후에 유저 필드를 추가해서 모델 수정 후 마이그레이션 파일도 생성해서 적용을 하는 것인가요??** (그렇게 했더니 email field 등등을 model에 작성해주고 migration을 만들어줘도 이미 스키마는 그 전에 생겼으므로..? 만들어진 field의 일부 세부사항을 수정하는 셈이 되었습니다.) 0001_initial.py에는 아직 과제를 통해 구현하지 않은 field에 대한 정보가 있어서 .... 과제를 진행하면서 결국엔 그 0001_initial.py에 지시하는 바와 같거나 유사하게 될 것 같기는 한데 잘 모르겠습니다...

**Comment by Jhvictor4** [comment]
아 넵 마이그레이션 과정을 명시하지 않은 건 그냥 구동 정상적으로 되도록 ORM이랑 DB 싱크만 잘 맞춰주시면 된다고 생각해서인데요 (개인적으로)

필드 구현하시고 그냥 마이그레이션 정상적으로 되었는지 체크 정도만 하시고 넘기셔도 될 듯 합니다..ㅎ

**Comment by ding-young** [comment]
넵 알겠습니다! 감사합니다.
