### ISSUE TITLE
리액트 useReducer 훅 관련

### ISSUE THREAD

**Issue by ice1039** [wafflestudio/19.5-rookies#423]
안녕하세요. 

현재 wsl2를 통해 우분투를 사용 중입니다.

context를 정리하는 과정에서 위의 코드를 아래의 코드와 같이 정리하였습니다.

![image](https://user-images.githubusercontent.com/86710785/133738939-8012128e-c02d-479b-bc1e-c72185ff8f0b.png)
![image](https://user-images.githubusercontent.com/86710785/133738678-ff770a66-e6f2-427c-a1f1-f7a4d2901b4c.png)

그런데 학생 목록을 렌더링하는 부분에서 TypeError: Cannot read property 'map' of undefined 가 발생하였습니다.
문제가 발생한 부분의 코드는 아래와 같습니다.
![image](https://user-images.githubusercontent.com/86710785/133739206-2c62a87a-825a-4aae-9d64-f4f8f5c24c79.png)

정리 이전의 코드로 실행할 때는 문제가 없었는데, 왜 이런 오류가 발생하게 되었는지 여쭤볼 수 있을까요?
감사합니다.

**Comment by woohm402** [comment]
`studentList`가 `undefined`라는 거니까, `state` 가 `undefined`일 거라고 추측할 수 있겠습니다.
즉 `useStudentState()`가 리턴하는 객체에 `state`라는 값이 없나 봅니다.

`StudentState.Provider`가 provide하는 value값이 `{state, dispatch}` 이기를 의도하신 것 같은데, 지금 코드대로면 `state, dispatch`를 보내는 것 같습니다. 중괄호로 한 번 더 감싸 보시겠어요?

**Comment by ars-ki-00** [comment]
`StudetnStateContext.Provider`의 value 넘기는 부분 한 번 확인해보세요
`state` 와 `dispatch` 함께 넘기는 과정에서 실수하신 거 같아요

**Comment by ice1039** [comment]
앗 바로 눈에 보이는 실수였네요ㅠㅠ 답변 감사합니다!
