### ISSUE TITLE
dictionary KeyError (  POST/api/v1/seminar/ )

### ISSUE THREAD

**Issue by OTY-Math** [wafflestudio/19.5-rookies#426]
장고 assignment2 requirement 8에서 POST/api/v1/seminar/

에서 개설을 신청한 user가 instructor라면 새로운 세미나를 개설하고 세미나의 instructor에 user의 instructorprofile을 할당하는 작업을 시도했습니다.

seminar/viewㄴ.py SeminarViewSet class 중 일부
![image](https://user-images.githubusercontent.com/87603284/133763371-f50aa1e3-bfde-48e2-a60f-be1f6732558f.png)

seminar/serializers.py SeminarSerializer class 중 create 함수
![image](https://user-images.githubusercontent.com/87603284/133764146-6a2e51bc-e877-46df-8685-9d617c07f407.png)

이에 따라 SemianrViewSet에서 위와 같이 data에 "user"를 key로 하는 정보를 update하고 
serializer의 create 함수에서 이를 받아 seminar를 개설하고자 했는데, 아래와 같이 
KeyError가 떴습니다. 

![image](https://user-images.githubusercontent.com/87603284/133764307-14ea9499-9cde-4128-b0f3-4984eb6b7b48.png)

이와 거의 유사한 방식이 Survey의 views.py와 serializers.py에 사용되는데 왜 이놈은 KeyError가 뜨는지 잘 모르겠습니다

Python 문법상의 문제일까요?

**Comment by Jhvictor4** [comment]
Serializer의 validation 과정에 정상적으로 담기는지 체크가 필요할 것 같습니다. SeminarSerializer에 해당 과정이 존재하는지 확인해보시겠어요?

**Comment by OTY-Math** [comment]
@Jhvictor4 

validation 과정이 필수적이지 않다고 판단하여, 일단 def validate 함수는 구현하지 않았습니다.
그런데 저도 이 함수가 없어서 그런가 해서, 
validated_data -> data로도 시도해보았지만 keyerror 가 똑같이 발생했고,

instructor data를 추출해서 seminar에 넣는 과정만 삭제했더니 코드가 정상적으로 작동하여 새로운 seminar가 생성되었습니다.(물론 instructor는 공란)
![image](https://user-images.githubusercontent.com/87603284/133769757-708ff3f3-e07a-49bc-8d49-daadeb7b2e7e.png)

**Comment by OTY-Math** [comment]
정정하겠습니다 
![image](https://user-images.githubusercontent.com/87603284/133770206-675da0eb-4289-4b05-a6b6-89b7e23f9996.png)
라는 validate 과정을 다시 구현했었네요 ㅠㅠ

**Comment by Jhvictor4** [comment]
Key error는 validated_data에 user라는 값이 없기 때문에 발생하는데, 보내주신 시리얼라이저 필드에  user가 없으면 시리얼라이저는 validation 과정에서 user를 무시합니다. 추가해보시면 좋을 듯 합니다

**Comment by OTY-Math** [comment]
user를 seminar serializer에 넣을순 없어서, instructor와 participant가 비어있는 seminar를 먼저 개설하고 view에서 instructor를 삽입해주는 형식으로 해결햇습니다. 감사합니다.
