### ISSUE TITLE
android Dao 구현 중 @Insert, @Delete 관련 질문드립니다

### ISSUE THREAD

**Issue by dongho-Han** [wafflestudio/19.5-rookies#427]
안녕하세요.
이번 과제 내용 중 Dao를 구현할 때, '@Insert', '@Delete' 부분을 작성하다 궁금한 부분이 생겨 질문드립니다.
1. 세미나 시간에 '@Insert'를 구현시,
'@Insert(onConflict = OnConflictStrategy.REPLACE)'
와 같은 방법으로 primary key가 중복되는 경우에 대해 덮어쓰기를 하는 방법에 대해 배웠습니다.
하지만, skeleton code  상의 data class Todo 정의를 보면, primarykey를 autogenerate=True 옵션을 주었기 때문에 primary key가 중복되는 경우가 있을지 궁금합니다. 단순히 table 내 data class를 같은 title, content로만 만들었을 시에는 primary key가 달라 문제되지 않는 것 같은데, 어떤 상황에서 primary key가 중복되는지 궁금합니다.

2. 아래 사진과 관련된 질문입니다.
이번 과제를 구현 시, 초기에는 중복되는 경우까지 고려하는 것이 좋다고 생각하여 '@Insert(onConflict = OnConflictStrategy.REPLACE)' 를 이용하여 구현하였고, 아래 '@Delete'를 구현하였습니다. 
하지만, Delete를 실행하니, 아래와 같은 오류가 출력되었습니다.
'java.lang.NoSuchMethodError: No interface method deleteTodo(Lcom/wafflestudio/assignment2skeleton/model/Todo;Lkotlin/coroutines/Continuation;)Ljava/lang/Object; in class Lcom/wafflestudio/assignment2skeleton/db/TodoDao; or its super classes (declaration of 'com.wafflestudio.assignment2skeleton.db.TodoDao' appears in /data/data/com.wafflestudio.assignment2skeleton/code_cache/.overlay/base.apk/classes4.dex)'
deleteTodo는 잘 구현한 것 같은데 무엇이 문제인지 도저히 찾지 못하다, 중복되는 primary key 문제를 무시하고 단순히 '@Insert'로 구현하니 얼떨결에 해결은 되었습니다. 하지만 근본적인 문제가 무엇인지 궁금합니다. 또한 '@Insert(onConflict = OnConflictStrategy.REPLACE)'로 insert를 구현하였을 시에는, 어떤 식으로 Delete를 구현하는 게 옳은 방법인지 여쭤보고 싶습니다. 

구글링을 좀 해 보았는데, 관련한 issue를 찾지 못해 질문드립니다. 혹시 관련된 링크가 있다면 답변으로 남겨주셔도 감사하겠습니다.

![question](https://user-images.githubusercontent.com/60506244/133771432-1af60771-cfb2-42f9-af2d-cf51d6dfc591.png)

**Comment by JYPSloth** [comment]
저는 일개 수강생이지만 조금이나마 도움이 될까 싶어 답변 남겨봅니다.

1.  이번 과제처럼 데이터베이스가 하나만 있는 상황에서는 autoGenerate만 설정해도 primary key가 충돌할 가능성은 없을 것 같습니다. 하지만 다른 데이터베이스를 불러와 merge해야 할 경우, 두 데이터베이스 모두에 autoGenerate가 설정되어 있는데 충돌 상황에 대한 대비가 따로 없을 경우 merge 이후에 primary key의 유일성이 보장되지 않으므로 primary key가 겹칠 수 있습니다. 이럴 때는 OnConflictStrategy를 사용하여 충돌한 데이터를 처리해줘야 할 것 같습니다.

2.  저는 OnConflictStrategy를 사용하지 않고 구현했는데, 이 이슈를 확인한 후 다른 것은 다 똑같이 하고 '(onConflict = OnConflictStrategy.REPLACE)'만 추가하여 실행해 보니 추가하기 전과 마찬가지로 별 문제 없이 돌아갔습니다. 저 오류에 대해 검색해보니 library의 버전이 충돌하는 경우에 뜨는 것 같은데 혹시 다른 부분에 문제가 있던 것이 아닐까요?! 큰 도움은 못 드려서 죄송합니다..
[해당 오류가 언급된 공식 문서 링크](https://developer.android.com/jetpack/androidx/releases/compose-compiler?hl=it)
[비슷한 오류를 겪은 사람의 질문글](https://stackoverflow.com/questions/38951218/java-lang-nosuchmethoderror-no-interface-method-sortljava-util-comparator-ex)

**Comment by veldic** [comment]
1. 네 이번 과제에서는 특별히 충돌이 일어나지 않을겁니다. onConflict는 통신을 통해 받아온 정보라거나 primary key가 중복될 경우를 생각해주시면 되기 때문에 이번에는 특별히 명시해주시지 않아도 됩니다. 
2. NoSuchMethodError에 관해서는 조금 생각이 필요할 것 같네요... 저도 처음보는 에러라...
삭제같은 경우는 기본적으로 Query문에서 id를 이용해 삭제하는 방식을 추천드립니다. Object를 통한 삭제방법은 조금 불안한 면이 있습니다.
Seminar 2에 올려드린 예시 코드의 Dao를 조금 참고해주시면 될 것 같습니다.
https://github.com/wafflestudio/19.5-rookies/blob/a6782bc8ebbdfd7f574bfa325f1ab8d575ed0093/android/seminar_2/seminar2/app/src/main/java/com/veldic/seminar2/db/MemoDao.kt#L19-L20

**Comment by dongho-Han** [comment]
답변 감사합니다!
