### ISSUE TITLE
React 과제2 잠금 기능 구현 관해 질문드립니다

### ISSUE THREAD

**Issue by 0114kek** [wafflestudio/19.5-rookies#428]
잠금을 학생상세페이지 내에서 설정하게 되는데
저의 경우 상세페이지를 하나의 독립적인 컴포넌트로 만들어
라우터에 의해서만 접근이 가능하도록 했습니다.

그러다 보니 잠금 설정을 한 후 다시 학생 리스트가 있는 페이지로 갔다가 다시 돌아온 경우에
잠금이 유지가 되지 않습니다.(상위 컴포넌트가 존재하지 않아 props를 줄수가 없다보니)

이런 경우 해결 방법은 useContext를 이용해 잠근 학생 id만 모은 배열을 만들어
매번 상세 페이지에 들어갈때 마다 해당 배열에 id가 들어있는지 비교해보는 것 뿐일까요??

**Comment by woohm402** [comment]
학생 데이터 자체에 잠금되어있는지에 대한 필드가 들어 있는 것이었습니다!

**Comment by 0114kek** [comment]
감사합니다 그렇게 해보겠습니다
