### ISSUE TITLE
Participant is_active 관련 질문  드립니다.

### ISSUE THREAD

**Issue by numnum97** [wafflestudio/19.5-rookies#433]
안녕하세요.
과제 중 8번 내용에서 해당 부분에 대해서 질문이 있습니다.
![image](https://user-images.githubusercontent.com/56782035/133912935-67cdf4ea-d036-4f3c-9416-1ea14e30c9da.png)

이 때 말하는 가득 찬 경우라는 것은 위에서 언급했던 내용처럼 `is_active`가 `false`인 참가자들은 제외를 하고 고려하는 건가요?

감사합니다.

**Comment by Hank-Choi** [comment]
현실 수강신청 처럼 드랍자 포함해서 정원초과를 나타내려했습니다. 가득 찬 조건을 드랍자 제외하고 구현하셨다면 그대로 하셔도 됩니다!
