### ISSUE TITLE
input 내부에 고정 텍스트 삽입하는 방법

### ISSUE THREAD

**Issue by ChrisLee02** [wafflestudio/19.5-rookies#434]
![image](https://user-images.githubusercontent.com/81219809/133913409-ad64246c-3aee-49c0-b3fa-0bb339635fa8.png)
사진에 보이는 이메일을 박스 내부에 넣는 방법을 모르겠습니다. 저런 요소를 보통 뭐라고 부르나요?

**Comment by woohm402** [comment]
input suffix 라고 검색하시면 나올 거예요 ([예시](https://stackoverflow.com/questions/47906932/add-suffix-to-value-displayed-inside-react-toolbox-input-number)

저였으면 `input`을 감싸는 `div`를 하나 만든 다음에 그 `div`의 css에서 [`:after`](https://developer.mozilla.org/ko/docs/Web/CSS/::after) 속성 써서 구현했을 것 같네요!

**Comment by ChrisLee02** [comment]
감사합니다:)
