### ISSUE TITLE
React Context 관련 질문 드립니다

### ISSUE THREAD

**Issue by Songmin17** [wafflestudio/19.5-rookies#437]
안녕하세요, 

리액트 과제 2를 하면서 context에 대해서 질문이 생겨서 글을 올리게 됐습니다.
Seminar2 PPT 36장에서는 context provider를 App 전체를 wrap해서 어느 컴포넌트에서든 context provider의 prop을 활용할 수 있는 방법이 적혀있어요.
저는 이 비슷한 것을 App이 아닌 List 컴포넌트에서 하고 싶어서 context provider를 List 컴포넌트에 wrap하는 방법에 대해서 검색을 해봤는데도 해결책을 찾지 못해서 질문 드립니다.
하나의 context를 가장 위에 있는 컴포넌트가 아닌 어떤 child 컴포넌트만 wrap하게 하려면 어떻게 해야 하나요?
감사합니다.

**Comment by woohm402** [comment]
동일한 방식으로 구현하면 됩니다. 다만 해당 예시에서는 `index.js`에서 `<App />`을 감싸 구현했는데, @Songmin17 님의 경우에는 `List`를 호출하는 컴포넌트에서 `<List />`를 감싸 구현해야 한다는 차이가 있습니다.

`Context`는 보통 해당 슬라이드에 나와 있는 것처럼 특별한 방식으로 다루지만, 근본적으로는 그냥 다른 컴포넌트들과 동일한 리액트 컴포넌트입니다. 그 부분을 인지하고 구현하시면 헷갈리는 거 없이 구현하실 수 있을 거 같네요!

-----

또한 과제 진행하면서 Context를 사용해 보셨다면 "굉장히 편하다"는 걸 느끼셨을 거예요. 하지만 '전역 데이터'라는 존재는 상당히 무겁습니다. 오류가 생겼을 때 디버깅도 힘들고, 컴포넌트간 결합도도 높이게 됩니다. 때문에 Context 남용하지는 말아야 한다는 점 인지해 주세요!

취향 차이겠지만, 실제로 저는 보통 앱을 만들 때 로그인 토큰이나 앱 테마 등 무조건 앱 전체에 적용되는 아주 중요한 정보 및 그를 다루는 로직을 제외하고는 전부 각 컴포넌트에서 처리하는 방식을 선호합니다

**Comment by Songmin17** [comment]
감사합니다! :)
