### ISSUE TITLE
React conditional routing 하는 방법에 대해서 질문 드립니다

### ISSUE THREAD

**Issue by Songmin17** [wafflestudio/19.5-rookies#440]
안녕하세요, 

React로 conditional routing을 해서 login 페이지와 students페이지로 선택적으로 가게 하고 싶은데, 어떻게 하는지 궁금해서 질문 드립니다.
conditional routing 하고 싶어서 코드를 이렇게 작성했는데 

```jsx
<Route path={"/"} component={() => (
    loggedIn? 
        <Route path={"/students"} component={StudentsPage} /> :
        <Route path={"/login"} component={Login} /> 
)} />
```

path가 "/"일때 다른 페이지로 가지 않고 있습니다.
conditional routing을 올바르게 하려면 어떻게 해야 하나요?

**Comment by woohm402** [comment]
일단 지금 올려주신 방식이 정확히 어떻게 동작하는지 설명드리겠습니다. (가독성을 위해 올려주신 이슈 코드 indent를 조금 수정했습니다)

일반성을 잃지 않고, `/students`로 보내는 상황이라고 가정하겠습니다.
1. `/` 라우트는 `/`에 부합하기 때문에 (사실 어떤 url이든 `exact` 옵션이 없다면 `/` 라우트에 부합하겠죠) 해당 라우트가 지정하는 컴포넌트로 라우팅됩니다. 즉 올려주신 코드가 아래 코드와 동치가 됩니다.
```jsx
<Route path={"/students"} component={StudentsPage} />
```

2. `/` 라우트는 `/students` 라우트에 부합하지 않습니다. 패스합니다.
3. ...?

따라서 정상 작동하지 않습니다. 아마 `<Route />` 대신 `<Redirect />` 쓰시면 해결은 될 텐데, 좋은 구조가 아닙니다.

---

일반적으로 어떻게 하는지에 대해서는 [이 이슈 댓글](https://github.com/wafflestudio/19.5-rookies/issues/424#issuecomment-921604488) 을 참고해 보시겠어요? 해결되지 않은 궁금증이 있으시면 아래 댓글로 계속 이어서 질문해주시면 될 것 같습니다!

**Comment by Songmin17** [comment]
해결했습니다~!
