### ISSUE TITLE
화면 크기+위 요소들에 따른 height 얻는 방법

### ISSUE THREAD

**Issue by subir-sh** [wafflestudio/19.5-rookies#441]
안녕하세요.

/
ㅁ (div1)
ㅁ (div2)
ㅤ
ㅤ
ㅤ
/

이렇게 화면과 화면 안의 div가 있다고 할 때,
자동으로 div2 밑을 꽉 채우게 또 다른 div3을 그리고 싶습니다.

/
ㅁ (div1)
ㅁ (div2)
ㅇ
ㅇ -> (div3)
ㅇ
/

이 때 div3의 길이를 어떻게 자연스럽게 얻을 수 있을까요?
고정된 값으로 하자니 창의 크기가 달라질 때 문제가 생겨서,
%를 써보려고 했는데 width는 잘 작동이 되는데 height는 아예 안 먹힙니다.
그래서 vh를 쓰고 있기는 한데, calc(100vh - (div1+div2의 height)px) 보다 더 좋은 방법이 있을 것 같아 질문해봅니다 ㅠㅠ

**Comment by woohm402** [comment]
[css `flex` 속성](https://developer.mozilla.org/ko/docs/Web/CSS/flex) 을 이용하면 구현 가능합니다.

`div3`에 남은 공간을 꽉 채우도록 `flex`속성을 적절히 설정해주면 됩니다. 혹시 요소가 항상 세 개인 게 아니라 일반적인 상황에서 맨 밑의 요소를 선택하셔야 하는 거라면, [css 'last-child` 속성](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child) 을 참고해 주세요!

답변이 충분하진 않은 것 같은데, 일단 시도해보시고 안 되시면 밑에 댓글로 추가질문 주시겠어요? 🙂

**Comment by subir-sh** [comment]
div들을 감싸는 flex(direction: column)을 만들고, 마지막 div에 flex: auto를 하니까 잘 됩니다. 감사합니다!
