### ISSUE TITLE
Network에서 받아오는 자료 선언시, dictionary type에 대해 질문 드립니다

### ISSUE THREAD

**Issue by chaemin2001** [wafflestudio/19.5-rookies#442]
struct ResponseData: Codable {
    var statusCode: Int
    var body: [Member]
}

struct Member: Codable {
    var id: Int
    var name: String
    var team: String
}

Profile을 불러올 때에는 이와 같이 list로 받아왔는데, member의 상세 정보를 불러올 시 body가 dictionary로 선언되어 있어 "Expected to decode Array<Any> but found a dictionary instead." 라는 오류가 발생합니다.
이를 해결하고자 [Member]을 dictionary 형태로 바꾸어야할 것 같은데, 적절한 방법을 찾지 못해 질문 드립니다.

**Comment by JSKeum** [comment]
멤버 상세 정보를 불러올 때는 샘플로 드렸던 Member 모델 말고 새로운 모델을 정의해 불러 오면 됩니다 😀

**Comment by chaemin2001** [comment]
해결했습니다 감사합니다!
