### ISSUE TITLE
과제2 login 관련 질문

### ISSUE THREAD

**Issue by ishlove77** [wafflestudio/19.5-rookies#444]
과제2에 아래 사진처럼 email, password 모두 정확히 입력했는데 로그인이 안됩니다........... 물론 JWT 역시 정확히 입력은 했습니다 이 로그인이 안되는 이유가 authencated 부분 때문에 안되는 것 같은데 어떻게 수정하면 되나요??](ur
![Screenshot from 2021-09-20 22-31-01](https://user-images.githubusercontent.com/88336033/134011102-3a7623fb-cf83-4a79-bfaa-63e6c6cd3f10.png)
l
![Screenshot from 2021-09-20 22-31-08](https://user-images.githubusercontent.com/88336033/134011115-a7b9abbf-c06e-4257-9e81-3b76c6c5ed95.png)
)

**Comment by Jhvictor4** [comment]
password 설정 시에, django는 기본적으로 db에 저렇게 raw string을 보관하지 않고 암호화를 거친 값을 보관합니다. 따라서 authenticate 함수에서도 기본적으로 암호화가 될 것이라는 전제 하에, body로 넘겨주신 1234 를 암호화 해서 디비 값과 비교합니다.

요청에는 암호화 된 1234, 디비에는 그냥 1234가 있으니, 장고가 보기엔 비번이 틀린 것이고, 그래서 오류를 내주고 있네요

user 비밀번호를 지정할 때는 set_password 함수를 사용하시면 장고의 기본 동작처럼 암호화된 비밀번호를 사용하실 수 있습니다.

참고하시고 반영해보시면 아마 잘 들어갈거에요
