### ISSUE TITLE
springboot skeleton code관련 질문

### ISSUE THREAD

**Issue by kohandy1902** [wafflestudio/19.5-rookies#445]
올려주신 skeleton code잘 다운 받았습니다. 그리고 과제1에서의 기능이 잘 동작하는지 실행시켜보았는데, 새로 SurveyResponse를 생성하는 과정에서 질문이 생겼습니다. 과제1에서는 Json형식을 넘겨줄 때 "spring_exp"와 같은 snakecase를 사용하였는데, Skeleton코드를 실행시켜보니 "springExp"와 같은 camelcase로 해야 잘 동작함을 확인할 수 있었습니다. 그냥 이 부분은 무시하면 될까요?

감사합니다.

**Comment by Hank-Choi** [comment]
앗 스네이크 케이스로 바꾸겠습니다!
