### ISSUE TITLE
잘못된 url 입력에 따른 리다이렉트 시에 studentList 초기화 문제

### ISSUE THREAD

**Issue by HyeongtaekOh** [wafflestudio/19.5-rookies#446]
과제 스펙에 따라 로그인이 된 상태에서 양식에 맞지 않는 url을 입력했을 시에는 /students로 리다이렉트되도록 코드를 작성했습니다.
그런데 리다이렉트 과정에서 페이지를 새로 불러옴으로 인해 studentList가 초기화되는데 초기화되지 않도록 구현하는 것도 과제 스펙에 포함되는 것인지 궁금합니다. 
url 입력을 통해 페이지를 이동할 때 페이지 reload 없이 이동하도록 하는 것이 가능한 것인가요?

**Comment by woohm402** [comment]
불가능합니다!

[이 이슈](https://github.com/wafflestudio/19.5-rookies/issues/415#issuecomment-920162899) 참고 부탁드립니다 :)

**Comment by HyeongtaekOh** [comment]
확인했습니다! 현재 이미 localStorage를 이용해서 로그인 기능을 구현해놓은 상황입니다.
그렇다면 과제 스펙 상 로그인 이후에 잘못된 url이 입력되었을 때 /students로 리다이렉트되는 건 studentList도 초기화되는 것이 맞다는 것으로 이해하면 될까요??

**Comment by woohm402** [comment]
넵 자동로그인이 구현되어 있다면 그게 맞고, 자동로그인이 없으면 로그인 상태도 초기화되니 /login 으로 보내질 것 같네요!

**Comment by woohm402** [comment]
@HyeongtaekOh 해결되셨나요?

**Comment by HyeongtaekOh** [comment]
아 넵 답변이 늦었네요ㅜ
해결됐습니다!
