### ISSUE TITLE
과제2 user default 질문드립니다.

### ISSUE THREAD

**Issue by youna1222** [wafflestudio/19.5-rookies#447]
과제2에 스펙에 따로 명시되어 있지는 않은데, user default도 구현하여야 하나요?
그럴 경우, 앱을 실행하고 화면이 넘어갈때마다 request의 response를 받아와야 하는 이번 과제에서, user default가 무슨 의미가 있는지, 어디에 적용되어야 하는지도 여쭤보고 싶습니다.
감사합니다!

**Comment by JSKeum** [comment]
과제2에서는 데이터를 로컬에 저장하지 않기 때문에 UserDefault를 구현하지 않아도 됩니다! 이번 과제에서 만드는 앱에서는 사용자와 관련된 데이터를 로컬이 아닌 웹서버에 저장한다고 생각하시면 됩니다!
