### ISSUE TITLE
npm start 무한 로딩 질문

### ISSUE THREAD

**Issue by sggithi** [wafflestudio/19.5-rookies#448]
안녕하세요 웹스톰에서 npm start를 시행했을때 페이지가 로드되지 않고 계속 로딩상태로 멈추는 문제가 발생하여 질문드립니다.(별다른 에러 메시지는 뜨지 않는 상태입니다.)

구글링을 해보니 무한로딩은 대부분 css에 문제가 있을 때 발생하는것 같은데 그 원인을 못찾겠습니다.ㅠㅠ

더보기 버튼 클릭시 학생 정보 창이 뜨도록하는 기능을 실현하는 함수의 자리들을 옮겼더니 문제가 발생하였습니다.
우선 다음은 이전 세미나 시간에 보여주셨던 TodoItem과 같은 기능을 하는 함수이고,

~~~

const StudentItemRe = ({item, removeStudent}) =>{
    return(
       <div >
            <button className="saveButton">저장</button>
           /<button className="removeButton" onClick={removeStudent}>삭제</button>
            <StudentItemRe item = {item}  />
            <li>이름</li>
            <input defaultValue={item.name} />
            <li>학년</li>
           <input defaultValue={item.grade}/>
           <li>프로필</li>
            <input defaultValue={item.profileImg}/>
       </div>

~~~

TodoList와 같은 기능을 하는 함수부분입니다.
manageInfoStudent의 css는 display:none;을 추가한 상태로, 평상시에는 보이지 않다가 버튼을 클릭하여 handleStudentInfo함수가 실행되면 해당부분이 block되도록 하였습니다.

~~~
const StudentInfo = ({studentList, removeStudent}) =>{
    const Info = document.getElementById('manage');
    const handleStudentInfo = () =>{
        Info.style.display = 'block';
    }
    return(
        <div id='manage' className="manageInfoStudent">
            {studentList.map(item =>(
                <StudentItemRe key = {item.id} removeStudent={removeStudent} item = {item}/>
            ))}
        </div>

    )
}
~~~
이부분을 버튼과 같은 파일에 넣어주면 실행에 무리가 없는데 div 영역을 분리하기 위해 파일을 분리하였더니 문제가 발생하였습니다..
혹시 getElementById에서 id를 검색하는 과정에서 무한로딩이 발생하는 것일수도 있을까요?

감사합니다.

**Comment by woohm402** [comment]
무한로딩이 정확히 어떤 상황이신 걸까요?

일단 리액트에서, `document`라는 변수는 사용하지 않는다고 생각하시면 됩니다.

콘솔창 켜고 한번 캡쳐해주시겠어요?
여유가 되시면 리액트 개발자 도구 (크롬 익스텐션에 있습니다) 설치해서 확인하시면 좀더 원인 파악하는 데 많은 도움이 되실 거예요)


일단 말씀하신 걸로만 봐서는 무한 리렌더중일 수 있을 것 같습니다

**Comment by sggithi** [comment]
리액트 개발자 도구를 설치하였는데 다른 사이트에서는 정상적으로 작동하지만 일단 제가 만든 페이지에서는 작동이 안됩니다.ㅠㅠ
![image](https://user-images.githubusercontent.com/80246502/134171618-c604b985-791b-4088-8c6f-d4e1513b0225.png)

documnet라인을 삭제 해봐도 문제가 생기네요 다시 원래대로 되돌려서 해보겠습니다ㅠㅠ
감사합니다..

**Comment by woohm402** [comment]
밖이라 정신없어서 아까 못 봤는데, `StudentItemRe` 에서 `StudentItemRe`를 무한 재귀 호출중인 것 같습니다.

```jsx
const StudentItemRe = ({item, removeStudent}) =>{
    return(
       <div >
            <button className="saveButton">저장</button>
           /<button className="removeButton" onClick={removeStudent}>삭제</button>
            <StudentItemRe item = {item}  />
            <li>이름</li>
            <input defaultValue={item.name} />
            <li>학년</li>
           <input defaultValue={item.grade}/>
           <li>프로필</li>
            <input defaultValue={item.profileImg}/>
       </div>
```

**Comment by sggithi** [comment]
와... 감사합니다ㅠㅠ
