### ISSUE TITLE
Django 과제 2 - 2번 문제 JWT token 관련 질문

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#449]
안녕하세요. 과제 2의 2번 문제를 하다가 문제가 생겨 질문을 드립니다.
과제 2의 readme에서는 signup이나 login을 하면, request body에 token이 뜬다고 명시되어 있는데, 
제가 login을 했을 때, response에 첨부된 사진과 같이 "Authentication credentials were not provided"라고 뜹니다.. 과제의 설명에 따르면 해당 부분에 저 문구 대신 token이 나와야 한다는 것인가요? 2번 문제에 대해서 보충 설명을 해주시면 감사하겠습니다.
감사합니다.

![스크린샷, 2021-09-22 03-44-55](https://user-images.githubusercontent.com/84329238/134230326-9d426ce4-fead-4f22-aed9-e168c303d2f9.png)

**Comment by kk0in** [comment]
이해가 되어서 이슈를 닫습니다!

**Comment by hansmaan** [comment]
저도 같은 문제를 겪고 있는데.. 혹시 어떻게 해결하셨나요?
