### ISSUE TITLE
고정된 frame 안에 <img> 넣는 방법 질문

### ISSUE THREAD

**Issue by HyeongtaekOh** [wafflestudio/19.5-rookies#452]
저희 과제 피그마 보면 프로필 사진이 원형 프레임 안에 들어가있는데 그렇게 하는 방법(프레임을 벗어나는 이미지는 잘린 상태로 표시)을 모르겠습니다. 
(지난 seminar 1 과제 할 때부터 방법을 찾아보고 있었는데 못 찾고 다른 스펙상 더 중요한 문제들 해결하느라 그냥 프레임을 직사각형으로 맞고 안에 크기에 맞게 이미지를 띄워뒀고, 이번 과제 내에는 해결하고 싶어서 질문 드립니다.)

**Comment by woohm402** [comment]
저같은 경우는 `<div>`태그로 `<img />`를 한번 감싸고, 해당 `<div>`태그 동그랗게 만들고 `overflow: hidden` 주는 방식으로 구현합니다

**Comment by HyeongtaekOh** [comment]
overflow 속성에 그런게 있었군요.
감사합니다!
