### ISSUE TITLE
로그인 된 상태에서 잘못된 url을 입력시 다시 로그인 창으로 가는 오류에 대해서 질문 드립니다

### ISSUE THREAD

**Issue by Songmin17** [wafflestudio/19.5-rookies#455]
안녕하세요,

리액트 과제를 하면서 이미 로그인 된 상태일때 '/students'페이지로 가게 구현을 했습니다. 
그런데 여기서 제가 직접 잘못된 url을 입력을 하면 로그인 state가 초기화되서 '/login' 페이지로 다시 이동을 합니다. 이 문제를 해결하려고 localStorage를 통해서 자동 로그인 기능을 만들어보려고 했지만, url을 직접 입력했을때 로그인 정보가 여전히 초기화되고 있습니다.
App에서 localStorage를 login정보로 update하고난 후, conditional routing을 할때는 localStorage에 있는 정보를 통해서 결정을 하는 방식으로 코드를 구현을 했는데, 코드에 어떤 부분 때문에 자동 로그인이 안되는지 알려주면 좋을것같아요.

**Comment by woohm402** [comment]
코드를 몰라서 확실하진 않지만 크게 다음 두 가지 가능성이 있습니다.

1. `localStorage`에 값이 안 들어가 있음
`localStorage`에 원하시는 값이 들어가 있지 않을 수 있습니다. 아래 사진과 같이 개발자 도구에서 `Application > Local Storage > 본인 사이트 url` 로 들어가셔서, 로그인 정보가 스토리지에 잘 들어가 있는지 체크해 보시기 바랍니다.

![image](https://user-images.githubusercontent.com/39977696/134359169-e5ecfd7e-84da-4f7c-8999-1eec53166a1f.png)

2. 코드 오류로 인해 `localStorage`에 들어 있는 값에 따라 라우팅이 잘 되고 있지 않을 수 있습니다.

가령 `localStorage.get`을 할 때 키값이 잘못돼 있다든가.. 하는 이슈일 수 있습니다. 이 부분은 코드를 읽어봐야 확인 가능할 것 같습니다.

---

사실 자동 로그인은 이번 과제 필수 스펙은 아닙니다: !446 참고해 주세요!
어차피 다음 과제에선 필수 스펙이지만요 😅

**Comment by Songmin17** [comment]
그러면 스펙에서 "로그인되어 있다면 url은 자유이나, 만약 잘못된 (어디에도 맞지 않는) url을 입력했다면 /students 로 리다이렉트된다." 이렇게 적혀 있는 부분은 자동 로그인 말고 다른 방법으로 해결할 수 있을까요?

**Comment by woohm402** [comment]
자동 로그인이 없으면 해결 불가능합니다! 자동 로그인 써서 구현하셔도 되고, 구현하지 않으셔도 됩니다. 자동로그인이 없으면 `로그인되어 있다면` 부터 틀린 명제라 무시해도 되는 스펙일 것 같네요

**Comment by Songmin17** [comment]
네 해결했습니다~!
