### ISSUE TITLE
git push 를 새 브랜치로 했을때 코드가 없어지는 문제에 대해서 질문 드립니다

### ISSUE THREAD

**Issue by Songmin17** [wafflestudio/19.5-rookies#456]
제가 assignment2를 하는 와중에 이 레포의 assignment2 branch로 git push origin assignment2를 하니까 제 로컬에 있는 레포 전체가 다 없어진 상태거든요. 지난번 과제에서 지금까지 한 부분을 다시 짤수도 있는데, 이런 실수의 원인이 무엇인지 잘 모르겠어서 질문을 드립니다.
일단 제가 입력했던 git command는 다음과 같아요:
(아직 assign1 브랜치에서)
git add .
git commit -m "login and routing"
git mv -k ./assignment1-app/* .
mv assignment1-app/node_modules ./node_modules
git add . && git commit -a -m "폴더 구조 변경"
git remote update
git checkout assignment2
git add .
git push origin assignment2

이렇게 하니까 코드가 다 없어졌습니다.
혹시 원인에 대해서 알려줄 수 있나요? ㅠㅠ 감사합니다.

**Comment by woohm402** [comment]
`push` 때문에 로컬에 있는 코드가 사라졌을 가능성은 없습니다.

올려주신 history대로면 다음 가능성이 있습니다.

1. `checkout` - 이 명령어는 현재 레포의 내용을 다른 브랜치 (또는 커밋)에 있는 걸로 갈아끼웁니다. 이거 때문이었다면, 딱히 실수는 아니고 흔히(사실 아주 자주) 있는 정상적인 상황입니다. 이런 경우라면 다시 `assign1` 브랜치로 체크아웃하시면 코드가 다시 생겨있으실 거예요. (`git checkout assign1`)

2. `mv`가 문제를 일으켰을 수 있는데.. 저거 아마 옛날에 하위 폴더에서 폴더 구조 변경하신 히스토리인 것 같네요 저거 때문은 아닐 거 같아요

이거 두개 외에는 직접 폴더를 삭제하셨을 경우밖에 없습니다!

**Comment by Songmin17** [comment]
브랜치를 바꾸려고 하니까 이런 메시지가 뜨는데
The following untracked working tree files would be overwritten by checkout:
구글링을 해보니까 
$ git clean -d -f -f 이런 명령어를 입력하면 branch를 쉽게 바꿀 수 있다고 나와요. 이렇게 하면 assign1 branch에 했던 커밋은 그대로 남아있나요?

**Comment by woohm402** [comment]
일단 `git clean` 명령어를 제가 잘 안 써서 확실하진 않지만, 살짝 찾아보니 꽤 위험한 친구인 것 같습니다

assign2 브랜치에서 뭔가 변경사항을 만드신 것 같은데, 비교적 안전한 `git stash` 등을 사용하시는 게 낫지 않을까.. 싶습니다

일단 assign2 브랜치에서 뭔가 작업하셨을 때 assign1 브랜치에 있는 게 날아갈 확률은 거의 없다고 보시면 됩니다!

**Comment by Songmin17** [comment]
해결했습니다~~
