### ISSUE TITLE
aws배포 이후 git 관련 질문입니다

### ISSUE THREAD

**Issue by 0114kek** [wafflestudio/19.5-rookies#457]
배포를 하고 난 후 aws와 관련된 파일들이 과제 폴더 안에 생성되었습니다.
몇몇 파일들을 수정하고  다시 push하려는데 aws와 관련된 파일들도 모두 깃에 올라가려는 것 같습니다.(양이 엄청 많음)
이런 파일들을 .gitignore로 제외해도 상관없을까요??

**Comment by woohm402** [comment]
혹시 빌드 파일인가요? 그거 말고는 있을만한 아이들이 없는데.. 어떤 파일들인가요?

**Comment by 0114kek** [comment]
![image](https://user-images.githubusercontent.com/88540493/134362484-33d93178-4e33-46f7-9bbb-2ee2779de585.png)
aws 폴더가 생성되어 위와 같이 많은 파일들이 생성되어있고(아래에 더 많습니다)
![image](https://user-images.githubusercontent.com/88540493/134362535-a44930fe-f7f8-4473-ad9b-e5ef8528c079.png)
awscliv2.zip이라는 무거운 파일도 생겼습니다

**Comment by woohm402** [comment]
혹시 어떤 블로그 참고해서 진행하셨나요..? aws가 저기 왜 가 있지

**Comment by 0114kek** [comment]
아마...
https://docs.aws.amazon.com/ko_kr/cli/latest/userguide/install-cliv2-linux.html
여기에서
$ curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
이거 입력해라해서 그대로 했던것 같습니다
설마 제가 저 폴더안에 들어간 상태에서 설치한건지 ㅠㅠ

**Comment by woohm402** [comment]
넵 그런 거 같습니다ㅠㅠ

그 커맨드 그대로 입력하면 딱 그 폴더 생길 것 같네요! `.gitignore`에 추가해 주시거나, 저 폴더 삭제 (해도 되는지 아닌지는 잘 모르겠지만?) 하시거나 해서 아무튼 깃에 안 올라오게 처리해주시면 됩니다 👍

**Comment by 0114kek** [comment]
네 감사합니다
