### ISSUE TITLE
학생의 이메일 및 전공 정보 수정 시 입력이 안되는 문제

### ISSUE THREAD

**Issue by kmsgm** [wafflestudio/19.5-rookies#458]
안녕하세요, 리액트 수강하고 있는 김민서입니다.

정보 수정 페이지에서 이메일과 전공을 수정하는 데 있어서 입력창에 입력이 되지 않는 문제가 발생했습니다.

이메일은 이런 식으로 @ 앞까지 잘라서 input 창에 보이도록 했습니다. 
이 값을 수정하려고 할 때, 지울 수는 있지만 새로운 입력이 아예 되지 않습니다.
혹시 substring 함수 때문에 안되는 걸까요? 그렇다면 이 문제를 어떻게 해결해야 하나요...?
```js
<label>이메일</label>
<input 
    className='email'
    name='email'
    value={selected.email.substring(0, selected.email.indexOf('@'))} 
    onChange={onChange}
/>
```

두 번째 문제는 전공 선택이 입력창에 반영되지 않습니다.
전공을 선택할 수는 있지만 해당 전공을 클릭했는데도 input 창에는 선택한 전공이 아니라 원래 전공이 계속 뜨게 됩니다ㅜㅜ
```js
<label>전공</label>
<select value={selected.major} onChange={onChange}>
    {majorList.map(item => (
        <option value={item} key={item}>
            {item}
        </option>
    ))}
</select>
```
혹시 몰라서 onChange 함수 추가했습니다!
```js
const onChange = (e) => {
  const { name, value } = e.target;
  setSelected({ ...selected, [name]: value })
};
```
* 전화번호와 프로필 입력은 제대로 됩니다!

**Comment by woohm402** [comment]
1. `indexOf`는 찾는 문자가 없으면 `-1`을 리턴하고, `substring` 함수는 타겟 인덱스를 `(0, -1)`로 받으면 `''`를 리턴합니다. 새로운 입력을 할 때는 `@`가 없을 테니 `value`가 항상 `''`로 뜰 것 같습니다. 해결방법으로는 보여줄 때 value값을 수정하기보다, onChange에서 state를 변경할 때 값을 수정하는 게 좋고, `@`를 가지고 있을 경우 `substring`을 한다든가 하는 식으로 처리해야 합니다!

여담으로 저였으면 매 렌더마다 그 처리를 하기보다는 그냥 마운트될 때 state의 email 필드에 `@waffle.hs.kr`을 제외한 부분을 넣는 방식으로 구현할 것 같습니다

![image](https://user-images.githubusercontent.com/39977696/134430092-742af048-d58a-4ba6-9245-6ee22cffdf84.png)


2. 전공 선택의 경우 `<select>` 태그에 `name`값이 없어서 onChange 에서 `e.target.name`이 `undefined`로 들어가고 있을 것 같습니다.

**Comment by kmsgm** [comment]
해결했습니다! 감사합니다!!
