### ISSUE TITLE
django assignment 2 2번 create_user 관련

### ISSUE THREAD

**Issue by LiTi0416** [wafflestudio/19.5-rookies#459]
2번에서 user를 새로 create하는 기능을 구현하는 중 token이 발급되는 것은 보았는데, 다른 정보로 signup을 주니 409 conflict를 확인하였습니다. 분명 없는 email의 user에 대한 signup인데 오류가 발생하는 것이 이상하여 이것저것 생각해보았는데, serializers.py 에서 제가 설계한 create이 제대로 동작하지 않음을 확인했습니다. 우선 이 부분에 대한 제 코드는 다음과 같습니다.

![image](https://user-images.githubusercontent.com/82010257/134405188-1f351e8b-d909-4ca8-a594-74517d5ed9b0.png)

제 생각을 토대로 어떤 것이 의문이 들었는지 말씀드리자면,
models.py에 필드를 작성하고 Objects를 이용해 CustomUserManager를 지정하여 User를 다루는 것으로 이해했습니다. 그런데 serializers.py에서는 (캡쳐한 부분을 참고하면) User가 get_user_model()로 선언되어 있는 것을 확인했습니다. 이게 정확히 어떤 기능을 하는 것인지 찾아보았지만 제대로 이해를 하지 못하였고, 그래서 문제가 여기에 있는 것인가 싶지만 어떻게 고쳐야 할지 모르겠습니다.

제가 잘못 이해한 부분이 있거나 고쳐야 할 방향을 알려주시면 감사하겠습니다!

**Comment by Jhvictor4** [comment]
달라진 db 반영은 되었나요? Integrity Error가 발생한다는 것은 어찌됐든 데이터가 존재한다는 얘기인데 , waffle_backend_2 db와 잘 연결되어있는것인지, 해당 db에 값이 다 잘 정리된 것인지 확인하는 절차가 필요해 보입니다.

해당 이슈만 문제이면 이메일을 바꿔서 시도하시면 바로 통과할 것 같은데,시도해보시고 다시 글 남겨주시면 감사하겠습니다

**Comment by LiTi0416** [comment]
db 연동이 제대로 안 된 것 같길래 더 찾다 보니 user 생성을 잘못 하고 있었습니다.. 해결되었습니다! 감사합니다.

**Comment by red1108** [comment]
같은 에러가 뜨는데, 어떻게 해결하셨는지 알려주실수 있나요?
