### ISSUE TITLE
Django 과제 2 다대다 구현 관련 문의

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#461]
안녕하세요. 저도 manytomanyfield 없이 foreign key만으로 다대다 구현을 하는데 있어서 어려움이 있어 이슈를 남깁니다.
https://github.com/wafflestudio/19.5-rookies/issues/418#issuecomment-920731758 링크에서 답변을 보면, foreign key의 through attribute에 대한 설명이 있는데, 이에 대해서 구글링을 해도 답변이 잘 나오지 않습니다 ㅜㅜ 이에 대해서 조금만 더 부연설명 해주실 수 있는지 궁금합니다. 감사합니다!

**Comment by Jhvictor4** [comment]
일단 through를 사용하지 않고, 연결 테이블을 직접 구현 하기만 해도 충분합니다.
다대다 관계인 두 model에 대해 각 모델의 ForeignKey 두 개를 연결 테이블에 두면 그것이 곧 다대다 관계 구현입니다..
세부적으로 궁금하신 것이 있으시면 다시 댓글 달아주세요.

**Comment by kk0in** [comment]
@Jhvictor4 답변 감사합니다.
그러면, 연결 테이블에 user와 seminar에 대한 foreign key 2개만 작성하면 끝이라는 뜻이신가요?
class User와 class Seminar에서는 따로 foreign key를 작성할 필요가 없는지 헷갈립니다 ㅜㅜ

**Comment by Jhvictor4** [comment]
넵 세미나 1 자료 참고하시면, 한 쪽에서만 선언해서 사용한다고 언급드린 바가 있습니다.

**Comment by kk0in** [comment]
감사합니다!
