### ISSUE TITLE
(Django) debug toolbar 사용법 질문

### ISSUE THREAD

**Issue by footprinthere** [wafflestudio/19.5-rookies#463]
안녕하세요. 이번 과제 마지막 항목에 django debug toolbar를 사용해보라는 것이 있었는데, 어떻게 사용하는지를 알 수 없어 질문 남깁니다.

다른 항목을 모두 구현하고 나서 크롬 브라우저로 `http://127.0.0.1:8000/api/v1/seminar/`에 접속했더니 아래와 같은 화면이 나왔습니다.

![image](https://user-images.githubusercontent.com/84006386/134440383-3546401d-8a40-4a48-8964-96d3852c2c27.png)

사진을 보면 자동으로 `GET` method로 요청이 들어간 것 같은데, JWT token이 요청에 포함되지 않아 에러 메시지가 표시된 것으로 보입니다.
그런데 여기서 debug toolbar를 어떻게 활용할 수 있는 것인지를 잘 모르겠습니다.
debug toolbar 사용법을 검색해보았는데 코드 구현 단계에서 세팅을 하는 방법만 나와 있고 실제 웹페이지에서 어떻게 사용해야 하는지를 다룬 설명은 찾을 수 없었습니다.
그래서 브라우저에서 `GET`외에 다른 method로 요청을 보내려면 어떻게 해야 하는지를 검색해보았는데 역시 답을 찾지 못했습니다.

과제 11번 항목의 debug toolbar 부분에서 의도하신 것이 무엇인지, 이 단계를 완료하려면 debug toolbar를 어떻게 활용해야 하는지 힌트를 조금 주시면 좋을 듯합니다.

**Comment by Jhvictor4** [comment]
아 미처 생각하지 못했네요. JWT 와 함께 사용하려면 조금 커스텀이 필요합니다. 이 부분은 제가 세미나 때 함께 다루도록 하겠습니다.
일단 11번을 진행하실 때에는 

![image](https://user-images.githubusercontent.com/54717129/134456074-d769aaf1-b069-465d-9fb8-f61c40a57e45.png)

이렇게 해서 인증 절차를 무력화시키시면, 해당 api에서 어떤 쿼리가 나가는지 확인하실 수 있을 거에요. 지적 감사합니다 ㅜ

퇴근 후 톡방에도 공지해야겠네요.
