### ISSUE TITLE
[Spring Boot] Assginment2 Mapping Table 관련 질문드립니다.

### ISSUE THREAD

**Issue by moonpiderman** [wafflestudio/19.5-rookies#465]
## 🧑‍💻 Seminar Table에 관련한 Mapping Table을 생성할 때에 관하여 질문드립니다.

![image](https://user-images.githubusercontent.com/70942197/134475426-d6db59ac-19bb-4330-a210-0150b034c1e0.png)

- 위 그림과 같이 모델링하여 Mapping Table(SeminarParticipant, SeminarInstructor)들을 생성하고 빌드했는데, 아래와 같은 형태의 PK가 없는 새로운 테이블들이 생성되었습니다.

![image](https://user-images.githubusercontent.com/70942197/134471583-b80bce3c-13fc-4793-be0d-5883c51af4f8.png)

### 혹시 왜 이러한 테이블이 생성되었는지 알 수 있을까요?

**Comment by Jhvictor4** [comment]
SeminarParticipant, SeminarInstructor에서 ManyToManyField를 가지고 있으면 안됩니다.

Many-To-Many 관계를 RDB가 표현할 수 없기 때문에 연결 테이블을 두고 One-To-Many, Many-To-One으로 관계를 쪼개서 표현하는 것입니다. 

그런데 그림처럼 하시면, 쪼개지지 않고 연결 테이블 속의 ManyToManyField를 표현하기 위해 RDBMS가 연결-연결테이블을 만들어버립니다. 아래는 그 결과물입니다.

Seminar와 각 Profile에서 OneToMany를 선언하셨으니, 연결 테이블에서는 ManyToOne을 선언하셔야 올바른 다대다 관계를 구현할 수 있습니다.

**Comment by moonpiderman** [comment]
@Jhvictor4 제가 다이어그램에 실수가 있었습니다! SeminarParticipant, SeminarInstructor 에서 ManyToMany가 아닌 ManyToOne field를 가지고 있습니다!

**Comment by moonpiderman** [comment]
JoinColumn 어노테이션 사용으로 해결했습니다! 감사합니다!

**Comment by pullup-dip-burpee** [comment]
@moonpiderman 안녕하세요, 뒤늦게 이슈 보고 질문드립니다. 저도 테이블이 생성되는 문제가 있어서 저는 `@OneToMany`의 mappedBy 속성을 이용하고 `@JoinColumn`은 별도로 사용하지 않았습니다. 이 이슈를 보고 mappedBy 속성과 `@JoinColumn`을 붙이고 없애면서 보니 `@JoinColumn` 유무는 테이블 생성에 영향을 안 미치고 mappedBy가 영향을 미치는 것 같아서 혹시 @moonpiderman 님 해당 부분 코드 참조해 볼 수 있을까요??
