### ISSUE TITLE
학생의 프로필 수정이 잘 안되고 있습니다

### ISSUE THREAD

**Issue by Songmin17** [wafflestudio/19.5-rookies#466]
안녕하세요,

리액트 과제를 하는 와중에 학생의 프로필 수정이 제대로 안되고 있어서 질문을 올리게 됐습니다.
수정이 아예 안되는것은 아니지만 수정을 한번 할때마다 url을 다시 클릭하고 나서 한번씩 수정만 가능합니다.

예를 들어서 url이 다음과 같다면 
<img width="403" alt="Screen Shot 2021-09-24 at 3 32 48 AM" src="https://user-images.githubusercontent.com/69232608/134563963-f0f208f6-2468-4d94-89d0-2696bce36429.png">

p를 입력하게 된다면 선택이 안되고 다음과 같이 다시 클릭해야 하는 상황이 발생합니다.
<img width="413" alt="Screen Shot 2021-09-24 at 3 33 31 AM" src="https://user-images.githubusercontent.com/69232608/134564035-896e4854-d5b9-4dc9-9a2f-c94d70edfa2a.png">

학생 상세 페이지를 위한 컴포넌트에서는 context를 통해서 pageProfile라는 변수를 입력 받은 다음에 url을 수정하면 pageProfile이 수정되게 구현 했습니다:
Page.js 파일 line 75에서

                       <header className={"ProfileURLWrapper"} >
                            <span className={"HardcodedProfileURL"}>프로필</span>
                            <input className={"StudentProfileURL"} value={pageProfile}
                            onChange={(e) => setPageProfile(e.target.value)}
                            />
                        </header>
그리고 /students 페이지에서 학생을 클릭할때 pageProfile을 그 학생의 profile_img로 state를 바꾸게 구현했습니다.

Person.js 파일 line 9에서
Person component에서 이런식으로요:

const chooseEventHandler = () => {
        setChosen(item);
        ...
        setPageProfile(item.profile_img);
        setChosenPage(false);
    }

제 github에서 제일 최근에 올린 commit에서 코드를 볼 수 있습니다.
학생 상세 페이지로 라우팅 되면서 생기는 문제일까 싶은데, 문제의 원인과 해결법에 대해서 알려주시면 감사하겠습니다.

**Comment by woohm402** [comment]
레포 들어가 봤는데, 일단 `assign2` 브랜치에서 작업중이신 것 같은데 다음 사항들 반영 부탁드립니다.
1. `.gitignore` 재적용 (`.DS_Store` 와 `node_modules` 가 올라와 있습니다): #431 참고해서 진행해 주세요
2. `assignment1-app` 폴더 제거 부탁드립니다. 불필요한 폴더입니다.

코드 봤을 때는 딱히 문제가 없는 것 같고, 현상을 봐야 분석할 수 있을 것 같습니다. 배포하고 나서 url 알려주시면 확인해보겠습니다.

**Comment by woohm402** [comment]
현재 코드상, 이메일 필드를 수정했을 때 일어나는 일은 다음과 같습니다.
1. `inputEmailHandler` 실행
2. `setPageEmail` 실행
3. ContextProvider rerender
4. App.js rerender
    - `() => { return <PageRouter /> }` 함수 재생성
    - 기존 컴포넌트 언마운트
    - 기존 컴포넌트 다시 만들어서 마운트
5. 새로 마운트된 컴포넌트이니 당연히 focus 풀림

이런 상황입니다. 구조에서 실수를 하셔서 발생한 일인데, 근본적으로는 App이 렌더될 때마다 모든 컴포넌트가 언마운트됐다가 다시 마운트되는 라우트 구조의 미스입니다.

아래 코드를
```jsx
            <Route path={"/student/:" + id} component={() => {
                return <PageRouter />
            }} />
```

아래와 같이 변경하셔야 합니다. 차이점은 컴포넌트를 리턴하는 컴포넌트를 새로 만들어서 리턴하느냐 vs 그냥 컴포넌트를 리턴하느냐입니다.
```jsx
            <Route path={"/student/:" + id} component={PageRouter} />
```

또한 Context가 가지고 있는 state가 너무 많습니다. 키보드 한 번 칠 때마다 앱 전체가 리렌더되고 있는데, 이 부분은 코드 리뷰에서 다시 말씀드리겠습니다.

**Comment by woohm402** [comment]
@Songmin17 해결되셨나요?

**Comment by Songmin17** [comment]
코드를 저렇게 바꿔봤는데도 해결이 안 됐습니다 ㅠㅠㅠㅠ

**Comment by woohm402** [comment]
다시 보니 라우트 path에서 parameter도 잘못 설정하셨습니다. PPT 자료 확인하셔서, `Route`에서 url param 값을 어떻게 가져오는지 확인해보시겠어요? 모르시겠다면 질문주시기 바랍니다.

**Comment by woohm402** [comment]
@Songmin17 해결되셨나요?
