### ISSUE TITLE
Webstorm auto import problem

### ISSUE THREAD

**Issue by s-yeoyul** [wafflestudio/19.5-rookies#468]
안녕하세요 React 세미나 수강중인 윤상면입니다.

Webstorm이 잘 되다가 갑자기 auto import가 되지 않는 현상이 발생해서 해결 방안이 궁금합니다.
다행히 코드가 잘 작동하긴 하는데 영 불편하네요..
![스크린샷, 2021-09-24 12-01-31](https://user-images.githubusercontent.com/81800659/134611725-0915b2ca-4ec3-423b-a00a-d23956a111ac.png)
평소랑 비교해 보면 Projectfile란에 노란색 음영이 생겼고 코드에 글자 색깔이 없어진것 같아요.

**Comment by woohm402** [comment]
파일들이 프로젝트에서 제외된 것 같습니다.

제일 깔끔하게 해결하려면 그냥 `.idea` 날리고 처음 폴더 클론받았다 생각하고 웹스톰으로 다시 열면 됩니다.

**Comment by s-yeoyul** [comment]
저도 정상적인? 방법 구글링 열심히 해봤는데 찾기가 어렵네요 ㅠㅜ
일단 말씀해주신 방법 사용하니까 해결되었습니다! 감사합니다 :)
