### ISSUE TITLE
로그인 여부에 따른 라우팅 관련 질문드립니다!

### ISSUE THREAD

**Issue by hmlinnie** [wafflestudio/19.5-rookies#471]
## 요약
안녕하세요! 와플 루키 김혜민입니다.
현재 로그인 여부에 따라 페이지를 다르게 라우팅하려고 시도하고 있는데, 기능 구현에 어려움이 있어 질문드립니다!

## 상황

로그인 여부는 `login`에서 useState를 이용해 true/false로 관리하고 있습니다.

App.js
```
const App = () => {

    const {login} = useStudentContext();

    return (
        <BrowserRouter>
            <Switch>
                <Route exact path={"/login"} render={props => (<Login {...props} />)} />
                <AuthRoute exact login = {login} path={"/students"} render={props => <Main {...props} />}/>
                <AuthRoute exact login = {login} path={"/student/:id"} render={props => <StudentDetail {...props} />}/>
                <Redirect to={"/login"} />
            </Switch>
        </BrowserRouter>
    );
}
```
Auth.js
```
import React from "react";
import { Route, Redirect } from "react-router-dom";

function AuthRoute({ login, component: Component, render, ...rest }) {
    return (
        <Route
            {...rest}
            render={(props) =>
                login ? (
                    render ? (
                        render(props)
                    ) : (
                        <Component {...props} />
                    )
                ) : (
                    <Redirect
                        to={{ pathname: "/login", state: { from: props.location } }}
                    />
                )
            }
        />
    );
}
```

## 문제 내용

a) 로그인 되지 않았을 경우 로그인페이지로 리다이렉트 되는 것은 성공하였으나,
b) 로그인이 되었을 때 로그인 페이지로 가지 못하게 하고 `/students' 페이지로 리다이렉트하는 것에 어려움을 겪고 있습니다.

관련해서 블로그를 찾아보다가 위와 같은 방법을 발견해 사용하였는데,

1. 이 방법을 계속 사용해도 될지,
2. 사용해도 된다면 b 기능을 어떻게 구현할 수 있을지 궁금합니다!

b 기능과 관련하여 AuthRoute에 추가 조건을 입력해보고, login 페이지에 대한 새로운 auth 페이지를 만들어보기도 했으나, 적용이 되지 않았습니다ㅠㅠ

**Comment by woohm402** [comment]
엄밀히 말하면, 스펙상 지금 상태는 문제가 없습니다! (관련 이슈: #455 , #446 , #424 )

스펙은 다음과 같습니다.

> 로그인되었을 때 url이 잘못되었으면 `/students`로 보낼 것

주소창에 url을 입력하면 페이지가 다시 로드되므로 state가 초기화됩니다. 따라서 state로만 로그인 상태를 판별한다면, "로그인되지 않은 상태"로 보는 게 맞습니다. 때문에 `/login`으로 보내지는 게 맞습니다.

이를 해결하려면 자동 로그인을 구현해야 하지만, 자동 로그인은 이번 과제의 필수 스펙이 아닙니다. 때문에 자동 로그인을 사용해서 b기능을 구현하셨든 아니든 정답으로 처리할 예정입니다..만 최근에 확정드린 [과제 3 문서](https://github.com/wafflestudio/19.5-rookies/blob/master/react/seminar3/assignment.md)에 따르면 어차피 다음 과제에서 자동 로그인이 필수 스펙이 됩니다.

결론은, 구현하지 않으셔도 무방하지만, 구현하시려면 첫 줄에 언급드린 관련 이슈들 참고하셔서 구현해 주시면 됩니다!

**Comment by hmlinnie** [comment]
넵!! 궁금증이 잘 해결되었습니다. 감사합니다 :)
