### ISSUE TITLE
cloudfront에 배포 관련 상태가 표시되지 않습니다.

### ISSUE THREAD

**Issue by HyeongtaekOh** [wafflestudio/19.5-rookies#472]
세미나 ppt 자료에 있는 링크타고 aws 배포 s3 cloudfront 연동 작업을 그대로 한 것 같은데 배포가 잘 안 된 것 같습니다. 일단 aws 웹이 업데이트 돼서 해당 링크에서의 화면과 형식이 좀 달라서 뭘 잘못했거나 빠뜨렸는지 모르겠네요. 설명대로라면 cloudfront console의 상태 열이 2개(State, Status)여서 각각 활성화됨(Enabled)과 배포 완료(deployed)가 보여야되는 것 같은데 State 열만 표시되고 있습니다. 루트 디렉토리에 .env파일 만들어서 입력한 PUBLIC_URL 입력해도 '사이트에 연결할 수 없음' 오류만 뜨네요. 뭘 어디서부터 확인해야될지 모르겠습니다..
<br/>
![스크린샷, 2021-09-24 16-08-12](https://user-images.githubusercontent.com/86342741/134633578-bedb7c14-bbe9-44cd-be37-4e6580ce02e6.png)

**Comment by woohm402** [comment]
1. 배포된 url로 들어가셨을 때 어떻게 뜨시나요? 캡쳐해 주시기 바랍니다. s3 정적 배포 링크로는 접속 잘 되시나요?
2. 변경사항이 반영되는 데 시간이 좀 걸릴 수 있습니다. 저도 설정 한번 꼬였다가 6시간 동안 헤매고 포기하고 잤는데 일어났더니 해결된 기억이 있습니다
    - 이 경우 그냥 버킷부터 삭제하고 다시 만드시는 게 나을 수도 있어요
3. 일단 저도 @HyeongtaekOh 님께서 cloudfront 설정을 어떻게 하셨는지 확인할 수가 없어서ㅠㅠ 설정 내용 올려주시거나 하면 확인하는 데에 도움이 될 것 같습니다

**Comment by HyeongtaekOh** [comment]
뭐가 뭔지 잘 모르겠어서 답변이 힘드네요ㅜㅜ
배포된 url이라고 함은 제가 .env파일에 입력한 public url을 말씀하시는건가요 아니면 cloudfront에 적힌 배포 도메인 이름을 말씀하시는 건가요??

**Comment by woohm402** [comment]
일단 `.env`는 안 만드셔도 정상 작동해야 맞습니다. cloudfront에 적힌 배포 도메인 말씀드린거예요! d어쩌구

**Comment by HyeongtaekOh** [comment]
![스크린샷, 2021-09-24 16-41-36](https://user-images.githubusercontent.com/86342741/134637236-49ec11d2-6698-4e4a-bf93-81dd78bf68fa.png)
이렇게 오류 나네요,, s3 확인해보니까 버킷 객체 리스트에 제 리액트 앱 디렉토리 중 README 작성을 위해 넣어놓은 png 파일들 정도를 제외하고 하나도 업로드가 안되어 있는데 원래 제가 직접 웹 상에서 업로드를 해야되는건가요?

**Comment by woohm402** [comment]
보통 로컬에서 `aws-cli` 설치하고 스크립트 세팅해둔 다음에 `yarn build && yarn deploy` 해서 S3에 빌드된 파일을 업로드합니다

![image](https://user-images.githubusercontent.com/39977696/134639992-190a7506-ae39-406e-98a6-19bd814bec0d.png)

이 과정 거치셨나요?

**Comment by HyeongtaekOh** [comment]
과제 클론 폴더에서 npm run build 한 후에 클론 폴더에서 나와서 로컬 루트 디렉토리에서 aws-cli 설치했고 package.json에 스크립트 세팅도 했습니다.
build폴더와 s3 버킷과 비교해보니 파일들 이름, 개수 모두 동일합니다.(파일 용량이 정확히 같지는 않습니다만 561kb 파일이 548kb인 정도.)

**Comment by woohm402** [comment]
그렇다면
1. cloudfront에서 s3 버킷이 제대로 연결되어 있지 않음
2. s3 버킷이 열려 있지 않음
3. react-router-dom 때문

세 가지 중에 하나일 것 같습니다.
1. `(cloudfront url)/index.html` 접속해 보시겠어요?
2. S3 정책은 복붙하셨으면 아마 문제가 되진 않을 텐데.. 그래도 한번 확인은 해보시는 게 좋습니다.
3. 이 케이스가 톡방에서 아까 공지드린 케이스인데요, react-router-dom 쓸 땐 cloudfront 설정에 뭔가를 더 해 줘야 정상작동합니다. https://leonkong.cc/posts/til-react-router-s3-cloudfront.html 참고해 보시겠어요?

**Comment by HyeongtaekOh** [comment]
해결했습니다! 뭐든지 해보려고 이것저것 했는데
s3 버킷 권한에 public access 차단이 모두 활성화되어있던 거 비활성화로 바꿔보고, cloudfront 배포 새로 만들어보고, 
말씀해주신 3번 react-router-dom 관련 오류 페이지 설정해줬습니다. 
아마 말씀하신 오류 페이지 설정 때문에 되지 않았나 싶네요. 감사합니다!

추가 질문 있는데 지난 세미나 마지막에 필수 스펙으로 말씀하신 소스맵 안 보이게 하는 script 수정 작업은 잘된건지 확인을 어떻게 하면 될까요? 제 도메인 링크에서 개발자 도구-Sources에서 /static/js 디렉토리 안에 js 파일에 제가 쓴 코드로 보이는 게 없으면 된건가요??

**Comment by woohm402** [comment]
넵 맞습니다!

**Comment by HyeongtaekOh** [comment]
넵, 잘 마무리한 것 같습니다. 감사해요!
