### ISSUE TITLE
user.serializers.create 구현 시, 비밀번호 설정 관련 (과제2 - 2번)

### ISSUE THREAD

**Issue by esc5221** [wafflestudio/19.5-rookies#473]
## 질문
`user.serializers.create` 구현 시에, `#TODO`에 명시된 `2. 비밀번호 설정하기`는 구현하지 않는 것이 맞지 않나요?

<br>

## 상황

```python
def create(self, validated_data):
    # TODO (1. 유저 만들고 (ORM) , 2. 비밀번호 설정하기; 아래 코드를 수정해주세요.)
    user = None
    return user, jwt_token_of(user)
```
`user.seralizers`의 `#TODO`를 보면, 유저를  생성하고, 비밀번호를 따로 설정할 것을 요구하고 있습니다.
<br>

```python
from django.contrib.auth.hashers import make_password
```
`user.seralizers`에 상단에 보면 `make_password`가 기본으로 import가 되어 있어, 이를 이용해 아래와 같이 비밀번호를 hashing 하는 코드를 포함하여 `create`를 구현 후, postman상에서 signup 후 login을 시도해보았습니다.

```python
validated_data['password'] = make_password(validated_data['password'])
```
<br>

그런데, 이렇게 구현했을 때, login이 잘 되지 않는 것을 확인했고, 위의 `make_password` 를 사용한 비밀번호 설정 코드를 지운 후, validated_data를 그대로 사용하여 user를 만들도록 `create`함수를 구현해보았습니다.
<br>

![2](https://user-images.githubusercontent.com/37990664/134636518-3180271b-8c0f-4c7a-8e92-0b07f234578c.JPG)

postman으로 확인 결과, login이 잘되는 것을 확인할 수 있었고, db에도 password가 hashing이 잘 되어 들어간 것을 확인할 수 있었습니다.

<br>
<br>

```python
class CustomUserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('이메일을 설정해주세요.')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
```
user.serializers.py의 `create`에서 password hashing을 구현하지 않아도 되었던 이유는 user.models.py의 `_create_user`함수에서 `set_password`를 이용해 password를 hashing하기 떄문이었습니다. 그래서 `make_password` 를 사용하게 되면 hashing을 두번하게 되는 것 같았습니다.
<br>
이렇게 된다면, user.serializers.create의 TODO에 `비밀번호 설정하기`는 없어야 맞는 스펙인 것 같은데, 제가 구현을 다른 방식으로 한 건지 아니면 이런 식으로 하는 것이 맞는지 확인부탁드리겠습니다. 감사합니다!

**Comment by Jhvictor4** [comment]
create_user를 사용하면 기존 객체에 create 요청을 날리는 것에 더해 추가적으로 password 암호화, is_active=True 작업을 거칩니다. 구현은 자유롭게 하시면 됩니다. Manager를 잘 이용하면 비밀번호 설정도 묶어서 처리할 수 있겠죠? 

TODO는 참고용입니다. 루키 분들이 해싱되지 않은 비밀번호를 디비에 집어넣는 실수를 하시기도 해서 명시한 것입니다.

**Comment by esc5221** [comment]
TODO를 정확히 따라야하는줄 알았네요. 감사합니다..!
