### ISSUE TITLE
Django 과제2 - 하나의 serializer에서 2개 model 사용하는 방법 질문

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#474]
안녕하세요. 과제를 하다가 주어진 양식을 만족시키기 위해선 제목 그대로 하나의 serializer에서 2개의 model을 사용해야 하는 경우가 있는데, 이 부분 구현에 대한 힌트를 얻을 수 있을까하여 이슈를 남깁니다. 작년 이슈 중에 비슷한 https://github.com/wafflestudio/18.5-rookies/issues/182#issue-707060695 를 찾았으나 여기서 self.context를 이용하는 부분이 잘 이해가 되지 않습니다.. ㅜㅜ
읽어주셔서 감사합니다!

**Comment by Jhvictor4** [comment]
어떻게 잘 도와드려야 될지 모르겠는데..
https://stackoverflow.com/questions/37275270/django-rest-framework-how-serializer-context-works
여기 참고하셔서 보시면 될 것 같습니다.
