### ISSUE TITLE
학생을 추가했을 때도 바로 pie chart에 반영되어야 하나요?

### ISSUE THREAD

**Issue by kmsgm** [wafflestudio/19.5-rookies#475]
학생 수를 보여주는 pie chart를 만들던 중에 의문이 생겨 질문드립니다.

처음 화면이 로드될 때 default 데이터에 있는 학생 수는 pie chart에 반영이 되는데
학생을 새로 추가할 때도 바로 차트에 반영이 되도록 구현해야 하나요?

**Comment by woohm402** [comment]
넵 맞습니다!

**Comment by kmsgm** [comment]
넵 알겠습니다!
