### ISSUE TITLE
adapter의 viewHolder에서 삭제된 것을 roomDB까지 적용하는 방법에 대한 질문

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio/19.5-rookies#477]
안녕하세요.

RecyclerView에서 한 view의 버튼을 눌렀을 때 DB에서 그 부분을 삭제하는 부분을 만드는 중입니다.

이때 Adapter에서 
```
...
holder.deleteButton.setOnClickListener{  
...
}
``` 
함수를 통해서 버튼이 클릭되었을 때 뭔가를 하도록 할 수 있습니다.

그런데 db를 수정하려면 dao의 다음 함수를 써야 하고,
```
@Delete
suspend fun deleteTodo()
``` 
이는 거꾸로 따라가면 repository과 viewModel를 거쳐 mainActivity에서 사용하는 함수입니다.
그런데 adapter는 mainActivity의 하위에 있는데, 어떻게 adapter에서 mainActivity로 정보를 보내야 할 지 모르겠습니다.
mainActivity에서 recyclerView의 한 view의 button에 접근하는 방법도 시도해 봤는데 잘 모르겠네요.

**Comment by JuTaK97** [comment]
https://stackoverflow.com/questions/56826346/kotiln-pass-data-from-adapter-to-activity
https://abhinayme.medium.com/android-passing-data-from-adapter-to-activity-using-interface-8a6e9a13f6e0

두 곳을 참조하여, interface를 사용해서 callback하는 방식으로 구현할 수 있었습니다.
그런데 과제에서 의도하신 것과는 조금 다른 방식인가 싶네요. 어떻게 하는게 더 나을까요?

**Comment by veldic** [comment]
이부분을 직접 찾아보시라는 의도로 낸 부분이긴 한데 찾으신 interface도 좋은 방법 중 하나입니다. 다만 코드가 좀 복잡해지는 단점이 있을 수 있겠죠. <br>
제가 추천드리는 방법은 lambda function을 이용하는 방법입니다. 오늘 세미나에서 언급한대로 Id를 이용해 delete할 시 Adapter의 constructor 부분에 `onDeleteClickListener: (Int) -> (Unit)` 과 같은 lambda 함수를 받는 부분을 만들어서, mainActivity의 adapter 생성 부분에서 function을 만들어주는 방법입니다.

다음과 같은 형태가 만들어집니다.
```
class MainActivity ... {
  override fun onCreate() {
    ...
    adapter = todoAdapter(
      // (Int) -> (Unit) 인 lambda function, viewModel을 부를 수 있겠죠.
    )
  }
}
```

```
class TodoAdapter constructor( private val onDeleteClickListener: (Int) -> (Unit) ) : RecyclerView.Adapter<...> { ... }
```

Todo Class를 Delete 시 이용하시려면 (Int) 가 아니라 (Todo)를 사용하시면 됩니다.
