### ISSUE TITLE
React 앱을 S3, Cloudfront로 배포 시 css, js 파일을 가져오지 못합니다.

### ISSUE THREAD

**Issue by symoon9** [wafflestudio/19.5-rookies#478]
`yarn build` 후 생성된 `build/index.html`에서 css, js의 위치가 `/waffle-rookies-19.5-react-assignment-1/static/path/to/file`의 형식으로 생성돼 S3 루트 경로에 업로드 된 파일들을 가져오지 못하는 것 같습니다.
그래서 임시방편으로 `build/index.html`의 위치들을 `/static/path/to/file`로 바꿔주니 페이지가 제대로 로딩이 되기는 합니다. 하지만 media 파일이 있는 경우 css나 js내 경로도 수정해야 하고 자동 배포를 고려했을 때애도 좋은 방법은 아닌 것 같습니다. 혹시 이 문제를 해결할 좋은 방법이 있을까요?

참고로 제 `package.json`에는 `build`가 아래와 같이 정의되어있으며,
```json
"build": "GENERATE_SOURCEMAP=false react-scripts build"
```
S3 root는 이렇게 구성되어 있습니다.
![image](https://user-images.githubusercontent.com/68627571/134683492-31250406-8e41-4459-9538-2046f0e83bcf.png)

+) 제가 생각해 본 바로는 S3 root에 `/waffle-rookies-19.5-react-assignment-1` 폴더를 만들고 그 안에 `build/*`를 넣어주면 어느 정도 해결이 될 것 같습니다. 하지만 AWS의 각종 설정에서 `/index.html`을 활용하는 경우가 많기 때문에 다른 방법이 있으면 좋을 것 같습니다.

++) question 템플릿을 이용해서 그런가 label과 Milestone 수정이 안 되는 것 같네요...

**Comment by woohm402** [comment]
제가 했을 때는 경로가 상대경로로 잘 생성되던데, 혹시 환경변수나 웹팩 설정 등에서 따로 건드리신 게 있으신가요?

![image](https://user-images.githubusercontent.com/39977696/134697555-15fb504c-c473-45ec-8a4a-823aca9440a7.png)

**Comment by symoon9** [comment]
아하 원래 그런 것이 아니었군요...
찾아보니 제가 전에 github pages로 배포할 때 설정해뒀던 게 문제가 됐던 것 같습니다.
`package.json`의 `hompage` 항목을 없애니 해결되었습니다!
