### ISSUE TITLE
<select>의 기본값 설정 구현

### ISSUE THREAD

**Issue by ice1039** [wafflestudio/19.5-rookies#481]
### 요약
select 에서 저장된 값을 가진 option을 selected로 설정하는 좋은 방법

## 상황
학생 상세 페이지의 드롭다운을 구현 하던 중 option의 selected 값을 바꿀 좋은 방법을 생각해내지 못하고 있는데, 조언을 구할 수 있을까요?

## 문제 내용

제가 생각했던 방법은 다음과 같습니다.

1. useEffect에서 document.getElementById를 사용하여 렌더링 할 때마다 선택된 id를 가진 option에 selected 값을 채우는 방법
이 경우에는 먼저 selected 값을 추가하는 것 자체를 구현할 방법을 못 찾았고, 처음 학생 상세 페이지에 왔을 때 저장된 값을 select 하지 못해 큰 의미가 없는 것 같습니다.

2. option 태그에서 직접 삼항연산자를 활용해 학생의 전공과 option의 값이 같은 경우 selected를 채우는 방법

```
<option value="frontend" 
                id='frontend'
                selected={studentSelected.major === value ? '' : ''}
>frontend</option>
```

위의 코드와 같은 방법인데, value에 들어갈 값(option의 값)이 모두 태그 안에 있어 비교를 어떻게 하면 좋을지 헤매고 있습니다.

 감사합니다!

**Comment by woohm402** [comment]
`<input />`의 디폴트값과 크게 다르지 않습니다. 

```jsx
<input value={state} onChange={(e) => setState(e.target.value)} />
```

```jsx
<select value={state} onChange={(e) => setState(e.target.value)}>
  <option value={"frontend">frontend</option>
  <option value={"backend">backend</option>
  ...
</select>
```

리액트 사용하시면서, `document` 변수를 사용할 일은 없습니다!

**Comment by woohm402** [comment]
@ice1039 해결되셨나요?

**Comment by ice1039** [comment]
아 네! 확인이 늦었습니다. 감사합니다!
