### ISSUE TITLE
장고 과제2 - validated_data 관련 질문

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#482]
안녕하세요. 크게 두 가지 질문이 있는데,
1. 주어진 코드 상에서 validated_data 라고 되어있는 변수의 정확한 의미가 궁금합니다. 이번 과제에서 유저를 생성할 때, 첨부한 사진처럼 코드를 작성하고자 했는데, 이렇게하면, 'first_name' 과 'last_name' 이라고 한 부분에서 key error가 납니다. key error가 났다는 것은 애초에 validated_data에 first_name과 last_name이 없다는 것 같은데, 그렇다면, validated_data는 무엇을 포함하고 있는 정보인가요? (저 코드에서 마지막에 first_name=~, last_name=~ 이라고 된 부분을 빼면, request body에 first_name과 last_name을 포함시켜도 DB에 반영이 되지 않아서 어떻게든 넣어볼려고 하다가 계속 안되서 결국 질문을 드립니다 ㅜㅜ)

![스크린샷, 2021-09-25 04-04-12](https://user-images.githubusercontent.com/84329238/134728431-1e86fa34-ed23-4b13-925b-2f5e5206312f.png)

2. 실제로 DB에 중복된 user가 없음에도 불구하고 signup을 시도했을 때, IntegrityError가 발생하는 경우가 있는데, 이러한 일이 일어나는 것이 가능한건가요? 코드 순서대로 보면, 유효성 검사를 먼저하니까 409 error보다는 400 error가 먼저 날 것이라고 생각했기 때문에 이런 질문을 드리게 되었습니다.

![스크린샷, 2021-09-25 04-14-17](https://user-images.githubusercontent.com/84329238/134728377-ac1148fe-6ff0-4e4c-aeeb-5293a4c249c0.png)

읽어주셔서 감사합니다.

**Comment by Jhvictor4** [comment]
1. Serializer에서 객체를 저장할 수 있습니다. create_user 메서드가 kwargs 로 무엇을 받는지 체크하시는 것이 필요합니다.
2. serializer.save()에서 어떤 에러가 나는지 한번 확인해보시면 좋을 것 같습니다.

**Comment by kk0in** [comment]
serializer.save() 에서 나는 에러는 debug tool bar 이용해서 확인해보면 될까요?

**Comment by kk0in** [comment]
@Jhvictor4 그리고 1번 질문에 대한 답변은 validated_data가 Serializer에서 저장하는 객체에 해당한다는 말씀이신가요?

**Comment by Jhvictor4** [comment]
@kk0in 

답변이 늦어서 죄송합니다.

에러는 그러셔도 되고.. `Integrity error as e: `처리 후에 `format(e)` 해서 보셔도 됩니다.

몰랐는데 IntegrityError 처리가 그냥 DB 에러 상속이라 , 다른 곳에서 에러 나도 그냥 정합성 에러로 내려보내지네요. 확인이 늦어 죄송합니다. 저도 처음 알았어요;;

1번은 아뇨, serializer에서 validation이 끝나면 data로 보내준 값들을 정리해서 그대로 validated_data로 넘겨줍니다. 기본적으로 이 데이터들은 Model과는 크게 상관이 없는 파이썬 딕셔너리일 뿐입니다.

'first_name', 'last_name' 이 validation 과정에 잘 담겨 있는지, 커스텀 모델에서는 잘 선언되어있는지 등등을 확인하셔보몀ㄴ 좋을 것 같습니다.

**Comment by Jhvictor4** [comment]
아 1번 같은 경우 'first_name' , 'last_name' 이 UserCreateSerializer에 기본적으로 선언되어있지 않습니다. validation 과정에서 이러면 data 정리할 때 빼버립니다..

**Comment by kk0in** [comment]
감사합니다.
