### ISSUE TITLE
django 세미나2 과제 5번 질문

### ISSUE THREAD

**Issue by red1108** [wafflestudio/19.5-rookies#483]
## 요약
5번 테스크에서 PUT /api/v1/user/me/를 처리할때 어떻게 현재 접속중인 user을 알아내야 하나요?

<br><br><br><br>

## 상황
Task 5에서 PUT /api/v1/user/me/ 을 보여주기 위해서는 현재 접속중인 유저를 알아야 합니다. 하지만, 도저히 알아낼 방법을 모르겠습니다. sign up과 sign in을 모두 정상적으로 진행한 뒤, request.user을 출력해보아도 `AnonymousUser` 라고만 출력됩니다.
세미나1의 과제에서는 authenticate과 login 메서드를 사용해서 request.user을 통해 현재 접속중인 유저를 알아낼수 있었습니다.  
본 과제에서는 어떻게 해결해야 하나요?

**Comment by OTY-Math** [comment]
pk != 'me' 로 자기 자신인지 확인 후,
 user = request.user로 user를 받는 식으로 했는데,
100% 맞는지는 모르겠네요 ㅠㅠ

**Comment by Jhvictor4** [comment]
로그인 뒤에 요청에 토큰을 담아서 보내고 계신가요? 말씀해주신 방법대로 하면 나오는게 맞습니다.

**Comment by red1108** [comment]
JWT토큰이름에 오타가 있었습니다 ㅜㅜ
