### ISSUE TITLE
Spring 과제 2 - Seminar 생성 후 instructor 등록이 안됨

### ISSUE THREAD

**Issue by PJH6029** [wafflestudio/19.5-rookies#484]
## 요약

```POST /api/v`/seminars/```을 통해 seminar를 생성하고, currentUser를 담당 instructor로 지정했지만, response에 나타나지 않습니다.

<br><br><br><br>

## 상황

```SeminarController```의 ```addSeminar```에서 아래 함수를 다음과 같이 부르고, 리턴했습니다. ```createSeminar```는 seminar를 생성하여 저장하고, instructorProfile의 seminar field를 방금 생성된 seminar로 지정한 후 저장합니다. (seminar 저장과 instructorProfile 저장의 순서를 바꿔봐도 결과는 똑같았습니다)
```kotlin
val newSeminar = seminarService.createSeminar(createRequest, currentUser)
return SeminarDto.Response(newSeminar)
```
<br><br><br><br>

## 문제 내용

아래와 같이, ```newSeminar```의 instructor가 빈 리스트로 나옵니다.
![image](https://user-images.githubusercontent.com/46991571/134754184-41f2597d-b986-4708-a2bb-135aaeaf5b90.png)

다만, ```GET /api/v1/seminars/1/```을 통해 해당 세미나 정보를 받아오면, 이전에 등록된 instructor가 정상적으로 들어가있습니다.
![image](https://user-images.githubusercontent.com/46991571/134754237-c982804d-e768-4084-9bda-fc4481ead1b6.png)

장고의 ```refresh_from_db```등과 같이, db를 업데이트하거나, 이외의 이 문제를 해결할 수 있는 방법이 있을까요?

**Comment by gina0605** [comment]
저도 같은 문제를 겪었는데, 이를 EntityManger를 이용해 해결하였습니다. (참고: [stackoverflow](https://stackoverflow.com/questions/45491551/refresh-and-fetch-an-entity-after-save-jpa-spring-data-hibernate)의 질문 내용)
```kotlin
@Service
@Transactional
class SeminarService(
    private val seminarRepository: SeminarRepository,
    ...
    private val em: EntityManager
) {
    ...
    fun joinSeminar(user: User, id: Long, role: String): Seminar {
        ...
        em.refresh(seminar)
    }
    ...
}
```
[이 글](https://www.javabullets.com/access-entitymanager-spring-data-jpa/)에 보면 refresh를 위해 EntityManger를 사용하는 것의 의미가 적혀있습니다 (이 글의 방법은 복잡해서 사용 안했습니다)
<img width="810" alt="Screen Shot 2021-09-26 at 5 55 07 AM" src="https://user-images.githubusercontent.com/69783927/134785729-f9223290-32e4-4923-b775-fcf002f616e7.png">

**Comment by PJH6029** [comment]
감사합니다! 덕분에 해결했습니다!!
