### ISSUE TITLE
django 과제2 2번 jwt token 관련 질문

### ISSUE THREAD

**Issue by hansmaan** [wafflestudio/19.5-rookies#486]
## 요약
 "Authentication Credentials were not provided"에 관한 문제

<br><br><br><br>

## 상황
 signup이나 login을 하면 jwt token을 출력하는 것이 UserSignUpView에 구현되어 있는 것을 보았습니다. 그러나 signup이나 login을 postman을 통해 post해보면, request body에 무엇이든 상관없이 항상 "Authentication Credentials were not provided"가 출력됩니다. validate가 이루어지기 이전에, 문제가 발생했다는 것으로 보여집니다. 이 문제를 구글링해서 이곳 저곳 찾아봐서 코드와 아무리 대조해봐도 분명 구현이 된 것으로 보이는데 왜 안 되는 것인지 이해가 되지를 않습니다. 무엇이 문제인지 도움을 주셨으면 합니다..

<br><br><br><br>

## 문제 내용
 

![스크린샷, 2021-09-25 12-18-06](https://user-images.githubusercontent.com/88359757/134756160-b8f4e15e-4bd1-4aba-a6cd-08a229e8218d.png)

**Comment by Jhvictor4** [comment]
코드 최신화 되어있으신가요?

해당 문제는 permission check를 회원가입에서 해버려서, 유저가 생기기도 전에 ㄱ컷 당하는 상황입니다.
`permission_classes = (permissions.AllowAny, )` 를 통해 권한 설정이 정상적으로 이루어졌다면 일어나지 않아야 할 에렁입니다.

**Comment by hansmaan** [comment]
UserSignUpView에 permission_classes = (permissions.AllowAny, )가 명시되어 있습니디만, 무엇이 문제인 건지 모르겠습니다..

**Comment by Jhvictor4** [comment]
아..

url 다시 확인해보시겠어요?

api/v1/signup 입니다.

저렇게 하면 라우터 타고 넘어가는 과정에서 다른 뷰로 들어갑니다.
