### ISSUE TITLE
django 과제2 5번 year값 질문

### ISSUE THREAD

**Issue by minkyu97** [wafflestudio/19.5-rookies#487]
## 요약

5번에 보면 year에 대한 조건으로 다음과 같은 문장이 있습니다.
> year에 0 또는 양의 정수가 아닌 값이 오는 경우는 400으로 응답하며

여기서 의미하는 게 "[0 또는 양의 정수] 가 아닌 값" 인가요 아니면 "[0]또는 [양의 정수가 아닌 값]" 인가요?
해석에 따라 year < 0 일 때 오류가 나는지 year <= 0 일 때 오류가 나는지가 달라질 것 같습니다.

**Comment by Jhvictor4** [comment]
이건 자유롭게 구현해주시고 별 체크 안하겠습니다.

0 포함하는 의미이기는 합니다.

**Comment by minkyu97** [comment]
감사합니다!
