### ISSUE TITLE
django 과제2 6번 "정보가 없는 경우" 질문

### ISSUE THREAD

**Issue by minkyu97** [wafflestudio/19.5-rookies#488]
## 요약
6번의 2번째 동그라미를 보면
정보가 없는 경우 company를 ""라고 설정하라고 되어있고,
마지막에서 2번째 동그라미를 보면
0글자가 들어온 경우 company를 ""라고 설정하라고 되어있습니다.

그 말인 즉, company라는 키의 value가 0글자 일 때와 company라는 키 자체가 없을 때 모두 company값을 ""로 수정하라는 뜻으로 보이는데 제가 이해한 게 맞나요??
저는 "company" : "" 일 때는 company를 ""로 수정하고 company라는 키 값이 없을 때는 기존 company 정보를 유지하는 방향으로 코드를 짰는데 이걸 키 값이 없을 때도 company정볼르 유지하는 게 아니라 ""로 수정하도록 바꿔야하는지 여쭤보고 싶습니다.

**Comment by Jhvictor4** [comment]
네, 스펙에서는 덮어씌우는 행동을 기대하고 있습니다.

**Comment by minkyu97** [comment]
수정하겠습니다 감사합니다!
