### ISSUE TITLE
react 배포 시 일부 li text가 안보이는 문제

### ISSUE THREAD

**Issue by Songmin17** [wafflestudio/19.5-rookies#489]
## 요약
react 앱을 배포를 했는데 local host에서는 아무 문제 없이 텍스트가 보이던 부분이 일부는 사이트에서 안보입니다.
여러가지를 시도해봤지만 문제 원인을 파악하지 못해서 질문을 드립니다.
<br><br><br><br>

## 상황
학생 목록에서 학생을 선택하지 않았을때는 텍스트가 잘 뜨지만, 선택한 학생의 이름과 학년만 안 뜹니다. 데이터는 여전히 남아있지만 보이는 것에서 문제가 있어서 CSS를 여러번 고쳐봤지만 바뀐것이 없었어요.
<br><br><br><br>

## 문제 내용
이런식으로 문제가 생깁니다:
<img width="571" alt="Screen Shot 2021-09-25 at 8 12 56 AM" src="https://user-images.githubusercontent.com/69232608/134748398-9272c73a-19b3-4bc8-a4df-b0cf89948ca2.png">

도움 부탁드립니다~

**Comment by woohm402** [comment]
opacity: 1% 로 세팅해두신 것 같습니다. 직접 세팅하신 적이 없다면, css className이 겹쳐서 문제가 생겼을 수 있을 것 같습니다. className을 변경해 보시겠어요?

![image](https://user-images.githubusercontent.com/39977696/134770193-cfea54cb-92f0-4b25-8e60-0de062b8ea85.png)

**Comment by Songmin17** [comment]
방금 opacity를 바꾸고 다시 deploy 해보니까 문제가 해결이 됐습니다! 원래 opacity를 80%로 설정을 했는데 아예 지우니까 잘 작동해요.

**Comment by woohm402** [comment]
@Songmin17 넵 원래도 `80%`가 아니라 `0.8`로 세팅하셔야 됐을 거예요
