### ISSUE TITLE
배포 시 특정 창이 생성되지 않습니다.

### ISSUE THREAD

**Issue by JiyeonP** [wafflestudio/19.5-rookies#490]
## 요약

npm start를 사용해 로컬에서 실행했을 때에는 창들이 문제 없이 뜨는데, 배포한 도메인으로 들어가면 학생 추가 버튼을 눌렀을 때 창이 뜨지 않습니다.

<br><br><br><br>

## 상황

웹페이지 구현 후 배포하는 것까지 성공했고, 배포한 도메인 상에서 기능 문제가 발생했습니다.

<br><br><br><br>

## 문제 내용

웹 도메인: d3arh86hafsfhz.cloudfront.net

학생 추가 페이지 구현 방식:
(1) 학생 리스트가 있는 메인 페이지에서 아래와 같이 addStudent state를 만들고,
![2_MainPage](https://user-images.githubusercontent.com/66158942/134766790-e7a15b1a-6394-4a63-b759-9a941130bca8.JPG)

(2) addStudent가 false일 때 wrapper를, true일 때 wrapper.show를 className으로 가지도록 설정
![2_AddStudent](https://user-images.githubusercontent.com/66158942/134766811-1d005b44-9607-4cc3-af68-61580488ba24.JPG)

(3) 각각의 css는 아래와 같이 구현
![2_AddStudentCSS](https://user-images.githubusercontent.com/66158942/134766839-34705fe1-7fa5-4471-a29c-52d86b80537d.JPG)

도움 부탁드립니다!

**Comment by woohm402** [comment]
아래 #489 와 비슷한 케이스인 것 같습니다. opacity가 100%로 설정되어 있는데, [MDN](https://developer.mozilla.org/ko/docs/Web/CSS/opacity)에 따르면 100% 말고 1로 설정하셔야 합니다.

![image](https://user-images.githubusercontent.com/39977696/134770283-7cfbe390-03cb-4f09-a027-3bbd529093c1.png)

![image](https://user-images.githubusercontent.com/39977696/134770291-6a22e725-9d1e-4e89-b18f-98cfb2e3ea38.png)

**Comment by woohm402** [comment]
배포 부분의 문제는 아니고 빌드하면서 css의 opacity값이 100% -> 1 -> 1%로 기적의 변환이 일어난 듯 합니다

**Comment by JiyeonP** [comment]
해결되었네요. 감사합니다!
