### ISSUE TITLE
배포 후 새로고침/url 입력시 404 Not Found가 발생합니다

### ISSUE THREAD

**Issue by s-yeoyul** [wafflestudio/19.5-rookies#491]
## 요약

배포 후 새로고침/url 입력시 404 Not Found가 발생합니다.

## 상황

Localhost에서 새로고침/url 입력을 하면 각각 초기 /login path로 이동, 학생 상세 화면으로 이동이 정상적으로 작동하는데
[배포된 사이트](http://yeoyul-sample-deploy.s3-website.ap-northeast-2.amazonaws.com)에서 새로고침/url 입력을 하면 404 에러가 뜹니다.

[구글링의 조언대로](https://leonkong.cc/posts/til-react-router-s3-cloudfront.html) 에러 사이트를 모두 index.html로 보냈는데도 해결되지 않네요...

App.js의 Route 구조입니다
  ```
<div className={'App'}>
          <Switch>
              <Route path='/students' component={MainPage} exact/>
              <Route path='/student/:id' component={DetailPage} exact/>
              <Route path='/login' component={LoginPage} exact />
              <Redirect to={'/students'} />
          </Switch>
      </div>
 ```

**Comment by woohm402** [comment]
S3 버킷의 주소가 `http://yeoyul-sample-deploy.s3-website.ap-northeast-2.amazonaws.com/` 이십니다. 이거 그냥 온라인에 올라가 있는 폴더라고 생각하시면 되는데요, 아래 url들 한번 접속해 보시겠어요?

http://yeoyul-sample-deploy.s3-website.ap-northeast-2.amazonaws.com/manifest.json
http://yeoyul-sample-deploy.s3-website.ap-northeast-2.amazonaws.com/favicon.ico
http://yeoyul-sample-deploy.s3-website.ap-northeast-2.amazonaws.com/robots.txt
http://yeoyul-sample-deploy.s3-website.ap-northeast-2.amazonaws.com/logo512.png

마지막으로 아래 url 접속해보시기 바랍니다.
http://yeoyul-sample-deploy.s3-website.ap-northeast-2.amazonaws.com/index.html

그리고 로컬의 `build/` 폴더에 있는 파일들과 비교해 보시면, 각각 똑같다는 게 보이실 거예요. 그러니까 url은 일단 `(S3 버킷 주소)/path/to/file` 로 인식됩니다. 그래서 `

**Comment by woohm402** [comment]
그래서 이걸 404가 떴을 경우 `/index.html` 로 리다이렉트되게 처리하면 해결이 되긴 하는데, 보통 그 작업을 S3단에서 처리하지는 않고 cloudfront단에서 처리합니다. cloudfront 배포까지 완료해 보시겠어요?

**Comment by s-yeoyul** [comment]
아 제가 배포 도메인을 http://yeoyul-sample-deploy.s3-website.ap-northeast-2.amazonaws.com/ 로 착각했네요 ㅎㅎ
CloudFront에서 얻은 [배포 도메인](https://d1l8z1i7pky4jo.cloudfront.net) 이용하니까 정상 작동하는 것 같습니다!!
감사합니다 !!
