### ISSUE TITLE
Django assignment 2 9번 질문

### ISSUE THREAD

**Issue by hansmaan** [wafflestudio/19.5-rookies#492]
## 요약
 9번에서 /api/v1/seminar/{seminar_id}/user/ urls를 어떻게 받아야 할지 모르겠습니다.

<br><br><br><br>

## 상황
 urlpatterns 속에 path를 이용하여 url을 적용해보았습니다. path(seminar/<pk>/user/, ~~)을 사용하려 했는데, 이렇게 사용할 시에 path 옆에 있는 함수에 pk가 대입된다는 사실을 구글링을 통해 알게 되었습니다.
 
![스크린샷, 2021-09-26 00-30-58](https://user-images.githubusercontent.com/88359757/134777064-e693ca9b-401d-40d2-9830-a10fda70b418.png)

그래서 이를 확인해보고자, pk를 입력받은 그대로 출력하고 status 200을 산출하는 함수 cal을 정의하였습니다. 그랬더니 (csrf token missing or incorrect)라는 문구가 나오며, 403 forbidden이 산출되었습니다. 이에 csrf token을 넣어주었더니 사진과 같이 internal_server_error가 납니다..

<br><br><br><br>

## 문제 내용
 위와 같이 path를 받는 한, pk를 전달할 수 있는 함수가 존재해야 하는데, 어떻게 인자를 받아야 하는지를 모르겠습니다... 이 방법 외에 router를 이용한 방법을 시도해보려 했으나, 구글링을 해보았을 때, <pk>와 같은 인자를 받는 url을 register하는 경우는 보지 못했습니다. 아무래도 router와 urls에 대한 근본적인 이해가 부족하기 때문에 이러한 문제가 생긴 것이라 생각하는데, 조금 도와주신다면 정말 감사하겠습니다..!

**Comment by graviol** [comment]
저도 비슷한 문제를 겪었었는데요, 저는 데코레이터를 이용하고 detail=True를 설정하였더니 pk를 전달하면서도 9번에서 요구하는 함수를 구현할 수 있었습니다! urlpatterns를 통해서도 할 수 있을지도 모르겠으나 저처럼 그 부분을 건드리지 않고서도 구현할 수 있을 것 같습니다 : )
