### ISSUE TITLE
Django Toolbar 사용법 질문

### ISSUE THREAD

**Issue by yabsed** [wafflestudio/19.5-rookies#493]
## 요약

Django Debug Toolbar가 보이지 않음

## 상황

나머지 문제를 어느 정도 해결하고 http://127.0.0.1:8000/api/v1/seminar/ 에 접속했더니 다음과 같았습니다

<img width="1440" alt="스크린샷 2021-09-26 오전 12 43 15" src="https://user-images.githubusercontent.com/14042027/134777453-cf38e061-dc4b-4f75-8f19-ea0946ac8e44.png">

Django Debug Toolbar가 보이지 않는 것이 기본적인 상황인가요?

## 문제 내용

urls.py

<img width="944" alt="스크린샷 2021-09-26 오전 12 53 39" src="https://user-images.githubusercontent.com/14042027/134777679-a99345ff-a290-4f9e-9076-c9adf11980df.png">

pip3 list
<img width="1230" alt="스크린샷 2021-09-26 오전 12 49 24" src="https://user-images.githubusercontent.com/14042027/134777693-c74e2897-ee83-48da-8d41-b8f19eeafac2.png">

settings.py
<img width="584" alt="스크린샷 2021-09-26 오전 12 53 00" src="https://user-images.githubusercontent.com/14042027/134777703-86028ac9-94e5-4322-a4b2-2b13909ec041.png">

<img width="307" alt="스크린샷 2021-09-26 오전 12 53 18" src="https://user-images.githubusercontent.com/14042027/134777707-4583c631-3ae3-4c8a-bb41-b649cdaa33b7.png">

**Comment by Jhvictor4** [comment]
환경변수 DEBUG_TOOLBAR가 설정되어있나요?

**Comment by yabsed** [comment]
https://github.com/wafflestudio/18.5-rookies/issues/112

`DEBUG_TOOLBAR = True`
써서 해결된 걸 보면
환경변수가 추가되지 않았던 게 문제였던 것 같습니다. 

<img width="1440" alt="Using Toolbar 😁" src="https://user-images.githubusercontent.com/14042027/134779479-d45a5f83-7e42-4b10-a291-d6b451654d83.png">
![Uploading Using Toolbar 😎.png…]()
