### ISSUE TITLE
과제2의 UserSeminar 모델에서 joined_at과 created_at의 차이점이 궁금합니다.

### ISSUE THREAD

**Issue by jhm1313** [wafflestudio/19.5-rookies#494]
저는 user와 seminar가 관계를 갖는다는 것을 의미하는 모델이 UserSeminar 모델이라 생각했습니다만,

이렇게 되면 결국 UserSeminar가 생성되는 시점(created_at)은 user와 seminar가 관계를 갖게 되는, 즉 user가 seminar에 참석하는 시점(joined_at)과 같지 않나요?

두 개의 column이 서로 구분되어야 하는 이유를 잘 모르겠는데, 어떤 의미상의 차이가 있는지 알고 싶습니다!

**Comment by graviol** [comment]
joined_at이 결국 created_at의 값을 가져오는 것이라고 생각할 수 있습니다. 그러나 joined_at 자체가 column은 아닙니다! 혹시 column을 새로 만드신건가요?
userserializer에서의 joined_at은, created_at의 값들을 읽어오도록 할 수 있습니다.

**Comment by jhm1313** [comment]
@graviol 아하 저도 joined_at의 값으로 created_at의 값을 읽는 형식으로 구현하다가 문득 joined_at과 created_at을 독립적인 column으로 만들어야하나? 하는 의문이 들고 둘의 이름이 달라서 살짝 헷갈리는 바람에 질문했었습니다 ㅎㅎ
답변 감사합니다!
