### ISSUE TITLE
Django 과제 2 - 스펙 상세 관련 질문 (university, company)

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#495]
안녕하세요! 이번 장고 과제2의 5, 6번에서 university와 company의 경우, 정보가 없는 경우에 대해서는 DB에 ""로 표시하라고 나와있는데, 정보가 없는 경우라는 것이, request body에서 {"university":""}와 같이 작성한 경우와 아무것도 없이 {}처럼 작성한 경우, 모두를 포함하는 건지 궁금합니다! 
저는 model.py를 작성할 때, participant profile과 instructor profile을 모두 blank=True 옵션만 주었기 때문에, 위 설명에서 후자처럼 request body를 작성하면, 해당 필드는 null이 될 수 없다며 error가 납니다. 그래서 null=True인 옵션을 추가해주면, 똑같이 후자의 경우, DB에 null이라고 표시가 되어있어서 어떻게 해야할지 모르겠습니다.
읽어주셔서 감사합니다.

**Comment by Jhvictor4** [comment]
db에 null이 아닌 빈 값으로 들어가도록 처리를 해주셔야 합니다. blank, default, null 옵션을 잘 참고해주세요.

**Comment by kk0in** [comment]
넵 감사합니다!

**Comment by kk0in** [comment]
@Jhvictor4 이슈를 다시 봤는데, 결과적으로 **제가 설명드린 모든 상황**(_request body에 "university"가 있는 경우, 아예 아무것도 없는 경우_)에 대해서 DB에는 university와 company가 모두 null이 아닌 빈 값으로 들어가야 하는건가요?
