### ISSUE TITLE
Spring 과제 2 - SigninAuthenticationFilter에서 UserController 호출 방법

### ISSUE THREAD

**Issue by PJH6029** [wafflestudio/19.5-rookies#500]
## 요약

SigninAuthenticationFilter에서 successfulAuthentication이 호출되었을 때, UserController의 signin() 메소드를 호출하고 싶습니다.

<br><br><br><br>

## 상황

successfulAuthentication에서는 response에 content 없이 header만 추가해주는 것으로 구현되어있는 것 같습니다.
이걸 UserController에  signin을 정의한 후, 호출해서 추가적인 구현을 하고싶은데, 혹시 방법이 있을까요??

**Comment by Hank-Choi** [comment]
AuthenticationFilter가 controller로 가는 길을 막고 있는 방식이라 원하시는 방법은 힘들 듯 합니다. 
controller단에서 유저 로그인을 처리하려면 BCrypt 암호화를 이용해 패스워드 매칭 확인하는 로직을 포함해 signin을 직접 구현하신 후
프록시 패턴을 사용해 각 api마다 유저 인증로직이 돌도록 하는 방법이 있을 듯 합니다.
하지만 spring security를 이용하시는 것이 더 좋을 것 같고 content를 추가하고 싶은 경우에는 successfulAuthentication 함수에서  ServletResponse.getOutputStream()  ServletResponse.getWriter() 등을 이용해 body를 추가하는 것이 좋을 듯 합니다.

**Comment by PJH6029** [comment]
넵 감사합니다. 참고해서 해보겠습니다!
