### ISSUE TITLE
세미나 1 PR 후 브랜치 컨벤션을 잘못 적용한 것 같습니다.

### ISSUE THREAD

**Issue by HyeongtaekOh** [wafflestudio/19.5-rookies#501]
## 요약

지난 세미나 2 과제 브랜치 컨벤션 관련해서 https://github.com/wafflestudio/19.5-rookies/issues/386 이슈 따라서 진행했었는데 main 브랜치로 rebase하는 과정에서 문제가 생긴 것 같아 질문드립니다. 어떤 것 때문에 문제가 생긴 것인지 몰라 최대한 지난 세미나 1 과제 제출 이후에 수행했던 대로 최대한 빠짐없이 적어보겠습니다.

## 상황

우선 위 이슈 내용을 잘못 이해해서 몇 가지 잘못 수행한 부분이 있었던 것 같습니다.
- 세미나 1 과제 PR에 대한 코드 리뷰를 받은 이후에 해당 PR을 머지하지 않고 이슈에 적어주신 커맨드를 수행했던 것 같습니다. 
(저 이슈글이 올라오고 며칠 안돼서 했던 것 같아서 기억이 정확하지 않을 수 있습니다. 죄송해요ㅜ)
![스크린샷, 2021-09-26 17-32-37](https://user-images.githubusercontent.com/86342741/134800215-6052adbc-d4cd-419b-9ad4-d2b1add8b37e.png)
그 상태로 세미나 과제 2 PR 할 때까지 seminar 1 머지를 안 하고 진행했습니다.
- 리뷰에서 언급한 스펙 오류 및 코드 수정사항 2가지가 있었는데 비교적 간단히 고칠 수 있었던 1번 오류를 수정하고 새로운 assignment-2 브랜치에 커밋하지 않고 다시 assignment-1 브랜치에 머지했습니다. (2번 수정은 assignment-2에 커밋했습니다.)
1. 한글+영어 혼합 이름 입력 가능 오류
2. detail view 관련 컴포넌트 위치로 인한 어색한 ui 오류

그 외 git 관련 했던 것들
- .gitignore 파일이 어쩌다보니 날아서 node_modules가 git에 올라가는 바람에 .gitignore 적용해줬습니다.
- 세미나 1 README 파일 오타가 보여서 수정을 github 웹에서 하느라 `git pull origin master` 한 번 해줬었습니다.

그 후에는 세미나 2 과제하면서 과제 내용 assignment-2 브랜치에 커밋만 반복하다가 배포까지 완료하고 PR 생성해서 제출 했습니다.

## 문제 내용

 좀 아까 리뷰어분께서 세미나 1 PR 머지 부탁하셔서 머지하고 다시 issue에 있는 위 커맨드 수행하던 중에 
```
git checkout main
git pull
git checkout assignment-2
git rebase main
git push --force
```
`git rebase main` 과정에서 이런 오류가 떠서
```
fatal: It seems that there is already a rebase-apply directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr ".git/rebase-apply"
and run me again.  I am stopping in case you still have something
valuable there.
```
다시 질문 드렸고 아래 커맨드 입력하라고 하셔서
```
git rebase --abort
git checkout main
git pull
git checkout assignment-2
git rebase main
```
입력했는데 이번엔 `git checkout assignment-2` 과정에서 이런 문구가 떴습니다.
```
브랜치가 'origin/assignment-2'보다 17개 커밋 뒤에 있고, 앞으로 돌릴 수 있습니다.
  (로컬 브랜치를 업데이트하려면 "git pull"을 사용하십시오)
```
`git rebase main` 해보니 이런 에러가 뜹니다.
```
먼저, 맨 위에 있는 작업을 다시 수행하도록 헤드를 되돌립니다...
적용하는 중: add arrow icon svg
인덱스 정보를 사용해 기본 트리를 다시 만듭니다...
M	src/component/StudentTable/Student/Student.css
M	src/component/StudentTable/Student/Student.js
베이스 패치 적용 및 3-방향 병합으로 대신합니다...
자동 병합: src/component/StudentTable/Student/Student.js
충돌 (내용): src/component/StudentTable/Student/Student.js에 병합 충돌
자동 병합: src/component/StudentTable/Student/Student.css
충돌 (내용): src/component/StudentTable/Student/Student.css에 병합 충돌
error: 변경 사항에서 병합하는데 실패했습니다.
패치가 0001 add arrow icon svg 위치에서 실패했습니다
힌트: 'git am --show-current-patch'를 사용하여 실패한 패치를 볼 수 있습니다
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```
현재 보니까 과제 클론 디렉토리가 머지한 assignment-1 브랜치 버전으로 pull되어 있고 세미나 2 PR에서 branch에 conflicts가 발생하고 있다고 나옵니다
![스크린샷, 2021-09-26 18-05-28](https://user-images.githubusercontent.com/86342741/134801232-b1af6154-7e7c-438f-bbf1-bae27d0d9c85.png)

**Comment by woohm402** [comment]
먼저 rebase가 무엇인지 이해하시면 좋을 것 같습니다. [이 블로그](https://brunch.co.kr/@anonymdevoo/7) 에 비교적 쉽고 깔끔하게 설명되어 있습니다.

해당 글에 나와있다시피 커밋을 재정렬하는 과정입니다. 따라서 코드 상태에 따라, 깔끔하게 재정렬할 수 없을 경우 (현재 브랜치와 타겟 브랜치가 동일한 부분을 수정했을 경우) conflict가 발생할 가능성이 있습니다.

이때 목표는 타겟 브랜치 (main) 을 현재 브랜치 (assignment-2) 밑에 재정렬하는 거기 때문에, 현재 브랜치에서 문제가 생긴 커밋들을 다시 적용해야 합니다.

에러가 뜰 때 git status를 찍어 보면 `both modified` 라며 파일 이름들이 뜰 거예요. 그럼 그 파일을 열어보면 아래처럼 난리가 나 있습니다.

```js
<<<<<<< HEAD
어쩌구
======
저쩌구
>>>>>>> main
```

이때 적당히 체크해서 원하는 방향으로 코드를 수정하면 됩니다.

그런데 리베이스가 꽤나 위험한 명령어라서.. 아무래도 줌으로 한번 봐드려야 할 것 같습니다 (이렇게까지 커밋이 난리나있을 줄 몰랐는데 생각보다 많은 일이 있었나 보네요 😅 )

**Comment by HyeongtaekOh** [comment]
와장님 도움으로 해결됐습니다 :)
