### ISSUE TITLE
(Django) 서버 연결이 안 되는 현상

### ISSUE THREAD

**Issue by footprinthere** [wafflestudio/19.5-rookies#502]
## 요약
터미널에서 runserver를 실행한 후 postman이나 크롬으로 접속하면 연결이 안 되는 경우가 있는데 해결책을 알고 싶습니다.

<br><br><br><br>

## 상황

터미널에서 `$ python manage.py runserver`를 실행해 서버를 동작시킨 후 크롬 브라우저로 URL을 입력해 접속했습니다.

<br><br><br><br>

## 문제 내용

![image](https://user-images.githubusercontent.com/84006386/134805202-c1cdb5e2-2ffa-4510-8c1a-ff1846f64f47.png)
![image](https://user-images.githubusercontent.com/84006386/134805165-37f39a75-2b70-4fbd-84e5-fc4178146ddd.png)
![image](https://user-images.githubusercontent.com/84006386/134805193-a1fe7d02-e081-4389-8629-822e711c983a.png)

터미널을 보면 정상적으로 서버가 작동하고 있는 것 같은데, 연결을 시도하면 연결할 수 없다고 나옵니다.
종종 이런 경우가 발생했는데 그럴 때마다 컴퓨터를 재부팅했더니 다시 연결이 잘 됐습니다.
그래도 매번 재부팅을 할 수도 없고 원인도 알고 싶어서 찾아보았는데 찾기가 어려워서 질문 드립니다.
혹시 예상되는 원인이 있을까요?

`$ sudo service mysql start`를 입력해 MySQL을 정상적으로 실행한 뒤 서버를 동작시켰습니다.

**Comment by Jhvictor4** [comment]
개발환경이 어떻게 되시는지 알 수 있을까요?

**Comment by footprinthere** [comment]
@Jhvictor4 Windows10 사용중이고 WSL2로 Ubuntu에 연결해서 쓰고 있습니다.
