### ISSUE TITLE
django Debug Toolbar 안보이는 문제

### ISSUE THREAD

**Issue by tjdqhrdkdl** [wafflestudio/19.5-rookies#503]
## 요약

DEBUG_TOOLBAR = true로 설정했음에도 debug toolbar가 보이지 않습니다. 환경 설정을 잘못한 건가요?

<br><br><br><br>

## 문제 내용

pycharm에서 환경변수를 true로 설정했으나, 이때는 디버그 툴바가 보이지 않았습니다.
이후 settings.py에서 직접 DEBUG_TOOLBAR = True로 설정하니 작동이 됩니다.
제가 가상환경 위에서 작업하지 않고 있다는 뜻인 건가요? 무슨 문제인지 궁금합니다!

**Comment by Jhvictor4** [comment]
파이참에서 어떻게 설정하셨던 건지 확인할 수 있을까요?

**Comment by tjdqhrdkdl** [comment]
![스크린샷, 2021-09-27 00-46-55](https://user-images.githubusercontent.com/81847778/134814815-c2b6a22c-7720-4b5a-8693-9014d9041b96.png)
이렇게 설정했습니다. 이때는 디버그 툴바가 안보이다가
![스크린샷, 2021-09-27 00-48-04](https://user-images.githubusercontent.com/81847778/134814834-6fa4066b-49f7-471b-a274-a23383ec56a9.png)
이렇게 아주 바꿔버리니까 툴바를 볼 수 있었습니다.

**Comment by Jhvictor4** [comment]
순서에 따라 좀 달라질 수 있나 싶기도 한데 내일 확잉 후 답변 드릴게오
