### ISSUE TITLE
리액트 useEffect 사용시 missing dependency / maximum update depth exceeded 문제

### ISSUE THREAD

**Issue by andhl204** [wafflestudio/19.5-rookies#505]
안녕하세요, 과제2에서 구현해야 했던 학생 이메일/전공/프로필링크 저장 기능 관련 질문입니다.
기존의 저장된 내용을 받아오고, 사용자의 인풋을 받아서 저장하는 데 이용하기 위해 다음과 같이 코드를 작성했습니다.

```   
 const [savedInputs, setSaved] = useState({
      emailInput: "",
      majorInput: "",
      profileImgInput: "",
  });

  useEffect(() => {
      setSaved({
          emailInput: emailId,
          majorInput: major,
          profileImgInput: profileImg,
      });
  }, [id]);

  const { emailInput, majorInput, profileImgInput } = savedInputs;
  const onSavedChange = event => {
      const { name, value } = event.target;
      setSaved({
          ...savedInputs,
          [name]: value
      });
  };
```

이렇게 했을 때 기능에는 문제가 없습니다. 다만 useEffect를 사용할 때 missing dependency가 있다는 경고가 뜹니다. 그래서 emailId, major, profileImg를 추가하면 maximum update depth exceeded라는 경고가 뜨는데, 어떻게 해결해야 할지 모르겠습니다.

**Comment by woohm402** [comment]
앞 부분 코드를 봐야 알겠지만, 지금 코드가 나쁘지 않은 걸로 보입니다. missing dependency 경고를 무시하시면 됩니다!

https://sgwanlee.medium.com/useeffect%EC%9D%98-dependency-array-ebd15f35403a

dependency array에 대해 정확히 이해하시면 도움이 될 거예요

**Comment by woohm402** [comment]
@andhl204 해결되셨나요?

**Comment by andhl204** [comment]
앗 네 감사합니다!
