### ISSUE TITLE
ViewLoad 의 비동기 처리 방법

### ISSUE THREAD

**Issue by eomiso** [wafflestudio/19.5-rookies#509]
## 요약
Server로부터 response를 받은 시점에 view를 load하는 방법이 없을지 궁금합니다!

<br><br><br><br>

## 상황
ios assignment 2에서, `baseUrl + member/{id}` 로  Get Request를 날려야 하는 2번째 화면을 구현하고 있었습니다. 구조가 MainViewController → MemberViewController → LectureViewController 이런 식인데, MainViewController에서 `baseUrl+ member/`로 리퀘스트를 날리고, MemberViewController에서 `baseUrl + member/{id}`로 리퀘스트를 날리도록 구현했습니다.

<br><br><br><br>

## 문제 내용
이때 문제가 발생하는게 , 수강목록 에 대한 TableView는 reloadData() 함수를 통해서 비동기 업데이트가 잘 처리 되는데, 나머지 (image, 이름, 팀명) 등은 비동기 처리를 해줄 방법이 없더군요.  그 결과 아래처럼 제가 디폴트로 설정해 놓은 값들이 Label들에 나타나게 됩니다.
![image](https://user-images.githubusercontent.com/17143087/134822874-f0ffb724-0997-4b51-839f-82560d1987e4.png)

비동기 처리를 해줘서 이름, 사진이 도착했을 때 view를 띄워줄 방법이 없을까요? 
그냥 MainViewController에서 request를 받아와서 MemberViewController를 NavigationController에 푸쉬해주는 시점에 정보를 넘겨 주는 방법만이 답인건가요? 또는 그전까지 로딩화면이 뜨게 하는 방법이 있을 것 같더군요... 그런데 그러면 ViewDidLoad() 부분을 어떻게 처리해줘야 하는지 찾아도 잘 안나오는 듯해서 질문 드립니다.

**Comment by JSKeum** [comment]
HTTP request는 비동기로 이루어지기 때문에, request 작업이 끝난 후 view를 업데이트하는게 맞습니다. request 비동기 작업이 끝나기 전에는  placeholder의 값이 뜨는게 맞지요. fetch한 데이터에 따라 view를 바꾸기 위해서는 request 클로저 안에 view의 값들을 업데이트하는 로직을 넣으면 되지 않을까요? 

그리고 MemberViewController 에서 `baseUrl + member/{id}` request를 보내는게 좋습니다!
