### ISSUE TITLE
recyclerview 가 제대로 안보입니다..

### ISSUE THREAD

**Issue by Whiteppanda** [wafflestudio/19.5-rookies#511]
![image](https://user-images.githubusercontent.com/50572383/134846874-5ff01761-129c-4e43-9445-48c1c65032e9.png)
![image](https://user-images.githubusercontent.com/50572383/134847086-ec05e350-1b62-40a6-a6c8-10cdf37a9aea.png)

recyclerview로 todo들을 보일려고 할때 위 코드처럼 했는데 폰으로 연결해서 앱을 실행시켯을때 내용이 전혀 보이지 않고 done 버튼만 보이게 됩니다... 뭐가 문제인지 도저히 모르겟네요 ㅠㅠ
위에가 adpater 이고 아래가 mainActivity입니다..

**Comment by veldic** [comment]
혹시 다크 모드 사용하시면 배경과 글자 색이 모두 흰색으로 되어서 보이지 않을 수 있어요.

**Comment by Whiteppanda** [comment]
![SmartSelect_20210927-210836_Assignment2](https://user-images.githubusercontent.com/50572383/134905518-84ad85e4-c5d7-4878-b920-07d91d3dd8f2.jpg)
음.. 딱히 다크 모드도 아닌데 이렇게 뜹니다.
데이터가 안들어갔다는 의미일까요

**Comment by veldic** [comment]
혹시 xml 파일 수정하신 것 있으실까요?

**Comment by Whiteppanda** [comment]
제가 skeleton code를 보면서 제꺼에 쓴거라 recyclerview에 background 설정이 빠져있긴했습니다.
다시 실행시켜도 저런식으로 뜨네요
