### ISSUE TITLE
과제 2 제출 시 directory 구조

### ISSUE THREAD

**Issue by esc5221** [wafflestudio/19.5-rookies#513]
## 요약
과제 2 제출 시 directory 구조에 대한 질문
<br>

## 상황

과제 2를 제출 시에, 아래와 같은 directory 구조를 갖추어야 한다고 되어 있습니다.
```
/README.md
/.gitignore
/waffle_backend/manage.py
/waffle_backend/waffle_backend/*
/waffle_backend/survey/*
/waffle_backend/user/*
...
```

<br>

그런데, 과제2의 skeleton 코드는 아래와 같은  directory 구조를 가집니다.
```
/README.md
/.gitignore
/manage.py
/waffle_backend/*
/survey/*
/user/*
...
```
<br>

master에서의 변경사항을 추적하기 위해선 skeleton 코드의 directory 구조에 맞추는 것이 좋을 것 같은데, 확인 부탁드리겠습니다. 감사합니다.

**Comment by Jhvictor4** [comment]
지적 감사합니다.

사실 제출 구조는 여태 크게 신경쓰지 않았던 부분입니다.

말씀하신 사항이 맞으니, 스켈레톤에 맞춰주시면 감사하겠습니다.

**Comment by esc5221** [comment]
감사합니다!
