### ISSUE TITLE
(Django) 유저 이메일 중복 시 IntegrityError 발생 조건 / Service 클래스 구현 관련 질문

### ISSUE THREAD

**Issue by footprinthere** [wafflestudio/19.5-rookies#524]
## 요약

1. serializer 내에서 `create()`나 `update()`를 통해 유저 정보를 반영하게 되는데, 이메일에 중복이 있을 경우 `create()`에서는 `IntegrityError`가 발생하고 `update()`에서는 발생하지 않는 것 같습니다. 맞나요?
2. 세미나3에서 `Serializer` 클래스를 상속헤 service를 구현하는 방법에 대해 말씀해주셨는데, `Serializer`를 상속하지 않고 일반적인 클래스 혹은 함수로 service를 구현해도 괜찮을까요?

<br><br><br><br>

### 1
과제 2에서 `POST /api/v1/signup/`과 `PUT /api/v1/user/me/`를 통해 각각 새로운 유저를 생성하고 기존에 존재하던 유저의 정보를 수정할 수 있도록 했습니다. 그리고 유저는 이메일로 식별되어야 하므로 이 과정에서 이메일이 중복이 발생할 수 없도록 해야 했습니다.
그래서 signup을 수행하는 부분에는 아래와 같이 예외 처리를 해주었습니다.

![image](https://user-images.githubusercontent.com/84006386/135187978-4a30b776-89e7-4101-b9b1-8257797da835.png)

중복된 이메일로 객체 생성을 시도할 경우 `save()`에서 `IntegrityError`가 발생하고, 이를 받아서 `409`를 반환하기 위함이었습니다. 실제로 테스트를 해본 결과 이미 존재하는 이메일로 회원가입을 시도하면 정상적으로 `409`가 표시되었습니다.  

그런데  `PUT /api/v1/user/me/`에서도 이와 동일한 구조로 예외 처리를 했지만, 여기서는 이미 존재하는 이메일로 수정을 시도하면 `409`가 아닌 `400`이 표시되었습니다. 
![image](https://user-images.githubusercontent.com/84006386/135188185-69937f81-9107-405c-8ccf-1d068c9fb174.png)
그리고 위 사진처럼 예외 처리 부분을 아예 빼버려도 `IntegrityError`가 발생하지 않고 여전히 `400`이 표시되었습니다.
![image](https://user-images.githubusercontent.com/84006386/135188418-5a023d7c-6d10-42ad-acff-cab29a5a3536.png)
Response body를 보니 아무래도 serializer 내부의 `validate()`에 이런 경우를 처리하는 로직이 들어 있는 것 같다는 느낌이 들었는데, 정확히 어디에서 이런 body가 return 된 것인지는 찾지 못했습니다. 이런 로직은 어디에 들어 있는 것인가요?
또 어째서 signup에서는 동작하지 않던 로직이 정보 수정을 시도할 때만 동작하는 것인지도 잘 이해가 되지 않습니다.  

참고로 저는 view에서 signup과 정보 수정을 수행할 때 각각 서로 다른 serializer를 사용하도록 구현했으며, 두 serializer의 `validate()` 내부에는 이메일의 중복 여부를 판정하는 로직은 넣지 않았습니다.  

### 2
세미나 3에서 serializer의 형태로 service layer를 구현하는 방법에 대해 말씀해주셨습니다. view는 최대한 가볍게 유지하고, 직렬화와 직접적으로 연관된 동작은 serializer로, 그 외의 동작들은 service로 구현하는 것이 좋다는 걸로 저는 이해했습니다.  

그래서 이번 과제를 수행하면서 view에 있던 것들을 최대한 service로 묶어봐야겠다고 생각했습니다. 그런데 그 과정에서 service 클래스가 굳이 `serializers.Serializer`를 상속하도록 구현할 필요는 없겠다는 생각이 들었습니다.  `Serializer`는 model field에 해당하는 값을 받아 처리하는 것이 주된 역할이고, view로부터 request 등 다른 정보를 받으려면 `context` 같은 방법을 이용해야 합니다. 그런데 굳이 field 데이터를 받아 처리할 필요가 없는 동작이라면 그보다는 오히려 일반적인(`Serializer`를 상속하지 않는) 클래스나 함수로 service를 구현하는 것이 더욱 효율적일 수도 있을 것이라 생각했습니다.  

![image](https://user-images.githubusercontent.com/84006386/135189218-085cc945-7f09-48c3-8964-5e5c1b2f1c48.png)
그래서 위와 같은 방식으로 service 클래스를 구현하여 Response를 만드는 데 필요한 status code와 body data를 view로 return하도록 했습니다. 정상적으로 동작하기는 하는 것 같은데, 이런 방식의 구현이 바람직한지의 여부가 궁금해서 질문 남깁니다.
`Serializer`를 상속하지 않는 service 클래스를 구현하여 활용해도 문제가 없을까요?

**Comment by Jhvictor4** [comment]
답변 드립니다.

1. ModelSerializer를 쓰셨으면, 업데이트 함수에서 instance.save()를 호출하게 됩니다.
아래 경로로 들어가서 Base Model 구조를 확인해보시면 좋을 것 같은데요,

django/seminar2/assignment2/venv/lib/python3.8/site-packages/django/db/models/base.py

위 모듈 1184번 줄에 성태님이 확인하신 에러 메시지를 내보내는 코드가 있습니다. 코드를 ValidationError, 즉 에러 코드 400으로 감싸고 있기에 400이 나가는 것이고, 이를 catch 후 409로 바꿔주시면 됩니다.

2. serializer에서는 인풋, 아웃풋 필드를 명확히 선언하고, 관리해줄 수 있습니다. 또한 가장 강력한 기능인 validation을 사용할 수 있고, Serializer Field들을 활용해 데이터 입출력의 가독성을 크게 향상시켜줄 수 있습니다.

이러한 장점들은 ModelSerializer에서는 아주 강력하지만, 아니고 그냥 Serializer에서 제공하는 기능만으로도 사용할 가치가 충분히 있는 것 같습니다. 물론 구현은 자유지만요.

+ ModelSerializer 등과 함께 DRF viewSet 등을 사용하면 DRF browsable API (크롬화면) 에서 필드값 관리를 해줍니다. 이러한 것도 위 맥락과 비슷하지만 또다른 장점이라고 할 수 있을 것 같습니다.

(애초에 Serializer의 구현이 Django Form으로부터 시작되었으니, 그것도 참고하여 보시면 좋을 듯 합니다.)

**Comment by Jhvictor4** [comment]
@footprinthere 답변 확인하시고 궁금증 해결되셨으면 이슈 닫아주세요.!

**Comment by footprinthere** [comment]
@Jhvictor4 
답변 감사드립니다!!

1번에 관해서, 그냥 `Serializer`를 쓸 때와는 다르게 `ModelSerializer`를 쓸 때만 `instance.save()`가 호출되는 것이라고 이해했는데 맞나요?

**Comment by Jhvictor4** [comment]
@footprinthere 네, 그냥 시리얼라이저는 업데이트 함수가 구현 안 되어 있어요.

**Comment by footprinthere** [comment]
감사합니다!
