### ISSUE TITLE
Button의 스타일이 클릭 이후에 반영되는 문제

### ISSUE THREAD

**Issue by shp7724** [wafflestudio/19.5-rookies#532]
## 상황

스토리보드 상에서 Button을 추가하고 글씨 크기 및 스타일을 변경하였는데,
시뮬레이터에서 실행 시 바로 반영되지 않고, 한 번 클릭을 해주어야 *부분적으로* 반영이 됩니다.

스토리보드 상에서 UI 컴포넌트를 추가한 것 외에 일체의 코딩은 하지 않았습니다.

### 스토리보드 상에서 보이는 버튼
![image](https://user-images.githubusercontent.com/33917774/135612599-324d4a8e-90b0-4627-8310-8ceaa0c3be55.png)
### 시뮬레이터에서 보이는 버튼
![image](https://user-images.githubusercontent.com/33917774/135612649-ee943040-b31c-4d5b-aabb-ca2df0aa553d.png)
### 시뮬레이터에서 보이는 버튼을 클릭한 직후
![image](https://user-images.githubusercontent.com/33917774/135612693-f2872155-aa99-49f5-8c6b-28fb3c7ff970.png)
(Tint Color는 제대로 변경되었는데, 폰트 크기 및 weight는 변하지 않은 것을 확인할 수 있습니다. )

<br><br>

## 문제 내용

XCode 13 버전을 사용중이고, iOS는 15.0 버전이 올라와 있습니다.
최신 버전이라 알려진 버그가 있는지 구글링을 해보았지만 관련 이슈는 찾을 수 없었습니다.

혹시 이러한 문제의 해결 방법을 알고계시다면 답변 주시면 감사하겠습니다!

**Comment by JSKeum** [comment]
Button의 어떤 property를 변경했나요?? 스토리보드 캡쳐 사진도 공유해주시면 자세히 살펴볼 수 있을 것 같습니다.
말씀해주신 것만으로는 문제의 원인을 모르겠고, 혹시 버그일 가능성도 있어 보입니다.

**Comment by shp7724** [comment]
iOS15 SDK에서 새롭게 추가된 것으로 보이는 Filled Button을 사용해서 버튼을 추가했고, 폰트, 색상이랑 Corner Radius 외에 딱히 건드린 부분은 없습니다 ㅠ 최신 버전이라 아직 불안정한걸까요?

![스크린샷 2021-10-06 오후 5 10 37](https://user-images.githubusercontent.com/33917774/136164781-1bcd16cf-f80e-47c0-bcc3-5948b363ed7f.png)

스토리보드 캡쳐도 첨부해두겠습니다.
![스크린샷 2021-10-06 오후 5 10 06](https://user-images.githubusercontent.com/33917774/136165016-a747e6a5-1838-438e-93f7-85985b4bad95.png)
![스크린샷 2021-10-06 오후 5 10 11](https://user-images.githubusercontent.com/33917774/136165002-12821560-2668-4e96-8d81-a35c334248db.png)

**Comment by JSKeum** [comment]
Xcode 13에 다양한 버튼이 추가됐네요😲
먼저 각 property의 기능을 이해해야 할 것 같습니다. 관련된 WWDC 2021 영상도 있네요
https://developer.apple.com/videos/play/wwdc2021/10064/

저는 Xcode 12를 사용하고 있고, filled button을 사용해보지 않아서 정확한 답은 못 드릴 것 같습니다.
그런데 캡쳐해주신거 보니까 UIButton의 background나 foreground를 설정하는 property에 색을 적용한 것이 아니라, UIView의 property를 수정하셨네요. 제 생각에는 UIButton의 property들을 변경하면 원하는 스타일이 나올 것 같습니다.

**Comment by shp7724** [comment]
오 그러네요 말씀하신대로 수정하니까 배경색 버그는 잘 해결됐습니다.
폰트 속성이 스토리보드와 시뮬레이터가 다르게 보였던 부분은 그대로였는데, Title을 Plain이 아닌 Attributed 속성으로 설정하니 해결됐습니다. (원인은 잘 모르겠습니다..)

한 가지 궁금한 점이 있는데, Filled button처럼 새롭게 추가된 UIKit 기능을 구버전 iOS 또는 XCode에서 실행하면 어떻게 되나요?
fallback style로 자동으로 바뀌는지, 아니면 그냥 튕겨버리는지 궁금합니다.
만약 그렇다면 이번 과제에서 사용하면 안될 것 같아서요.
