### ISSUE TITLE
POST 학생 잠그기가 안됩니다 (react)

### ISSUE THREAD

**Issue by Arsture** [wafflestudio/19.5-rookies#534]
## 요약

`axios.post("https://p04fpgjlo3.execute-api.ap-northeast-2.amazonaws.com/v1/student/${params.id}/lock", {headers: {Authorization: "Bearer ${login}"}})`
이 작동하지 않습니다. ("가 아니라 `를 사용했지만, 마크다운 문법으로 코드로 인식되서 "로 바꾸었습니다)<br>
여기서 params는 student의 id를 가져온 것이고 login은 localStorage에 있는 access_token을 state로 저장한 값입니다.

<br><br><br><br>

## 상황

`axios.post("https://p04fpgjlo3.execute-api.ap-northeast-2.amazonaws.com/v1/student/${params.id}/lock", {headers: {Authorization: "Bearer ${login}"}})`이 작동하지 않는데, POSTMAN을 사용하거나 세미나장님께서 만드신 웹페이지로는 잘 작동하지만, axios를 사용하면 안되는 것 같습니다.

<br><br><br><br>

## 문제 내용

![image](https://user-images.githubusercontent.com/87017787/135704934-9372cda2-cd11-4e6c-9282-3b2e3a022369.png)
![image](https://user-images.githubusercontent.com/87017787/135704960-c051cab2-1440-44bf-934a-3a15ad609a71.png)
위와 같은 오류가 발생하는데, POSTMAN을 사용하면 <br>
![image](https://user-images.githubusercontent.com/87017787/135704984-79e8f553-c274-40e0-8d7f-e84b42e7751a.png)
잘됩니다... 분명 똑같은데, 왜 안될까요...??

**Comment by woohm402** [comment]
![image](https://user-images.githubusercontent.com/39977696/135705171-cc1071cf-d745-478c-8ee8-4f2e3ee3dd1c.png)

postman에서 하신 대로, Authorization 정보는 헤더에 들어가야 합니다. 지금은 바디에 ```{headers: `Bearer ${token}`} ``` 으로 넣으신 것 같습니다.

**Comment by woohm402** [comment]
`axios.post` 함수는 인자 1~3개를 받습니다. 1개를 받을 경우 url, 2개를 받을 경우 url과 body, 3개를 받을 경우 url과 body와 config입니다.

인자 두 개를 넘겨주셨기 때문에, 넘겨주신 인자가 body 자리에 들어가게 되었습니다. `axios.post(써주신 url, null, 써주신 config)` 로 하시면 해결될거예요

**Comment by woohm402** [comment]
axios.post 말고 이런 방법도 있습니다.

https://axios-http.com/docs/api_intro

참고해주세요!

**Comment by Arsture** [comment]
아하,,, 그래서 안되는 거였군요,,,, 이해갔습니다! 그러면 `axios()`사용하는 것 외에 axios.post로 url과 config만 넘겨주고 싶은 경우 방법이 있나요?? `axios()`로 해결은 하였습니다!

**Comment by woohm402** [comment]
사실 저는 보통 https://github.com/axios/axios#global-axios-defaults 이런 식으로 디폴트값 세팅하는 방식으로 하긴 합니다

**Comment by Arsture** [comment]
넵 답변 감사합니다!
