### ISSUE TITLE
장고 과제 3 - 리드미 관련 질문

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#537]
안녕하세요. 간단한 질문인데, 과제 3 리드미 1번에서 'POST api/v1/user/'가 아니라 'POST api/v1/signup/'이 구현되어 있다고 의도하신 것이 맞을까요? 반대로 작성되어 있는 것 같은데, 혹시나해서 여쭤봅니다!

**Comment by kk0in** [comment]
추가적으로 과제3의 7번 문제는 자유 과제인지 궁금합니다!

**Comment by Jhvictor4** [comment]
리드미 최신화가 안되어있으신 것 같습니다.ㅏ signup이 맞습니다.

네 자유과제로 진행하도록 하겠습니다. 혼자 해보기에 무리 없는 내용이라고 판단했습니다.

**Comment by kk0in** [comment]
@Jhvictor4 답변 감사합니다. 자유과제는 꼭 기한까지 할 필요는 없는 것이 맞나요?
