### ISSUE TITLE
장고 과제 3 - test 예시 코드 관련 질문

### ISSUE THREAD

**Issue by kk0in** [wafflestudio/19.5-rookies#538]
안녕하세요.
과제 3에서 test 예시로 주어진 파일과 관련해서 질문이 있어 이슈를 남깁니다.
PUT api/v1/user/me/ 과 관련된 test_put_user_me_instructor 함수에서 
email을 'bdv111@naver.com' 로 수정하고자 하는데, 이는 이미 가입되어 있는 메일이므로 409 에러가 나야하는 것 아닌가요..? 제가 놓치고 있는 것이 있나 궁금합니다! 감사합니다.

**Comment by Jhvictor4** [comment]
지금 400으로 들어가있나요? 명세 상으로는 409 나야 하는 것이 맞습니다. 수정하도록 하겠습니다.

**Comment by kk0in** [comment]
@Jhvictor4 지금 test 파이썬 파일에서 put을 test 할 때, 이미 존재하는 메일로 수정을 하는데, 409 에러를 체크하는것이 아니라, 실제로 수정이 진행되었는지를 체크하고 있습니다
