### ISSUE TITLE
storage 접근 최소화를 위한 API 설계 질문

### ISSUE THREAD

**Issue by yeonsumia** [wafflestudio/19.5-rookies#539]
안녕하세요, React 청강생 전현성입니다.

storage 접근을 최소화하기 위해 context에서 token을 열람하여 axios를 정의하려 해보았습니다. 
원래는 
```JSX
const loginToken = localStorage.getItem('loginToken');
const API = axios.create(...)
export default API;
```
으로 했던 것을 

```JSX
import {useUserContext} from "../context/UserContext";

const API = () => {
    const {loginToken} = useUserContext();
    return axios.create({
        baseURL: "...",
        headers: {
            "Content-Type": "...",
            "Authorization": `Bearer ${loginToken}`
        }
    });
}

export default API;
```
와 같이 context를 사용하기 위해서 arrow function 형태로 만들었는데 잘 실행되지 않습니다.
어떻게 해야할까요?

**Comment by woohm402** [comment]
https://ko.reactjs.org/docs/hooks-rules.html

훅의 규칙에 따라 함수 컴포넌트 안에서만 훅을 호출할 수 있습니다. `API`는 함수 컴포넌트가 아닙니다. 따라서 해당 코드는 잘 작동하지 않을 것 같네요!

저같은 경우에는 그냥 로그인할 때 [이 문서](https://axios-http.com/docs/config_defaults) 에서 소개하는 방식처럼 `axios.defaults` 를 매뉴얼하게 세팅하는 방식을 선호합니다. `immutable`에 부합하지 않긴 하지만, 로그인과 관련된 부분이니만큼 저는 예외적으로 `mutable`하게 구현합니다

### `src/apis/requester.js`
```js
import axios from 'axios';

const requester = axios.create({ baseURL: 'https://p어쩌구' });

export default requester;
```

### `어딘가에 있을 로그인과 로그아웃 로직`
```js
const handleLogin = () => {
  // ...
  requester.defaults.headers.common['Authorization'] = `Bearer ${token}`;
  // ...
}

const handleLogout = () => {
  // ...
  delete requester.defaults.headers.common['Authorization'];
  // ...
}
```
