### ISSUE TITLE
PATCH할 때 design major에서만 Error 400이 발생합니다

### ISSUE THREAD

**Issue by s-yeoyul** [wafflestudio/19.5-rookies#540]
## 요약

axios.patch를 사용할때 major를 design으로 설정하면 서버에서 400 에러를 반환합니다

<br><br>

## 상황

DetailPage에서 전화번호/이메일/프로필/전공 을 수정하고 저장하는 버튼을 구현하는 과정에서 다른 전공은 에러가 발생하지 않는데 
design만 에러가 발생해서 뭔가 서버에 문제가 있는게 아닌가 싶어서 이슈 올립니다!
처음엔 제가 데이터 포맷을 잘못 짠 줄 알고 postman으로 이것저것 해보다가 혹시나 해서 [과제 예시 사이트](https://waffle-rookies-19-5-react-assignment-1.vercel.app/)에서도 해봤는데 design 항목만 에러가 뜨는 것 같아요 ㅜㅜ

<br><br>

## 문제 내용

![스크린샷, 2021-10-05 20-24-31](https://user-images.githubusercontent.com/81800659/136013846-06a6f604-098d-4cc2-b80b-7afedba21c48.png)
major: design으로 보내면 400 error를 return합니다.
![스크린샷, 2021-10-05 20-25-17](https://user-images.githubusercontent.com/81800659/136014101-5b63354b-d251-4e62-bcda-2ff2f47ebe05.png)
다른 major는 문제가 없습니다.

**Comment by woohm402** [comment]
아주 서버 오류였네요 😅  제보 감사합니다! 수정했습니다 👍
