### ISSUE TITLE
response를 받아서 값을 할당할 때 문제

### ISSUE THREAD

**Issue by subir-sh** [wafflestudio/19.5-rookies#547]
## 요약

아마도 비동기/동기 순서 문제인 것 같습니다.

<br><br><br><br>

## 상황

response를 받아서 어떤 함수들의 인자에 값을 넘겨줄 때 문제가 생깁니다.

<br><br><br><br>

## 문제 내용
안녕하세요, 

```
const [token, setToken] = useState(null);

requester.post("v1/auth/login", {
      username: content.id,
      password: content.password
    })
.then((res) => {
      setToken(res.data.access_token);
      localStorage.setItem("loginToken", token);
    })
```

이렇게 하고 token을 하면 제대로 나오는데, localStorage.getItem을 하면 null이 나옵니다. 
그런데,

```
.then((res) => {
      const temp = res.data.access_token;
      setToken(temp);
      localStorage.setItem("loginToken", temp);
    })
```

이렇게 하면 잘 작동합니다.

res를 받은 후에는 동기처럼 처리하는 것으로 이해했는데, 그게 아닌가요? 
뭔가 더 나은 해결 방법이 있을 것 같아 질문드립니다.

**Comment by woohm402** [comment]
말 나온 김에 좀만 덧붙이자면 setState는 비동기로 작동하기 때문에, 현재 실행 중인 작업이 다 끝난 다음에야 실행됩니다!

https://stackoverflow.com/questions/36085726/why-is-setstate-in-reactjs-async-instead-of-sync
