### ISSUE TITLE
학생 정보 수정 시 코멘트 형식

### ISSUE THREAD

**Issue by kmsgm** [wafflestudio/19.5-rookies#576]
## 요약

학생 정보를 수정할 때 학생 정보 코멘트 형식과 관련하여 질문드립니다.

<br><br><br><br>

## 상황

여러 학생 정보 중 이메일만 수정했을 때 코멘트에 수정된 이메일 정보만 나타낼 수 있는 방법이 있을까요?

<br><br><br><br>

## 문제 내용

주어진 스펙에서 빈 값이면 null을 보내라고 해서 수정되지 않은 정보는 다 null을 넣어놓았는데 
예시 사이트처럼 코멘트가 작성되지 않는 것 같습니다...
![image](https://user-images.githubusercontent.com/49176503/136660529-e62db6f2-72fd-4477-9032-3eeda0de4693.png)
<br>
예시로 주어진 사이트에서는 여러 학생 정보 중 이메일만 수정하면 이메일 수정 사항만 코멘트에 반영되는 것 같습니다.
![image](https://user-images.githubusercontent.com/49176503/136660535-7fa2b5c5-17ed-497d-9d8d-88b2f4f5278a.png)
<br>
제가 만든 버전은 수정된 이메일 뿐만 아니라 다른 정보 값도 null 이라고 코멘트 내용에 들어가게 됩니다.
![image](https://user-images.githubusercontent.com/49176503/136660562-80dddeab-17f1-4e66-b5e4-c3e786365f4f.png)
<br>
이런 부분은 코드에서 처리해줘야 하는 부분일까요?

**Comment by woohm402** [comment]
아 저게 정확히 어떤 의미였냐면

1. 수정되지 않은 필드면 -> 보내지 말고
2. 수정된 필드면 -> 보내는데,
   1. 빈 값으로 수정됐으면 -> `""` 말고 `null`로 보내고
   2. 아니면 값을 보내라

라는 이야기였습니다 😅  제가 봐도 애매하게 썼네요ㅠㅠ
