### ISSUE TITLE
장고 과제 3 - user의 field 넘겨받기 관련

### ISSUE THREAD

**Issue by hansmaan** [wafflestudio/19.5-rookies#579]
## 요약

user/participant/를 post하는 것을 test하려고 하는데, client.post할 때 user의 나머지 field들은 잘 넘어가는 반면, participant와 instructor는 넘어가지지 않습니다.

<br><br><br><br>

## 상황
 request.user를 넘겼는데, 다른 field들은 다 넘어가는 반면, participant와 instructor는 넘어가지 않습니다

<br><br><br><br>

## 문제 내용
 
user/participant/를 post하는 것을 test하려고 하는데, 그것을 위해서 self.client.post('api/v1/user/participant/', HTTP_AUTHORIZATION = self.token)와 같은 식으로 적었습니다. 저것과 같은 방식으로 하면, view에 있는 함수로 token을 소유한 user가 request.user로 넘어가게 됨을 인지하고 있습니다. 그래서 이제 participant field가 none이 아닌 상태라면 status 400을 출력하는 것을 구현하려고 하고 있었습니다. 그런데, 명백히 setUpTestData에는 participant를 만들어놓았는데, 201이 response로 출력되고 있었습니다. 
![스크린샷, 2021-10-10 04-42-20](https://user-images.githubusercontent.com/88359757/136671976-ff4a8cda-f344-41b3-88a2-b4db526bc9ed.png)
![스크린샷, 2021-10-10 04-38-13](https://user-images.githubusercontent.com/88359757/136672020-50aa7566-dcd9-4ddf-8c4e-46ffc80e3b94.png)
![스크린샷, 2021-10-10 04-44-11](https://user-images.githubusercontent.com/88359757/136672023-3274a07b-c69d-4d39-b2dd-dd0eea703d74.png)

그래서 print를 통해서 출력해보니, 실제로 client.post하기 전 token을 소유한 user는 participant를 가지고 있으나, client.post를 통해 넘기는 순간 participant가 사라지는 것 같습니다. 구글링을 통해서 문제를 해결해보려 했지만, client.post를 하는데 onetoonefield만 넘어가지지 않는 굉장히 specific한 문제는 잘 없는 것 같습니다... 아니면 애초에 HTTP_AUTHORIZATION과 token을 기반으로 한 request.user 데이터 전송이 잘못된 것인지 여쭙고 싶습니다.

**Comment by hansmaan** [comment]
user instance가 save되지 않아서였습니다... save하니까 잘 돌아가네요

**Comment by esc5221** [comment]
저도 같은 오류때매 헤매다 해결하고나서 이 issue를 봤네요 ㅋㅋ....
