### ISSUE TITLE
장고 과제3 testcase setUpTestData 질문

### ISSUE THREAD

**Issue by minkyu97** [wafflestudio/19.5-rookies#589]
## 질문1
testcase 만들 때 setUp 또는 setUpTestData를 설정해줘야되는 걸로 알고있습니다.
setUp은 매 테스트 실행 시 마다 실행되는 거고 setUpTestCase는 클래스메소드라서 맨 처음에 한 번만 실행되는 걸로 아는데요.
setUpTestData에서 유저를 하나 만들어 놓고 어떤 test에서 POST /api/v1/user/signup/ 으로 새로운 유저를 만들어도 다른 test에서는 해당 부분이 반영이 되지 않더라고요. 제 생각에는 setUpTestData는 맨 처음에 한번만 실행되는 거니까 어떤 test에서 새로운 유저를 만들면 그 유저가 test db에 추가되어 다른 test에서도 남아있어야될 것 같은데 왜 그렇지 않은가요?

## 질문2
질문1에 대한 답과 관계 없이 어쨌든 setUpTestData를 이용해도 각 테스트들이 독립적으로 실행되는 것이라면 매번 실행되느라 속도도 느린데 왜 굳이 setUp(self)를 따로 만들어 놓았는지 두 메소드의 용도 상의 차이점이 궁금합니다.

**Comment by Jhvictor4** [comment]
민규님 안녕하세요, 뒤늦게나마 답변 남깁니다.

1. test 끼리는 영향을 주고받지 않도록 하나하나 끝날 때마다 transaction을 rollback하기 때문에, setUpTestData에 명시적으로 들어가ㅏ 있는 데이터가 아니면 다른 테스트에서 사용할 수 없는게 맞습니다.

2. 파이참에서 django.test.testcases.TestCase 클래스를 확인해보시면 이해가 빠르실 것 같습니다.
- TestCase -> TransactionTestCase -> SimpleTestCase -> unittest.TestCase 순으로 상속 트리를 거슬러 올라갈 수 있는데요,
-  SetUP & TearDown 개념은 Unittest에서 쓰이는 개념인데, 유닛 테스트는 테스트 작성을 위해 항상 TestCase 클래스를 선언해주어야 합니다. setup 함수는 이렇게 만들어진 클래스 인스턴스 위에서 각 테스트가 실행될 때마다 데이터를 만들고, 지우기를 반복합니다.
- 말씀해주신 것처럼 해당 과정이 번거롭고 비효율적이기 때문에, 클래스마다 데이터를 한번만 생성해두고 쓸 수 있도록 Django에서 유닛테스트를 확장해 지원하는 개념이 SetUpTestData 입니다.

**Comment by minkyu97** [comment]
결론적으로 어차피 test 끼리는 영향을 줄 수 없도록 원자성이 보장되어있고, setUp 함수의 비효율성을 개선시킨 것이 setUpTestData 함수군요! 답변 감사합니다 :)
