### ISSUE TITLE
Could not initialize proxy ... - no Session 문제

### ISSUE THREAD

**Issue by yg-moon** [wafflestudio/19.5-rookies#643]
## 요약
- EnableJpaAuditing을 켜니 이전에 없던 `Hibernate could not initialize proxy – no Session` 문제가 발생합니다.

## 상황
- 과제2에서 작성한 코드를 다시 한번 포스트맨으로 검증하려던 중 문제를 발견했습니다.
- GET users/me/ (자신의 정보 받기), POST seminars/ (세미나 생성) 등 FetchType이 Lazy인 필드를 포함하는 엔티티에서 문제가 발생합니다.
- BaseTimeEntity의 createdAt을 사용하기 위해 EnableJpaAuditing을 켜니 문제가 발생한 것으로 보입니다.

## 문제 내용
- 위에 언급된 API들을 포스트맨으로 실행해보면 `500 internal server error`가 나면서, 인텔리제이 터미널에 `Hibernate could not initialize proxy – no Session` 오류 메시지가 출력됩니다.
- https://www.baeldung.com/hibernate-initialize-proxy-exception 을 참고하니 FetchType을 Eager로 설정하거나, JPQL문에서 fetch join을 사용하라고 합니다.
  - 하지만 FetchType은 Lazy로 하는 것이 권장되어 있고, 직접 JPQL을 쓴 곳은 없기에 어떻게 고쳐야 할지 모르겠습니다.
- EnableJpaAuditing을 끄고, createdAt을 LocalDateTime.now()로 처리하는 임시방편이 있지만 좋은 해결책이 아닌 것 같습니다.
  - 이렇게 하더라도 GET users/me/ 는 여전히 오류가 나는 것 같습니다. 뒤늦게 발견했네요.

**Comment by numnum97** [comment]
과제2를 할 때 제가 겪었던 경우와 비슷한 것 같습니다! 저의 경우는 Entitygraph로 해결하였습니다.

**Comment by yg-moon** [comment]
EnableJpaAuditing을 켜기 전에는 다 잘 돌아갔는데, 갑자기 왜 이러는지 잘 이해가 안 되네요.
그냥 원래 있었던 개념적인 문제가 드러난 것이라고 봐야 하는 것일까요?

**Comment by yg-moon** [comment]
@CurrentUser로 가져온 user를 그대로 쓰는게 문제였습니다.
과제에서 User model과 @CurrentUser에서 가리키는 user가 다른데 둘을 혼동해서 발생한 문제였습니다.
