### ISSUE TITLE
integration test 실행 에러 질문

### ISSUE THREAD

**Issue by yeonsumia** [wafflestudio/19.5-rookies#661]
안녕하세요, springboot 수강생 전현성입니다.

<img width="968" alt="스크린샷 2021-11-09 오후 9 36 23" src="https://user-images.githubusercontent.com/81272473/140925634-192daf75-fc15-47ea-a4d1-7f09807fd5ee.png">

integration test를 진행하려 하는데 다음과 같은 에러가 발생합니다.
빨갛게 표시된 것처럼 Unresolved reference: springframework 등의 에러가 발생하는데, 어떻게 해결해야 할지 모르겠어서 여쭙니다.
자바 설정? 과 관련된 것 같은데 구글링을 해도 해결되지 않아서 issue 올립니다.
감사합니다.

**Comment by yg-moon** [comment]
저도 같은 문제를 겪었는데, Gradle 설정이 꼬여서 발생하는 문제라서 .idea 파일을 삭제하고 다시 폴더를 열면 되었습니다.

참고: https://jojoldu.tistory.com/364

**Comment by yeonsumia** [comment]
해결하는 데에 도움이 되었어요! 알려주셔서 감사합니다. :)
