### ISSUE TITLE
안드로이드 과제4 토큰 관련 질문

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio/19.5-rookies#663]
## 요약

가장 처음 서버와 통신할 때, POST로 signup을 해서 토큰을 받아와야 할 텐데, 이 과정 전체에서 총체적 난국입니다.

<br><br>

## 상황

우선 readme에서 제공해 주신 대로 다음과 같이 항상 헤더에 토큰을 붙여서 서버와 통신하게 됩니다.
```Kotlin
OkHttpClient.Builder()
    .addInterceptor { chain ->
        val newRequest = chain.request().newBuilder().addHeader(
            "Authorization", "JWT $savedToken"
        ).build()
        chain.proceed(newRequest)
    }
    .build()
```
login 때는 토큰이 필요하지 않다고 하셨고, signup때도 아마 없을 거라 생각해서 이 코드 대신 seminar3의 
```
    @Provides
    @Singleton
    fun provideHttpClient(): OkHttpClient {
        return OkHttpClient.Builder()
            .addInterceptor(
                HttpLoggingInterceptor().apply {
                    level =
                        if (BuildConfig.DEBUG) HttpLoggingInterceptor.Level.BODY
                        else HttpLoggingInterceptor.Level.NONE
                }
            ).build()
    }
```
를 가져와서 사용해 봤습니다.
<br />
질문 1.  signup의 응답을 받아와서 받아온 토큰을 확인하는 코드를 우선 짜 보았는데요, 다음 postman이 보여주는 서버의 response를 참고해서

![캡처](https://user-images.githubusercontent.com/88367636/141131685-d2eb9eaf-4000-400f-9354-1b6a979835b0.JPG)

```
data class FetchSignup (
    val user:String,
    val token:String
)
```
이런 data class로 response를 받아와서 처리하는 형식입니다.<br />
그런데 아무리 해도 ```Call<FetchSignup>```에서 ```onFailure()```만 뜹니다. 
```
interface LoginService {


    @FormUrlEncoded
    @POST("api/v1/signup")
    fun signup(@Field("email")email:String,
               @Field("username")username:String,
               @Field("password")password:String,
               @Field("roll")roll:String): Call<FetchSignup>
}
```
이런 LoginService를 만들었는데, 어떤 부분이 문제인지 잘 모르겠습니다.
<br />
로그캣에 뜨는 유일한? 알아볼 수 있는 오류는 <br />
HTTP FAILED: java.net.UnknownServiceException: CLEARTEXT communication to ec2-3-37-16-171.ap-northeast-2.compute.amazonaws.com not permitted by network security policy <br />
입니다. 검색해봐도 딱히 해결방법을 찾질 못했습니다.
<br /><br /><br />
질문 2. 받아온 토큰이 있을 때, 저곳(provideHttpClient 함수)으로 인자를 어떻게 전달하나요?<br />
저는 seminar3의 NetworkModule.kt를 그대로 가져온 후, ```provideHttpClient``` 함수 부분만 제공해주신 위의 코드로 바꾸어 주었습니다. 그런데  ```provideHttpClient``` 함수의 인자로 String을 받으려 했더니 java.lang.securityexception: permission denied (missing internet permission?) 를 비롯한 수많은 오류가 납니다.<br />

<br><br><br><br>

**Comment by veldic** [comment]
1. https가 아닌 http로 구현되어 있어서 생기는 cleartext 문제네요. 제가 언급하는걸 깜빡했네요. [링크](https://codechacha.com/en/android-cleartext-http-traffic-issue/)참고하셔서 구현해주세요!
2. missing internet permission의 경우 AndroidManifest.xml에 internet user-permission을 제공했는지 확인해주세요!

**Comment by JuTaK97** [comment]
> 1. https가 아닌 http로 구현되어 있어서 생기는 cleartext 문제네요. 제가 언급하는걸 깜빡했네요. [링크](https://codechacha.com/en/android-cleartext-http-traffic-issue/)참고하셔서 구현해주세요!
> 2. missing internet permission의 경우 AndroidManifest.xml에 internet user-permission을 제공했는지 확인해주세요!

다 구글링해보면서 찾아서 한번씩 해 본 것들인데 효과가 없네요.. 일단 다시 한번 확인해보겠습니다

**Comment by JuTaK97** [comment]
![image](https://user-images.githubusercontent.com/88367636/141138330-a5b01187-a264-48dd-9ae4-0f555b39c3e9.png)

모두 확인했는데 여전히 안됩니다.
로그캣 캡처 첨부합니다.

**Comment by JuTaK97** [comment]
AndroidManifest.xml 전체입니다.
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.assignment4">

    <uses-permission android:name="android.permission.INTERNET" />
    <application
        android:name=".App"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.Assignment4"
        android:usesCleartextTraffic="true"
        android:networkSecurityConfig="@xml/network_security_config">
        <activity
            android:name=".login.LoginActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".MainActivity"
            android:exported="true"/>
    </application>
</manifest>
```

res/xml 에 있는 network_security_config.xml 입니다.
```
<?xml version="1.0" encoding="utf-8"?>


<network-security-config>
    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="true">http://ec2-3-37-16-171.ap-northeast-2.compute.amazonaws.com/api/v1</domain>
    </domain-config>
</network-security-config>
```
저 주소 부분에 정확히 어떤 값이 들어가야 되나 애매해서 <br />
ec2-3-37-16-171.ap-northeast-2.compute.amazonaws.com <br />
http://ec2-3-37-16-171.ap-northeast-2.compute.amazonaws.com <br />
등등 여러개를 다 해봤는데 잘 안되네요.. 어떤 게 맞을까요?

**Comment by veldic** [comment]
AndroidManifest.xml 에 usesCleartextTraffic="true" 만 놔두고 나머지 network security config 관련된 부분은 지워보실 수 있으실까요?

**Comment by JuTaK97** [comment]
400 Bad Request 오류로 바뀌었네요 감사합니다!!
이제 제가 뭘 잘못 보냈는 지를 찾아야 하는데.. 일단 열심히 찾아 보겠습니다.
늦은 시간에 감사합니다!

**Comment by JuTaK97** [comment]
> 1. https가 아닌 http로 구현되어 있어서 생기는 cleartext 문제네요. 제가 언급하는걸 깜빡했네요. [링크](https://codechacha.com/en/android-cleartext-http-traffic-issue/)참고하셔서 구현해주세요!
> 2. missing internet permission의 경우 AndroidManifest.xml에 internet user-permission을 제공했는지 확인해주세요!

혹시 2번 질문에서, Dagger Hilt를 사용하는데 저 $savedToken 자리에 token을 어떻게 전달하나요?
토큰이 아직 없을 때는 다른 형태를 사용해야 하고, 토큰이 있을 때 토큰을 전달받아서 넣어야 되는데 NetworkModule은 너무 따로 있어서 어떻게 전달해야 할지 잘 모르겠네요.

**Comment by veldic** [comment]
Dagger hilt를 사용하신다면 PreferenceModule 과 같은 형태의 모듈을 하나 더 만들어서 sharedPreferences를 inject 가능한 형태로 만든 뒤, NetworkModule에서 Inject 받아서 사용하는 방식으로 구현할 수 있습니다. 

``` kotlin
@InstallIn(SingletonComponent::class)
@Module
object PreferenceModule {
    @Provides
    @Singleton
    fun provideSharedPreference(@ApplicationContext context: Context): SharedPreferences {
        return context.getSharedPreferences(BuildConfig.PREF_KEY, Context.MODE_PRIVATE)
    }
}
```

``` kotlin
@Provides
@Singleton 
fun provideOkHttpClient(sharedPreferences: SharedPreferences): OkHttpClient = ~~
```
`NetworkModule 내에서..`

**Comment by JuTaK97** [comment]
```
    @Provides
    @Singleton
    fun provideHttpClient(sharedPreferences: SharedPreferences): OkHttpClient {
        return OkHttpClient.Builder()
            .addInterceptor { chain: Interceptor.Chain ->
                val newRequest = chain.request().newBuilder().addHeader(
                    "Authorization", "${sharedPreferences.getString("token", "")}"
                ).build()
                chain.proceed(newRequest)
            }
            .build()
    }

    @InstallIn(SingletonComponent::class)
    @Module
    object PreferenceModule {
        @Provides
        @Singleton
        fun provideSharedPreference(@ApplicationContext context: Context): SharedPreferences {
            return context.getSharedPreferences("token", Context.MODE_PRIVATE)
        }
    }
```
와 같이 해 봤는데, 저렇게 되면 맨 처음 signup때는 빈 string으로 된 토큰이 포함된 헤더를 전달하게 되는데, 서버는 그냥 신경쓰지 않는건가요? 일단 에러는 나지 않는 것 보면 그런 것 같긴 하네요..

**Comment by veldic** [comment]
정 신경이 쓰이신다면 sharedPreferences.getString 으로 받아온 값을 분기로 newRequest를 만드셔도 상관없습니다 ㅎㅎ

**Comment by JuTaK97** [comment]
newRequest 만드는 부분은 제가 지금 이해도가 0인 상태라... 

혹시 저 액티비티에서 확보한 token을 sharedpreference에 넣어주려면, 액티비티에게도 동일한 sharedPreference를 주입(?)해줘야 할 텐데, 액티비티의 생성자에  ```(sharedPreferences: SharedPreferences)```로 넣어 줬더니 하위 코드에서sharedPreference를 인식을 전혀 못하는데 이 부분은 어떻게 해야 할까요..
정말 막히는 부분이 많은데 해결하기가 참 쉽지 않네요.

**Comment by JuTaK97** [comment]
> 정 신경이 쓰이신다면 sharedPreferences.getString 으로 받아온 값을 분기로 newRequest를 만드셔도 상관없습니다 ㅎㅎ

현재 이 방법을 사용하여,
```

    @Provides
    @Singleton
    fun provideHttpClient(sharedPreferences: SharedPreferences): OkHttpClient {
        if (sharedPreferences.getString("token","")=="") {
            return OkHttpClient.Builder()
                .addInterceptor(
                    HttpLoggingInterceptor().apply {
                        level =
                            if (BuildConfig.DEBUG) HttpLoggingInterceptor.Level.BODY
                            else HttpLoggingInterceptor.Level.NONE
                    }
                ).build()
        }
        else {
            return OkHttpClient.Builder()
                .addInterceptor { chain: Interceptor.Chain ->
                    val newRequest = chain.request().newBuilder().addHeader(
                        "Authorization", "JWT ${sharedPreferences.getString("token", "")}"
                    ).build()
                    chain.proceed(newRequest)
                }
                .addInterceptor(
                    HttpLoggingInterceptor().apply {
                        level =
                            if (BuildConfig.DEBUG) HttpLoggingInterceptor.Level.BODY
                            else HttpLoggingInterceptor.Level.NONE
                    }
                )
                .build()
        }
    }
```
이렇게 만들어서 사용하고 있습니다.<br />
token이 없을 때(if문 통과)를 1번, 있을 때(if문 탈락)를 2번이라고 해 보면, 사용자가 맨 처음 앱을 켰을 때는 토큰이 없어서 1번 okHttpclient가 생성되고 쭉(앱 종료 전까지) 사용됩니다. 그래서 토큰을 주고받지 않는 형태라서 이후 모든 request에서 authorization에서 실패합니다.<br />
하지만 받아온 토큰이 저장은 되기 때문에, 앱을 껐다 켜면 정상적으로 2번 okHttpclient가 만들어져서 쓰이기 때문에 그 이후로는 문제가 없습니다.<br />
조건문과 1번 없이 2번만 사용하면, 맨 처음 login에서 authorization fail이 뜹니다. login은 토큰 인증이 필요하진 않은데 헤더에 뭔가 붙어 있어서 안되는 것 같네요.<br />
이부분을 어떻게 해결해야 될까요?

**Comment by veldic** [comment]
OkHttpClient를 여러번 만드는 것이 아니라 addInterceptor 내부 구현에서 분기를 만드는 방향으로 가면 좋을 것 같아요

**Comment by JuTaK97** [comment]
> OkHttpClient를 여러번 만드는 것이 아니라 addInterceptor 내부 구현에서 분기를 만드는 방향으로 가면 좋을 것 같아요
