### ISSUE TITLE
local에서 Authorization Error

### ISSUE THREAD

**Issue by yabsed** [wafflestudio/19.5-rookies#670]
## 요약

예시 코드를 실행하고 나서 Authentication 에러 발생

<br><br><br><br>

## 상황

local에서 과제2 결과물을 다시 한번 실행해 보려고 했는데, 실행은 잘 되지만 
과거와는 다르게 JMT 토큰을 이용하는 과정에서
"Authentication credentials were not provided."가 뜨는 오류가 발생하고 있습니다. 

<br><br><br><br>

## 문제 내용

자체 코드로 실행해봐도 그렇고, 
https://github.com/Jhvictor4/19.5-rookies/tree/assignment-2-solved
에 나와있는 코드로 다시 실행해도 같은 결과를 보이고 있습니다. 

<img width="1440" alt="Screen Shot 2021-11-12 at 12 11 47 AM" src="https://user-images.githubusercontent.com/14042027/141321760-03d2c637-fcb3-4e6f-b434-87d72a6397f4.png">
<img width="1440" alt="Screen Shot 2021-11-12 at 12 12 23 AM" src="https://user-images.githubusercontent.com/14042027/141321870-19f83a9b-3ee0-4d78-ab42-e9ca8034a9c7.png">
<img width="1440" alt="Screen Shot 2021-11-12 at 12 12 32 AM" src="https://user-images.githubusercontent.com/14042027/141321881-4e2eacca-733c-4fd9-b17b-2eaf6b919f57.png">
<img width="1440" alt="Screen Shot 2021-11-12 at 12 21 59 AM" src="https://user-images.githubusercontent.com/14042027/141323547-c33a8915-4e6b-4cd6-8867-52b5f7648626.png">
<img width="1440" alt="Screen Shot 2021-11-12 at 12 24 47 AM" src="https://user-images.githubusercontent.com/14042027/141323872-a89c9ec4-4c2f-41a0-8188-16be15eabe5a.png">

**Comment by Jhvictor4** [comment]
토큰 명이 잘못되어서 그렇습니다. 토큰 이름은 JWT 입니다 :)

**Comment by yabsed** [comment]
😂😂😂😂😂😂😂
정말 민망합니다
야심한 밤에도 계속 봐주고 계시니 든든합니다 😍
