### ISSUE TITLE
백엔드 서버가 보낼 수 있는 여러 에러 응답 처리 관련

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio/19.5-rookies#671]
## 요약
예를 들어, 로그인창에서 이름을 빼먹었거나, 잘못된 형식의 이메일을 썼거나, 없는 이메일을 쓰거나 하면 서버는 그에 맞게 에러 메시지를 보내줍니다.<br />
1. API 문서에는 없는 것 같은데, 모든 에러 메시지 종류를 볼 수 있는 곳이 있나요?
2. 각 에러 메시지 json마다 가지는 key라던가 모두 다른데, 통합해서 처리할 수 있는 방법이 있나요?<br />
과제 스펙에는 없는 부분이긴 한데, 궁금해서 질문 남깁니다.

<br><br>

## 상황
이메일 칸을 빼먹고 login을 하려 하면 ```{"email":["This field may not be blank."]}```가 옵니다.
이메일 형식이 틀리면 ```{"non_field_errors":["이메일 또는 비밀번호가 잘못되었습니다."]}```가 옵니다.
이메일과 비밀번호를 모두 빼먹으면 ```{"email":["This field may not be blank."],"password":["This field may not be blank."]}```가 옵니다.
이상한 role을 적어서 signup을 하면 ```"role":["\"\" is not a valid choice."]``` 가 옵니다.<br /><br />
다양한 에러 종류마다 json의 key가 모두 다릅니다. 이런 상황에서,
```
override fun onResponse(call: Call<FetchLogin>, response: Response<FetchLogin>) {
                    if(!response.isSuccessful) {
                        val error = JSONObject(response.errorBody()!!.string())
                    }
}
```
로 일단 JSON 객체는 잡아 놨는데, 매번
```
           if(error.has("email")) {
                            Toast.makeText(this@LoginActivity,
                            error.getString("email"), Toast.LENGTH_LONG).show()
                        }
```
와 같이 각 key가 있는지 없는지 확인해서 처리하기도 좀 그렇고, 
```
data class Error (
    val email:String?,
    val password:String?,
    val detail:String?,
    val non_field_errors:String?,
    val role:String?
    ...
)
```
와 같이 null의 가능성이 있는 data class 로 error를 받아볼 생각도 해봤는데 이건 잘 안되네요.<br />
어떻게 해결하는게 최적의 방법일까요?

<br><br><br><br>

**Comment by Jhvictor4** [comment]
@JuTaK97 
안녕하세요, 백엔드 세미나장입니다.
서버 에러 리스폰스 처리 관련해서 질문 주셨는데요, 일단 에러 메시지 관리는 서버가 하는 것이 일반적입니다. (형식 등에 대한 논의는 다같이 하되)

에러 메시지 관련 명세가 백엔드 세미나 & 안드용 서버 전달받을 때 없기는 했습니다. (서버 작업할때까지는 status_code 만 나누는 것으로..)

(때마침 백엔드 세미나에서는 저번주에 에러 메시지 관련 수업 & 과제를 낸 상태입니다ㅏ.)

아무튼 보통은 서버가 내려주는 메시지 (가공해서 내려주면) 그대로 표시해주는 식인 것 같습니!

**Comment by JuTaK97** [comment]
답변 정말 감사합니다!
