### ISSUE TITLE
안드로이드 과제4 스펙 관련

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio/19.5-rookies#672]
## 요약
과제의 구현 스펙에 대해 몇 가지 질문이 있습니다.

<br><br>

## 문제 내용
1. User Fragment에서 GET "api/v1/user/me/" 으로 유저 정보를 가져올 때, 유저가 instructor이면 현재 진행중인 세미나의 목록을, 유저가 participant이면 현재 수강중인 세미나의 목록을 vertical list로 표시하는 것으로 되어 있습니다.
그런데 instructor은 아래 그림과 같이 "instructor"안에 "charge"라는 key로 담당 세미나가 들어 있는데, 리스트가 아니라 딱 1개만 들어 있습니다.
![image](https://user-images.githubusercontent.com/88367636/141507948-56d904b9-60d0-47df-bec7-daecca1e65ee.png)
하지만 participant의 경우 수강중인 세미나가 리스트로 전달되기 때문에 fragment에서 같은 view에 담을 수 없는 상황입니다. 자유롭게 구현하는 과제이니 그냥 recyclerview랑 textview 두개 다 만들어 놓고, 각 상황마다 하나는 그냥 빈 칸으로 놓고 나머지 하나만 채우면 될까요? 두 경우 모두 공통의 recyclerview를 사용해 보려 했는데 잘 안되네요.<br />

2. DetailSeminarActivity는 instructor만 접근할 수 있는 CreateSeminarActivity를 거쳐야 갈 수 있게 되어 있습니다. 그런데 DetailSeminarActivity 설명에는 participant가 버튼을 누른 경우의 구현도 제시되어 있는데, 이 부분은 어떻게 하면 될까요?

**Comment by veldic** [comment]
1. 후자의 방법으로 구현하는걸 의도하긴 했는데 전자의 방법도 구현할 수 있다면 시도해보는 것도 좋아보입니다! Flow.collectLatest나 Flow.map과 같은 문서들을 한번 구경해보시는 것도 좋을 것 같네요.
2. Seminar list의 각각의 아이템을 클릭했을 때 DetailActivity로 가주면 좋을 것 같네요! 추가하겠습니다

**Comment by JuTaK97** [comment]
> 1. 후자의 방법으로 구현하는걸 의도하긴 했는데 전자의 방법도 구현할 수 있다면 시도해보는 것도 좋아보입니다! Flow.collectLatest나 Flow.map과 같은 문서들을 한번 구경해보시는 것도 좋을 것 같네요.
> 2. Seminar list의 각각의 아이템을 클릭했을 때 DetailActivity로 가주면 좋을 것 같네요! 추가하겠습니다

flow를 열심히 공부해봐야겠네요. 감사합니다!!
