### ISSUE TITLE
Django 과제4 RDS 데이터베이스 생성 요금??

### ISSUE THREAD

**Issue by minkyu97** [wafflestudio/19.5-rookies#673]
## 요약

데이터베이스 생성 시 월별 청구 요금 약 1000달러라고 나와있는데 무시하고 그냥 생성하면 되나요?
아니면 EC2 생성 시와 마찬가지로 프리티어 선택하고 생성해도 과제 진행하는데 문제가 없나요

<br><br><br><br>

## 상황

<br><br><br><br>

**Comment by minkyu97** [comment]
그냥 프리티어로 선택하고 진행했는데 별 문제 없이 되는 것 같습니다.

**Comment by woohm402** [comment]
그거 프리티어 선택 안 하시면 돈 엄청 들어요..ㄷㄷ

**Comment by minkyu97** [comment]
> 그거 프리티어 선택 안 하시면 돈 엄청 들어요..ㄷㄷ

세미나장님은 프리티어 말고 일반으로 진행하시길래 저도 그렇게 해야되는 줄 알았어요 ㅎㅎ 뒤늦게 봤지만 답변 감사합니다!
