### ISSUE TITLE
안드로이드 과제4 에러 메시지 관련

### ISSUE THREAD

**Issue by JuTaK97** [wafflestudio/19.5-rookies#674]
## 요약
서버가 보내주는 에러 메시지를 Toast로 띄우든 해야 되는데, 어떤 경로로 오는 건지 모르겠습니다.

<br><br>

## 상황
예시로 든 위 상황은 세미나에 join하려 하는데 이미 참여중인 상황입니다. 

postman으로 확인해 보면
![image](https://user-images.githubusercontent.com/88367636/141612446-24017400-2283-45b3-9e25-229c969ee511.png)
헤더의 정보는 위와 같고,
![image](https://user-images.githubusercontent.com/88367636/141612548-8f45206a-fa0a-4811-947c-59e8c1f0ec97.png)
postman으로 보기에는 바디에 해당 에러 메시지가 담겨 있습니다.

![image](https://user-images.githubusercontent.com/88367636/141612521-f19fb8d6-0437-420d-a71b-2ff0f18eef4f.png)

받아온 Call<> 을 enqueue해서 나온 response 객체에 분명 모든 정보가 있을 텐데, 저 에러 메시지는 대체 어디에 있는지 모르겠습니다. 당연히 response.body().toString() 이나 response.errorBody().toString() 하면 나올 줄 알았는데 아니네요.
![image](https://user-images.githubusercontent.com/88367636/141612627-712560e5-fc92-414d-8718-08d48b78e5c1.png)
얻을 수 있는 건 다 출력해 봤는데, "이미 참여중입니다" 는 찾을 수가 없네요.
어떻게 값을 얻어야 하나요?

**Comment by veldic** [comment]
Call 이라는 Class를 사용해본 적이 없어서 답변을 확실하게 드리기가 어렵네요. 사실 세미나에서 사용한 method들만 이용했다면 Call을 사용하지 않고도 진행할 수 있어서... 직접 한번 찾아보시는 방향이 좋을 것 같습니다.

**Comment by kwish2** [comment]
response.errorBody().toString() 말고
response.errorBody()?.string()!! 하시면 됩니다!

**Comment by JuTaK97** [comment]
> response.errorBody().toString() 말고 response.errorBody()?.string()!! 하시면 됩니다!

 정말 별 짓 다해보고 있었는데 계속 못 찾고 있다가.. 깔끔하게 해결됐네요. 정말 감사합니다!!
