### ISSUE TITLE
장고 과제4 migration 관련 에러 질문

### ISSUE THREAD

**Issue by graviol** [wafflestudio/19.5-rookies#675]
## 요약

서버에 migration하는 과정에서  "Table 'auth_permission' already exists"라는 문제가 발생한 이후 제대로 migrate가 되지 않고 있습니다.

<img width="1049" alt="스크린샷 2021-11-13 오후 6 43 04" src="https://user-images.githubusercontent.com/33542047/141614135-5d016d28-37d9-4155-9cf1-99c2478dcb01.png">

## 상황
setting.py에서 HOST를 제 데이터베이스의 주소로 바꾸고, Datagrip을 통해 waffle_backend_2 DB를 만든 다음 가상환경 설정을 한 뒤에 makemigrations->migrate을 하려고 했는데, 위와 같이 이미 auth_permission이라는 테이블이 있다는 문구가 뜬 다음에 이후의 과정이 진행되지 않고 있습니다.

## 문제 내용

![KakaoTalk_Photo_2021-11-13-18-53-34](https://user-images.githubusercontent.com/33542047/141614342-17f977c7-cf1b-450d-a18a-f74d6c63eafd.jpeg)
![KakaoTalk_Photo_2021-11-13-18-53-26](https://user-images.githubusercontent.com/33542047/141614346-a67ab192-0452-4640-8476-8957a38b9a7f.jpeg)

로컬에서 돌렸을 때에는 문제 없이 돌아가던 코드이고, migration 관련 오류도 발생한 적이 없었습니다. 관련하여 문제 상황을 찾아보았더니 fake라는 command를 통해 해결할 수도 있을 것 같습니다만 완전히 같은 상황인지 확인이 되지는 않아서 시도하지는 못 했습니다. 아래의 사진은 showmigrations를 통해 현재의 상황을 확인한 것입니다.

<img width="477" alt="스크린샷 2021-11-13 오후 6 55 46" src="https://user-images.githubusercontent.com/33542047/141614428-c32970a4-8001-4205-aca0-e70295f55f9d.png">
<img width="498" alt="스크린샷 2021-11-13 오후 6 55 52" src="https://user-images.githubusercontent.com/33542047/141614427-43dbc1c2-fd37-4b2c-ad5e-439a1798898c.png">

그리고 Datagrip에서의 상황은 다음과 같습니다.
<img width="952" alt="스크린샷 2021-11-13 오후 7 00 21" src="https://user-images.githubusercontent.com/33542047/141614531-6829289b-51d1-4dee-85da-bfbfb43af135.png">

또 이 오류가 뜨기 전에는 아래의 사진과 같이 REFERENCE command denied to user이라는 문구도 떴었는데, 이 문구는 제가 보안 그룹 설정을 변경한 이후에는 따로 뜨진 않으나 혹시 현재의 오류가 고쳐진 이후에 다시 문제가 될 수 있을지가 궁금하여 첨부드립니다. (수정 : DB를 지우고 다시 했을 때에 이 오류가 다시 생성된 것을 보니, 이 문제도 해결해야 할 것 같아 보입니다. 일단 이에 관련한 오류 해결을 시도해보겠습니다.)
![KakaoTalk_Photo_2021-11-13-18-53-32](https://user-images.githubusercontent.com/33542047/141614344-2077bf46-4692-473d-9b01-8fd67012a0a1.jpeg)

**Comment by graviol** [comment]
권한 설정의 오류였습니다. 해결하였습니다 :)

**Comment by hansmaan** [comment]
저도 똑같은 문제가 발생했는데, 혹시 어떻게 문제 해결하셨는지 여쭤봐도 될까요?

**Comment by hansmaan** [comment]
![스크린샷, 2021-11-14 23-01-38](https://user-images.githubusercontent.com/88359757/141684425-19e8674b-f443-4ded-9d15-abad5e3c3cb0.png
![스크린샷, 2021-11-14 23-01-36](https://user-images.githubusercontent.com/88359757/141684428-1bc149e7-f5a0-4809-ac5f-7ff5a2a5be15.png)
)
제 에러 형태는 이렇습니다.

**Comment by Jhvictor4** [comment]
@hansmaan 그냥 --fake 해주시면 될 것 같습니다

**Comment by hansmaan** [comment]
> @hansmaan 그냥 --fake 해주시면 될 것 같습니다

감사합니다..!
