### ISSUE TITLE
장고 OperationalError: (1045, "Access denied for user 'waffle-backend'@'172.31.44.17')

### ISSUE THREAD

**Issue by jhm1313** [wafflestudio/19.5-rookies#678]
![스크린샷, 2021-11-14 06-21-27](https://user-images.githubusercontent.com/44698831/141659632-b4a49cb0-fdb7-4a09-aabc-3581f1218339.png)

구글링 해보니, 프로젝트의 settings.py의 user, password와 mysql의 것이 서로 일치하지 않을 때 일어나는 현상이라고 하더라구요.
(password를 seminar에서 Seminar4!로 바꾼것은 seminar로 하려니 mysql 정책상 설정이 안 된다 하더군요....저번달까지만 해도 문제없었는데 그 사이에 바뀐건지 궁금하기도 합니다.)

그런데 아무리 해봐도 settings.py와 mysql의 것이 일치한데 계속 이 에러가 발생합니다.

'waffle-backend'@'172.31.44.17' 여기서 172.31.44.17 이 IP 주소가 제 IP 주소와 다른 것이던데, 이것이 문제일까요?
(보안 그룹에서 ssh 접근을 제 IP만 허용해놔서 그런 건가 싶어 이 IP 주소도 보안 그룹에 추가해봤는데 해결되지는 않았습니다.)

또, datagrip 상에서는 아래와 같이 데이터베이스가 제대로 연결된 것처럼 보이는데, datagrip 콘솔에서는 db 및 유저 생성 등 쿼리를 날려도 mysql에서는 반영이 안 되더라구요.
(즉, datagrip에서 user, db 등을 생성해도 ssh waffle로 접속한 서버에서 mysql을 직접 실행하여 조회해보면 해당 변경 사항이 적용이 안 되어있었습니다.)

![스크린샷, 2021-11-14 06-45-04](https://user-images.githubusercontent.com/44698831/141659884-be759384-7ae4-4086-92ff-bd452b626bb3.png)

이러한 부분에서도 ec2로 만든 인스턴스와 rds가 어떻게 연동되는지 이해가 잘 안 됩니다...

세미나 영상에서 쉘과 datagrip, pycharm의 팝업 창이 전부 생략되어있어서 세미나장님께서 어떤 코드를 작성하셨고, 어떤 결과가 나왔는지 확인이 안 되니 따라가는게 너무 힘듭니다 ㅠㅠㅠ

**Comment by jhm1313** [comment]
![스크린샷, 2021-11-14 07-20-51](https://user-images.githubusercontent.com/44698831/141660659-3e0efea6-d1eb-4c8f-9cd5-083a82bf8dad.png)

이 사진과 같이 ssh waffle로 연 서버에서 mysql을 실행시킨 것과 datagrip의 db 내용이 다릅니다....ㅠㅠㅠㅠ
연결이 제대로 안 된 듯 한데, 구글링을 해봐도, 세미나 영상을 다시 봐도 뭐가 틀렸는지 감이 잡히지가 않습니다...

**Comment by Jhvictor4** [comment]
> 'waffle-backend'@'172.31.44.17' 여기서 172.31.44.17 이 IP 주소가 제 IP 주소와 다른 것이던데, 이것이 문제일까요?

권한 설정 시 와일드 카드를 통해  'waffle-backend'@'%' 로 GRANT 커맨드 실행해주신 것이 맞나요?

> 이 사진과 같이 ssh waffle로 연 서버에서 mysql을 실행시킨 것과 datagrip의 db 내용이 다릅니다....ㅠㅠㅠㅠ

ssh waffle로 mysql을 실행시키셨다고 했는데, 

`mysql -h <rds IP> -u 계정 -p` 로 접속하신 것 맞을까요? DB 내용이 다르려면 그냥 다른 DB인 것 같은데, 혹시 EC2에 로컬 mysql이 돌아가고 있는게 아닐까 싶어서요. 

위 두 가지 체크 한번 부탁드립니다. 추가적인 질문이나 문제사항 계속 코멘트로 남겨주세요!

**Comment by jhm1313** [comment]
제가 두개의 db를 완전히 혼용하며 사용중이었네요....

ec2와 rds의 개념을 더 정확히 알게 되었습니다!

이후 다른 문제가 몇개 발생했었는데, 구글링하여 migration 파일 싹 지우고 wafle_backend_2 DB도 지우고 다시 생성한 다음에 makemigrations, migrate 다시 실행하니 migration 성공했습니다.

감사합니다!!
