### ISSUE TITLE
장고 과제 5 exception_handler을 찾지 못하는 문제 관련

### ISSUE THREAD

**Issue by graviol** [wafflestudio/19.5-rookies#682]
## 요약
정의한 exception_handler을 장고가 찾지 못하는 에러가 있습니다.

<img width="1117" alt="스크린샷 2021-11-14 오후 6 46 32" src="https://user-images.githubusercontent.com/33542047/141676074-20c5bde7-1dd0-41cb-83df-08a29096edd5.png">

## 상황
exception_handler.py를 정의한 다음 customise하고, settings.py에 이를 가리키는 path를 적은 뒤 gunicorn과 nginx를 재시작하였더니 위와 같은 에러가 발생하였습니다. 과제 4는 성공적으로 수행되었고 settings.py에서 해당 부분만 주석 처리하면 역시 잘 돌아가는 것을 볼 때 경로 설정의 문제가 유력해 보입니다.

## 문제 내용
<img width="1360" alt="스크린샷 2021-11-14 오후 6 46 52" src="https://user-images.githubusercontent.com/33542047/141676126-cadafb70-3907-4304-8300-444b17ee1297.png">
현재의 파일 구조는 다음과 같고, 세미나장님께서 시연해주신 대로 root에서부터 해당 경로까지를 나타내는 path를 따라서 적어보려고 하였습니다만, 이를 찾지 못하는 문제가 발생하였습니다. 
<br><br>
또한, 지금은 에러가 명시되지 않았으나, 아까 전에는 waffle-rookies-19.5-backend-2 부분에서 19.5의 .을 하위 directory로 인식하는 문제 또한 발생하였습니다. 이 부분에 대한 해결책을 찾으려고 구글에 검색하였으나 기본적으로 python은 .를 제대로 인식할 수 없음을 확인하였고, 이 문제 뿐만 아니라 애초에 현재의 에러에서는 module named 'home'이 존재하지 않는다는 오류까지 떠서 해결에 난항을 겪고 있는 상황입니다ㅠㅠ 이 부분에 대해서 조언을 구할 수 있을까요?

**Comment by minkyu97** [comment]
저는 경로를 waffle_backend 폴더를 홈폴더로 가정하고 잡았는데 잘 되었습니다.

waffle_backend.utils.exception_handler.exception_handler 이런 식으로요.

**Comment by graviol** [comment]
안녕하세요 민규님, 말씀하신거를 유추해보면 waffle_backend에 utils라는 폴더를 만드시고 그 안에 exception_handler.py를 넣으신 것 같은데, 제가 제대로 이해한 것이 맞을까요? 그리고 waffle_backend.를 뺀다는 것은 그렇다면 utils.exception_~~~ 으로 설정하신 것으로 이해해도 좋을까요?

**Comment by Jhvictor4** [comment]
네, 민규님 말씀이 맞습니다. 프로젝트 루트에서부터 적어주시면 됩니다 :)

**Comment by graviol** [comment]
해결했습니다!! 민규님 그리고 지혁님 두 분 다 도와주셔서 정말 감사드립니다ㅠㅠㅠㅠ
