### ISSUE TITLE
장고 과제 5(3) notebook 실행 오류 질문

### ISSUE THREAD

**Issue by graviol** [wafflestudio/19.5-rookies#690]
## 요약
python manage.py shell_plus --notebook을 통한 notebook 실행이 되지 않습니다.

## 상황
<img width="1204" alt="스크린샷 2021-11-15 오전 7 19 37" src="https://user-images.githubusercontent.com/33542047/141700903-15d4deb9-514c-4798-bfb4-48eb74a5ceef.png">
문제 5(3)을 수행하기 위해 notebook을 실행하려고 했는데, 위와 같이 _sqlite3과 pysqlite2 모듈이 없다는 에러가 표시되고, IPython Notebook을 load할 수 없다는 commandError도 표시되면서 진행이 되지 않습니다. (사진에서는 python3 command로 했지만, python으로도 마찬가지의 결과를 얻었습니다.)
<br><br>

## 문제 내용
brew를 설치 후 sqlite3을 따로 설치했는데도 불구하고 이러한 문제 상황이 여전히 발생하는데, 어떠한 문제 상황을 의심하면 좋을지에 대해 질문드립니다.

**Comment by Jhvictor4** [comment]
@graviol 

해당 이슈는 sqlite3 버전 이슈입니다. [링크](https://kogun82.tistory.com/192) 한번 참고해보시겠어요?

**Comment by Jhvictor4** [comment]
그런데 MySQL RDS로 DB 세팅이 되어있어도 해당 이슈가 발생하고 있나요?

**Comment by graviol** [comment]
> 그런데 MySQL RDS로 DB 세팅이 되어있어도 해당 이슈가 발생하고 있나요?

넵, 과제 4때부터 DB는 MySQL RDS를 사용 중이었습니다. 그리고 링크 보여주신 것 저도 문제를 해결하는 과정에서 읽어 보았는데, ./configure이 folder을 의미하는 것 같은데 어느 디렉토리에 있는지 알 수 있을까요?

**Comment by graviol** [comment]
그리고 조금 전에 링크의 블로그에서 하라는 대로 했는데도 동일한 오류가 나오는 것을 확인하였습니다. 음... 다른 문제가 있는 것일까요?

**Comment by Jhvictor4** [comment]
./configure는 그냥 python 다운로드 받은 파일 안에 생기는 makefile 같은 개념입니다.

**Comment by graviol** [comment]
네네 터미널 명령어로 ./configure을 찾아서 해보았는데 별 소득이 없네요... 그리고 저 에러 화면에서 venv 가상 환경의 python 주소와 다른 곳에서도 python 에러가 뜨는 것 같은데, 이 것이 에러의 원인일 가능성이 있을까요?

**Comment by graviol** [comment]
앗 혹시 로컬에서 돌려야 하나요...???

**Comment by graviol** [comment]
지혁님 이 이슈는 로컬에서 실행하는 것으로 해결했습니다… 도와주셔서 감사합니다😊
